### ISSUE TITLE
Custom CSS builds

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#1001]
## Feature Request
I just tried adding a Button to a blank page and ran `Lighthouse`. It appears that due to many types of combinations a button might have, button's css has all the content in it. Even though I am not using primary or accented or raised kind of buttons, but the CSS still has it all.

Chrome currently reports a lot of unused CSS in coverage tab.

Is it possible we can have a builder kind of place where I can check what all I need and just download that CSS.

If this is possible with some kind of SCSS `webpack` plugin please let me know

**Comment by Garbee** [comment]
The individual sub-pieces like state modifiers for buttons isn't possible currently. Also, simply because you don't use it in that case doesn't mean it may not get used in other components later on when building a full application.

In my opinion, this kind of case is where you'd want to build your own CSS if you want to get "to-the-rule" level accuracy of what exists or not within your application. Building out a system to handle this level of detail across each component would be hard to maintain, difficult to document and explain, and simply get in the way in the future. The return-on-investment simply isn't there for CSS parsing minimalism to this degree.

**Comment by prateekbh** [comment]
I somewhat agree on the pain what this thing will bring in. Was just curious if this was somewhat already thought by the team.

Feel free to close the issue if nothing in near future roadmap

**Comment by yeelan0319** [comment]
@prateekbh This has been brought up by other community members as well. However, what @Garbee mentioned is exactly what we concern about and due to the ambiguity that this question have, we are not planned to have something in the near future.

However, we agree this is a interesting topic. Feel free to open a issue specifically for discussion, well-thought needs and suggestions will definitely help us to understand what is needed from the community and how we may work toward that. Thanks!
