### ISSUE TITLE
refactor mdc-textfield to mdc-text-field

### ISSUE THREAD

**Issue by RobJacobs** [material-components/material-components-web#1019]
Please consider refactoring mdc-textfield to mdc-text-field so the naming convention matches other components (i.e. mdc-form-field).

**Comment by amsheehan** [comment]
Makes sense to me since our spec refers to it as "text field" and not "textfield"

Would you want to make that change and create a pull request? Change would include:

- [ ] Changing directory name
- [ ] Changing `./github/ISSUE_TEMPLATE.md`
- [ ] Renaming `textfield` to `text-field` in the demos and docs. This includes: `demos/index.html`, `demos/snackbar.html`, `demos/textfield.html`, `docs/docsite-index.md`, `docs/getting-started.md`, `docs/migrating-from-mdl.md`
- [ ] Rename it in `package.json` as well as `mdc-textfield/package.json`
- [ ] Renaming it in the package itself. This includes `index.js`, `foundation.js`, `mdc-textfield.scss`, and the README
- [ ] Adjusting all of the unit tests to account for the new name
- [ ] Renaming it in `webpack.config.js`

**Comment by RobJacobs** [comment]
@amsheehan Will do, should I wait for PR 998 to merge?

**Comment by amsheehan** [comment]
I wouldn't. We're making several breaking changes to MDC Text Field and MDC Select in the next few weeks. I'd just make the PR and I'll worry about resolving any merge conflicts that may arise.

Thanks!

**Comment by RobJacobs** [comment]
@amsheehan PR #1052 created, thanks.
