### ISSUE TITLE
what is the relation of polymer elements with https://material.io/components/web/catalog/

### ISSUE THREAD

**Issue by spyhole** [material-components/material-components-web#1027]

**Comment by touficbatache** [comment]
There is no relation between them: Polymer is a completely different project. MDC-Web is the successor of [MDL](https://getmdl.io) but with less components because it's not yet complete. You can check the [pivotal tracker](pivotaltracker.com/n/projects/1664011) to know when new components are planned to be released.

**Comment by spyhole** [comment]
thanks @touficbatache

**Comment by touficbatache** [comment]
No problem. Feel free to comment if you have any more questions!

**Comment by saimAbdullah** [comment]
can we use MDC in polymer project?

**Comment by kfranqueiro** [comment]
MDC Web is vanilla HTML + Sass + JS. There is a separate repository being worked on by the Polymer team to provide MDC wrappers in the context of web components: https://github.com/material-components/material-components-web-components, so you can have a look there to get an idea of how MDC Web can be used with web components.
