### ISSUE TITLE
How to help add type definitions?

### ISSUE THREAD

**Issue by pspeter3** [material-components/material-components-web#105]
I'm happy to help write type definitions for the code. Anything I can do to help?

**Comment by traviskaufman** [comment]
Hey @pspeter3,

Thanks for filing this issue.

Supporting Typescript is actually a big theme for us as we work towards a "beta" release, and we're tracking that issue at #134. Because we haven't yet decided on a strategy for doing moving forward with this, I'm hesitant to advise you to start working on anything right now. However, if you're interested in helping out definitely subscribe to the tracking issue and once we've come up with a solution moving forward, we'll loop you in. Thanks again for your interest!

**Comment by pspeter3** [comment]
Thanks for the update!
