### ISSUE TITLE
Overriding ripple color with the compiled CSS

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1063]
Hey,
I was creating a toolbar for my web app and I came across a small problem: the toolbar's background color is dark so text and icons on it are _white_. I added ripples to icons but the ripples color is _black_ so it's not very clear in the toolbar.

I was searching in the READMEs for a way to add `primary-on-primary` to the ripple but there was nothing showing how we can change the ripple color, with the compiled MDC CSS, in the first place!

What I suggest doing is:

- Adding a class to style the ripple with `primary-on-primary` (and obviously other styles like primary on dark, etc...)

**OR**

- Adding the ability to change the ripples color with the `background-color` property in CSS (easier than adding a single class for each style)

And the changes would be added, of course, to the READMEs. So, it would be great if you think about these changes as it makes it easier for everyone that ran in the same issue as me. Thanks!

**Comment by Garbee** [comment]
As per #1067 you're structure for this is a little off. Which is my guess as to why it isn't working right.

As far as I understand the spec, developers should not need any controls over ripple color. Which means if any exist in a well formed MDC system those are specific bugs that need to get addressed.

**Comment by yeelan0319** [comment]
@Garbee is right. Generally ripple is a feature that we don't want to ask developers address at high level. However, it is still customizable with SASS mixin because we intended to leave a lower level API for people who necessarily want to customize it. 

As that being said, the problem that you find is accurate and it is a problem that we are working on with our designers, so that in the future ripple will be more context aware and adopt the right color. Some of the corrections will be rolled out together with button improvement soon
