### ISSUE TITLE
Correct unbounded ripple diameter

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#1067]
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> All browsers (Chrome newest)

### What OS are you using?

> All OS (Windows 7, Android 7)

### What are the steps to reproduce the bug?

> 1. Add a ripple to the toolbar icons
> 2. Observe the component's behavior
>
> https://codepen.io/anon/pen/YxGLQE

### What is the expected behavior?

> The ripple should be close to the size of the icon.

### What is the actual behavior?

> The ripple is a lot bigger than what it should be.

**Comment by Garbee** [comment]
You can't just put the icon into a toolbar. There is a toolbar icon structure that is necessary for them to work right. Also, this is going to change as per #992 a little bit along with #993.

**Comment by yeelan0319** [comment]
@Garbee is right that you should use `__icon` provided by toolbar instead of `icon-toggle` here. However, that being said, it seems like the `unbounded ripple` do have an incorrect radius, so we need go ahead and correct that implementation.

What need to be changed here:

- [ ] Correct the padding of right most `__icon` in toolbar, so it have the same padding with other icons and use margin to make the last icon is positioned correctly.
- [ ] Make the diameter of unbounded ripple from half diagonal of the bounding box to half length of the bounding box (see the image below)

<img width="119" alt="screen shot 2017-08-03 at 15 21 25" src="https://user-images.githubusercontent.com/1894234/28940008-36a378d6-7861-11e7-81a5-03df548a2f0a.png">
<img width="117" alt="screen shot 2017-08-03 at 15 30 07" src="https://user-images.githubusercontent.com/1894234/28940009-3810eae6-7861-11e7-9aaf-3a9bdae3d31a.png">

**Comment by touficbatache** [comment]
I'm not using `icon-toggle` in the demo @yeelan0319

**Comment by touficbatache** [comment]
I would be happy to make those changes. Would you want to guide me through it @yeelan0319?

**Comment by touficbatache** [comment]
@yeelan0319 What do you mean by:
> "Make the diameter of unbounded ripple from half diagonal of the bounding box to half length of the bounding box"
Should I change the ripples size from the `foundation.js` file?

**Comment by kfranqueiro** [comment]
Unfortunately, we're going to need to revert the PR, because it caused visible regressions on *bounded* ripples.  See the animated gif in #1183.

**Comment by yeelan0319** [comment]
@touficbatache My apology that I should have caught that bug before merging it. Thanks @kfranqueiro for get on this for a quick revert.

Meanwhile, I have some ideas how this could be fixed after digging deeper into the code:
1. The ripple should *always* cover the surface (may with/without boundary), so we might not touch the surface diameter
2. Given 1, the surface of unbounded ripple should either be treat carefully to differentiate the usage of `margin`/`padding` or we strictly exclude both `padding` and `margin` from calculation. IMHO, I would vote for the former because a few cases I saw, we have been interchangeably using `margin` / `padding` as the boundary is not visible while it shouldn't be. 
3. Further we might consider adding a `mdc-ripple--unbounded` modifier beyond `mdc-ripple-upgraded--unbounded` to facilitate CSS only unbounded ripple, so they won't show a huge ring in that case. This will also help address #1139 

For @touficbatache question, I actually tried to modify the codepen that you shared and I feel simply adjusting `padding` to `margin` could meet your need? Could you confirm if the following [pen](https://codepen.io/yeelan0319/pen/xLJaOJ/ ) works? 

For our demo page, I think we might also consider fix the demo.
1. `.mdc-ripple-surface[data-mdc-ripple-is-unbounded]` is specified to be `40px` in its width and height even though the icon is only `24px`. I am not clear the intention behind that, but I think it should be correctly reflect how large the ripple surface is.
2. I also suggest we remove the below line `.mdc-ripple-surface[data-mdc-ripple-is-unbounded][data-demo-no-js]::before,
      .mdc-ripple-surface[data-mdc-ripple-is-unbounded][data-demo-no-js]::after`, which will make the demo unbounded ripple have a different and IHMO unnecessary style different from CSS only ripple.
Here is how the demo look like after those changes.
<img width="687" alt="screen shot 2017-08-25 at 11 19 53" src="https://user-images.githubusercontent.com/1894234/29720284-6b23636e-8987-11e7-95da-ca0cfa681a46.png">

**Comment by touficbatache** [comment]
It's not a problem :smiley: I'd be happy to make another change to fix that problem.

[Your pen]
 (https://codepen.io/yeelan0319/pen/xLJaOJ/) is great and the ripple looks very good but I'm sorry to say that it feels a little bigger than what I would have expected. If you take a closer look at the ripple on toolbar icons in Android 7 (for example: Gmail, Whatsapp, etc...), you'll see that it's a little bigger than the size of the icon itself.

I also may be able to make the changes needed in the demo page for the unbounded ripple. The screenshot you provided is *exactly* what I need for the toolbar icon.

Thank you for the help @yeelan0319

**Comment by kfranqueiro** [comment]
I've been catching up on the various issues involving unbounded ripple diameter today. I don't think we're going to resolve this prior to 2018 given that holiday season is right around the corner, but I wanted to at least summarize the known issues (let me know if you think I missed anything and I'll edit this):

* JS unbounded ripples are overly large, probably at least in part due to the scaling that is currently performed with the same values regardless of bounded vs. unbounded. This might be resolvable either through radius style adjustments or JS computation adjustments.
* CSS unbounded ripples are overly large by default because they are effectively not styled whatsoever - there is no modifier class to distinguish bounded vs. unbounded CSS-only ripples. Adding a modifier class for this would ostensibly also require its inclusion in components that use it, though. Alternatively, perhaps we should consider splitting up bounded and unbounded styles to separate mixins to only be applied where necessary on a per-component basis.
* We currently have special cases in our styles in the following places:
  * Checkbox and radio for CSS-only, to support focus state across all supported browsers
  * Ripple demo page, to constrain CSS-only unbounded ripple size

It would probably also be a good idea for us to confirm with designers on what the appropriate relationship is between icon size and unbounded ripple size. Currently what I've found in the guidelines are the checkbox/radio and icon toggle examples, and I think even our checkbox/radio-specific ripple styles may be a bit off based on that (a bit too small).

**Comment by touficbatache** [comment]
Fixed in #2178 by @kfranqueiro
