### ISSUE TITLE
Menu Question: Keeping Menu "Open" when clicking inside

### ISSUE THREAD

**Issue by oneezy** [material-components/material-components-web#1090]
This question is in relation to the **Menu Component**: 
https://material.io/components/web/catalog/menus/ 

I've modified the code so that the menu opens when hovered instead of clicked. I'm now trying to make the menu stay open and/or close when certain elements inside the menu are clicked on..But I'm having some trouble getting it to do that...

Can anyone help?

----
**Example:**
- When `<li class="wont-close">` is clicked, the menu won't close. `menu.show();`
- When  `<li class="will-close">` is clicked, the menu will close. `menu.hide();`

https://codepen.io/oneezy/pen/prejpw

![image](https://user-images.githubusercontent.com/7369575/29047411-3f8537f4-7b91-11e7-9c26-6f569169dc35.png)

**Comment by Garbee** [comment]
There is support within the spec for keeping a menu open for multiple selections.

> Selecting a menu item should also dismiss the menu. An exception is when a menu allows for multiple items to be chosen, for example, by using checkmarks.

Looks to me like a feature improvement to the current menu would allow for this without violating the MD Spec.

**Comment by acdvorak** [comment]
Hi @oneezy!

It looks like you're pretty close - you just need to call `e.stopPropagation()` in your `.wont-close` event handler instead of `stopPropagation()`. That's it! 🙂 

Here's a modified [CodePen](https://codepen.io/anon/pen/oewMOM) that shows it working.

I recommend always keeping your browser's dev tools open while you're working on front end stuff -
 it makes it way quicker and easier to spot these sorts of errors:

> Uncaught ReferenceError: stopPropagation is not defined

**Comment by oneezy** [comment]
thanks @acdvorak !

that works perfectly.
