### ISSUE TITLE
[Question] MDCSimpleMenu: is focus on open mandatory?

### ISSUE THREAD

**Issue by xxRockOnxx** [material-components/material-components-web#1111]
Would propose a PR if my question is answered.

I am reusing the SimpleMenu component as a autocomplete results box as it seems suitable (on how it looks like).

<img src="https://s27.postimg.org/7j9659io3/Screenshot_from_2017-08-10_23-48-20.png">

My problem tho is, every time it opens, it focuses on the menu.

Not only it is a bad UX (need to click again on the input) but if I want to type again, the menu closes and might stop user from typing continuously if the user pauses.

If the answer is No, is autocomplete box component acceptable as a PR? Similar to SimpleMenu, but just doesn't autofocus.

I feel like the answer is no because, the component is a "Menu" from the first place but thought asking if my proposals are worth submitting a PR.

**Comment by Garbee** [comment]
A select box is a dialog of sorts, so focus on open is required for accessibility. Otherwise having the proper tab order to get into the menu could be an issue for people that need keyboard navigation.

**Comment by xxRockOnxx** [comment]
I'm not sure if I understand what you mean. To me, it seems you're saying focus > typing?

I mean, I use debounce, once I paused for a while and it triggers the query (api call), the response will be returned. Upon returning, the menu will open and will focus there.

Isn't that a bit frustrating? I could increase the debounce time but that can cause frustration also.

Again, I am not sure if that's what you mean.

**Comment by Garbee** [comment]
You're trying to use a *menu* to do something. *Menus* require focus shift because they are essentially a dialog type thing which gains focus on opening. What you seem to be doing is typeahead functionality, which is not yet supported internally but is planned. Menu's probably won't be involved there, nor should they be since typeahead lists don't gain focus when detailed. However, opening up the menu system to not gain focus could lead developers into building in-accessible systems with it.

I don't see where the menu should open itself up to this kind of use-case. It is an in-accessible menu and they aren't intended for this type of use at all.

**Comment by xxRockOnxx** [comment]
Material guidelines does not provide a bit much regarding desktops or web in general. I just relied on the images and found SimpleMenu to be visually the same (at least on google results).

What I did is copied the whole `open` method inside the SimpleMenu's foundation except for the `focusOnOpen` part.

It's currently usable and does not show any bad effects in my use-case. I plan on making a dedicated component, but beating the deadline is priority.

**Comment by acdvorak** [comment]
@Garbee is right - menus are sort of like mini modeless dialogs, which is why they grab focus. I definitely see where you're coming from, in that menus are visually similar to what you want, but unfortunately their behavior and intended usage are fundamentally incompatible with what you need.

The [spec for text field components](https://material.io/guidelines/components/text-fields.html#text-fields-layout) mentions inline autocomplete (aka typeahead), which we do not currently support. We would like to add it in the future, but it probably won't be anytime soon.

The [spec for search patterns](https://material.io/guidelines/patterns/search.html#search-in-app-search) _does_ describe what you're looking for (which is search suggestions), but there's no component spec for it, so we have no plans to build it into MDC-Web at this time. Unfortunately that means you'll need to build your own component or find an existing implementation elsewhere.
