### ISSUE TITLE
Incorrect unbounded ripple diameter on JS version

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#1139]
### What MDC-Web Version are you using?

> 0.17.0

### What are the steps to reproduce the bug?

> 1. run the demo server
> 2. go to [material-components-web.appspot.com/ripple.html](http://material-components-web.appspot.com/ripple.html)
> 3. Click js & css only ripple
> 4. They have different diameter
>

### What is the expected behavior?

> Feel they should have same diameter

### What is the actual behavior?

> But not

**Comment by touficbatache** [comment]
That's because the diameter is calculated in the JS foundation file so it only works on JS version. I think that could be fixed easily!

**Comment by yeelan0319** [comment]
I tried some naive fix but it doesn't work well.
1. Currently, we are differentiating `bounded` and `unbounded` ripple via JS's upgrade (which will make the component being either `mdc-ripple-upgraded` or `mdc-ripple-upgraded--unbounded`, however, we cannot differentiate the case for css only version and my gut feeling is since these two thing are different in nature, it is not quite possible to provide a initial css set up that satisfy both. Here we might need to have a `ripple-surface--unbounded`?
2. I am also quite curious about why `mdc-radio` got its own background `::before` serve a similar purpose as ripple.

**Comment by kfranqueiro** [comment]
I believe the answer to Yiran's 2nd question has to do with the fact that checkbox and radio's DOM structure puts ripple on an element other than the one that directly receives focus, so ripple's `:focus` wouldn't Just Work. Prior to the States styles rework, MDC Ripple had no way to accommodate that, and even `:focus-within` doesn't work in all browsers we support, whereas the current approach used in checkbox and radio does. Unfortunately this means we're not making full use of ripple's upgraded unbounded styles for checkbox/radio though.

Yiran's observations are certainly useful though, since it illuminates why checkbox/radio have their own unique behavior for CSS-only ripple, and also highlights the fact that CSS-only unbounded ripple styles in MDC Ripple are effectively style-less OOTB because there is no selector to apply for them.

I'm going to close this in favor of #1067 and summarize some findings there, since there's already a lot of info on it and we probably need to look at unbounded ripples as a whole.

**Comment by kfranqueiro** [comment]
FYI the style and demo page issues are resolved in #2092.
