### ISSUE TITLE
[IDEA] => CSS Modules => Ability to pass identifier names to methods

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [material-components/material-components-web#1159]
## Goal
- To further optimize the processed CSS after importing it as a module. Example:
  - `.mdc-button` becomes `.b_0`

## Story
Webpack along with css-loader using [css-modules](https://github.com/css-modules/css-modules) allow us to import necessary for a developer component and then call it in the following way, assuming we import object named `styles`:
- `styles.mdcButton`

## Problem
The problem is with the JavaScript architecture that is currently in use.
The methods should accept classes (identifiers using css-modules) as parameters, instead you are returning **constants**. See example [@material/ripple/constants](https://github.com/material-components/material-components-web/blob/master/packages/mdc-ripple/constants.js)

In the end, we have huge nonsense in production classnames like `mdc-ripple-upgraded--foreground-activation`, when we instead could pass it as a generated CSS local identifier such as `b_0`

## Suggested solution
The function should accept an object parameter, default = false, with the classnames generated from the local identifiers of the processed component. Instead of returning constants  after interacting with elements like Ripple that become no longer valid, since the classnames change based on the local identifiers.

**Comment by kfranqueiro** [comment]
Hi @OlzhasAlexandrov and thanks for raising this suggestion.

We're beginning to think about how to go about supporting CSS renaming as well, but haven't arrived at a prototype just yet.

If you'd be willing to put together a small example in a comment or gist to illustrate what you have in mind and how your toolchain would hook into it, this may be helpful for us to compare against to ensure we come up with a solution that works not only for us, but for others in the community. Thanks!

**Comment by OlzhasAlexandrov** [comment]
@kfranqueiro Yeah, I would be glad to provide you with an example.

[Here is a link for the example repo I prepared](https://github.com/OlzhasAlexandrov/material-vue-webpack)
- I have created a starting repo for this purposes based on [vue webpack template](https://github.com/vuejs-templates/webpack)
- You could familiarize yourself with the project structure [here](http://vuejs-templates.github.io/webpack/structure.html)

I have modified it slightly, so now CSS renaming works with `.mdc-button` in `src/views/Homepage.vue`.

Now, I'm wondering what would be the best approach to pass parameters to initialize ripple component.
I think the following two articles describe what we need:
- [Integrating MDC-Web into Frameworks](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md)
- [MDC-Web Architecture Overview](https://github.com/material-components/material-components-web/blob/master/docs/architecture.md)

We probably need to pass CSS local identifiers by using [foundations and adapters approach](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md#the-advanced-approach-using-foundations-and-adapters)

**How would you suggest to proceed?**

**Comment by lynnjepsen** [comment]
Hi @OlzhasAlexandrov , sorry its been so long.

We've spent a lot of time working on CSS renaming for some our internal Google CSS renaming. 

The way we support CSS renaming is to create wrapper JavaScript controllers which reference the Foundation and Adapter class. Any time an Adapter needs to add a CSS class to an element, we implement our internal Adapter to add the renamed CSS class to the element. 

So, for example:
`addClass: (className) =>
          this.root_.addClass(getRenamedCss(className)),`

Let me know if that helps.

There are also a couple Vue wrappers you could use:
* Vue MDC Adapter: MDC-Web Integration for Vue.js (using foundation/adapters.)
* Material Components Vue: MDC-Web Integration for Vue.js (using vanilla components)

**Comment by OlzhasAlexandrov** [comment]
@lynnjepsen 
I don't use the wrappers as I think making UI framework-specific is logically incorrect. GMC isn't ready for the prime time and using more unfinished packages developed by small groups of enthusiasts is questionable.
Also, it is expensive to have skilled employees doing UI and that's what your suggestion is when developers would have to know Vue.js (in this case) in order to build mere UI.

I apologize for being straightforward; IMHO, your answer doesn't add any value to the thread, you don't:
1. Suggest anything that I haven't discussed in my previous message.
2. Provide the audience with any examples.

**Comment by amsheehan** [comment]
Keep in mind with regard to framework specific UI libraries that some frameworks require wrappers because they interact with the DOM in different ways. This is exactly why MDC Web is architected the way it is—so specific frameworks can implement all of their DOM interactions in the way required by a specific framework.

I see nothing wrong with having enthusiasts with domain specific expertise maintain framework specific wrappers in lock step with MDC Web. We found it’s a better use of everyone’s time and results in a better MDC Web, and better framework specific wrapper libraries.

As for spending time building UI—while it may not be a goal of your project to spend engineering time on the front end, that doesn’t mean that a library like MDC Web shouldn’t provide for, and recommend the work of other highly skilled front end engineers. 

In terms of suggesting things to address your specific request. It is my opinion that css renaming (shortening) should not even really be the responsibility of a UI library like MDC Web, and that something in your build chain should do does this. What Lynn suggested is to reimplement the adapter methods in the components that add or remove classes to use shorter custom names in place of the default MDC classes. I think that’s a valid suggestion and is supplemented with a code snippet.
