### ISSUE TITLE
mdc-textfield-helptext within mdc-form-field

### ISSUE THREAD

**Issue by aaronhudon** [material-components/material-components-web#1162]
Should an mdc-textfield be rendered within a mdc-form-field?  If no, please close this post.  If yes, please advise how to correctly render the mdc-textfield-helptext without custom css hacks.

### What MDC-Web Version are you using?

0.17.0

### What browser(s) is this bug affecting?

> Using Chrome v60

### What OS are you using?

> Win10

### What are the steps to reproduce the bug?

Place a mdc-textfield with mdc-textfield-helptext *within* an mdc-form-field

https://codepen.io/aaronhudon/pen/yojBgL

### What is the expected behavior?

The helptext will be below the mdc-textfield on focus

### What is the actual behavior?

The helptext to the right of the mdc-textfield

**Comment by kfranqueiro** [comment]
mdc-form-field's main purpose is to associate a label and input component together and enable the ripple effect even via interaction with the label. On the other hand, mdc-textfield already manages its own label and ripple itself, making mdc-form-field's functionality redundant, so it doesn't make much sense to use form-field around textfield.

This is a great question though, since it clearly indicates that our Getting Started example is promoting something that shouldn't be recommended. I'll log a separate bug about updating that.

The reason this problem occurs with the combination of mdc-form-field and mdc-textfield is due to mdc-form-field's style `display: inline-flex`, and the fact that textfield's help text is simply a sibling to the textfield itself. Instead, what you can do is wrap each textfield and help text in an element with the style `display: inline-block`, and in cases where some fields have help text and some don't, also add `vertical-align: top` so that both textfields align. I [forked your codepen](https://codepen.io/kfranqueiro/pen/QMrJvN) with an example that works.

Hope this helps, and thanks again for pointing out this problem in our docs!

**Comment by dipakchandranp** [comment]
How to dangerouslySetInnerHTML for react mdc Textfiled helpText ?
