### ISSUE TITLE
Button: Focus gives button disabled-ish look

### ISSUE THREAD

**Issue by pndewit** [material-components/material-components-web#1174]
### What MDC-Web Version are you using?

0.18.0 (latest)

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

macOS

### What are the steps to reproduce the bug?

Setting focus on a button makes the button look like it's disabled: https://codepen.io/anon/pen/gxKwqW?editors=1010

Was this an intentional change? Previous versions did not behave like this.
It is especially visible when the button is primary and raised.

### What is the expected behavior?

Buttons did not behave like this in previous versions of MDC (AFAIK).

**Comment by Garbee** [comment]
This is the expected behavior. It isn't any disabled styling but a focus styling to let the user know where focus is on the page. This helps improve accessibility with keyboard navigation.

If this was broken before, then that was a bug. The only time this may not happen is when a button is upgraded with JavaScript so the ripples would be in action which don't keep focus states.

**Comment by pndewit** [comment]
Alright, thanks for the quick reply :)
