### ISSUE TITLE
mdc-tab RTL bug

### ISSUE THREAD

**Issue by ict-programmer** [material-components/material-components-web#1189]
A bug which can also be observed on the [mdc-tab demo page](https://material-components-web.appspot.com/tabs.html). When we have three tabs, when toggling to RTL, click on **tab one**, selects **tab three**, and click on **tab three**, selects **tab one**

### MDC-Web Version: 
The latest, installed with NPM

### Browsers: 
chromium, opera, brave, firefox | all latest version as of Today Aug/26/2017

### OS: 
OpenSUSE Leap 42.3

### Steps to reproduce the bug:
1. Navigate to the demo page: https://material-components-web.appspot.com/tabs.html
2. Toggle RTL several times
3. Select "item one" and "item three" repeatedly

### What is the expected behavior: 
When RTL is toggled, the mdc-tab components is expected to behave like this: click on **item one** selects **item one** and click on **item three** selects **item three**

### What is the actual behavior: 
It is observed that click on **item one** selects **item three** and likewise, click on **item three** selects **item one**

**Comment by kfranqueiro** [comment]
Thanks for reporting this!

This happens to be a bug isolated to the very first tab bar instance in the demo page, caused by forgetting to call `layout` on the instance after swapping to RTL. I've filed a PR to fix the demo, and a similar fix should work for any situation you might experience this in your own code.
