### ISSUE TITLE
Regression: ripple cannot be loaded in iframe with display: none on Firefox

### ISSUE THREAD

**Issue by dessant** [material-components/material-components-web#1195]
Besides a [CSP bug](https://github.com/material-components/material-components-web/issues/1121#issuecomment-321939238), https://github.com/material-components/material-components-web/pull/1041 also surfaces a long-standing Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=548397.

Loading ripple inside an iframe which has its `display` CSS property set to `none` will crash with this error:
```
TypeError: windowObj.getComputedStyle(...) is null
```

**Comment by kfranqueiro** [comment]
Thanks for bringing this to our attention; it's unfortunate that such a bug has persisted in Firefox for 8 years.

I looked through our components and found 2 others, select and slider, which need to invoke `getComputedStyle` upon init in order to display properly, and thus demonstrate this same issue. The ripple feature-detect which was added needs to run when the first ripple is initialized, to determine whether to bother executing further JS at all based on browser support.

While we could arguably make an exception for Firefox in the ripple feature detect, it'd somewhat defeat the point of feature detecting (rather than relying on UA sniffs), and I don't know that it'd be feasible to avoid the initial `getComputedStyle` calls in the other two components that need it for proper layout.

In your case, do you think it'd be feasible to defer constructing MDC components until the frame is actually displayed?

**Comment by dessant** [comment]
As a wokaround, I'm not using `display: none`.

I think it is worth finding a way to support Firefox properly, especially when a regression is introduced in Firefox with a function which in turn is meant to detect an Edge bug.

Do you plan to add a new `regression` label for the project?
https://github.com/material-components/material-components-web/labels

**Comment by dessant** [comment]
I see how it's more problematic to avoid this in select and slider though, but ripple is present in more components, mitigating this Firefox bug at least for ripple would be an easy win. Maybe it could assume the test was successful if getComputedStyle returns null?
