### ISSUE TITLE
Make some theme variables to have the !default flag

### ISSUE THREAD

**Issue by mralessio** [material-components/material-components-web#1215]
Currently the text color is programmatically computed based on its contrast. All properties in `$mdc-theme-property-values` map calculated using `$mdc-theme-primary-tone, $mdc-theme-secondary-tone...` etc variables which cannot be overriden.  It affects also on ripples' background (on pseudo elements)

In some cases the results are far from ideal. Please look at my case and compare, the the first buttons - are automatically suggested, the last one looks way better. 

![image](https://user-images.githubusercontent.com/16015111/29882590-2ac61b3a-8db6-11e7-85d3-cfa9ee2d224e.png)

For better control over the final result, it would be good to have the `!default` flag for these vars: 
`$mdc-theme-primary-tone
$mdc-theme-primary-light-tone
$mdc-theme-primary-dark-tone
$mdc-theme-secondary-tone
$mdc-theme-secondary-light-tone
$mdc-theme-secondary-dark-tone`
This would be the easiest and clean way to override them.

**Comment by kfranqueiro** [comment]
Thanks for the feedback!

The `tone` variables are specifically computed to adhere to a minimum contrast ratio to ensure accessibility for colorblind users. This is also in line with the [WCAG 2.0 specification](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html). The color combination you show on the right falls below the WCAG minimum contrast ratio, which is why that particular `tone` variable computes to black instead.

That being said, we do plan on expanding our code to more easily facilitate customization of properties such as button background and foreground colors, so in the near future it should be straightforward for you to craft whatever combination you prefer.

The tone variables are computed very purposefully, however, so we don't plan to allow altering those specifically.
