### ISSUE TITLE
Bootstrap CSS utilities alternative

### ISSUE THREAD

**Issue by Extarys** [material-components/material-components-web#1311]
Hey,

I mnust admit that I midd all the _.col_ feature of bootstrap. And all similar little features.

But we cannot include that in a webpage with MCW since it will rewrite or at least modify other property of the elements.

Any similar library that would not interfere with MCW?

**Comment by LeviHassel** [comment]
If you want just the grid, http://flexboxgrid.com should work great and has almost the same syntax as Bootstrap. If you want a lightweight CSS framework that has a grid system and some other features comparable to Bootstrap's, I'd look into http://milligram.io.

**Comment by Extarys** [comment]
Thanks! Do you think eventually the drawer will collapse by itself on smaller device or we will need to implement this on our side?

**Comment by LeviHassel** [comment]
I'm not sure exactly how the drawer works as I haven't experienced much with it, but if you need to replace Boostrap's custom screen sizes, check this out: https://www.w3schools.com/css/css_rwd_mediaqueries.asp

Also, since in some cases, screen-size-based breakpoints  aren't the best approach (read more about this here: https://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints/), consider using CSS flexbox for a more fluid approach to the design: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

There's no one right way, just do some research and you'll find what you need. Good luck!

**Comment by Extarys** [comment]
Thanks for all that useful info! I aleays enjoy learning to do better UX ;) that is awesome

**Comment by amsheehan** [comment]
I'll try to get some clarification from design about the automatic drawer collapsing behavior @Extarys is describing above. 

As far as using MDC Web alongside other style libraries goes, it should be entirely feasible. This is why we namespace all of our classnames and use BEM syntax. If the style library itself collides with the behavior achieved through MDC Web, that would be something that would have to be solved on an implementation level.

**Comment by amsheehan** [comment]
Alright everyone thanks for your patience on this. Design does mention that the drawer should close on its own, and that there's a prescriptive subset of components that can exist inside of the drawer. Because of that, it is technically feasible to collapse the _temporary_ drawer when one of these is actioned on. That said, we are not going to bake that into MDC Web; let me explain why.

Consider a single page app that uses MDC Temporary Drawer for navigation. In this context. it's perfectly reasonable to collapse the drawer whenever a navigation item is selected since there will be no browser navigation involved, just some content being shuttled into view. Now consider any other website or app. In any other app, when a user selects a navigation item, the browser will navigate. This is problematic when we're talking about the closing animation of the temporary drawer, because it is interrupted by the page navigation. We feel this is the common case, and for that reason, are hesitant to automatically collapse the temporary drawer.

All of that is a long way of saying if you would like that functionality, we encourage you to implement it in your app using the `open` setter when a user performs an action you would like the drawer to collapse on. E.g.:

```
function navigationHandlerInYourApp() {
  // ... Do some stuff ...
  instanceOfTemporaryDrawer.open = false;
  // ... Do some other stuff and navigate when the animation is done
}
```

If you would like more assistance feel free to reach out to us on Discord. Closing.
