### ISSUE TITLE
General Feedback: Open Standards & Keep It Simple 

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#1378]
Google delivers huge value. That's probably why Google is twice the size of Amazon (in market cap terms). After several weeks, maybe months, of dealing with MDC-Web's behavior, I feel compelled to share constructive feedback. This may not be the appropriate channel, for that, I apologize. I appreciate your work and skill.

### Keep it Simple
Frameworks come, frameworks go; Microsoft Fabric is already doomed, DOA, because they force feed "React" and/or "Angular" on their users. No particular JS pattern whatsoever should be required to use MDC-Web, e.g. dialog custom events are unnecessary. JavaScript is rather easy and intuitive, yet you use "strict mode" and sophisticated patterns which, while displaying superior coding skill, scares off 95% of your consumers. 

Look at your demo's source code for the snackbar or dialog. IIFE's with "global" as an argument? What is that? It's unnecessary and introduces complexity with no added value. It actually destroys value. 

### The Trend is [not] your friend.
![image](https://user-images.githubusercontent.com/12751611/31098644-f146997e-a788-11e7-9830-c4cad578afde.png)

**Comment by acdvorak** [comment]
Thanks for the kind words! It's always nice to hear that our work is appreciated by valued members of the community 🙂

We definitely strive to keep our code and demos as simple and framework-agnostic as possible. At the same time, we also need to ensure high code quality and guard against inevitable human error.

To that end, we sometimes employ industry-standard techniques (such as strict mode) to help us avoid common mistakes that are 100% preventable. Such practices are widely accepted within the Web community because the value they provide is significantly greater than their cost.

In addition, users who are new to front-end development are only a quick Google search away from discovering what `'use strict'` is for, and stand to benefit from learning about it. We eschew [obscure language trivia](https://stackoverflow.com/a/5971668/467582) in favor of clarity, readability, and maintainability.

If you have specific concerns about our code, feel free to create separate issues for them and we will be happy to address them.
