### ISSUE TITLE
Dialog: footer buttons with <span> labels not accepting clicks

### ISSUE THREAD

**Issue by robcaldecott** [material-components/material-components-web#1400]
### What MDC-Web Version are you using?

MDC-Web: **0.22.0**
material/dialog: **0.4.5**

### What browser(s) is this bug affecting?

So far I have reproduced this on latest versions of Chrome, Firefox, IE11 and Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

1. Clone https://github.com/robcaldecott/mdc-dialog
2. Run npm install
3. Run npm start
4. Try clicking on the text of the **Click bug** button

Alternatively, copy/paste the MDC Dialog sample markup and change one of the buttons to look something like this:

```html
<button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept"><span>Accept</span></button>
```
### What is the expected behavior?

Clicks should make it through to the button.

### What is the actual behavior?

The <span> click events are ignored and the button does not work as expected.

### Any other information you believe would be useful?

We are using MDC Dialog with the popular React i18n lib **react-intl**. This lib lets you wrap translated string using a special `<FormattedMessage />` component which will load the correct string. Internally a `<span>` is then used to wrap the string.

**Comment by Garbee** [comment]
Giving the inner span `pointer-events: none;` solves the problem. Since the buttons are well scoped one solution could be to apply `.mdc-dialog__footer__button * { pointer-events: none; }` to the code. So any child node of a button wouldn't have pointer events allowing all the button logic to run as expected.

You shouldn't really ever have children of buttons with their own pointer events anyways since the button is what is expected to conduct an action.

**Comment by robcaldecott** [comment]
@Garbee That works perfectly. Many thanks!
