### ISSUE TITLE
Component internal colors are hard to change

### ISSUE THREAD

**Issue by marcosmiani** [material-components/material-components-web#1401]
Using version 0.22 of MDC Web
As a develeloper I want to customize all the colors on the components using SASS without having to overrite all the internal MDC CSS rules.

Actual case:
The Texfield case has an error color variable assigned, since isn't using the flag !default is impossible to assign a new value to that variable without modifying the internal code.

**Comment by acdvorak** [comment]
We are actively working on this 😄 

You can view the [Theme Improvements milestone](https://github.com/material-components/material-components-web/milestone/8) to track our progress.

Some of the components have turned out to be more complicated than we anticipated, but we're getting there - button and FAB are now fully customizable via mixins, and [checkbox is nearly complete](https://github.com/material-components/material-components-web/pull/1365).
