### ISSUE TITLE
Dark theme mixin for single component doesn't work properly

### ISSUE THREAD

**Issue by pndewit** [material-components/material-components-web#1412]
### What MDC-Web Version are you using?

0.22.0

### What browser(s) is this bug affecting?

Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
User agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

### What OS are you using?

macOS Sierra (version 10.12.6)

### What are the steps to reproduce the bug?

I was trying to get the dark theme working for a single button, but it didn't work until I found out the **mdc-button** element needed to be a child of the element containing the **mdc-button--theme-dark** class.

I am using the following piece of SCSS to get it to work:

    @include mdc-theme-dark(".mdc-button") {
        @include mdc-button-ink-color(text-primary-on-dark);
        @include mdc-button-ripple((theme-style: text-primary-on-dark, opacity: $mdc-unfilled-button-ripple-opacity));
    }

### What is the expected behavior?

I expected the **mdc-button** and **mdc-button--theme-dark** classes to be combined as *--theme-dark* is a modifier class.

I think this is a bug in the mixin and has impact on all components!

**Comment by acdvorak** [comment]
It sounds like you might need to set the second parameter of `mdc-theme-dark` to `true`:

```scss
.my-button {
    @include mdc-theme-dark(".mdc-button", $compound: true) {
        @include mdc-button-ink-color(text-primary-on-dark);
        @include mdc-button-ripple((theme-style: text-primary-on-dark, opacity: $mdc-unfilled-button-ripple-opacity));
    }
}
```

Then you can put all three classes on the same element:

```html
<button class="my-button mdc-button mdc-button--theme-dark">Foo</button>
```

If that doesn't fix the issue, could you possibly provide a CodePen or a min-viable Git repo/gist that clearly illustrates the problem?

**Comment by pndewit** [comment]
Ah man, thank you! That fixed the issue!
Is it an idea to make this default behaviour? (since it is a modifier class)

**Comment by acdvorak** [comment]
> Is this documented somewhere?

Yes, but not very well. The [mdc-theme README](https://github.com/material-components/material-components-web/blob/262e17b87e60d5ba2adb15135ed37386ff849fec/packages/mdc-theme/README.md) mentions it, as does a [comment in `_mixins.scss`](https://github.com/material-components/material-components-web/blob/8dfda544a016c58d913f646435f3a03c6325221b/packages/mdc-theme/_mixins.scss#L82), but neither is terribly clear.

I have a local branch that rewords those comments to be clearer, but I decided to hold off for now (see below for why).

> Is it an idea to make this default behaviour? (since it is a modifier class)

No. At least half of the usages of `mdc-theme-dark` within MDC-Web do _not_ use (and cannot use) `$compound`. I know it's not a great situation, and we considered doing some refactoring to address it, but...

We're actually planning to remove dark mode altogether.The details are still being worked out, but the current TL;DR is:

1. Dark mode adds a lot of complexity to our code (see the [discussion on #1332](https://github.com/material-components/material-components-web/issues/1332#issuecomment-335724659))
2. It makes accessibility harder, because all of our theme mixins need to know what background color they're on top of, which isn't always possible or practical
3. You can accomplish the same result (i.e., a dark theme) by simply creating a custom theme with dark colors

This decision is not final, and may change at any time, but for the moment it seems fairly likely that we will eventually remove dark mode mixins and CSS classes.

If you have compelling use cases for keeping dark mode, we're all ears 🙂 👂
