### ISSUE TITLE
Dialog body style guide (scrollable)

### ISSUE THREAD

**Issue by j-o-d-o** [material-components/material-components-web#1442]
What is the reason for having a scrollable and a not scrollable Dialog body? And then the Dialog body height is set to a very small 195px on scrollable body and has overflow: scroll so the scrollbar is always visible, even if the content does not use all the space.
Would it not make more sense to make it dynamic? e.g. Dialog body is filling the screen until a certain % and after that, the body will scroll. 
Also liked that the dialog of MDL got to fullscreen on mobile (just don't forget to add a close / cancel button :-) )

**Comment by kfranqueiro** [comment]
There are a few good questions here. I'll try to answer them all:

* The scrollable dialog is separate because it is intended for specific cases (e.g. containing a list); it's more of an exception than the norm, and in general, dialogs are encouraged to limit their content such that scrolling doesn't occur.
* Aside from the reason above, dynamically determining whether or not to allow scrolling could cross the line towards being too opinionated.
* The 195px height is an arbitrary default, intended to be overridden. This might be something for us to improve in our docs.
* RE MDL's fullscreen dialog support, I wasn't able to see this in MDL's Dialog demos even from a mobile device or with mobile device emulation, but I do see it in the spec, and it probably deserves its own enhancement issue.

**Comment by j-o-d-o** [comment]
Thanks for clarification! The docs also make this clear now. I get, that by style guide a dialog should not have overflowing content. But we are not in an ideal world and at times, this might occur. I am not sure the solution should be a dialog where bottom and top overflows out of the window view. 
Of course, the opinion starts then, e.g.: what part is scrollable, only content? is the footer/header fixed? At what % does the dialog start to scroll etc...

Here are the SCSS overrides I am currently using (for my needs), with fixed header and footer, dynamic scrolling and fullscreen on mobile: https://codepen.io/j-o-d-o/pen/KmBRMo

```
.mdc-dialog__header {
  padding-bottom: 10px;
  padding-top: 10px;
  display: block;
  border-bottom: 2px solid #e8e8e8;
}
.mdc-dialog__surface {
  max-height: 87%; 
}
.mdc-dialog__body {
  margin-top: 0px;
  overflow: auto;
}
.mdc-dialog__footer {
  min-height: 40px;
  border-top: 2px solid #e8e8e8;
}
@media screen and (max-width: 480px){
  .mdc-dialog__surface {
    width: 100%;
    height: 100%;
    max-height: 100%;
    max-width: 100%;
    overflow: auto;
  }
  .mdc-dialog__body {
    height: 100%;
  }
}
```

**Comment by piotr-cz** [comment]
IMO there should be max allowed size for form sufrace, just like it is for width [here](https://github.com/material-components/material-components-web/blob/v0.29.0/packages/mdc-dialog/mdc-dialog.scss#L65):

```css
.mdc-dialog__surface {
  max-height: calc(100% - 30px);
}
```
