### ISSUE TITLE
Radio Button default checked not working

### ISSUE THREAD

**Issue by kumaresank** [material-components/material-components-web#1459]
How to make Radio button checked by default i tried checked and selected both are not working

**Comment by hebbet** [comment]
Please provide a jsfiddle or codepen

**Comment by kfranqueiro** [comment]
The `checked` attribute on the `input` element should work, and is demonstrated in the [MDC Radio demo page](http://material-components-web.appspot.com/radio.html).

If you're still having problems after following the examples in the demo or [readme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-radio#readme), we'd really need to see a CodePen demonstrating the problem in order to help. Thanks!

**Comment by kfranqueiro** [comment]
Given no further response, and since the demo page demonstrates this, I'm going to close this issue. If you're still having a problem and can provide a CodePen demonstrating it, we'll happily take a look. Thanks!
