### ISSUE TITLE
mdc-select creates duplicates ID's in page

### ISSUE THREAD

**Issue by quicoto** [material-components/material-components-web#1480]
This question affects the accessibility and how the mdc-select handles the options values.

As can be seen here https://github.com/material-components/material-components-web/tree/master/packages/mdc-select the `<li>` id is the select value.

Our issue comes when you have 2 mdn-select in the same page and both have an option with the same value. Something quite to come across in big forms.

The result is a duplicate ID in the page. 

**Couldn't we use data attributes to handle the value instead of ID attribute?**

**Has anyone encountered this before? Is there already a workaround in place?**

### What MDC-Web Version are you using?

0.16.0

### What browser(s) is this bug affecting?

All.

### What OS are you using?

Any.

### What are the steps to reproduce the bug?

 1. Add mdn-select to page
 2. Add another mdn-select to the same page and repeat 1 option
 3. Now the page has duplicate ID's.

### What is the expected behavior?

No duplicate ID's in the page, even if I have multiple mdn-select and have options that already exist in another mdn-select

### What is the actual behavior?

Duplicate ID's in page

**Comment by RobertSmits** [comment]
I think this might fix your problem.
I took a look in the js code and it seems that you can also use the name attribute to give values to your select items. I can't find anything about it in the docs but a test showed it was working. And you can have multiple elements with the same name.

This: ```<li class="mdc-list-item" role="option" id="xyz" tabindex="0">test</li>```
Becomes: ```<li class="mdc-list-item" role="option" name="xyz" tabindex="0">test</li>```

**Comment by quicoto** [comment]
Thank you @RobertSmits it seems to work just fine. Documentation should be definitely updated to reflect this, as its a far better solution than ID's.

**Comment by kfranqueiro** [comment]
Sorry for the confusion here. I believe we have a PR in mid-review that removes those IDs from the readme, among other things.

**Comment by quicoto** [comment]
@kfranqueiro even better! Thank you

**Comment by nikolov-tmw** [comment]
For anyone stumbling across this, I took a look at the source code of version [0.31.0](https://github.com/material-components/material-components-web/blob/v0.31.0/packages/mdc-select/index.js#L128) and [0.30.0](https://github.com/material-components/material-components-web/blob/v0.30.0/packages/mdc-select/index.js#L119) and both were still using the `id` attribute.

To work around that situation, I added this shim:

```
import autoInit from '@material/auto-init/index';
import { MDCSelect, MDCSelectFoundation } from '@material/select/index';

class MyMDCSelect extends MDCSelect {
	static attachTo( root ) {
		return new MyMDCSelect( root );
	}

	getDefaultFoundation() {
		const foundation = super.getDefaultFoundation();
		return new MDCSelectFoundation(
			Object.assign( foundation.adapter_, {
				getValueForOptionAtIndex: (index) => {
					return this.options[index].getAttribute( 'name' ) || this.options[index].textContent
				},
			} )
		);
	}
}

autoInit.register( 'MyMDCSelect', MyMDCSelect );
```

The main thing here is that I only override the `getValueForOptionAtIndex` method of the default Select Foundation. Since I don't plan on using the `id` attribute for storing option values, I directly switch to `this.options[index].getAttribute( 'name' )`.

And then I just use `data-mdc-auto-init="MyMDCSelect"` in my markup to auto-initialize my custom component.
