### ISSUE TITLE
Slider keyboard events are broken in Edge/IE

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#1554]
### What MDC-Web Version are you using?

> 0.24.0

### What browser(s) is this bug affecting?

> Edge and IE 11

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

1. Open the [slider demo page](https://material-components-web.appspot.com/slider.html) in Edge and IE 11
2. Press the <kbd>Tab</kbd> key until a slider gets focus
3. Press the <kbd>→</kbd> and <kbd>←</kbd> arrow keys

### What is the expected behavior?

> The slider thumb should move right and left, and the value should increase/decrease

### What is the actual behavior?

> Nothing happens; the thumb doesn't move and the value doesn't change

**Comment by anton-kachurin** [comment]
The problem here that in IE `KeyboardEvent.key` values are not standard. According to MDN, it uses an outdated spec:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

For example, when the right arrow key pressed, in IE the corresponding event has the property
`{key: "Right"}` while MDCSlicer expects it to be `{key: "ArrowRight"}`

One possible solution might be to split the switch into two separate ones:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/foundation.js#L315

So that instead of this:
```
switch (kbdEvt.key || kbdEvt.keyCode) {
    case KEY_IDS.ARROW_LEFT:
    case 37:
        return KEY_IDS.ARROW_LEFT;
...
}
```

it will look like this:
```
switch (kbdEvt.key) {
    case KEY_IDS.ARROW_LEFT:
        return KEY_IDS.ARROW_LEFT;
...
}

switch (kbdEvt.keyCode) {
    case 37:
        return KEY_IDS.ARROW_LEFT;
...
}
```

**Comment by kfranqueiro** [comment]
Or replace the `switch` with `if` conditions that are more explicit:

`if (kbdEvt.key === KEY_IDS.ARROW_LEFT || kbtEvt.keyCode === 37)`

(Admittedly this doesn't look great but I think I'd opt for it over having 2 separate switch blocks that do the same thing.)

**Comment by lynnjepsen** [comment]
I like the if statement, seems simpler and more explicitly. Would you like to submit a PR?

**Comment by anton-kachurin** [comment]
If statements look much better, will submit a PR.
