### ISSUE TITLE
Offline documentation of MDC Web

### ISSUE THREAD

**Issue by einnar82** [material-components/material-components-web#1555]
Hello,

Is there a offline docs in the repository? Hmm.. i tried to `npm install` the repository but it made some errors.

`npm ERR! Error: EPERM: operation not permitted, scandir 'D:\App\material-compone
nts-web-master\material-components-web-master\node_modules\fsevents\node_modules
\tar-pack\node_modules'`

**Comment by Garbee** [comment]
Offline docs would be best handled by a service worker on the documentation site rather than encouraging users install the repo and try to figure it out on their own.

With the repo though, just go into the packages folder, go to the component, and look over the readme. That should be most of the content you need as far as the docs go.

**Comment by lynnjepsen** [comment]
Its probably simplest if you just clone the repo. Then you can reference the documentation offline.
