### ISSUE TITLE
Update MDC List to use mdc-states-color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1560]
Use the mdc-states-color mixin created in #1556

MDC List already uses mdc-ripple-color mixin:
https://github.com/material-components/material-components-web/blob/master/packages/mdc-list/mdc-list.scss#L158

this should be replaced with the new mdc-states-color mixin, with any relevant opacity tweaks

**Comment by kfranqueiro** [comment]
Note that list presently only applies ripple styles for upgraded ripples with JS component instances. As part of states work, we will want to apply states styles to _all_ list items by default, with an optional modifier class for opting out of this.

However, there is an issue with list / menu / drawer styles: currently, menu and drawer nuke the padding that `mdc-list` normally applies, which causes problems due to the styles applied for ripples to counteract that padding. (I'm currently under the impression that menu and drawer are applying these styles to properly support separators that extend to both edges of the list, but separators are technically part of mdc-list along with mdc-list-group, so we should probably seek to fix this in mdc-list itself instead.)

**Comment by kfranqueiro** [comment]
Resolved by #1737 + #1738 + #1739.
