### ISSUE TITLE
I guess because of the textfield changes...

### ISSUE THREAD

**Issue by jamesskyoung** [material-components/material-components-web#1587]
### What MDC-Web Version are you using?
LATEST

### What browser(s) is this bug affecting?
ALL

### What OS are you using?
MAC, WINDOWS and LINUX

### What are the steps to reproduce the bug?
Go to the textfield demo

https://material-components-web.appspot.com/textfield.html

**Result:**

/textfield.html was not found on this server.

**Comment by Nitroretro** [comment]
Hello there, I had the same problem. The link itself is broken, just go to [https://material-components-web.appspot.com/text-field.html](https://material-components-web.appspot.com/text-field.html)

**Comment by DjSloth** [comment]
instead of latest:
https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

get the previous version : 
https://unpkg.com/material-components-web@0.24.0/dist/material-components-web.min.css
<script src="https://unpkg.com/material-components-web@0.24.0/dist/material-components-web.min.js"></script>

they broke the class interface(spelling of the class) from 
window.mdc.textfield.MDCTextfield to window.mdc.textfield.MDCTextField

**Comment by jamesskyoung** [comment]
Thanks for the replies. I fixed my issue (the texttField rename).  Just wanted to point out the page is still broken...

**Comment by kfranqueiro** [comment]
This file was renamed in the latest release, and it took a day to get material.io in sync. The link from the text field page on material.io also works now.
