### ISSUE TITLE
Validation message should still behave like help text

### ISSUE THREAD

**Issue by bwobrien** [material-components/material-components-web#1590]
When the help text element (.mdc-text-field-helptext) is serving as a validation message (.mdc-text-field-helptext--validation-msg), it no longer behaves like help text. That is, when the user focuses the text field, the help text is not displayed. It is only shown when the input becomes invalid. However, help text and validation message are often related, if not the same. e.g. for a password field we would want to show a help text such as "Minimum 8 characters". If the user does not input 8 characters, then the same help text should display as a validation message (i.e. it turns red). Currently, it's only possible to have help text and validation text if the help text is persistent, as seen on the [Text Field demo](https://material-components-web.appspot.com/text-field.html) for "Password field with validation". The fact that this works implies that help text as validation text should still behave like help text and display on focus.

### What MDC-Web Version are you using?

0.25.0

### What browser(s) is this bug affecting?

All

### What OS are you using?

Ubuntu 14.04

### What are the steps to reproduce the bug?

Codepen of a Text Field with help text as validation message, but not persistent: https://codepen.io/anon/pen/zPdZdN

### What is the expected behavior?

When the user focuses the input, the help text should display so the user knows the field's requirements.

### What is the actual behavior?

When the user focuses the input, the help text does not display and thus they don't know the field's requirements. Only after the user blurs the input field do they see what error they made.

### Any other information you believe would be useful?

The help text is deliberately kept hidden on focus when the help text is also a validation message: https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/mdc-text-field.scss#L666

**Comment by robbyrice** [comment]
I think what you might be looking for is the persistent attribute that can be applied to the help text.  I've updated [your Codepen example](https://codepen.io/anon/pen/JOyNBx) to show what that would look like.

**Comment by bwobrien** [comment]
I specifically do not want the text to be persistent. I want the help text to continue to exhibit the default behavior (show on focus, hide on blur so long as there is no error).

**Comment by bwobrien** [comment]
Here's another codepen showing how I think it should work. I basically just overrode the CSS rule that hides the help text when it's also a validation message. Now the help text shows on focus. If I don't meet the input's requirements (< 8 chars) then when I blur the help text turns red. Otherwise, it hides on blur as usual.

https://codepen.io/anon/pen/bYrRYv

**Comment by anton-kachurin** [comment]
You don't have to set `mdc-text-field-helptext--validation-msg` class to the helptext element. If you omit it, there still will be a red `*` next to the label indicating that the input is invalid.

**Comment by MrKuja** [comment]
In the [demo](https://material-components-web.appspot.com/text-field.html) (MC Web v0.27.0) it should use the classes `mdc-text-field-helper-text` instead of `mdc-text-field-helptext`, like given in the documentation page.
Due to this commit : https://github.com/material-components/material-components-web/commit/1a5acee2b012120db6ae26cf2cb20ec56b73a7e9

It looks like the documentation has to be updated.

**Comment by bonniezhou** [comment]
Because the validation message can be different from the regular helper message (and because we want to support having multiple validation messages), we don't want to assume that a validation message will be also used as a regular helper message. 

In general, you can have a `mdc-text-field-helper-text` element with a regular helper message (which will appear on input focus), and use `MDCTextField.setHelperTextContent` and `MDCTextFieldHelperText.setValidation` to change it to a validation message upon invalid input.
