### ISSUE TITLE
MDC-Web Tabs Fails To Display on Dynamic Load

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#1593]
[Here's the codepen](https://codepen.io/rhroyston/pen/jaGqbW).

Issue is that when tabs are hidden with a CSS class via `display:hidden`, they do not render properly. To reproduce issue click Toggle View button in codepen[.](https://www.youtube.com/watch?v=iNK_VlIFTUI)

**Comment by anton-kachurin** [comment]
After a window resize, the behavior returns to normal. If you toggle it off and on after that, it still works normally. This suggests that the problem is that the tabs were hidden during initialization.

https://github.com/material-components/material-components-web/blob/master/packages/mdc-tabs/tab-bar/index.js#L97

Actually, `MDCTabBar` has a method called `layout`. Just call it when toggling the tabs on.
https://codepen.io/anton-kachurin/pen/VrMboo

**Comment by anton-kachurin** [comment]
**TODO:** The `layout` method needs to be documented.

**Comment by rhroyston** [comment]
👍 Thanks Anton.

**Comment by rhroyston** [comment]
I suppose I'll close this...

![image](https://user-images.githubusercontent.com/12751611/32906800-b363443c-cac3-11e7-9a35-8f390131b241.png)
