### ISSUE TITLE
remove implicit DOM querying within constants files

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#16]
See #17 

Once the above story is done, we should go back and remove places where this is happening.

> Copied from https://github.com/google/material-design-lite/issues/4746

**Comment by traviskaufman** [comment]
@amsheehan can we follow up here with all packages/foundations that will be affected by these changes?

**Comment by amsheehan** [comment]
Existing packages that will need revision:

- mdc-checkbox
- mdc-drawer
- mdc-menu
- mdc-ripple
- mdc-snackbar

We would have to change the foundations classes for each package since the plan is to ask the user to pass the component an object with a DOM object as its child (or any server side flavor thereof).
