### ISSUE TITLE
Label Selector should look for any child label, not just direct descendant

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#1607]
https://github.com/material-components/material-components-web/blob/f0b607de9b6b78f815ca29b74d5979457da7ea91/packages/mdc-form-field/constants.js#L25

Related to:
https://github.com/jamesmfriedman/rmwc/issues/26

Problem
--------
According to the docs [https://material.io/components/web/catalog/input-controls/form-fields/#usage-with-mdc-web-components ](here), FormField should work with any MDC component. 

The current LABEL_SELECTOR is too specific targeting direct children of .mdc-form-field which means you can't have a nested component.

Example
--------
```javascript
// this works
<div class="mdc-form-field">
  <input>
  <label>Hi</label>
</div>

// this doesn't
<div class="mdc-form-field">
  <div class="mdc-text-field">
    <input type="text" id="my-text-field" class="mdc-text-field__input">
    <label class="mdc-text-field__label" for="my-text-field">Hint text</label>
    <div class="mdc-text-field__bottom-line"></div>
  </div>
</div>
```

Fix
---
Would there be any issue with `LABEL_SELECTOR: '.mdc-form-field  label'`?

**Comment by amsheehan** [comment]
We're going to have to have a discussion with design to clarify the use of MDC Text Field inside of Form Fields. Currently, we use it to associate ripples with checkboxes and radios, but maybe we need to dive a little deeper.

**Comment by jamesmfriedman** [comment]
It's more of a consumer level issue. I had people wrapping TextField in FormField because they're using it for default spacing, and they think that it "should" be wrapped in a form field.

All of the components in RMWC instantiate the foundation classes by default, so this was creating an error and causing rendering failure. My interim fix was actually to just try/catch the MDC constructor and send the error through as warning.

Seems safer for my entire lib anyways since at the very least consumers will always get visual styling even if there is an error deep down in MDC.

**Comment by Garbee** [comment]
Another point here, why is it even targeting a `label` directly? It should be targeting a custom class that the developer would put on the intended label node.

**Comment by jamesmfriedman** [comment]
the docs state it will work with any label + input combo and encourages people to mark it up with there own. I honestly think just removing the direct descendant selector `>` would fix this issue.

**Comment by Garbee** [comment]
It's not about whether it works as expected. It is why target a direct type of node when it is not necessary? That is strictly enforcing a specific node type be used when there is no need for that.

**Comment by kfranqueiro** [comment]
Quoting from the docs (emphasis mine):

> mdc-form-field will work not just with input elements, but with any element as long as its **successive sibling** is a label element.

The documentation here is correct as written, and matches the code's behavior. I'll send a PR to attempt to tweak the docs a bit to make this clearer in more places.

Moreover, it does not make sense to use Form Field in conjunction with JS-enhanced Text Field (as in your example), because in that case the label is _already inside_ the text field, which would defeat the point. Form Field assists with laying out a label and _neighboring_ input/component, and links ripple activation/deactivation to the label in the case of JS-enhanced components e.g. checkbox/radio. In the case of JS-enhanced text field, however, if you're clicking the label, you're already clicking within the ripple surface, so this isn't needed.

Regarding the question of using a class selector instead of `label`, it's certainly true that we apply that principle in most cases to avoid being prescriptive about what tags to use, but Form Field's use case and functionality does specifically apply to labels, so it seems redundant in this case to require users to add an extra class as well.

**Comment by jamesmfriedman** [comment]
To be more explicit, the code does NOT currently work with a standard input label combo in cases where the label and input are nested inside of another DOM Node. The only issue here was the selector was too specific and didn't allow for any other DOM nesting and was creating issues.

Clarity in the docs would help as well, just thought ditching the direct descendant selector would make this work in more cases.

**Comment by kfranqueiro** [comment]
That's a good point, and maybe I need to do a better job in my PR of clarifying the docs...

Do you have other examples where this problem has been encountered, aside from JS-enhanced Text Field (where Form Field doesn't really make sense)?
