### ISSUE TITLE
Drawer attachTo() fails

### ISSUE THREAD

**Issue by MSbitani** [material-components/material-components-web#1643]
### What MDC-Web Version are you using?
0.25.0

### What browser(s) is this bug affecting?
Chrome 62 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36]

### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
Example: https://codepen.io/anon/pen/MOBGQb

1. Try to attach a MDCPersistentDrawer or MDCTemporaryDrawer with `attachTo()` or `new MDC...Drawer()`, **not** `autoInit()`
2. Check that the component is not attached.

### What is the expected behavior?
Using `attachTo()` or `new MDC...Drawer()` should attach the component, just as `autoInit()` does

### What is the actual behavior?
The component is not attached

### Any other information you believe would be useful?
No console log errors or warnings

**Comment by bonniezhou** [comment]
It works when the drawer object is put in a variable and the toggling of it into a function: https://codepen.io/bonniezhou/pen/ooJLLJ

I suspect that the issue is in how the drawer object is accessed in `onclick="document.querySelector('#bad').MDCPersistentDrawer.open ^= true"`...though I'm not familiar with this way of accessing objects from elements.
