### ISSUE TITLE
Use dist/*.js as package.json main entry point for each package

### ISSUE THREAD

**Issue by kripod** [material-components/material-components-web#167]
By default, ES5-compatible code should be used as entry points in order to ensure compatibility with most web browsers used today. To keep the benefits of ES6+, I would suggest using the `jsnext:main` field of `package.json`, [as suggested by the readme of Rollup](https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module).

**Comment by traviskaufman** [comment]
Hey @kripod,

Interesting suggestion! I've never seen `jsnext:main` before until now, and it actually looks like it should be ["module"](https://github.com/rollup/rollup/wiki/pkg.module).

 The reason why we originally chose to put ES2015 sources within `main` is because we assumed that if a client was importing front-end code, she was almost definitely using a module loading system, and therefore specifying our ES2015 sources as `main` would make the most sense.

The obvious drawback to this approach is that you have to make whichever module loading system you're using aware of the fact that the MDC-Web modules need to be transpiled, e.g. by including the `node_modules/@material` folder (and subfolders) for pre-processing targets by an ES2015 transpiler. However, this seemed easy enough to do, so we went for it. Looking back, I don't know if this is documented anywhere, so maybe we should ensure we do that.


My main reservation about switching `main` to be our UMD sources and `module` to be our ES2015 sources is that our built sources embed their dependencies into the output files. For example, looking at [the built @material/checkbox js](https://unpkg.com/@material/checkbox@0.1.1/dist/mdc.checkbox.js), you can see that its dependencies are included within that file. This is done intentionally, so that our built files can be used as standalone packages. I'm wary that having users import these files by default will lead to a lot of unintended increases in payload sizes.

I'd like to leave this open as a discussion for now and gather more feedback on the issue. If users are okay with making the switch, then I say we go ahead and do it. But I'd like to hear more before making a final say.

**Comment by traviskaufman** [comment]
Since it looks like no one has responded to this in a while, I'm going to go ahead and close it out. We can always come back to it in the future and look into it again.
