### ISSUE TITLE
Ripple effect freezes

### ISSUE THREAD

**Issue by desvandev** [material-components/material-components-web#178]
Whenever I click on a checkbox the ripple effect freezes. I guess this is because the animation trigger is set on focus. I suppose the animation should bounce back?.

![image](https://cloud.githubusercontent.com/assets/8462871/21934186/3f6378a0-d987-11e6-92b3-58adf71ed549.png)

![animation](https://cloud.githubusercontent.com/assets/8462871/21934554/97b7453a-d988-11e6-9f7c-2344269bf749.gif)

**Comment by traviskaufman** [comment]
You're correct that this happens because the element is focused (for example, if you're on a Mac try this within Firefox or Safari and you shouldn't see the behavior). This is actually intended behavior for the checkbox without any javascript; the ripple effect functions as the element's "focus ring", and is there for a11y purposes.  

We actually haven't added ripples to checkboxes yet (we're tracking that in #20), so what you're seeing is a gracefully-degraded version of the ripple effect when a checkbox is focused. Once we integrate the ripple, this should behave as you expect.
