### ISSUE TITLE
Proposed to launch the official framework

### ISSUE THREAD

**Issue by weihongyu12** [material-components/material-components-web#1844]
Hi,

I hope to withdraw from the official framework version. There was some demo in the previous code, but it was later removed. Although there are already developers to implement React and Vue, but the quality is uneven, and there is no uniform standardization. If there is an official version, will help promote the use of material components.

Thanks.

**Comment by acdvorak** [comment]
Unfortunately we do not have the resources or expertise to do this, which is why we let the community write their own wrapper libraries.

If the wrappers look decent and are actively maintained, we link to them in our main [README](https://github.com/material-components/material-components-web/blob/master/README.md).
