### ISSUE TITLE
bug(ripple): Clicking on element with ripple, stays highlighted.

### ISSUE THREAD

**Issue by izakfilmalter** [material-components/material-components-web#1951]
Seems that with the new ripple mixins, everything that has a ripple stays active when selected.

![](https://d2ffutrenqvap3.cloudfront.net/items/3S3d3X0L0w0b3b361Z36/Screen%20Recording%202018-01-12%20at%2009.27%20AM.gif?v=717ddd1a)

I am not sure if this is the new design direction, or regression. One area that this causes problems is with a long list of `mdc-list-item mdc-ripple-upgraded`. On android when you scroll this list, each one gets this selected state that you touch as you are scrolling through it.

Is there a simple way of disabling this?

**Comment by izakfilmalter** [comment]
After doing some more digging. Seems like the following class stays active on the tab: `mdc-ripple-upgraded--background-focused`.

**Comment by izakfilmalter** [comment]
When a `mdc-tab` is a `a` tag you get this issue. If it is any other tag eg `span`, this goes away.

**Comment by acdvorak** [comment]
Thanks for filing this issue and including a super-helpful video!

RE your first question: The new ripple focus behavior is intentional for UX and accessibility reasons. Whenever the browser tells us that a focusable\* element received focus - via either the `:focus` CSS selector or the `focus` JS event - we render it in a focused state, with a slightly darker background, so that the user knows where focus will go when they press the <kbd>Tab</kbd> key.

_\* A "focusable element" is one that the browser allows the user to focus without any special markup (e.g., `<a href="...">`, `<button>`, `<input>`), or a non-focusable element (like `<span>`) that has been made focusable by giving it a `tabindex="0"` attribute._

The `MDCTab` constructor creates a ripple automatically, so the only way to prevent the focus state from showing on a tab is to make the tab non-focusable (e.g., by using a `<span>` element). I **do not recommend this**, as it will make your tabs unusable for many people.

RE accidental activation while scrolling: There's an open bug for that: #1080
