### ISSUE TITLE
permanent drawer not taking full height of the page

### ISSUE THREAD

**Issue by prakharrke** [material-components/material-components-web#1962]
While using permanent drawer, the drawer does not take full height of the height. How to make it do that?

**Comment by RyanSquared** [comment]
Please fill out the following information:

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

> Please be specific, e.g. _major.minor.patch_

### What browser(s) is this bug affecting?

> Please include the browser version. A user-agent string is also quite helpful.

### What OS are you using?

> Please include the OS version.

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible, e.g.
>
> 1. Run the demo server
> 2. Go to localhost:8080/textfield.html
> 3. Tab-focus on the first text field
> 4. Observe the component's behavior
>
> We also have a [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) which we encourage you to use to create a reproduction of
> the issue. The less time it takes for us to repro the issue, the less time it takes to verify and
> fix it!

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.

### What is the actual behavior?

> Please describe what the component/code is actually doing that's different from what it should be
doing.

### Any other information you believe would be useful?

**Comment by prakharrke** [comment]
Got it fixed. Thank you. Closing the issue.
