### ISSUE TITLE
Implement multi-select component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#2]
Extricated from https://github.com/google/material-design-lite/issues/4475
> Copied from https://github.com/google/material-design-lite/issues/4948

**Comment by amsheehan** [comment]
Here is a first cut at multi select.

I think it should be included in the mdc-select package, since currently there is only an HTML/CSS implementation of multi-select on the roadmap. As a result, to turn a select into multi select, the user must only set the `multiple` attribute.

Thing to consider:

- Should dividers always span the width of the select box (regardless of nesting)?
- Should dividers have vertical padding?


[Codepen](https://codepen.io/amsheehan/pen/xRyNdo)
[MDC Select README changes](https://gist.github.com/amsheehan/81ec49d3f692faf5527a830f24662fc9)

**Comment by traviskaufman** [comment]
@amsheehan LGTM on the whole. Only thing is on the Codepen, I can focus the list dividers. I think it needs a `disabled` attribute in addition to `role="presentation"`, since it's an option. Also, I think there's a blank final option but that's nbd.
