### ISSUE TITLE
Text fields are not visible with the dark theme

### ISSUE THREAD

**Issue by arnaudby** [material-components/material-components-web#2086]
### What MDC Web Version are you using?

> 0.29.0

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> Ubuntu 17.10

### What are the steps to reproduce the bug?

> 1. Go to the demo page https://material-components-web.appspot.com/text-field.html
> 2. Check box Dark Theme

### What is the expected behavior?

> Contrast in colors

### What is the actual behavior?

> Text is not visible

**Comment by moog16** [comment]
We are in the process of removing dark theme https://github.com/material-components/material-components-web/pull/2106. Please use the sass mixins that we have provided. In your case since you need to update the text color, you can use `mdc-text-field-ink-color($color)`.

For further customizations please refer to https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#sass-mixins. We also show case these in our demo pages.
