### ISSUE TITLE
textarea without border

### ISSUE THREAD

**Issue by MrChriZ** [material-components/material-components-web#2157]
Is there any provision for a multiline textarea without a border like in this MDL demonstration:
https://getmdl.io/templates/portfolio/contact.html

So as to match the standard text-fields?

**Comment by bonniezhou** [comment]
Thanks for your question! There are no plans for a standard-style textarea like the one in your demo because it results in a poor user experience: the large amount of white area with no defining border means that it's unclear where the user should click, where focus/the cursor would land, or even that it's a textarea at all.
