### ISSUE TITLE
Textfield - Add icon signifier

### ISSUE THREAD

**Issue by jfily** [material-components/material-components-web#2164]
Hello,

As far as i know, there is no way to add an icon signifier for textfield like described in Material Design specs
![image](https://user-images.githubusercontent.com/10220170/35721579-f5b59e22-07f2-11e8-9655-b49ff60821e7.png)
In mdc, trailing icon only works with boxes and outlined textfields.

I've done a quick workaroud but didn't fully test it : https://codepen.io/jfily/pen/GQoKaV

**Comment by kfranqueiro** [comment]
That's correct; we've only implemented leading/trailing icons specifically for the box and outlined variants, where it's more necessary to be handled internally, since the icon needs to fit within the component's bounding box. There's a note about this in the [icon readme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/icon), but I'll add a clarification to the top-level text field readme as well.
