### ISSUE TITLE
Menu: initial open state -> wrong position of menu

### ISSUE THREAD

**Issue by j-o-d-o** [material-components/material-components-web#2217]
### What MDC Web Version are you using?
0.30.0

### What browser(s) is this bug affecting?
Chrome 64.0.3282.140

### What OS are you using?
Win 10

### What are the steps to reproduce the bug?
Use the `mdc-menu--open` class on the menu.
https://codepen.io/j-o-d-o/pen/zppEdL

### What is the expected behavior?
The menu is open as usual

### What is the actual behavior?
The menu is shifted to the right of the button that is opening the menu.

### Any other information you believe would be useful?
I am not sure this is on purpose or if it is a bug?

**Comment by kfranqueiro** [comment]
MDC Menu runs positioning logic when the component's `open` property is set, so that's really the intended way of opening the menu. The positioning logic became more complex as of 0.28.0, but even prior to that, I am under the impression that manually applying the class would not have worked.

It's quite likely we never considered having a menu that was initially open, so I'm curious what your use case is?

If you're looking to have a statically-positioned list of items, it may be more appropriate to use `mdc-list` directly instead.

**Comment by j-o-d-o** [comment]
I don't have a direct use case for myself. I was just playing around and trying out some features the docs where describing. In this particular case: 

> The menu can be configured to start in the opened state by adding the mdc-menu--open class to the element.

And as an example the docs show this code:
```html
<div class="mdc-menu mdc-menu--open">
...
</div>
```

**Comment by kfranqueiro** [comment]
Whoops. Yeah, I just combed through history and these docs are clearly from a _much_ earlier time (like, October 2016 earlier), before _any_ auto-positioning code existed. It seems like the code evolved a couple of times since then, and these docs were never properly pruned.

Thanks for poking around and running across this! I'll send a PR to fix the docs.
