### ISSUE TITLE
Ripple effect looks weird when building with webpack

### ISSUE THREAD

**Issue by yannski** [material-components/material-components-web#2233]
### What MDC Web Version are you using?

0.30.0

### What browser(s) is this bug affecting?

Chrome, Firefox

### What OS are you using?

Linux

### What are the steps to reproduce the bug?

Import MDC Web through webpack with this line:
```
@import "~material-components-web/material-components-web";
```

### What is the expected behavior?

Ripple effect should look like the demo on appspot demo

### What is the actual behavior?

Same weird looking described in #1184

### Any other information you believe would be useful?

When I include MDC Web CSS https://unpkg.com/material-components-web@0.30.0/dist/material-components-web.min.css with a link tag without building with webpack, everything looks normal.

**Comment by kfranqueiro** [comment]
I just tried reproducing this using a CSS file compiled using `node-sass` and don't see an issue with ripples. It's odd that this would break specifically with locally-compiled scss but work with what should effectively be the same scss online though, if everything else remains constant...

I guess one thing you could try is build a scss file that _only_ includes material-components-web.scss, and diff the output against https://unpkg.com/material-components-web@0.30.0/dist/material-components-web.css?

The issue you pointed to was a very specific regression due to style changes that had unintended side effects, and the change in question was reverted the same day that was reported, so I'm very surprised if that's exactly what you're seeing (unless you're invoking the `mdc-ripple-radius-unbounded` mixin with values that are too small).

Something I'd expect to be more likely is that you're instantiating ripples on components that aren't initially in document flow, and need to call `layout` on those ripple instances when their surfaces are displayed, but I'd expect that to happen regardless of using unpkg's CSS or your own.

If you still experience the issue after the ideas above, can you reduce it to a simplified case and post the HTML that you're using to reproduce the issue?

**Comment by ombimo** [comment]
@yannski did you use default mdc-ripple-surface or use sass mixin to produce new ripple class ?
![image](https://user-images.githubusercontent.com/20896126/36144003-4c2bfa18-10df-11e8-817f-c6089447cd80.png)
when i use mixin, i have same problem with you. but when im use mdc-ripple-surface no problem anymore

**Comment by yannski** [comment]
I didn't add any sass mixins. I just initialized the JS component like this:
```js
import {MDCRipple, MDCRippleFoundation} from '@material/ripple'

document.querySelectorAll('.mdc-button, .mdc-ripple-surface').forEach((elem) => {
  new MDCRipple(elem)
})
```

**Comment by yannski** [comment]
@kfranqueiro thanks for your suggestion. I'm a noob with MDC Web (currently transforming a project from Bootstrap Material Design to "pure" MDC Web). Is there some kind of jQuery DOM Ready stuff to be sure to run my JS code after the elements are rendered?

**Comment by ombimo** [comment]
@yannski im currently using laravel-mix (webpack), and i initialized the JS like yours and it work.
did you attach mdc-ripple-surface in inline element (display: inline)?

**Comment by yannski** [comment]
@kfranqueiro  I've just noticed this warning in my wepack output:
```
webpack_1   |     WARNING in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/usr/src/app/.postcssrc.yml"}}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"includePaths":["node_modules"]}!./app/javascript/css/application.scss
webpack_1   |     (Emitted value instead of an instance of Error) postcss-custom-properties: /usr/src/app/node_modules/@material/ripple/_mixins.scss:27:2: Custom property ignored: not scoped to the top-level :root element (.mdc-checkbox { ... --mdc-ripple-fg-translate-end: ... })
webpack_1   |     NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /usr/src/app/node_modules/@material/ripple/_mixins.scss:27:2: Custom property ignored: not scoped to the top-level :root element (.mdc-checkbox { ... --mdc-ripple-fg-translate-end: ... })
webpack_1   |         at Object.emitWarning (/usr/src/app/node_modules/webpack/lib/NormalModule.js:117:16)
webpack_1   |         at result.warnings.forEach (/usr/src/app/node_modules/postcss-loader/lib/index.js:149:49)
webpack_1   |         at Array.forEach (<anonymous>)
webpack_1   |         at postcss.process.then (/usr/src/app/node_modules/postcss-loader/lib/index.js:149:27)
webpack_1   |         at <anonymous>
```

Could this be related?

**Comment by yannski** [comment]
After a few tests, I'm pretty convinced the problem lies with the webpack loaders/modules somewhere, not in the material stuff :)

**Comment by yannski** [comment]
By removing postcss-cssnext from the postcss stuff, I get it working normally (I'm using Rails with webpacker and that was the default)

**Comment by moog16** [comment]
@yannski are you saying that cssnext conflicts with ripple? Which part of cssnext do you think was affecting it?

**Comment by moog16** [comment]
close
