### ISSUE TITLE
Placeholder in text fields

### ISSUE THREAD

**Issue by dflorey** [material-components/material-components-web#2336]
Material design specifies placeholder in text fields (see placeholder section):
https://material.io/guidelines/components/text-fields.html#text-fields-layout

Is there a way to set the placeholder in MDC web? If yes, it would be great to have such an example on the demo page.
It requires that the label is always on top of the text field (non floating) and that the placeholder is in gray instead of the theme primary color.

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. Could you provide some detail about your use case? I'm curious why the floating label is undesirable in this instance.

Also, is it placeholder you want to set or the default value? The placeholder is in gray to show the user that it's not a user-supplied value.

Thanks!

**Comment by suneelv** [comment]
Hi @patrickrodee , placeholder might be useful to provide additional hint about the type of input the user is expected to enter. An example use case can be a date input asking the user for his birthdate. In this case label will be "Birth Date" and placeholder can be date format like "DD/MM/YYYY" or "DD.MM.YYYY"

**Comment by dflorey** [comment]
I want to set a label, a placeholder, a help text and - if available - a default value.
Just check out the examples on the material.io page using the provided link e.g. the Destination or Phone number use case.
It would be great if the demo site would provide all the examples from material.io implemented with MDC.

**Comment by patrickrodee** [comment]
Thanks for explaining your use cases!

**Comment by patrickrodee** [comment]
After discussing with design, we’ve decided not to implement placeholder support for now. We’ll revisit this later but I’m going to close this for now.

Thanks for providing examples of your usecases for placeholder. It’ll be helpful if we revisit this in the future.

**Comment by rosenbjerg** [comment]
For anyone looking for a workaround that will be enough for some cases:
```
.mdc-text-field:not(.mdc-text-field--focused) .mdc-text-field__input::placeholder {
    opacity: 0;
}
```

I'm experiencing the issue in `material-components-web v. 0.38.0` and this is my "fix" for now

**Comment by sharpmachine** [comment]
Another use case for this: Let's say I'm building a chat app, so i have a text field for sending chat messages. I don't want or need a label (floating or otherwise), but I still want a placeholder like "say something…". The current implementation wont allow me to accomplish this. So it forces me to use `value` as the placeholder. But to mimic the behavior of a placeholder, I need to make the default input text color gray, clear the value and set the text color to black using `onFocus`, and then set it back it it's default state after submitting the message (using either the enter key or clicking the trailing icon) or `onBlur`. It's a crazy long workaround for something as simple as a placeholder.
