### ISSUE TITLE
Creating Jasmine tests for code that uses material components

### ISSUE THREAD

**Issue by FirebertNY** [material-components/material-components-web#2359]
### What MDC Web Version are you using?

0.31.0

### What browser(s) is this bug affecting?

n/a

### What OS are you using?

Win10

I am having trouble figuring out how I should be writing jasmine tests for my controllers that use material components. The components assume there is a document, which there isn't when I'm running my tests. I feel like I should be able to write a unit test for a function that uses material components, but I'm not sure how to get around this issue. Has anyone else experienced this and figured out the appropriate way to handle it?

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. Given that our components are meant for use inside a browser, they'll always require access to the DOM. Since this issue is based off issues with the test environment, I'm going to close it.

I'd suggest checking out [Karma](https://github.com/karma-runner/karma) and the [Karma Jasmine runner](https://github.com/karma-runner/karma-jasmine). They'll help you resolve those DOM issues.

Thanks!
