### ISSUE TITLE
Unpkg Cannot find module for MDCRipple's minified distribution 

### ISSUE THREAD

**Issue by TangSteven** [material-components/material-components-web#2393]
### What MDC Web Version are you using?

0.32.0

### What browser(s) is this bug affecting?

65.0.3325.125 (Official Build) beta (64-bit)

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Visit https://unpkg.com/@material/ripple@0.32.0/dist/mdc.ripple.min.js

### What is the expected behavior?

It should actually host a minified version of the JavaScript like the previous version: https://unpkg.com/@material/ripple@0.31.0/dist/mdc.ripple.min.js

### What is the actual behavior?

Cannot find module "/dist/mdc.ripple.min.js" in package @material/ripple@0.32.0

**Comment by patrickrodee** [comment]
Thanks for submitting an issue. Sorry about that unpkg weirdness.

However, it does seem to be working now, so that's good!

From looking into unpkg, it appears to not load a resource until it's requested for the first time. The most-likely source of the problem you encountered is that the 0.32.0 release of mdc.ripple.min.js hadn't been requested yet.

There's more info about on [this unpkg issue](https://github.com/unpkg/unpkg/issues/38#issuecomment-305313002).

I'm gonna close this since it's now working.
