### ISSUE TITLE
Revert `mdc-select` to use the `<select>` element

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2399]
We initially removed this because we we're trying to style `mdc-select` so it used `mdc-menu`. But we discovered that we lost a lot of native functionality with the `<select>` element. So we will remove `mdc-select`'s dependency on `mdc-menu`, and instead use the native `<select>` element

**Comment by kfranqueiro** [comment]
One thing worth noting which had contributed to why we removed this: we ran into an issue due to the `select` no longer being the root element of the CSS-only version after it was re-styled to match Text Field Box in #1097. This caused awkwardness due to remaining top-level styles selecting on the disabled (or aria-disabled, can't remember) attribute, meanwhile the nested `select was the actual element that needs to be functionally disabled. Ideally, users shouldn't need to set attributes or classes on more than the `select` element itself.

If we're seeking to revert to code that existed several versions back, we should make sure to avoid this situation, presumably by making styles work with `select` as the root element.

**Comment by djensen47** [comment]
I understand there were technical reasons for this but 🤦‍♂️ omg, this looks terrible. 

I've read through a few of the issues to get an idea of what's going on. My realization is that this library is being built for Google internal use (and at this rate maybe not even that) but it happens to be open source. Unfortunately I chose this library thinking that Google was building for developers, like the Android libraries. I was mistaken and that's my bad, it's free so I shouldn't complain, I've just made a terrible mistake and I hope others don't make the same mistake.

### The new implementation

![image](https://user-images.githubusercontent.com/527865/38234685-6fe9c34e-36d3-11e8-81dd-ba0bd99fb2f4.png)


### From the spec

![image](https://user-images.githubusercontent.com/527865/38234577-22afab84-36d3-11e8-9cd0-d5e8a4d7d25f.png)

**Comment by djensen47** [comment]
Throwing out the baby with the bath water?

**Comment by dessant** [comment]
What is the native functionality you have lost that could not have been possible to implement without reverting to the native select element?

**Comment by kfranqueiro** [comment]
There are a few reasons we wanted to take advantage of native select:

* Interoperability with native HTML forms (#2221)
* Keyboard type-ahead accessibility (#1961)
* Automatically gets an appropriate UI on mobile devices (e.g. a list dialog on Android) rather than potentially ending up stuck with a menu that doesn't even fit on the screen

While it's of course theoretically possible to implement these features with more JavaScript, we opted to take advantage of the platform rather than add a great deal of complexity (and bytes) to the MDC Select which would require a significant amount of time to complete and maintain.

MDC Menu will continue to exist for other use cases, but for cases where form input is involved, wrapping and reusing the native select element is the most expedient solution.

**Comment by dessant** [comment]
Thanks for the reasoning, I can understand the desire to avoid the additional maintenance and the catch-up game with native features, though this decision will likely face contention and drive some users away.

Native select elements cannot be reliably styled, and they do look unpleasant and out of place compared to the rest of the Material Design spec, especially in desktop browsers.

**Comment by djensen47** [comment]
> ... though this decision will likely face contention and drive some users away.
>
> Native select elements cannot be reliably styled, and they do look unpleasant and out of place compared to the rest of the Material Design spec, especially in desktop browsers.

Agreed. A nice, consistent select box is on my list of must-haves for UI frameworks. If I were deciding on a UI framework now, I'd probably go to Materialize for this very reason. I could tolerate the inconsistencies of Materialize in favor of a clean, consistent and nice looking select box.

Instead, the project punted to MDC Menu. If that's the case, why not just go ahead and create **MDC Select Menu** as a separate component from MDC Select. When the time is right, combine the two but in the meantime, allow the developer to choose which one is right for their situation.

**Comment by danielweck** [comment]
I hope you guys ; or external contributors ; find the bandwidth to (re)implement the MDCMenu-based alternative to the native 'select'. As I also mentioned in this related issue ( https://github.com/material-components/material-components-web/issues/2552#issuecomment-382415822 ), I understand the rationale for favouring the native 'select' widget instead of a custom MDCMenu-based renderer. I also appreciate that the development team has limited resources and must therefore make hard choices, such as focusing its efforts on native 'select' only (i.e. complete removal of the MDCMenu alternative).

However, this breaking change from 0.33.0 to 0.34.0 (see: https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md ) totally blows existing apps that make use of the old UI paradigm, which contradicts Semantic Versioning for a "minor" increment (see: https://semver.org ).

I am tempted to rollback to 0.33.0 in my project, but I would also like to keep up to date with the latest developments ... the more I postpone the inevitable upgrade, the harder it will be to update my code in the future (because of the accumulation of breaking API changes). So in the interim, I am going to (try to) put together my own MDCMenu-based "selector" component.

**Comment by Nerg4l** [comment]
The minor version (https://semver.org/#spec-item-7) you refer to in your comment states

> Minor version Y (x.Y.z | x > 0) MUST be incremented if [...]

Which means only if the Major version (x) is greater than 0.

And also in the FAQ about rapid development and fast iteration (https://semver.org/#doesnt-this-discourage-rapid-development-and-fast-iteration)

> Doesn't this discourage rapid development and fast iteration?
> Major version zero is all about rapid development. If you’re changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version.

So this is not a violation of semantic versioning.

**Comment by danielweck** [comment]
@Nerg4l that was my point exactly in the other issue ( https://github.com/material-components/material-components-web/issues/2552#issuecomment-382415822 )

That'll teach me for cross-posting ;)
