### ISSUE TITLE
mdc-ripple or mdc-toolbar: Ripple is being cut out

### ISSUE THREAD

**Issue by pshe94** [material-components/material-components-web#2431]
### What MDC Web Version are you using?

> 0.32.0

### What browser(s) is this bug affecting?

> Chrome 66.0.3359.33, Edge 41.16299.248.0 (EdgeHTML 16.16299)

### What OS are you using?

> Windows 10 1709

### What are the steps to reproduce the bug?

> 1. Go to [demo page of toolbar](https://material-components-web.appspot.com/toolbar/index.html)
> 2. Press one of the icons in toolbar that has ripple attached to it (for example Bookmark icon)

### What is the expected behavior?

> Ripple should not be cut out.

### What is the actual behavior?

> Ripple is cut out from right and bottom side (in Chrome) and top and left side (in Edge) by 1px. In Firefox 60.0b4 this problem doesn't occur.

Chrome:
![image](https://user-images.githubusercontent.com/34661843/37573974-8772bf00-2b1d-11e8-8cd5-a0680ee78889.png)

Edge:
![image](https://user-images.githubusercontent.com/34661843/37574029-14bb071e-2b1e-11e8-89f7-2f4fcfde51ef.png)

### Any other information you believe would be useful?

> This problem might be related to #1753, but I'm not sure.

**Comment by acdvorak** [comment]
I think this is a subpixel rendering issue.

`--mdc-ripple-fg-size` has a fractional value of `28.8px`.

If you wrap the `initialSize_` calculation in `Math.floor()`,
the resulting `28px` seems to render correctly without getting cut off.

Change this line:

https://github.com/material-components/material-components-web/blob/670c349417ef7922aac37f1c8cd1682f93b41794/packages/mdc-ripple/foundation.js#L520

to this:

```js
this.initialSize_ = Math.floor(maxDim * MDCRippleFoundation.numbers.INITIAL_ORIGIN_SCALE);
```

**Comment by williamernest** [comment]
Thanks for filing this issue. We've added it to our tracker.

**Comment by acdvorak** [comment]
This issue affects all _unbounded_ ripples (e.g., [icon-toggle](https://material-components-web.appspot.com/icon-toggle.html)).

To correct my [earlier comment](https://github.com/material-components/material-components-web/issues/2431#issuecomment-374355442): There are actually _two_ CSS properties that get multiplied together to determine the rendered size of the ripple:

```css
--mdc-ripple-fg-size: 28.8px;
--mdc-ripple-fg-scale: 1.66667;
```

I'm guessing that the cutoff happens because `28.8 * 1.6666 = 47.99` which is not _quite_ a whole number, so the browser tries to do subpixel rendering.

### Surface element (48px):
![image](https://user-images.githubusercontent.com/409245/37670297-2a899188-2c26-11e8-9a28-b4f43734c71a.png)

### `::before` pseudo-element (47.99px):
![image](https://user-images.githubusercontent.com/409245/37670309-323c1afe-2c26-11e8-94bc-fa7aee95137c.png)

**Comment by touficbatache** [comment]
Hi @acdvorak, why not have a `Math.round()` around `28.8 * 1.6666`? It would be 48
