### ISSUE TITLE
Button with ripple problem

### ISSUE THREAD

**Issue by jhonToni** [material-components/material-components-web#2458]
I have read the [Getting started](https://material.io/components/web/docs/getting-started/) page of the documentation and I tried to create the proposed web page .

I have visualized  the created  web page in the browser (Google Chrome), I clicked on the rippled button , but the button has changed color instead of changing  opacity.

How can I solve the problem?

[My source code ](https://github.com/jhonToni/Material-design-web-site-demo.git)

**Comment by kfranqueiro** [comment]
This looks like it's caused by the same problem as #2410: variables in the ripple mixins aren't getting interpolated properly. Similarly to that issue, if I roll back node-sass in your repo to 4.7.2, the issue goes away.

IIRC at the time #2410 came up, node-sass 4.8 hadn't been published publicly to npm, but it looks like that's changed now, and 4.8.3 is being pulled in to match `^4.7.2`.
