### ISSUE TITLE
mdc-text-field in mdc-menu doesn't accept spaces

### ISSUE THREAD

**Issue by QJan84** [material-components/material-components-web#2471]
See [#2422](https://github.com/material-components/material-components-web/issues/2422) (closed)

I have the same problem.
I have an input (free user input) in a MDCSelect menu and can also enter here no space.

---
![select-input-1](https://user-images.githubusercontent.com/18675776/37970307-730c920e-31d3-11e8-97b7-4501a8fa4ec9.png)
---
![select-input-2](https://user-images.githubusercontent.com/18675776/37970315-75a76804-31d3-11e8-8aa3-f9b0dc1a3b48.png)

**Comment by williamernest** [comment]
@QJan84 The material menu is not designed to contain input elements. It's designed to allow you to make a single selection from a list. We disable the space key event to prevent inadvertent scrolling of the page while interacting with the menu.

**Comment by apoterenko** [comment]
Ohh... Guys...

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Sadly this is not a use case we can support right now 😢

The problem is that the current menu component assumes it only contains list items, which are selected with the <kbd>Space</kbd> key. So it needs to prevent the browser's default behavior of scrolling the page when the <kbd>Space</kbd> key is pressed in order to improve UX.

We would love to find a way to allow clients to customize that behavior, but doing so would require a substantial rewrite of the menu component, and unfortunately we don't have the resources to do that right now.

(FYI, the "select" component was simplified to use a native `<select>` element in #2462.)
