### ISSUE TITLE
Re-Publish @material/top-app-bar on NPM 

### ISSUE THREAD

**Issue by MarkOGDev** [material-components/material-components-web#2554]
Hello,

Please republish https://www.npmjs.com/package/@material/top-app-bar to add the latest features.
E.g. Fixed Toolbar.

Regarding version number, seems a bit confusing when both github and npm say v0.34.1 but they have different files. 

Shouldn't the additional code be added to a separate branch; then when ready merged with master branch and published to NPM at the same time?

Kind Regards,
Mark.

**Comment by williamernest** [comment]
@MarkOGDev Thanks for the question. We usually publish to npm on a 2 week cycle. I say usually because we're delaying our current release for 1 additional week, so you can get the `--fixed` top app bar variant in the v0.35.0 release that will be published on April 23rd. 

Our development process is to use the master branch as our constant sprint branch and to tag/release versions from that branch on a set cycle. So the commits that get merged into master won't be reflected in npm until the next release.
