### ISSUE TITLE
Select component is not Material design Why ?!

### ISSUE THREAD

**Issue by HamedFathi** [material-components/material-components-web#2749]
I just ran your online demo for Select component Why is it not material design ?!

![1](https://user-images.githubusercontent.com/8418700/40161190-386ed5d4-59c5-11e8-9c8c-dddb744ea600.png)

While in other Material Design components Select component is good !!!

**Angular material:**
![2](https://user-images.githubusercontent.com/8418700/40161293-8e03dc6a-59c5-11e8-8be9-d0b63bc06d2a.png)

**Materialize:**
![3](https://user-images.githubusercontent.com/8418700/40161338-bca74426-59c5-11e8-9f42-da434641c7c6.png)

Can you say why?!

**Comment by merlinnot** [comment]
Select element is not finished yet AFAIK. Components which are considered "done" are being published to the NPM registry. Select element is not.

**Comment by HamedFathi** [comment]
@merlinnot 

How can I find `done` and `undone` components?

**Comment by merlinnot** [comment]
https://www.npmjs.com/search?q=%40material%2Fmwc-

**Comment by kfranqueiro** [comment]
FYI, the `@material/mwc-*` prefixed packages are Web Components implementations specifically, not the core vanilla Web implementations (which are simply `@material/*` with no further prefix).

https://github.com/material-components/material-components/blob/develop/ROADMAP.md provides a more cohesive view across platforms of what is currently implemented against the new Material Design guidelines, and what we're aiming towards in the near future.

As to the original question:

MDC Select's use of the native HTML select was a conscious decision discussed with the design team pertaining specifically to the web platform. Using the native HTML select immediately offers far superior usability and interoperability with HTML forms.

From https://github.com/material-components/material-components-web/issues/2399#issuecomment-378626129:

> * Interoperability with native HTML forms (#2221)
> * Keyboard type-ahead accessibility (#1961)
> * Automatically gets an appropriate UI on mobile devices (e.g. a list dialog on Android) rather than potentially ending up stuck with a menu that doesn't even fit on the screen, or requiring two versions of markup
> 
> While it's of course theoretically possible to implement these features with more JavaScript, we opted to take advantage of the platform rather than add a great deal of complexity (and bytes) to the MDC Select which would require a significant amount of time to complete and maintain.
> 
> MDC Menu will continue to exist for other use cases, but for cases where form input is involved, wrapping and reusing the native select element is the most expedient solution.

There is a separate issue #2552 tracking an enhancement for a select using MDC Menu, but it is lower priority than other components on our roadmap given the effort it would involve simply to achieve parity with the usability already present in the native element. (Do all of those other implementations pictured above implement all of those features?)

Since there is already an issue representing this, I'm going to close this one.
