### ISSUE TITLE
Need a basic sample template for top nav bar

### ISSUE THREAD

**Issue by voletykiran** [material-components/material-components-web#2759]
Can you provide a basic template for the top nav bar included with tabs and a search icon as in the template of [material.io](url)

I'm trying to implement it but unfortunately it was not aligning the icons with the tabs.

I need to build exactly the same as on the site for desktop and for mobile. Please provide me the media screens for them too.

![1](https://user-images.githubusercontent.com/1023081/40249256-082bcc2a-5af0-11e8-810c-c0f145aa193b.png)

When its on mobile it should look like this

![2](https://user-images.githubusercontent.com/1023081/40249287-1e664916-5af0-11e8-893f-5d1ed2554ad3.png)

Lastly when selected search icon a textbox should be shown
![3](https://user-images.githubusercontent.com/1023081/40249317-3b67d462-5af0-11e8-9982-d842924f3d34.png)

**Comment by williamernest** [comment]
@voletykiran Thanks for filling this issue. The material.io page isn't using our top app bar component just yet, because it wasn't ready for them in time. You can take a look at the examples we have for our current top app bar on our catalog page. Our current tabs component can be embedded into the top app bar, but you may need to adjust some styles to get the exact layout shown on the material.io page. 

https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar
