### ISSUE TITLE
Shape doesn't work with hosted version

### ISSUE THREAD

**Issue by danieldaeschle** [material-components/material-components-web#2764]
Browser: Chromium

## Bug
![image](https://user-images.githubusercontent.com/30751516/40258036-88384eca-5af0-11e8-9c7a-a1695d119d3c.png)

with code:
```
<div class="mdc-shape-container my-shape-container">
    <button class="mdc-button mdc-button--unelevated">Button</button>
    <div class="mdc-shape-container__corner mdc-shape-container__corner--top-left"></div>
    <div class="mdc-shape-container__corner mdc-shape-container__corner--top-right"></div>
    <div class="mdc-shape-container__corner mdc-shape-container__corner--bottom-right"></div>
    <div class="mdc-shape-container__corner mdc-shape-container__corner--bottom-left"></div>
</div>
```
from [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-shape)

There are no edged corners!

In head i have this scripts:
```
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
````

**Comment by kfranqueiro** [comment]
MDC Shape does not provide any predetermined shape styes OOTB, since there's no way of knowing how large the cut corners should be.

The [Styles section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-shape#styles) of the README includes an example of including a mixin invocation to apply cut corners for an outlined surface.

Moreover, the [Sass mixin](https://github.com/material-components/material-components-web/blob/v0.35.1/packages/mdc-shape/_mixins.scss#L18) that provides these styles computes math based on the passed-in desired corner sizes. If exposing this through CSS variables were possible, it'd at minimum require a significant amount of additional styles OOTB relying on CSS `calc` invocations, which aren't needed at all when using the Sass mixin directly.

This is a feature that takes advantage of the Sass preprocessor in order to present a usable API with minimal CSS output. It's unfortunately not going to be nearly as helpful using precompiled styles via CDN.

**Comment by danieldaeschle** [comment]
Ok :/

**Comment by pspeter3** [comment]
I've also had issues with shapes and the SCSS mixins not producing any cuts. Specifically following the documentation on the website.

**Comment by danieldaeschle** [comment]
Are you using scss? This issue is only for hosted css version which doesn't include scss mixins.

**Comment by danieldaeschle** [comment]
I would suggest to create a new issue
