### ISSUE TITLE
Deprecate and delete the non-box version of text field

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2780]
The Material guidelines only specify the box and outlined variants of text field.
https://material.io/design/components/text-fields.html#spec

The current "non-box" version of text field should be deprecated.

The Material research team showed that the box and outlined variants of text field are much more discoverable by users, which is why the Material guidelines stopped recommending the non-box version.

**Comment by robcaldecott** [comment]
Gulp. This is a big UX change. Can't you leave the "classic" mode sass in this lib for a while? :)

**Comment by kfranqueiro** [comment]
Material Design concluded (based on both their own studies as well as external user feedback) that the box variant is far more discoverable as an input than the plain underline variant, and developed the outlined variant as another alternative. So while this is perhaps a drastic UX change, from our perspective, it's a much more accessible one.

The repository has contained all 3 variants for several months, which provided an opportunity for users to try the new variants. The new [design guidelines](https://material.io/design/components/text-fields.html) published this month officially adopt filled and outlined text fields and remove the old underline-only style.

FYI, the changes in code that uses MDC Text Field should be negligible, since both the default and box variants use the same markup, aside from the addition of the `--box` modifier class. Nothing should outright break; the `--box` modifier will simply no longer do anything.

**Comment by kfranqueiro** [comment]
I'm going to split this into 2 issues, one for each component, because trying to bundle both into one PR would make for a very large review. I'll keep this one for Text Field, which already has a PR in review.

**Comment by GusRuss89** [comment]
Any chance we could keep the legacy text and select variants around under something like `--legacy`? This is a big change that will require design refactoring work for anyone who is using the components seriously in an existing application where the new styles may not play as nicely as the old. The work involved in adding a modifier class like `--legacy` to existing text and select components is less than a re-design.
