### ISSUE TITLE
Mark mdc-typography variables as !default to allow overriding them

### ISSUE THREAD

**Issue by juhov** [material-components/material-components-web#280]
Is there a reason why mdc-typography [variables](https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_variables.scss) (for example `$mdc-typography-styles`) don't have the !default flag set?

In my current project I would need to override few font size and weight settings from Material Design typography guidelines and it would be nice to do it the same way you can override mdl-layout-grid [variables](https://github.com/material-components/material-components-web/blob/master/packages/mdc-layout-grid/_variables.scss) as those have the !default flag.

**Comment by traviskaufman** [comment]
I think the reason why we initially did not do this is because our typographic guidelines are a well-defined part of the spec, with concrete values for leading, tracking, etc. Whereas with mc-layout-grid, the margin/gutter widths are variable:

> Margins and gutters can be 8, 16, 24, or 40dp wide.
- https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-grid

We obviously can't enforce that users use those exact values, but we made the Sass variables `!default` so users could change them if need be. 

This being said, I see it being useful to be able to alter typographic values, so I don't see the harm in adding in `!default`.
