### ISSUE TITLE
material-components-web release 0.36.0-0 not tagged as latest in npm registry

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#2857]
According to the npm registry material-components-web@0.36.0-0 does not have the latest tag. Is there a reason for that? Currently npm will install the 0.35.2 release, unless you explicitely ask for 0.36.0-0.

![material components web npm](https://user-images.githubusercontent.com/533888/40837784-ee03bf54-659b-11e8-9ba0-3877a23aadbc.png)

**Comment by kfranqueiro** [comment]
This is intentional. 0.36.0-0 is a pre-release so that we can start updating dependent repos (e.g. the [catalog](https://github.com/material-components/material-components-web-catalog)) ahead of the release. It's not intended to be shipped out to everybody without warning. 0.36.0 is intended to release next Monday.

I have an [open PR](https://github.com/material-components/material-components-web/pull/2847) that adds some documentation around this process.

(TBH when we first published 0.36.0-0 it was accidentally tagged as latest, and I fixed it shortly afterwards.)
