### ISSUE TITLE
Is there any way to use the Sass mixins without npm, i.e. using CDN?

### ISSUE THREAD

**Issue by devxpy** [material-components/material-components-web#2864]

**Comment by kfranqueiro** [comment]
Sass mixins cannot be used via CDN. CDNs serve static precompiled CSS and are not capable of processing Sass on the fly. Moreover, when Sass preprocesses `@import` statements, it typically expects to work against the local filesystem (though I suppose it might be theoretically possible to implement a custom importer that does otherwise).

On the "without npm" front, It should possible to use MDC Web's Sass mixins with any Sass compiler, whether via npm or otherwise. We've resolved issues related to usage with Ruby Sass, for example, and there are also libsass wrappers for Python, etc. If you encounter issues using our Sass with a particular Sass wrapper, please let us know.

There are tools such as StackBlitz and CodeSandbox which support prototyping with CSS preprocessors; however, these would need to be able to pass custom options to `node-sass` (either directly or via webpack configuration) in order to [set the include path correctly](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-2-include-css-for-a-component) for use with MDC Web.

**Comment by devxpy** [comment]
Thanks for the clarification
