### ISSUE TITLE
Outdated npm latest tags

### ISSUE THREAD

**Issue by code-chris** [material-components/material-components-web#2867]
The last release `0.36.0-0` is not published as `latest` or another tag on npm. Is this intentional?

### What is the expected behavior?

New versions of the packages are published on npm with the `latest` or another dist-tag.

### What is the actual behavior?

The last version `0.36.0-0` is published on npm, but the `latest`dist-tag still points to a `0.35.x` version.

**Comment by williamernest** [comment]
@code-chris Yes, this is intentional. We released a pre-release version so we could update our catalog to point to the new packages. Our normal release cycle has us pushing out the `0.36.0` release on Monday. We will continue to use pre-release versions if we make breaking changes and have to keep other repositories in sync.

**Comment by code-chris** [comment]
@williamernest I'm fine with that. Thanks for the quick response!
