### ISSUE TITLE
mdc-textfield label misalignment

### ISSUE THREAD

**Issue by thomassross** [material-components/material-components-web#287]
Using MDC 0.4.0, on Firefox 52 and Chromium 55 on Debian Linux (Stretch), the label for a `mdc-textfield` has `margin-left` set to `4px`. As far as I can tell from [the spec](https://material.io/guidelines/components/text-fields.html#text-fields-labels) (scroll to "specs"), the label and the text field are supposed to be aligned.

Here's a codepen to demonstrate: https://codepen.io/anon/pen/KarOQo

**Comment by thomassross** [comment]
If you want I can send a PR to fix this (_if_ this is a bug)

**Comment by traviskaufman** [comment]
I think the problem is that you're using `mdc-form-field` directly on the `mdc-textfield` element. `mdc-form-field` is meant to be a wrapper element used to make putting form controls and labels (e.g. checkbox + label, radio + label) easy to do from both a UX and an accessibility perspective. For example, `mdc-form-field` is RTL-aware and will switch the positions of each element when it detects an RTL context.

You don't need to use `mdc-form-field` with `mdc-textfield`, so if you remove that class it should fix your issue. Hope that helps!

**Comment by thomassross** [comment]
Thanks, that makes sense!
