### ISSUE TITLE
Firefox mobile scroll overlaps on drawer

### ISSUE THREAD

**Issue by micdalco** [material-components/material-components-web#2887]
### What MDC Web Version are you using?

Latest (0.36.0)

### What browser(s) is this bug affecting?

Firefox mobile

### What OS are you using?

Android all versions

### What are the steps to reproduce the bug?

- Open the demo Material components web demo site
- Open the left drawer
- Expand the Components item
- Try to scroll the drawer up & down with touch actions

### What is the expected behavior?

The drawer should scroll in a consistent manner

### What is the actual behavior?

The component in the drawer scrolls in separate ways and speeds, often overlapping and flickering.
When you complete the scroll action, the drawer layout recompose itself with a short delay.

Here a short video:
https://youtu.be/JXnM2UfBQZQ

### Any other information you believe would be useful?

This happens the very same in a web app that I'm developing. Provide an appropriate item list for the drawer that allows to scroll the drawer body.
This does not happens on PC or Mac platform version of Firefox.
This happen the very same with the scrollable body of a Dialog box, when filled with multiple elements.

**Comment by kfranqueiro** [comment]
Thanks for pointing out these issues.

The ripple issue is reflected in #1080. I've moved that up in our tracker because while it might be a bit challenging to implement, I agree it's gone unaddressed for too long.

The scrolling issue is...interesting, and at least some symptoms seem to also be reproducible within our [drawer demos](https://material-components.github.io/material-components-web-catalog/#/component/drawer) - you can observe that the divider line scrolls slower for some reason, and there's some noticeable jitter to the rest of the items' scrolling.

Firefox Mobile sees relatively little usage compared to our supported platforms, so I can't see prioritizing this within the core team, but we'd be willing to review and test a PR for it.

**Comment by micdalco** [comment]
I tried to look into this bug, so I attached webdig Firefox "debugger" to my Firefox Mobile... as soon as the debug starts the bug disapperars... check this video:
https://youtu.be/rxMlWgqbzjY
At 0:23 I connected webide to the active tab, and the scroll bug goes away.

It seems like it is a specific Firefox mobile bug and not a MDC one.
So I filed a bug in bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1475288

**Comment by kfranqueiro** [comment]
@micdalco thank you for looking into this and reporting that issue!

**Comment by kirbyfan64** [comment]
Are there any known workarounds for this?

**Comment by abhiomkar** [comment]
The original issue does not seem to use MDC Drawer.

Please feel free to re-open if this issue still persists in new version of MDC Drawer.

Thanks!
