### ISSUE TITLE
MDC Shape usage?

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#2907]
### What MDC Web Version are you using?

> 0.36.0

### What browser(s) is this bug affecting?

> _

### What OS are you using?

> _

### What are the steps to reproduce the bug?

> 1. https://codepen.io/anon/pen/rKWdee
> 2. Observe the component's behavior

### What is the expected behavior?

> Button should be cut from the corners

### What is the actual behavior?

> A normal button

### Any other information you believe would be useful?

> The demos are working but mine isn't

**Comment by kfranqueiro** [comment]
Using MDC Shape requires invoking Sass mixins and compiling Sass (which also prevents demonstrating it via codepen). This is necessary in order to generate appropriate styles based on the desired size of the cut corners.

Assuming you're looking at the [catalog](https://material-components.github.io/material-components-web-catalog/#/component/shape) for reference, the code you're missing is in [ShapeCatalog.scss](https://github.com/material-components/material-components-web-catalog/blob/master/src/styles/ShapeCatalog.scss).

**Comment by touficbatache** [comment]
So I can't use it without Sass?? That's strange...

**Comment by kfranqueiro** [comment]
We use Sass to calculate styles appropriately for the given corner sizes: https://github.com/material-components/material-components-web/blob/v0.36.1/packages/mdc-shape/_mixins.scss#L24-L40

You would need to write these styles manually if not using Sass.

See also https://github.com/material-components/material-components-web/issues/2764#issuecomment-390760939
