### ISSUE TITLE
Stance on CSS-only?

### ISSUE THREAD

**Issue by Download** [material-components/material-components-web#293]
Hi guys, just wanted to ask you a question about css-only design.

Please have a look at this (demo) project:
http://mildrenben.github.io/surface/

It is built to function even without Javascript enabled. The big (imho) advantage of this is that is has the best time-to-interactive performance possible; even before the JS loads, it functions as expected.

Another big advantage is that they are easier to work with, because they require no initialization or state management; state is in a checkbox in the dom and toggled just like we always toggle checkboxes. You can hook into it with events if you want, or control it from JS, or just server-side render the checkbox on or off... Simple. During runtime there is no need to track the open state or read from the DOM what the state is etc. Also if you look at the trouble with React at al with MDL, none of these would have existed if you simply would have had no JS to deal with in the first place.

I understand it is a pretty hefty requirement, but Surface proves there is a lot that can be achieved this way. If only the most important components (such as the drawer) would work like this, it would still give a great benefit. Of course not all components can be built this way. Surface is a great experiment but I would never let the final design be compromised just to support CSS-only.... However it is a great goal for the more fundamental components. Drawer is one of those because without it the user can not navigate.

Have you given this any consideration? And can you maybe share your thoughts on this?

(cross-posted from [mdl#5036](https://github.com/google/material-design-lite/issues/5036) because I hadn't seen this new repo yet)

**Comment by Download** [comment]
I tested a bit but with Javascript disabled, some examples look disastrous.

![Temporary Drawer with JS disabled](http://i.imgur.com/CbTclck.jpg)

I know JS is almost never disabled on real clients, but if they have a slow connection and it is only activated after a few seconds, the page will give a very ugly f.o.u.c until it is loaded.

What I would like to see is for the drawer component to not only look great with JS disabled, I would like it to *work*. Surface proves that this can be done. I experimented with it myself and it is definitely doable. I even ended up with a design where I combine the temporary drawer with the permanent one; on small screens you get the temporary drawer and on larger screens the 'permanent' one. I made the 'permanent' drawer act slightly different; it could be toggled on or off with the menu button.

Would you be open to PRs that introduce such CSS-only behavior?

**Comment by Garbee** [comment]
The builds need JS to work currently since it is the webpack build output. Which provides the CSS as JS for hot reloading.

Things should mostly work without JS and enhance where-ever needed for full-fidelity components. This was a fairly critical piece in the early designing. However with the temporary drawer it isn't really feasible to have that work with CSS only for instance since the toggle action would essentially be stuck on open-only.

**Comment by Download** [comment]
> The builds need JS to work currently since it is the webpack build output. 

Ah! That explains it. I hadn't delved too deep into the cause but this totally explains that.
I think it still would be good to do regular testing with JS disabled though just to keep an eye on it.

> However with the temporary drawer it isn't really feasible to have that work with CSS only for instance since the toggle action would essentially be stuck on open-only.

Can you elaborate? I have a CSS-only implementation that works (afaict) exactly the same as the one in MDL... I don't have too much experience with MDC yet but I assume the drawer functionality is not radically different...

When you say 'the toggle action would be stuck' are you talking about the Hamburger button? Or the JS code that toggles the drawer open/closed?

If I can deliver you a version of the drawer that works CSS-only, would you accept a PR for it?

**Comment by traviskaufman** [comment]
Hey @Download 

Thanks for raising this. As @Garbee mentioned, we try to build all of our components with a CSS-fallback in mind. For some, however - such as temporary drawers - JS is required. We purposefully do _not_ rely on certain CSS hacks, like the checkbox + sibling combinator for menu toggles, because this leads to brittle code, and tightly-coupled DOM. It also has disastrous implication for accessibility. 

We will continue to try to always provide CSS-only fallbacks/solutions where appropriate, but ruling out JS altogether is untenable. Thanks!

**Comment by Download** [comment]
> It also has disastrous implication for accessibility.

Any links about that? I never heard of that before and would like to learn more.
