### ISSUE TITLE
Material components official website 404 error

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#2940]
## Bugs

There is an issue with the material design website where the icon documentation page returns as a 404 error
<img width="521" alt="screen shot 2018-06-15 at 1 39 23 pm" src="https://user-images.githubusercontent.com/26075792/41446058-8ab6d84e-70a1-11e8-89ac-c5f698d35332.png">
<img width="1440" alt="screen shot 2018-06-15 at 1 39 17 pm" src="https://user-images.githubusercontent.com/26075792/41446057-8a7c30d6-70a1-11e8-845f-ebf6cb8f0d76.png">

This is after clicking on the documentation button on the demo page on material components web page

<img width="731" alt="screen shot 2018-06-15 at 1 40 31 pm" src="https://user-images.githubusercontent.com/26075792/41446102-bfff6aac-70a1-11e8-88bf-a97c08f560bb.png">
<img width="914" alt="screen shot 2018-06-15 at 1 40 48 pm" src="https://user-images.githubusercontent.com/26075792/41446103-c06b102c-70a1-11e8-8600-33349d645551.png">

**Comment by kfranqueiro** [comment]
Thanks for reporting this. This error is currently occurring because the catalog was updated in advance of a material.io site push which experienced a longer-than-expected delay. This should be addressed early next week.

In the interim, you can see the same documentation by clicking the Source Code link, which links to the folder in the github repository which contains the README which the docs are generated from for material.io.

**Comment by CyborgSemon** [comment]
Awesome thank you!

**Comment by kfranqueiro** [comment]
The site was updated earlier this week, so this link is now working.
