### ISSUE TITLE
.map sourcemap files missing from npm releases

### ISSUE THREAD

**Issue by diuming** [material-components/material-components-web#2942]
I'm a newbie with web technology?
The MDL is easy to use, but it's no longer to update.
The MDC-web is difficult for me and I can't find a step by step manual for general web server.
I always get errors when I run the code in general web server(like apache or nginx `not for Nodejs`). 
Do I need to install nodjs, npm and webpack? 
errors: (sorry: I don't have any experience with MDC-Web)

---
Cannot find module `/dist/material-components-web.js.map` in package material-components-web@0.36.0
Cannot find module `/dist/material-components-web.js.map` in package material-components-web@0.36.0

the code
----
    <!DOCTYPE html>
    <html>
        <head>
            <title>Material Components for the web-Drawer</title>
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
            <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
            <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.js"></script>
        </head>
        <body>
            <div>Toolbar goes here</div>
                <div class="content">
                    <nav class="mdc-drawer mdc-drawer--permanent mdc-typography">
                        <nav id="icon-with-text-demo" class="mdc-list">
                            <a class="mdc-list-item mdc-list-item--activated" href="#">
                                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">inbox</i>Inbox
                            </a>
                            <a class="mdc-list-item" href="#">
                                <i class="material-icons mdc-list-item__graphic" aria-hidden="true">star</i>Star
                            </a>
                        </nav>
                </nav>
                <main>
                    Page content goes here.
                </main>
            </div>
        </body>
    </html>

**Comment by matsp** [comment]
You couldn't provide less information about your intention.

**Comment by kfranqueiro** [comment]
This error is occurring because we don't include the `.map` files within our npm releases. I'm a bit surprised though, since I don't actually see this error in Chrome at all... I do see an error reported in Firefox, though.

This is mostly harmless, since the `.map` file is only used for debugging.

However, it might be worth us considering including the `.map` files in each npm release. The only foreseeable downside is increased burden on bandwidth when first installing a new version of MDC Web packages via npm.

**Comment by pavelsevcik** [comment]
Dear @kfranqueiro, 

can you either 

A) **include .map files in npm packages** 

or

B) **disable map generation in prod build**

reason is, that current setup where 

https://github.com/material-components/material-components-web/blob/f310e7364f6f7a7ae162908ca27808f0e4619184/scripts/webpack/js-bundle-factory.js#L78       

is 

```js
devtool: 'source-map',
```

and 

https://github.com/material-components/material-components-web/blob/f310e7364f6f7a7ae162908ca27808f0e4619184/scripts/cp-pkgs.js#L82

is 

```js
Promise.all(globSync('build/*.{css,js}').map(cpAsset)).catch((err) => {
```

causing, that generated minified files ends with sourceMappingURL

```js
/*# sourceMappingURL=mdc.drawer.min.css.map*/
```
but those files are not present in packages.

But that is causing for example build warnings when we use mdc with aurelia-cli

```shell
Error: An error occurred while trying to read the map file at /data/com__app/node_modules/@material/drawer/dist/mdc.drawer.js.map
Error: ENOENT: no such file or directory, open '/data/com__app/node_modules/@material/drawer/dist/mdc.drawer.js.map'
    at readFromFileMap (/data/com__app/node_modules/aurelia-cli/lib/build/convert-source-map/index.js:32:11)
    at new Converter (/data/com__app/node_modules/aurelia-cli/lib/build/convert-source-map/index.js:39:32)
    at Object.exports.fromMapFileComment (/data/com__app/node_modules/aurelia-cli/lib/build/convert-source-map/index.js:112:10)
    at Object.exports.fromMapFileSource (/data/com__app/node_modules/aurelia-cli/lib/build/convert-source-map/index.js:131:22)
    at acquireSourceMapForDependency (/data/com__app/node_modules/aurelia-cli/lib/build/bundle.js:200:33)
    at work.then (/data/com__app/node_modules/aurelia-cli/lib/build/bundle.js:222:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

it's just warning, but because we include mdc packages one by one we get tons of those warnings and that make aurelia-cli output bloated with noise and as that hard to read.

appreciate your time and efford required to solve this cosmetic issue

Pavel

**Comment by pndewit** [comment]
Having the same issue @pavelsevcik .. 😞

**Comment by pavelsevcik** [comment]
@pndewit, I just submitted PR to add missing source-map files to npm releases

in meantime, try this quick and dirty hack of aurelia-cli in node_modules in your project (if you have aurelia-cli installed globaly hack code in global location)

add to `<your-project-path>/node_modules/aurelia-cli/lib/build/bundle.js` just right bellow first `if` in `acquireSourceMapForDependency`

```js
  function acquireSourceMapForDependency(file) {
    if (!file || !file.path) {
      return;
    }
```

this quick and dirty hack to exclude `@material` packages source-map acquiring

```js
    // WARNING: Hack / Workaround to supress Error: An error occurred while trying to read the map file
    if (/node_modules\/@material/.test(file.path)) return;
```

code gonna look like

```js
function acquireSourceMapForDependency(file) {
    if (!file || !file.path) {
      return;
    }
    // WARNING: Hack / Workaround to supress Error: An error occurred while trying to read the map file
    if (/node_modules\/@material/.test(file.path)) return;
```

cheers
