### ISSUE TITLE
Top-App-Bar--Fixed: left and top margin (missing css properties)

### ISSUE THREAD

**Issue by Deilv** [material-components/material-components-web#2944]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What MDC Web Version are you using?

0.36.0

### What browser(s) is this bug affecting?

Chrome 67.0.3396.87, Firefox 60.0.2.

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

The mdc-top-app-bar--fixed css class does not define left and top margins (while mdc-toolbar--fixed does) and as a result the fixed Top App Bar has an 8px top and left margin, which isn't the intended behavior. This is demostrated in the example below:

https://codesandbox.io/s/71oqjl880j

### What is the expected behavior?

The fixed Top App Bar should have 0 left, top and right margin to appear "virtually fixed" at the top of the window.

### What is the actual behavior?

The fixed Top App Bar has an 8px top and left margin, like the non-fixed version.

### Any other information you believe would be useful?

The problem is solved by adding the missing css properties to /top-app-bar/mdc-top-app-bar.scss and change
```
.mdc-top-app-bar--fixed {
  transition: box-shadow 200ms linear;
}
```
to:
```
.mdc-top-app-bar--fixed {
  transition: box-shadow 200ms linear;
  top: 0;
  left: 0;
}
```

**Comment by williamernest** [comment]
@Deilv Thanks for filing this issue. Some browsers have implemented a margin on the `body` element which causes this. You can set the styles on the `body` tag or use something like `normalize.css` to fix this issue. 

Adding `left` or `right` to the `mdc-top-app-bar` or `mdc-top-app-bar--fixed` classes will break compatibility with some of the drawer variants, since the top app bar should not be displayed on top of the drawer header.
