### ISSUE TITLE
Checkbox ripple issues

### ISSUE THREAD

**Issue by liabru** [material-components/material-components-web#298]
### What MDC-Web Version are you using?

0.2.0

### What browser(s) is this bug affecting?

Chrome

### What OS are you using?

OSX

### What are the steps to reproduce the bug?

1. Click on the basic `mdc-checkbox`, e.g. on the [demo](http://material-components-web.appspot.com/checkbox.html)
1. Observe the ripple

### What is the expected behavior?

1. The ripple should fade away after growing, see [paper-checkbox](https://www.webcomponents.org/element/PolymerElements/paper-checkbox)

### What is the actual behavior?

1. The ripple stays indefinitely

### Any other information you believe would be useful?

The javascript enabled `mdc-checkbox` ripple does seem to dismiss but it has other problems: it seems to grow too large and animates too quickly. I think it should be possible to fix both the basic and javascript enabled versions to have the same ripple behaviour as [paper-checkbox](https://www.webcomponents.org/element/PolymerElements/paper-checkbox).

**Comment by traviskaufman** [comment]
This is the expected behavior of the CSS-Only checkbox. This is our replacement for the default "focus ring", which indicates that the element is currently focused. E.g. if you were to try this on Safari, you would not see a focus ring. Unlike paper-checkbox, our basic checkbox uses only CSS. However, our JS checkbox contains a ripple implementation and should fade away immediately on pointer interaction.
