### ISSUE TITLE
where is material.io website 's github repo|?

### ISSUE THREAD

**Issue by anlexN** [material-components/material-components-web#3009]
Excuse me, i found no website source code link from [material.io](https://material.io). I'm from china. i think something maybe be better. at least, on the chinese views. i am willing to contribute.

**Comment by moog16** [comment]
@anlexN material.io is actually not a public site. What would you like to change?

**Comment by moog16** [comment]
I think you're asking about material.io - that is not a public repo, because its mainly a page for all the material design content that is updated/maintained by our designers (not developers). 

Regarding material studies, they are not real applications which is why you cannot find them. If you're interested we have codelabs which focuses on building shrine: https://github.com/material-components/material-components-web-codelabs/tree/master/mdc-103. Its not feature complete, but it should give you a good idea on how to build some of the other ones.

**Comment by anlexN** [comment]
this is it. please be a public repo. if you wouldn't let others make change, you can make it only read. i only want to clone to realize my some dreams.

**Comment by moog16** [comment]
I think some of our conversation might be getting lost in translation, but are you saying that the codelabs link I sent you is what you were looking for?

We won't be accepting large changes in that repo, since its part of our codelabs found here: https://codelabs.developers.google.com/io2018. We are just trying to keep it up to date with our MDC-Web repo.

**Comment by williamernest** [comment]
Closing this issue because it's not an issue with the components.
