### ISSUE TITLE
Delete mdc-toolbar

### ISSUE THREAD

**Issue by lynnmercier** [material-components/material-components-web#3040]
There is no longer a toolbar component in the new https://material.io/design/

We will delete this package and stop supporting it. If you would like to continue using mdc-toolbar, please use [@material/toolbar](https://www.npmjs.com/package/@material/toolbar) on version 0.37.0

**Comment by GRRedWings** [comment]
Any progress on this?  The warning message on each scss I have is pretty annoying.

**Comment by abhiomkar** [comment]
We've a PR open for this https://github.com/material-components/material-components-web/pull/4687

**Comment by GRRedWings** [comment]
Any progress on this?  I believe this is causing my warnings for each scss file.  

(13421:5) start value has mixed support, consider using flex-start instead


I think this stems from the use of MDCToolbar instead of Top App Bar
https://github.com/material-components/material-components-web/issues/4233

**Comment by moog16** [comment]
Closing since #4687
