### ISSUE TITLE
mdcAutoInit(elem) does not work on elem

### ISSUE THREAD

**Issue by neclepsio** [material-components/material-components-web#309]
### What MDC-Web Version are you using?
0.4.0

### What browser(s) is this bug affecting?
Chrome at least

### What OS are you using?
Linux and Windows

### What are the steps to reproduce the bug?
var elem = document.getElementById("elemid");
mdcAutoInit(elem);

### What is the expected behavior?
I think elem should be initialized if it has attribute mdc-auto-init.

### What is the actual behavior?
The element is not initialized, but only its children are.

**Comment by traviskaufman** [comment]
This is the expected behavior, as outlined in the [mdc-auto-init README](https://github.com/material-components/material-components-web/tree/master/packages/mdc-auto-init#initializing-only-a-certain-part-of-the-page):

> To override this behavior, you can pass in an optional root first argument specifying the root node whose _children_ will be queried for instantiation.

I'm hesitant to change the semantics of this function. Usually, if you need to instantiate only one component, using the proper constructor directly is encouraged. This is to prevent subtle bugs that may surface if you change your MDC-Web DOM without changing the call which instantiates its JS component.

Furthermore, having mdc-auto-init work on a root element directly could lead to ambiguity as to what is being auto-initialized. For example, if one were to attach `data-mdc-auto-init` on the root itself, is it apparent that mdc-auto-init is only working on the children of that element, plus the element itself? Or is it working on the element's siblings as well?

Could you specify your specific use-case which would require this behavior?

**Comment by neclepsio** [comment]
I don't have a use-case which *requires* this behavior. 

I'm writing a wrapper for MDC in Go. When a component is changed, I delete it from the DOM and recreate it (it's a little smarter than this, but you got the idea). 

So the easiest thing to do would be to run mdcAutoInit on the newly created element. Anyway, doing so on its parent using `mdcAutoInit(elem.parent, function(){});` is not a big deal.
