### ISSUE TITLE
Implement Dialog Component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#32]
Spec reference: https://www.google.com/design/spec/components/dialogs.html

I also made a Codepen mocking up a basic dialog sketch: http://codepen.io/traviskaufman/pen/yJayZj

Even though the spec doesn't have an "x" button in their mocks, it does work well for large dialogs on big screens, so we may want to consider it. 

> Copied from https://github.com/google/material-design-lite/issues/4486

**Comment by Garbee** [comment]
Here is a trick we can implement with dialog.... [CSS Variables for adaptive width](http://codepen.io/Garbee/pen/QGzqwG). The spec states that dialogs should be sized in units of `56px`. Phones are like a 3 or 4 unit default and desktops like 8. So, we can set two root-level vars `--mdc-dialog-unit-width: 56px;` and `--mdc-dialog-unit-count: 3`. Media query for desktop to change the count, easy. Then for the dialog width we set it with `width: calc(var(--mdc-dialog-unit-width) * var(--mdc-dialog-unit-count));`. This will let developers do `.app-dialog { --mdc-dialog-unit-count: 8; }` for example to expand the width automatically by the proper number of units.

**Comment by amsheehan** [comment]
After discussing with the team, we are going to implement a dialog component without the use of the `dialog` element. 

Part of this is because only one browser supports `dialog`, and it is still marked as experimental on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

That said, we will implement focus trapping and aria roles to keep it accessible.

This also means that once this story is finished we'll have a dialog component 👍

**Comment by mikegleasonjr** [comment]
Hi guys, loving how the library is going. I was about to pull a 3rd party dependency in my project for modals. I am not ready to go live and I can live with window.alert for now but my question is, is there any ETA on this? Is there a roadmap for components integration? Thanks guys!
