### ISSUE TITLE
docs(drawer) Can't provide long text on drawer above toolbar

### ISSUE THREAD

**Issue by peluprvi** [material-components/material-components-web#324]
I'm working on a new [demo of a permanent drawer above fixed toolbar](https://github.com/peluprvi/material-components-web/blob/drawer-fixed-toolbar-demo/demos/drawer/permanent-drawer-above-fixed-toolbar.html) but there is an issue on the current [permanent drawer above toolbar demo](https://github.com/material-components/material-components-web/blob/master/demos/drawer/permanent-drawer-above-toolbar.html).  Tested on Chrome 56.0.2924.87 (64-bit). Windows 10.

```html
<p class="mdc-typography--body1">It sits to the left of this content.</p>
```

The layout breaks when the paragraph text above is larger. Example:

```html
<p class="mdc-typography--body1">
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
</p>
```

What's the best solution, for both demo, following the best pratice implemented on material-components-web?

**Comment by peluprvi** [comment]
References:

* [Material - Navigation Drawer](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior)
* [Material - Responsive UI Grid](https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-grid)
  * See "The effects of a permanent panel on the responsive grid" example
  * See "The effects of a persistent panel on the responsive grid" example

Expected behavior:
* Both example (permanent or persistent drawer) can have default or fixed toolbar.
* A Navigation Drawer has its own scrollbar

Possible solutions:
* For scrolling all together:
  * Add `min-width: 240px` to `.mdc-permanent-drawer`
* For fixed toolbar and drawer
  * Add `min-width: 240px` to `.mdc-permanent-drawer`
  * Add `position: fixed;` to `.mdc-permanent-drawer`
  * Add to `.mdc-permanent-drawer` a `z-index` higher then the toolbar
  * Add a 240px extra left padding to fixed toolbar when using a permanent drawer layout

**Comment by sgomes** [comment]
Thanks for the suggestions, @peluprvi!

I think the bigger issue here is that the toolbar needs to be aware of the presence of the drawer in order to push its contents to the side. Furthermore, if we consider the persistent drawer, it also needs to be aware of its state.

We also need to think about the situation where a drawer is placed under the toolbar, therefore not affecting it, which is also a valid pattern.

There are several ways of achieving this.

## Option 1 - CSS class on the drawer, selectors on the toolbar

The drawer would apply a CSS class to itself, indicating whether or not it's currently open. The toolbar would build its styles with this in mind, assuming that the drawer would be a sibling (or an immediate sibling, if we're comfortable with that restriction). For the general sibling case, this would look something like:

```css
.mdc-persistent-drawer--open ~ .mdc-toolbar,
.mdc-permanent-drawer ~ .mdc-toolbar {
  /* ... */
}
```

Pros:
- Simple, easy to understand.
- No need for permanent drawers to do anything in JS.
- Persistent drawers can just reuse the JS class they will have for their own styling.
- Easy to avoid incorrect behaviour if the drawer is below the toolbar, as in that scenario the drawer doesn't appear as a preceding sibling in the DOM.

Cons:
- The toolbar has special knowledge about the drawer, including its width.
- Doesn't work unless the elements are direct siblings. We could mitigate this by doing `.mdc-permanent-drawer ~ * .mdc-toolbar`, but that's expensive.

## Option 2 - CSS class on the body, selectors on the toolbar

The drawer would place a CSS selector on the document body, indicating whether or not it's currently open. The toolbar would build its styles with this in mind:

```css
body.mdc-drawer--open .mdc-toolbar {
  /* ... */
}
```

Pros:
- Simple, easy to understand.

Cons:
- The toolbar has special knowledge about the drawer, including its width.
- Permanent drawers need JS in order to place a permanent class on the body.
- Persistent drawers need to toggle a JS class on the body in addition to their own classes.
- Drawers need to be aware of their position in the DOM and only add the class to the body if below the toolbar.
- Potential issues if there are more than one drawer on the page.

## Option 3 - CSS class on the toolbar, selectors on the toolbar

The drawer would search the DOM and place a CSS selector on every toolbar, indicating whether or not it's currently open. The drawer itself would define the style:

```css
.mdc-drawer--push-aside {
  /* ... */
}
```

Pros:
- The drawer is the one in charge of knowing its own width, which is more easily maintainable.

Cons:
- Somewhat unintuitive to have the drawer style other components.
- Requires a DOM search on every state change.
- Drawers need to be aware of their position in the DOM and only add the class to elements affected by their opening.


Given the choices above, I would lean towards option 1, and make it clear in documentation that the drawer needs to be a preceding sibling of the toolbar in the DOM. What do you think, @yeelan0319?
