### ISSUE TITLE
Naming rule for protected fields

### ISSUE THREAD

**Issue by luzhang** [material-components/material-components-web#3264]
### What MDC Web Version are you using?

> master branch

### What are the steps to reproduce the bug?

> Check out this protected field in [base foundation](https://github.com/material-components/material-components-web/blob/master/packages/mdc-base/foundation.js#L56) file.

### What is the expected behavior?

> Based on the [Google style guide](https://google.github.io/styleguide/jsguide.html#features-classes-fields), only private fields require underscore at the end. It is not necessary to append underscore for protected fields.

### What is the actual behavior?

> The protected variable " this.adapter_" in "packages/mdc-base/foundation.js" includes an underscore, same for "this.root_" and "this_foundation_" in "packages/mdc-base/component.js" .

### Any other information you believe would be useful?
Our team is looking for leveraging MDC components in our component library. But we noticed this naming issue and we are not sure if we should follow Google style guide or the naming rules in MDC web library, we understand making the naming change will cause lots of rewriting in MDC lib.

Thanks,
Lu

**Comment by acdvorak** [comment]
Thanks for filing this issue!

We intentionally deviate from the [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#features-classes-fields) here. \
We use a trailing underscore to indicate "_not_ public" rather than "private".

That's because `@protected` annotations are only useful if you're reading the source code. \
When you inspect an object in the Chrome DevTools, the JSDoc annotations are not visible.

A trailing underscore makes it really obvious that this is an implementation detail that should not be relied on by clients.

Closing this issue for now - feel free to reopen if the names are causing technical issues!

**Comment by luzhang** [comment]
That totally makes sense, thanks for explaining that!
