### ISSUE TITLE
Tab Indicator should not have modifier classes on subelements

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#3295]
`mdc-tab-indicator__content--icon` and `mdc-tab-indicator__content--underline` should instead be `mdc-tab-indicator--icon` and `mdc-tab-indicator--underline`.

See comment from MDCR: https://github.com/material-components/material-components-web-react/pull/202/files#r207386002

**Comment by kfranqueiro** [comment]
I don't think this is a bug?

This is the tab indicator DOM:

```html
<span class="mdc-tab-indicator">
  <span class="mdc-tab-indicator__content"></span>
</span>
```

The `--icon` and `--underline` modifiers are applied to the `__content` block, not the `mdc-tab-indicator` element. According to BEM, modifiers are valid in either case.

If we were to change these classes, I would think we would also need to change which element they are added to, which would then also require us to write more specific CSS selectors (e.g. `.mdc-tab-indicator--icon .mdc-tab-indicator__content` instead of just `.mdc-tab-indicator__content--icon`), which IMO would defeat the point.

**Comment by lynnjepsen** [comment]
Say you have this kind of HTML structure 
```
<div class="foo">
  <div class="foo_bar"/>
  <div class="foo_baz"/>
</div>
```

Then you write a CSS Selector like this
```
.foo_bar--qux .foo_baz
```

This is actually a valid selector, but you cannot tell just looking at the CSS. You have to know that `foo_baz` is NOT a child of `foo_bar`.

But if you only put modifiers on the root element then you guarantee any element CSS classes are children of the root element.

It is not actually a problem in `mdc-tab-indicator` (because there is only one child, `mdc-tab-indicator__content`)...but i think we should follow a best practice of only placing modifiers on root elements.

**Comment by kfranqueiro** [comment]
TBH I'm a little confused by your argument. This would be equally confusing completely outside the context of modifiers (e.g. `.foo__bar .foo__baz`), and moreover the intent of the modifier being on the element rather than the block is to reduce/avoid the need descendant selectors in the first place.

Avoiding excessive CSS specificity is a large part of why we use BEM (I'm pretty sure you pointed out several instances of overspecificity which we fixed in the past), and this "best practice" contradicts that purpose.

Additionally, we can't enforce this as a blanket rule across MDC Web. For example, we have `.mdc-card__action--button` and `.mdc-card__action--icon`, both of which can exist within a single card. There is no single top-level modifier class you can apply in that situation, and the modifier specifically affects styles on the element it is specifically applied to. That seems a lot clearer than a top-level modifier that you have to hunt through styles to realize it only actually affects one specific child element through the use of descendant selectors (which we would rather avoid in the first place).

**Comment by acdvorak** [comment]
I'm with Ken on this 🙂

`mdc-tab-indicator__content--icon` and `mdc-tab-indicator__content--underline` are correct.

We should not change them, for two reasons:

1. The [BEM Naming docs](http://getbem.com/naming/) explicitly recommend element modifiers (e.g., `.form__submit--disabled`).

2. The purpose of BEM is to reduce CSS selector _specificity_ and _complexity_. Top-level block modifiers with descendent selectors (e.g., `.block--modifier .block__element`) break both of those goals. We should only use them as a last resort when the alternatives are even worse \
    (e.g., `mdc-text-field--focused .mdc-notched-outline__path`).
