### ISSUE TITLE
Inputted value in textbox is not aligned correctly vertically

### ISSUE THREAD

**Issue by CreativeGuy2013** [material-components/material-components-web#3336]
## Bugs

The text in a mdc textbox is not aligned properly vertically, it renders over the mdc-line-ripple.

![Broken](https://user-images.githubusercontent.com/7829205/44004749-01a7fbc4-9e68-11e8-8468-1600ccf84de0.png)

### What MDC Web Version are you using?

@material/textfield@0.38.0

### What browser(s) is this bug affecting?

Safari and Chrome 68

### What OS are you using?

macOS 10.13.6

### What are the steps to reproduce the bug?

[BrokenTextfield.zip](https://github.com/material-components/material-components-web/files/2281167/BrokenTextfield.zip)

1. Download zip
2. run 'npm start'
3. Go to localhost:8080/test.html
4. Click on textbox and enter any value
5. Observe the component's behavior

### What is the expected behavior?

Text should be rendering correctly between label and line.
![Correct](https://user-images.githubusercontent.com/7829205/44004781-bad56546-9e68-11e8-8fe6-1d1ee9861f45.png)

### What is the actual behavior?
The inputted text in the field renders over the line in the box.
![Broken](https://user-images.githubusercontent.com/7829205/44004749-01a7fbc4-9e68-11e8-8468-1600ccf84de0.png)

### Any other information you believe would be useful?
When i use this codepen i made it does work: https://codepen.io/anon/pen/QBowNr

**Comment by kfranqueiro** [comment]
The reason this is happening in your code is that your HTML is missing a `DOCTYPE`, which is putting the browser in quirks mode and is apparently resulting in an extra `box-sizing: border-box` rule on inputs.

We would heavily encourage adding `<!DOCTYPE html>` to the top of all HTML documents, since standards mode is generally a much saner development experience.

However, it should also be possible for us to resolve this particular issue for text fields by being explicit about our reliance on `box-sizing`, which would also resolve this for cases with CSS resets that set `box-sizing: border-box` on all elements. (In fact, it looks like this same issue was logged in #2992.)

#1455 exists to address this across components, but it had since fallen off of our backlog; I've put it back on so we can address this.

**Comment by CreativeGuy2013** [comment]
Cool ty!
