### ISSUE TITLE
Tab Scroller AlignEnd and AlignCenter do not scroll to the left (in ltr)

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#3352]
https://codepen.io/moog16/pen/rrbbvP

If you add either `mdc-tab-scroller--align-end` or `mdc-tab-scroller--align-center` classes to the mdc-tab-scroller element, you aren't able to scroll to the left.

**Comment by kfranqueiro** [comment]
The `align-start`, `align-center`, and `align-end` modifier classes are intended for cases where the total width of the tabs is less than the width of the tab bar (which typically only happens if you're using the `mdc-tab--min-width` class on your tabs). In your case, you're setting a min-width for each tab such that this is not the case.

I have been confused by this in the past as well, since the modifiers do nothing if the tab bar itself is restricted in width (since these classes only affect positioning of contents within the tab scroller, which is within the tab bar).

I think at the very least we can probably improve the docs for these classes.

**Comment by kfranqueiro** [comment]
That's the only OOTB application where it would make sense, so I suppose so, yes.

However, if there are still enough tabs to exceed the width of the tab bar, this issue will still happen regardless. It would be nice if there _were_ a graceful fix for that case, especially considering viewport sizes may vary.

**Comment by kfranqueiro** [comment]
Actually, nevermind that last thought... I just tested a modification in that codepen and it doesn't seem to be a problem in that case. You can test by removing the width style in that codepen and replacing the JS with this:

```js
const scrollContent = document.querySelector('.mdc-tab-scroller__scroll-content');

for (number = 1; number <= 15; number++) {
  const tab = document.createElement('div');
  tab.classList.add('mdc-tab');
  tab.classList.add('mdc-tab--min-width');
  tab.innerText = `Really Long Tab ${number}`;
  scrollContent.append(tab);
}
const scroller = document.querySelector('.mdc-tab-scroller');
const tabScroller = new mdc.tabScroller.MDCTabScroller(scroller);
```

It also occurs to me that this codepen could be affected by not using the full MDC Tab Bar with correct markup for each component, but I'm assuming (or hoping) you first saw this in context of a tab bar instance...

**Comment by moog16** [comment]
Gotcha - ya it seems like I shouldn't have that min-width property on the .tab in the CSS (RE: old codepen).

I did update the codepen to your JS, and by adding the correct markup for the mdc-tab element: https://codepen.io/moog16/pen/rrbbvP?editors=1010

It still seems like there is an issue with aligning center/end. Or like you said, needs a doc update.

**Comment by kfranqueiro** [comment]
What issue remains? It's occupying the full width of the container, so it's technically aligning left, center, _and_ end at once. It resolves the leftmost items being inaccessible.

**Comment by moog16** [comment]
Ok talked to @patrickrodee, there is no issue. I updated the codepen: https://codepen.io/moog16/pen/rrbbvP. 

However I was confused what exactly was going to be center/end-aligned.
