### ISSUE TITLE
IE11 doesnt support

### ISSUE THREAD

**Issue by kaaviyakavi** [material-components/material-components-web#3393]
### What browser(s) is this bug affecting?

> Internet Explorer 11

### What OS are you using?

> Windows 10 version- 10.0.17134 

### What is the actual behavior?

> 
![mdc](https://user-images.githubusercontent.com/31274234/44456723-f4bc2200-a61e-11e8-8ff0-661d82f3e90f.png)

The error shows after the npm run build

**Comment by kfranqueiro** [comment]
Can you provide the actual console output for this error? It's not possible to actually see the error in this screenshot.

Also, since it looks like you're using React, it'd be helpful to understand your environment / configuration, since otherwise it'll be hard to guess what the issue is.

Our [getting started](https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md) guide might also help within the scope of configuring webpack for ES2015 and Sass.

**Comment by williamernest** [comment]
Closing due to no response. Feel free to add comments if this is still an issue and we can help resolve.
