### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by Balmat** [material-components/material-components-web#3399]
Tabs not working, https://codepen.io/balmat/pen/mGJapB  

I have added CSS and JS file directly. Please help me how to I can fix it.

**Comment by kfranqueiro** [comment]
I fixed this in https://codepen.io/kfranqueiro/pen/pOjEMM.

I think the issues were in large part due to documentation bugs which have since been fixed in master and will be mirrored to material.io on the next release (you can see them in the GitHub repo now). Sorry for the confusion.

The other issue was that you were using ES2015 syntax in the JS pane, but that won't work in the context of codepen which is loading the precompiled JS in UMD format.

**Comment by Balmat** [comment]
it is working now, thank you so much for the reply and fixed the tabs issues.
