### ISSUE TITLE
Suggestion: --mdc-theme-primary-on-background

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#3475]
Right now, --mdc-theme-primary is applied in all instances where you "think" you would want a primary color.

I've been exploring the Shrine theme exported from the Sketch plugin, and it appears there is an opportunity for a primary color used AS a background vs when a primary color is used ON a background.

![image](https://user-images.githubusercontent.com/975256/44821479-db3d4c00-abc3-11e8-8ec6-4ed8f8d725b0.png)

In this example, you would have --mdc-theme-primary set to the light pink, but --mdc-theme-primary-on-background set to a darker color for more contrast. At a glance, this could apply to buttons, list item selected text, and tabs.

You can view this behavior live by using the RMWC theme picker on the top right hand corner.
https://jamesmfriedman.github.io/rmwc/buttons

**Comment by kfranqueiro** [comment]
This is certainly a situation where MDC Web OOTB falls short, and can't automatically make the right call.

What's interesting is at one point we actually had light and dark variants for primary and secondary (e.g. `mdc-theme-primary-light` and `mdc-theme-primary-dark`), but we ended up pulling them after further discussions, since they weren't used OOTB, and also since they were opinionated about the difference between "steps" when it can vary case-by-case.

Our designers are still working on refining parts of the color design spec to see what simplifications can be made, but the current state of affairs is that the [Theme Editor](https://material.io/tools/theme-editor/) and the [material.io Palette Generator](https://material.io/design/color/the-color-system.html#tools-for-picking-colors) can be used to arrive at appropriate colors for different situations.

This would still amount to manually applying mixins within MDC Web, however, since it seems unlikely to be able to provide a one-size-fits-all default - i.e., some primary colors would have this problem, while others wouldn't, and it's also dependent on the background behind each element.

If design arrives at any simplifications, or at least any rules of thumb that can be reliably implemented without edge cases or "it depends", we can investigate coding them into MDC Web.

**Comment by jamesmfriedman** [comment]
Thanks Ken, appreciate the feedback.
