### ISSUE TITLE
Default Styles TextField

### ISSUE THREAD

**Issue by sashless** [material-components/material-components-web#3477]
### What MDC Web Version are you using?

0.38.0

------------------------

Basically i am a bit confused about what can i expect from the components and what is expected to be changed by the developer

Please see this Screenshot displaying the MDC Dialog containing two MDC TextFields. A default sized TextField and a fullWidth TextField.

![screen shot 2018-08-30 at 15 44 55 1](https://user-images.githubusercontent.com/1218924/44855891-55c1a680-ac6c-11e8-9553-f7b17875c3c7.png)

I was assuming the default styles will fit nicely out of the box aka take the remaining space but on the right side of the default sized input is a lot of space.

Do i need to adapt the width of TextFields or the Dialog to my needs via css or do i use it wrong with the Dialog ?

Maybe the default Dialog width is just a random value and needs to be set by the developer to fit projects needs ?

Additionally the TextField has a `fullWidth` property but on the other hand the README is discouraging the usage of floating labels which i would like to use in this scenario. With doing that i would create components which are no longer spec compliant ?

> NOTE: Do not use mdc-floating-label within mdc-text-field--fullwidth. Labels should not be included as part of the DOM structure of a full width text field.

It would be also nice to get some insight into why this is discouraged.

**Comment by robbyrice** [comment]
Normal TextField components have a default width set out of the box. If the container (a Dialog component for example) is wider than the TextField then the TextField will not take up the full width of the container. If you want the TextField to take up the full width you can set that using css according to your needs.

Concerning your second question about the `fullWidth` property, I think the reason having a full width floating label is discouraged is because instead you should have some helper text in the TextField that disappears once a user clicks into it. Someone with a better understanding of the Material Design spec can correct me on that if I am wrong.

**Comment by williamernest** [comment]
@sashless Thanks for filing this issue. As @robbyrice mentioned, you can modify the length of the text field as you see fit with normal css. The full width text field is designed to be used with a `placeholder` attribute directly on the `input` element. See below for an example.  

```
<div class="mdc-text-field mdc-text-field--fullwidth">
  <input class="mdc-text-field__input"
         type="text"
         placeholder="Full-Width Text Field"
         aria-label="Full-Width Text Field">
</div>
```

**Comment by tychenjiajun** [comment]
@robbyrice it works when I trying to add `width:100%;` to a normal TextField but how can I make a full width outlined TextField? I tried `width:100%` but it seems to have an overflow and makes the page horizontal scrollable. 

[CodePen](https://codepen.io/chankcccc/pen/qMoQXd)
