### ISSUE TITLE
Overriding variables like $mdc-toolbar-height

### ISSUE THREAD

**Issue by kminehart** [material-components/material-components-web#348]
I'm trying to "do the right thing" and keep as much css manual overriding out of my application I'm working on.  It becomes a hassle to take this idea that I want to apply, like changing the height of the toolbar, and then have to change all of the components that would use `$mdc-toolbar-height` whenever I should just change `$mdc-toolbar-height`.

So I was wondering if there's a way to override these variables?  I'm at a loss because I'd normally do:

```
@import '~@material/toolbar/_variables';

$mdc-toolbar-height: 50px;

/*...*/
@import '~@material/toolbar/mdc-toolbar
```

however, the variables are built into `mdc-toolbar`.  Is there no way to override them?

**Comment by yeelan0319** [comment]
@kminehart Thanks for leaving this feedback!

Current material design guideline is written in a rigid way and we do have a required height and padding for toolbar on desktop and mobile devices. The reason is for giving for good visual experience to users as well as making sure each component goes along with others components. That's why you see these variables is not 'by default' but 'set to'.

Bearing that risks in mind, if you do need to change the height of toolbar for the purpose of your project, we recommend you adding your own class modifier and define style like:

    <div class="mdc-toolbar kminehart-styled-toolbar">
        ...
    </div>

    .kminehart-styled-toolbar {
        height: 50px;
        padding: 10px;
    }

Don't hesitate to overwrite css style or adding your own modifier when needed.
