### ISSUE TITLE
It's not beautiful, it's horrible!

### ISSUE THREAD

**Issue by midenok** [material-components/material-components-web#3492]
I'm f.cking tired of fixing sites mutilated by your design. How this misconception ever can be usable? See even your starting page didn't fit my screen halfway.

![image](https://user-images.githubusercontent.com/3307037/44945859-dd88eb80-adf9-11e8-98ee-68c543c24ef4.png)

Are you serious about design? First start using the computer hours a day and you'll see how clumsy, ineffective and difficult your UI is.

What's about all black? Are you mourning, did someone die? What about monochrome, flat pictures and enormously large text and lots of empty space. Do you think people mostly imbecile and must read only several lines from screen? You perverted everything. You made digital technology unattractive: now it's impossible to work fast.

**Comment by The-Don-Himself** [comment]
Disclaimer : I am NOT a maintainer, developer or even contributor, to this library. (Hope to change the last part soon :))

@midenok I totally understand developer frustration, but this is not the way to phrase an issue surely. I advise you edit it to add a bit of decency.

That said, please note that this library is still pre version 1.0, which basically means it can be used, but is highly subject to change - breaking changes - that can cause issues when you update. The past 2 weeks in particular, have seen many breaking changes in my experience - especially around menu, drawer and text input, but I haven't ranted because, it's written there in the [READ.ME](https://github.com/material-components/material-components-web/blob/master/README.md). So I knew what I was getting myself into.

> Note: Material Components Web follows semver and is still in version 0.x, which means it is regularly subject to breaking changes. We typically follow a 2-week release schedule which includes one minor release per month with breaking changes, and intermediate patch releases with bug fixes. A list of changes is always available in the CHANGELOG, and a tentative schedule of what we are working on next is available in the ROADMAP.

I've been using this library since it's inception and MDL before that. I can personally vouch for the amount of thought and effort that gets put into this library for all to use for FREE, No strings or backlinks attached.

My two cents :- 
1.) Don't autoupdate frequently. Especially in production.
2.) Explain to your clients the potential drawbacks of living on the cutting edge, they can always use [bootstrap](https://getbootstrap.com/) or similar alternatives with a longer track record.

Last but not least, this library is not ugly, I have a beautiful fully responsive web app using this library (running v0.38.2) : [Campus Discounts](https://campus-discounts.com/).

There is a saying, "a bad workman blames his tools". I think it applies in this case.

**Comment by midenok** [comment]
In this case I'm not a developer, but user who compares old-style sites and new-style sites. In new-style you don't read, but click and scroll a lot. Fixed top bar takes a lot of screen, monochrome icons are indistinguishable from each other. It's real experience of 20+ years of many hours a day that tells you this. You are saying that it is new and immature, buggy, etc. There is good working standard of classical design and UI that should be taken as a basis for a starting version, but not making everything upside-down. Only selfish people are denying existing good in favor of own mediocre jobbing.

**Comment by The-Don-Himself** [comment]
That site is used by thousands of university students as we speak, but I understand, it could be an age thing that makes you see it different from them.

I know this is not the forum to debate or argue so I'll leave it at that. You are free to use any other library.

Cheers.

**Comment by midenok** [comment]
This is the **trend**, so we are talking about hundreds of millions, not thousands. Trend that was provided by Apple, Microsoft, Google and maybe someone else. But who did say that numbers means quality. Popularity was always mediocre thing. And average Joe maybe really don't want to read more than 3 lines of text and see more than one color. But he won't learn to read more, to do more if there is no such possibility. I guess if your site provided several hundreds of search results it were a nightmare to scan them all.

**Comment by lynnjepsen** [comment]
Thank you all for the feedback. I believe most of the feedback in this thread is directed at our material.io site, so I have forwarded your feedback to the team that works on the material.io site. That team works closely with the MDC Web team.

In the future, you can file feedback on the material.io site through this feedback link
![pjk70nqi2tf](https://user-images.githubusercontent.com/4703432/45056762-ad835780-b048-11e8-9d77-76795bdcbb9f.png)

Or, if you file GitHub issues instead, we will continue to forward that feedback to the material.io team.
