### ISSUE TITLE
MDC-Web Dialog Mandatory mdc-dialog__surface Missing From Documentation Examples

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#3621]
The [documentation example code](https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog) does not work as the mandatory `mdc-dialog__surface` class is missing. 
**FIX:** 
Add `mdc-dialog__surface` class to element with `mdc-dialog__container`.

Also the `mdc-dialog__scrim` is not working at all. 
**FIX:** 
add class `mdc-dialog__backdrop` to the element with `mdc-dialog__scrim`.

Lastly, the HTML5 `<aside>` element seems more appropriate for the `mdc-dialog`.

> The HTML `<aside>` element represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes. 

Source MDN's [The Aside element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside)

**Comment by kfranqueiro** [comment]
Thanks for catching the missing `surface` element in the docs!

RE `aside`, I recall noticing Dialog's root element got changed from `aside` to `div` when it was first updated in this cycle, but I forgot to ask about that during review. I'm changing it back in the PR I'm going to send out, but I've got a question out to Andy to confirm and I'll have him review it.

**Comment by acdvorak** [comment]
I changed `<aside>` to `<div>` because ARIA is very prescriptive about which elements to use, and it only allows dialog-related attributes on `<div>` elements.

According to https://mdn.io/html/aside:

> Permitted ARIA roles: `feed`, `note`, `presentation`, `region`, `search`

From https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html#rps_label:

| Role | Attribute | Element | Usage |
| -- | -- | -- | -- |
| `dialog` | | `div` | Identifies the element that serves as the dialog container. |
| | `aria-labelledby=IDREF` | `div` | Gives the dialog an accessible name by referring to the element that provides the dialog title. |
| | `aria-describedby=IDREF` | `div` | Gives the dialog an accessible description by referring to the dialog content that describes the primary message or purpose of the dialog. Used in three of the four dialogs included in the example. See the above accessibility features section for an explanation. |
| | `aria-modal=true` | `div` | Tells assistive technologies that the windows underneath the current dialog are not available for interaction (inert). |

A `<div>`, on the other hand, can have any ARIA role.

**Comment by kfranqueiro** [comment]
Missing `surface` element fixed in #3623
