### ISSUE TITLE
Card: Proposed Simplified Approach w/ CSS Grid

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#3632]
Maybe explore the idea of simplifying the approach to the card using simple, standards-based markup and CSS. 34 line of HTML, 48 lines of CSS. ...Just throwing this out there. [Here's the codepen](https://codepen.io/rhroyston/pen/wEbZLN).

<img src="https://user-images.githubusercontent.com/12751611/45985879-ebfba900-c02d-11e8-945e-a113f17f9302.png" width=156>
<img src="https://user-images.githubusercontent.com/12751611/45985913-1a798400-c02e-11e8-994f-b7cff79aa11e.png" width=156>

```
<section class="card">
    <h6 class="mdc-typography--headline6">Headline 6</h6>
    <h6 class="mdc-typography--subtitle1">Subtitle 1</h6>
    <p class="mdc-typography--body2">Body 2. Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <button class="mdc-button">
        Read
    </button>
    <button class="mdc-button">
        Bookmark
    </button>
    <button class="mdc-icon-button" aria-label="Like Button" aria-hidden="true">
        <svg class="mdc-icon-button__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            ...
        </svg>
    </button>
    <button class="mdc-icon-button" aria-label="Share Button" aria-hidden="true">
        <svg class="mdc-icon-button__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            ...
        </svg>
    </button>
    <button class="mdc-icon-button" aria-label="More Button" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            ...
        </svg>
    </button>
</section>
```

...and CSS

```
.card {
    display: grid;
    grid-template-columns: 1fr 1fr 48px 48px 48px;
    grid-template-rows: 50% auto auto auto 48px;
    grid-gap: 8px;
    min-height: 0;
    height: 500px;
    min-width: 0;
    max-width: 400px;
    
    background-position: top;
    background-repeat: no-repeat;
    background-size: 100% 50%;
    background-image: url("https://hightechtele.com/media/plasticballs.jpg");
    -webkit-box-shadow: 0px 2px 6px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 0px 2px 6px 0px rgba(0,0,0,0.75);
    box-shadow: 0px 2px 6px 0px rgba(0,0,0,0.75);    
}
.card .mdc-typography--headline6 {
    grid-column: 1 / span 5;
    grid-row: 2;
    margin: 12px 12px -48px 12px;
}
.card .mdc-typography--subtitle1 {
    grid-column: 1 / span 5;
    grid-row: 3;
    margin: 0px 12px -48px 12px;
    color: #424242;
}
.card .mdc-typography--body2 {
    grid-column: 1 / span 5;
    grid-row: 4;
    margin: 0px 12px 12px 12px;
    color: #424242;
}
.card .mdc-button {
    grid-row: 5;
    align-self: center;
}
.card .mdc-button:nth-of-type(1){
    grid-column: 1;
}
.card .mdc-button:nth-of-type(2){
    grid-column: 2;
}
.card .mdc-icon-button{
    grid-row: 5;
}
```

**Comment by abhiomkar** [comment]
Thanks for the proposal @rhroyston! 

This approach looks very neat and importantly avoids nesting elements. Unfortunately, CSS Grid is not fully supported in IE11 that MDC Web is compatible with. I'm interested to see how the CSS Grid syntax changes with `-ms-` prefix on IE11. & I'm not sure if it can render similar to other browsers even with fallback CSS.

**Comment by kfranqueiro** [comment]
I don't think we would want to build cards around grid within MDC Web. Aside from the reason of IE support, the grid styles presented above may work for your example, but it presents some problems:


* The columns seem rather contrived and brittle (see: nth-of-type selectors)
* The arrangement of buttons deviates from [spec](https://material.io/design/components/cards.html#specs), which indicates that buttons remain their natural width based on content and only the padding in between is set to a specific value
* The rich media is applied rather loosely as a background image with percentage sizes, which means it would quickly distort and not maintain the correct aspect ratio if the card were to become taller or wider due to its content

Cards are relatively free-form, so if adhering to CSS grid works for you (and you don't need IE 11 support), then that may be fine. But out of the box, our goal is to provide styles that adhere to spec for regions of cards that are well-defined, and that scale and adjust properly across use cases. That's how we arrived at the documented DOM structures and classes.
