### ISSUE TITLE
[Help wanted] Useing MDC with php in xAMPP

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3668]
I really want to use MDC in a website that I'm building with php and mysql, but I'm having a few issues. I can't seem to get npm (specifically webpack-dev-server) playing nicely with xAMPP. Since they both run a localhost. I can get them to run on different local hosts (localhost:8080 for xAMPP and localhost:8082 for npm), but I cant seem to get them running in the same localhost, or directory. I would love to hear any thoughts on how I should go about doing this as I would love to use MDC for this website.

**Comment by abhiomkar** [comment]
Webpack dev server might not be very useful for your usecase. You would need to bundle your JS and point the compiled version in script tag that'll be rendered on PHP page.

**Comment by CyborgSemon** [comment]
@abhiomkar And how would I go about doing that... I'm kinda new to this :P

**Comment by kfranqueiro** [comment]
In short, you run `webpack` instead of `webpack-dev-server`, which should just generate the assets in-place.  For example, following the getting-started example, if you just run `npx webpack`, it will generate `bundle.js` and `bundle.css` in the project directory. You can then copy those 2 files to a folder served by any static web server.

I've been meaning to get to #3062 for some time which involves adding docs for this. I'm going to close this since it's effectively a duplicate.

**Comment by CyborgSemon** [comment]
Sweet. thank you!
