### ISSUE TITLE
[List] Not able to arrow through the list when focus is on list root.

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#3760]
Steps to reproduce:
1. Render interactive list.
2. Focus on list root element.
3. Press DOWN arrow.

Actual result:
Nothing gets focused.

Expected result:
First list item needs to be focus when DOWN key is pressed. & Last list item needs to be focused on UP key.

[Codepen](https://codepen.io/abhiomkar/pen/dgZJNX).

**Comment by kfranqueiro** [comment]
If I remove the focus call from that codepen and instantiate the MDC List component it works (and arrow keys are never going to work without the List JS). I'm not sure this is a valid bug?

**Comment by abhiomkar** [comment]
Updated the codepen in just few minutes ago. PTAL.

You need to press arrow keys when the root is on focus. For example, The menu component that contains list when not have any item on focus when it is opened but the list root might be on focus.

**Comment by kfranqueiro** [comment]
I think the main intended context of this issue is related to menus.

FYI, when we worked on Menu, our designers stated that focus should immediately move to the first item in the menu when it opens, which is why this case currently doesn't exist / isn't handled. (Unfortunately the Menu design article on material.io doesn't mention focus at all.)

The possibility of menus not immediately focusing a menu item might be more relevant in the context of menu bars, which the design article doesn't really mention in any detail. Native OSes are inconsistent in how they handle this: OS X keeps focus on the menu bar item when it first opens, whereas Windows immediately focuses a child menu item (but arrow left/right still move between menu bar items and immediately open the neighboring menu).
