### ISSUE TITLE
Investigate migrating unit tests from Sauce Labs to CBT

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#3854]

**Comment by kfranqueiro** [comment]
An alternative to this would be to leave unit tests on SauceLabs but revert to an open sauce account and focus resources in terms of concurrency on CBT for screenshot tests.

In #4046 I updated our karma config so that we only need one remote unit test run, and Open Sauce accounts are allowed 5 concurrent runs, which means we should now be able to run unit tests on 5 PRs concurrently even with an Open Sauce account.

**Comment by kfranqueiro** [comment]
We're going with leaving our unit tests running on Sauce Labs for now, to leave more room for concurrent screenshot tests on CBT.
