### ISSUE TITLE
Ripple effect only happens on mouse up

### ISSUE THREAD

**Issue by LoganDark** [material-components/material-components-web#388]
[Material Design Lite](https://getmdl.io) shows a ripple effect on buttons on mouse down, but this version only shows it on mouse up. I prefer the ripple effect on mouse down. Could this be changed? Is there a workaround?

I don't have knowledge of what version [this website](http://material-components-web.appspot.com) uses

**Comment by traviskaufman** [comment]
Hey @LoganDark,

Unfortunately we are not open to changing this, since a ripple effect on mouse up is actually spec-compliant. We have consulted with our designers before implementing the ripple and this is the UX treatment that they recommended for us. 

The only workaround I can think of is attaching an event listener for mousedown/pointerdown/touchstart which programmatically calls [deactivate()](https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple#mdcrippledeactivate) within a `setTimeout`. Other than that I'm not sure.

**Comment by anton-kachurin** [comment]
Note: there is a bug in the current version which does not allow to run deactivate_(null) if the component is  activated by anything other than activate_(null), so you probably would have to create events of appropriate types and dispatch them manually

**Comment by LoganDark** [comment]
@traviskaufman on android it happens on touch and not on release, on most google chrome application components (bookmarks bar elements and stuff, but for some reason not on macOS) it does as well, holding it down makes the ripple stay there after expanding instead of fading out

**Comment by LoganDark** [comment]
Well, upgrading to android 7.0, the effect only happens when you release. That's sad, and I miss the old effect. :(
