### ISSUE TITLE
Compatibility with AMP

### ISSUE THREAD

**Issue by Download** [material-components/material-components-web#389]
I am wondering, is Material Components Web compatible with [AMP](https://www.ampproject.org/).

I do not find any mention of AMP on this project and the AMP website does not mention Material Components. 

Both Google projects seem to be targetting the same kind of modern progressive web app style, but I don't think we are allowed to include the material components web JS script in an AMP page... So can we combine them?

I am wondering about this because I am hoping to support AMP and it would be very convenient if the AMP pages could use the same Material Components as the main pages... But I wonder if it's possible?

Is AMP support a target for you guys?
Do you have pointers on docs/guidance about this?

If I am right in thinking we cannot embed the material-components-web JS script on an AMP page, is there guidance available on which components we can still use if we don't have this script?

**Comment by traviskaufman** [comment]
Unfortunately Material Components for the web is _not_ compatible with AMP as of now.

AMP doesn't allow JS on its pages, which MDC-Web needs for its more complex components. Furthermore, there are [certain restrictions on CSS styles](https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages), such as disallowing `!important` and `:not`. We make use of both of these constructs within our (S)CSS, since in many cases its needed to facilitate the complexity of the Material Design UX.

Having custom AMP components built that leverage MDC-Web is something that we can definitely investigate in the future, but it's not on our radar right now.

**Comment by Download** [comment]
Thanks for your explanation!

**Comment by niutech** [comment]
You can use the [Surface](http://mildrenben.github.io/surface/) CSS-only framework to create AMP pages - see the [demo](http://jsbin.com/xohugojufe/).

**Comment by rhroyston** [comment]
Curious of MDC-Web could provide guidance on achieving some goals of the AMP project, namely, fastest possible loading / rendering of pages. One thing I see them doing in AMP is embedding the CSS in the `head` and avoiding reflow / repaint of the page. Usage of `srcset` and art direction. Seems like we could get this baked into the Getting Started Guide or a Best Practices Guide. 

As an aside, AMP's caching seems to be heavily highlighted. Doesn't Firebase hosting have this baked in already (i know getting off topic, ..but)

**Comment by niutech** [comment]
Update: I have also AMP-lified another Material Design CSS framework [MUI](https://github.com/niutech/amp-mui/) - see the [demo](https://niutech.github.io/amp-mui/).
