### ISSUE TITLE
load components multiple times on the same page

### ISSUE THREAD

**Issue by broros** [material-components/material-components-web#4004]
load text field component multiple times on the same page using the same class..

when I add 2 text fields on the same page only the first text field works , second and third text field does not work.

```
<div class="mdc-text-field">
  <input type="text" id="my-text-field" class="mdc-text-field__input">
  <label class="mdc-floating-label" for="my-text-field">Hint text</label>
  <div class="mdc-line-ripple"></div>
</div>

<div class="mdc-text-field">
  <input type="text" id="my-text-field" class="mdc-text-field__input">
  <label class="mdc-floating-label" for="my-text-field">Hint text</label>
  <div class="mdc-line-ripple"></div>
</div>


<div class="mdc-text-field">
  <input type="text" id="my-text-field" class="mdc-text-field__input">
  <label class="mdc-floating-label" for="my-text-field">Hint text</label>
  <div class="mdc-line-ripple"></div>
</div>

```

**Comment by kfranqueiro** [comment]
This is more of a generic DOM question than anything specific to MDC Web.

Many of MDC Web's examples show using `document.querySelector(...)` to retrieve an element. `querySelector` retrieves at most exactly **one** element (and stops searching once it finds one). To work with multiple elements, you'll want to use `document.querySelectorAll` instead, e.g.:

```js
const textFields = [].map.call(document.querySelectorAll('.mdc-text-field'), function(el) {
  return new MDCTextField(el);
});
```

Since this comes up every so often from newcomers, I'm sending a PR to add examples to the centralized docs for importing JS which are linked from most of our READMEs.
