### ISSUE TITLE
[Help wanted] / possible feature request | Card with side image

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4015]
Is there support make a card that is more styles towards this?

<img width="475" alt="screen shot 2018-10-30 at 1 59 11 pm" src="https://user-images.githubusercontent.com/26075792/47688832-038d0980-dc4c-11e8-9b42-7dde2e8407a9.png">

If not, could I request that support is added as it is also apart of the card image in the catalog.
<img width="222" alt="screen shot 2018-10-30 at 2 00 32 pm" src="https://user-images.githubusercontent.com/26075792/47688898-42bb5a80-dc4c-11e8-9c29-0b34ef6d1b06.png">

So support for images on the left or right.

**Comment by kfranqueiro** [comment]
Cards are relatively free-form so we might not have examples of everything, but I believe we used to have an example like this in the old catalog. This might be something we can incorporate in the new catalog.

I created https://github.com/material-components/material-components-web-catalog/issues/222 to track this there. I'm going to close this issue here since I don't think there's any action necessary within the MDC Card package directly.
