### ISSUE TITLE
ripple on lists?

### ISSUE THREAD

**Issue by br4nnigan** [material-components/material-components-web#4031]
Why does the demo have a ripple effect when in "usage" it's not being initialized? Do you know how long I wondered what I had done wrong? FFS...

**Comment by kfranqueiro** [comment]
Many of our components with JS automatically instantiate ripples within their component logic. MDC List is an exception, due to the complexity that would arise out of needing to create and tear down instances if anyone were to dynamically add/remove list items. In that situation, you would need to manually call an API anyway, thus limiting the value of the automatic instantiation.

That being said, we should explicitly document this.
