### ISSUE TITLE
MDC Select outlined: Error: <path> attribute d: Expected number, "MNaN,1hNaNaNaN,Na…".

### ISSUE THREAD

**Issue by kidar2** [material-components/material-components-web#4075]
The essence of the bugs is that mdc-select is created with an error if you attach it to html markup that has not yet been added to the document.

### What MDC Web Version are you using?
0.41.0

### What browser(s) is this bug affecting?
Chrome 70.0.3538.77
### What OS are you using?
Windows 10

### What are the steps to reproduce the bug?
1. Open the link [http://jsfiddle.net/qj4a1x50/ ](http://jsfiddle.net/qj4a1x50/ )
2. Open console dev tools
3. Click the "create" button => 
 _<path> attribute d: Expected number, "MNaN,1hNaNaNaN,Na…"._

### What is the expected behavior?
No errors in console

**Comment by acdvorak** [comment]
Thanks for filing this issue!

It looks like your `create()` function is detaching the `#container` element from the DOM before instantiating `MDCSelect`:

```js
function create()
{ 
   let node = document.querySelector('#container');
   document.body.removeChild(node);
   mdc.select.MDCSelect.attachTo(node.querySelector('.mdc-select'));
}
```

This will not work because `MDCNotchedOutlineFoundation` needs to measure the `.mdc-select` element in order to draw the SVG outline. We can only measure it if it's attached to the DOM. (That might change once we fix #4066.)

If you set a breakpoint on [your JSFiddle](http://jsfiddle.net/qj4a1x50/), you'll see all the measurements return `0` or `NaN`:

![image](https://user-images.githubusercontent.com/409245/48367677-498f9780-e666-11e8-908e-262d74b765d3.png)

Make sure the element is attached to the DOM before instantiating `MDCSelect`, and you should be good to go 😀 

If you think there's a bug in MDC Web, feel free to reopen!

**Comment by kfranqueiro** [comment]
PS: We are currently working on a new implementation of the notched outline which will no longer require SVG, which should avoid a lot of the problems around requiring the element to be in document flow.

**Comment by kidar2** [comment]
Сan you say when you expect a new version release?

**Comment by acdvorak** [comment]
#4066 is currently slated for [milestone R21 (v0.42.0)](https://github.com/material-components/material-components-web/milestone/12), which is due by December 03, 2018.

This could potentially change if other issues come up, but that's the tentative plan.
