### ISSUE TITLE
mdc-fab stays highlighted when closing a dialog it opened

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#4080]
## Bugs

The FAB button stays highlighted after a dialog is closed that it opened.

### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Chrome Version 70.0.3538.102 (Official Build) (64-bit)

### What OS are you using?

> MacOS 10.14.1

### What are the steps to reproduce the bug?

> Have a FAB open a dialog
> Close the dialog with one of the buttons (doesnt matter which one)
> The FAB stayed highlighted even though the ripple animation has passed while the dialog was open.
>
> Visit [CodePen](https://codepen.io/anon/pen/QJGedJ)

### What is the expected behavior?

> The FAB does not stay highlighted when the dialog is closed

### What is the actual behavior?

> The FAB stays highlighted when the dialog is closed

**Comment by abhiomkar** [comment]
Hi @CyborgSemon, this is expected behaviour as per dialog accessibility guidelines. The focus should restore to last focused element when dialog is closed. Please see [Handling focus trapping](https://github.com/material-components/material-components-web/tree/master/packages/mdc-dialog#handling-focus-trapping) section of dialog.

**Comment by CyborgSemon** [comment]
ahhhh ok sweet. thanks
