### ISSUE TITLE
Bug in get selectedChipIds? (space)

### ISSUE THREAD

**Issue by rhroyston** [material-components/material-components-web#4096]
Master branch, I simply console.dir(mdc), traverse the object and it sure looks like there's a space in the method name?

![image](https://user-images.githubusercontent.com/12751611/48750818-b4cd0100-ec46-11e8-999b-03a25fa7f456.png)

**Comment by rhroyston** [comment]
Suggestion: the developer probably wants to know the `innerText` of the selected chips, ...no the `id`'s.

```
function getSelectedChipsText(chipsetEl){
    var selectedChipElements = chipsetEl.querySelectorAll(".mdc-chip--selected");
    var textArray = [];
    for (var i = 0; i < selectedChipElements.length; i++) {
        var chipText = selectedChipElements[i].querySelector(".mdc-chip__text").innerText;
        textArray.push(chipText);
    }
    return (textArray);
}
```

**Comment by kfranqueiro** [comment]
`get ...` is typically how developer tools represent an ES5 getter. `get selectedChipIds` isn't a method name - it's a property that executes code when referenced (via `chipset.selectedChipIds`).

The reason it returns IDs rather than text content is because IDs are already integral to the selection feature of the chip set, and returning text content is apt to be error-prone especially in the context of localization. By returning an ID you get something that is guaranteed to uniquely identify the chip, and you can potentially tie this back to another data structure if you wish (or query the text content yourself based on the ID, if you want to do that).

**Comment by rhroyston** [comment]
the documentation appends it with `()` and refers to it as a "method Signature". ...Not sure why documentation would not simply call it what it is - a property? Kinda misleading.

![image](https://user-images.githubusercontent.com/12751611/48792019-d1098600-ecb8-11e8-8042-fa2564a3f7a3.png)

**Comment by abhiomkar** [comment]
@rhroyston Good find! I just sent #4099 to fix the documentation.
