### ISSUE TITLE
mdc-list-group inside mdc-menu

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#4097]
### What MDC Web Version are you using?

Latest which at time of writing is 0.41.1

### What browser(s) is this bug affecting?

I'm using chrome, but this is not a browser specific issue.

### What OS are you using?

Windows 10.

### What are the steps to reproduce the bug?

I'm trying to use an mdc-list-group inside an mdc-menu.

See codepen at https://codepen.io/deap82/pen/aQVGop

The first group in the menu works as expected but;
1. Selecting with mouse in the second group does not close the menu.
2. Second group is not reachable with arrow keys.

### What is the expected behavior?

To be able to use an mdc-list-group inside an mdc menu.

### What is the actual behavior?

See above.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

MDC Menu component do not support having multiple list components inside the menu. I suggest using list dividers to visually separate and group the menu items instead of creating individual groups.

Alternatively you can also follow this [drawer example](https://material-components.github.io/material-components-web-catalog/#/component/drawer/permanent) where `mdc-list-group__subheader` element is used to label the groups.
