### ISSUE TITLE
List: Use appropriate role for selected/activated list items based on parent role

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#4128]
From #3403:

We may be able to auto-detect the presence of roles in which `aria-selected` is valid, and in other cases opt for `aria-current` instead (which is the most semantically-correct attribute to use for e.g. drawer navigation).

Since this role is applied dynamically within the List foundation based on user interaction, it would require JS updates, in addition to documentation updates to the relevant components.

**Comment by abhiomkar** [comment]
Turns out `aria-current` is not supported by major screen readers since this ARIA attribute is relatively new and not being used in most of the sites as navigation state.

References:

- Work around for aria-current for cross-screen reader support: https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/current/
- Supported screen readers: https://labs.levelaccess.com/index.php/Aria-current_attribute
- Navigation landmark example: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/navigation.html
- W3C aria-current spec: https://www.w3.org/TR/wai-aria-1.1/#aria-current

**Comment by abhiomkar** [comment]
Here are some useful pointers from accessibility team:

* http://design-patterns.tink.uk/aria-current/
* https://www.w3.org/WAI/tutorials/menus/structure/#using-wai-aria

Seems like `aria-current` is indeed supported by majority of the screen readers as per `tink.uk` data.

I tested that it works on Safari with VoiceOver.
ChromeVox (on Mac) has a bug opened to implement `aria-current`:
https://bugs.chromium.org/p/chromium/issues/detail?id=609362
