### ISSUE TITLE
MDCDialog: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by vedtam** [material-components/material-components-web#4131]
Hi,

I noticed this uncaught error while implementing MDCDialog in my custom element. The dialog opens still, but the error gets thrown in the console:

![screen shot 2018-12-01 at 02 10 32](https://user-images.githubusercontent.com/4981592/49321306-4e31c800-f50f-11e8-9598-19bb412d0eeb.png)

I have have put together a [sample project on GLitch](https://glitch.com/edit/#!/nonchalant-tuesday?path=src/app-home.js:1:0) that demonstrates the issue.

------------------------

### What MDC Web Version are you using?

> 0.41.0

### What browser(s) is this bug affecting?

> Chrome 70

### What OS are you using?

> OSX

### What are the steps to reproduce the bug?

> 1. Set up a custom element 
> 2. Import and initialise MDCDialog, add markup
> 3. Trigger a MDCDialog.open()
> 4. Observe the error in Devtools

**Comment by abhiomkar** [comment]
Thanks for reporting this issue @vedtam! 

Seems like a bug in tabbable third-party library that we use for focus trap. It breaks when using `.parentNode` on `#shadow-root` when [calculating](https://github.com/davidtheclark/tabbable/blob/e8ecf52617fe97066361356070ae42364e089c8b/index.js#L185) if a target element is shown on the page.

**Comment by kfranqueiro** [comment]
FWIW, it might be worth seeing how the Web Components wrapper (https://github.com/material-components/material-components-web-components) gets around this issue (they wrap MDC Dialog).

**Comment by abhiomkar** [comment]
Web components implementation seem to be using [PolymerLabs/blocking-elements](https://github.com/PolymerLabs/blocking-elements) which is more aligned with the web standard.

Maybe we should move to this?

**Comment by vedtam** [comment]
While going trough [material-components-web-components](https://github.com/material-components/material-components-web-components/blob/master/packages/dialog/mwc-dialog.js#L79) dialog implementation, I noticed the comment on [line 79](https://github.com/material-components/material-components-web-components/blob/e4d94121944d6dc045fe6bd462d3881c24d60b87/packages/dialog/mwc-dialog.js#L79): 

> TODO(sorvell): DialogFoundation's `isOff` method does not work with Shadow DOM
> because it assumes a parentNode is parentElement (thing you can call getComputedStyle on)

Haven't tested the element, but I guess they face the same issue.

**Comment by acdvorak** [comment]
Possibly related: #4104

@abhiomkar Unfortunately, we can't use the `blocking-elements` library because
[it relies on `Symbol()`](https://github.com/PolymerLabs/blocking-elements/blob/3033577abbe7fb8f675a270a2f51533708c0d848/blocking-elements.js#L20), which is [not supported in IE](https://mdn.io/js/Symbol#Browser_compatibility).

The comment on [line 79 of `material-components-web-components`](https://github.com/material-components/material-components-web-components/blob/e4d94121944d6dc045fe6bd462d3881c24d60b87/packages/dialog/mwc-dialog.js#L79) is inaccurate;
`isOff()` is a function in `tabbable`, not `MDCDialogFoundation`.

I noticed that we're currently using outdated versions of [`focus-trap`](https://github.com/davidtheclark/focus-trap) and [`tabbable`](https://github.com/davidtheclark/tabbable):

> `@material/dialog@0.42.0` → `focus-trap@2.4.3` → `tabbable@1.1.2`

We could try updating to the latest version of `focus-trap` (`3.0.0`), but I'm guessing that won't fix the problem, because the latest version of `tabbable` (`3.1.1`) still uses `parentNode` and assumes it's an `Element`.

Somebody filed https://github.com/davidtheclark/tabbable/issues/34 ("getComputedStyle fails with shadow dom"), but they closed it without any explanation. Maybe we should reopen it and send them a PR to fix it?

**Comment by acdvorak** [comment]
Created upstream PR to fix this: https://github.com/davidtheclark/tabbable/pull/35

**Comment by kfranqueiro** [comment]
Update: The PR was merged and the maintainer claimed it's in a release, but no new tabbable release has yet been tagged with the merged PR, so this isn't fixable on our end yet.
