### ISSUE TITLE
MDCTextField labels gets crossed out by the outline.

### ISSUE THREAD

**Issue by vedtam** [material-components/material-components-web#4157]
Hi,

When updating the value of a text field (programatically) in my SPA, while the host element is `hidden`, as the element becomes visible again labels get crossed out by the outline.

![screen shot 2018-12-08 at 23 34 00](https://user-images.githubusercontent.com/4981592/49691135-9ae75580-fb44-11e8-8761-a1407ad2aa59.png)

From what I have observed while experimenting, if the value of a textfield gets set without first clearing the previous value, the outline animation doesn't get triggered and the above issue happens.

I have put together a [glitch demo that illustrates the issue.](https://mdc-textfield-notch-issue.glitch.me)

### What MDC Web Version are you using?

> ^0.42.0

### What browser(s) is this bug affecting?

> Chrome 70

### What OS are you using?

> OSX

**Comment by williamernest** [comment]
Thanks for filing this issue. You need to call `.layout()` after the text field is shown so that the width of the label can be calculated correctly. When the text field is hidden, the width returned is 0. You can also wait to instantiate the text field until after it is shown to prevent this issue as well.

**Comment by vedtam** [comment]
@williamernest thanks for your feedback. Earlier I have tried using `.layout()` but it doesn't seem to make any difference, and the text fields are instantiated long before I'm setting their values:

```
...
firstUpdated() {
    this.storyTitle = new MDCTextField(this.shadowRoot.querySelector('.story-title'));
    this.storyDescr = new MDCTextField(this.shadowRoot.querySelector('.story-descr'));
  }
  
  updated(changedProps) {
    this.storyTitle.value = this.state[this.storyId].title;
    this.storyDescr.value = this.state[this.storyId].descr;
    
    this.storyTitle.layout();
    this.storyDescr.layout();
  }
```
I forgot to share the source, please have a look:
https://glitch.com/edit/#!/mdc-textfield-notch-issue?path=src/item-app.js:61:4

**Comment by williamernest** [comment]
Your component is eagerly instantiated when the page loads instead of when the active flag is set. You have a couple of options here. 

You can set the component up to instantiate after the parent is updated (you can do this by passing the active prop down to the child element and instantiating the component when that is updated.

You can dynamically insert the html after the active attribute is updated, so that the component instantiates after the markup is shown. 

I also recommend you take a look at the `material-components-web-components` repo, which may have resolved this issue with their text field component.

**Comment by vedtam** [comment]
@williamernest, aham, thanks, well the above two solutions could totally work. I try checking out `material-components-web-components`, maybe there's something related to the above. I would like to be in sync if possible with what they/you r doing :)
