### ISSUE TITLE
Enhanced select menu doesn't stay open

### ISSUE THREAD

**Issue by MarcoTroost** [material-components/material-components-web#4173]
When using the the enhanced version of the mdc-select menu (v. 0.42.0), the menu-list immediately disappears. One would expect the menu to stay open until it loses focus.

This behavior can also be seen @ https://material-components.github.io/material-components-web-catalog/#/component/select , at least on my computer (mac os mojave, chrome v 71).

**Comment by williamernest** [comment]
Thanks for filing this issue. It looks like any long-click on the enhanced select will cause the menu to close when you release. Definitely a bug.

**Comment by shelart** [comment]
I think it's caused by the same reason as the enhanced MDCSelect doesn't work on touch screens. It seems like Chrome emits both events `touchstart` and `mousedown` when a laptop trackpad used, as a touch screen on mobile devices.
I actually don't understand why MDC have to listen for `...down` events instead of listening just `click`-s, which are working well on all types of devices: mouse, touchpad, touch screen (tested).
