### ISSUE TITLE
[TabBar] MDCTabBar: At least one tab must have mdc-tab--active class

### ISSUE THREAD

**Issue by RobJacobs** [material-components/material-components-web#4226]
There must be one tab element in the tab bar component with a class of mdc-tab--active or an error is thrown in the console: Cannot read property 'deactivate' of undefined when switching tabs

### What MDC Web Version are you using?

Latest from master branch.

### What browser(s) is this bug affecting?

All

### What are the steps to reproduce the bug?

See this [CodePen](https://codepen.io/robjacobs/pen/Kboapr?editors=1011) example.  Notice the error in the console that results from trying to use the tab bar activateTab method.  Notice the error is also thrown when clicking on tabs.  Uncommenting the last tab in the example fixes the issue as it has a mdc-tab--active class.

### What is the expected behavior?

Using the mdc-tab--active class to initially set the active tab should not be required.  You should be able to use the mdc-tab activateTab method to set the initial active tab.

### What is the actual behavior?

You must use the mdc-tab--active on at least one child mdc-tab element.

**Comment by abhiomkar** [comment]
Thanks for reporting this issue.

This is expected behaviour of MDC TabBar, it mandates to have at least one tab to be active by default. Please refer [Tabs spec](https://material.io/design/components/tabs.html#states) article on Material Design site.

Can you please give us some more context on why would the tabs won't be active by default in your example?

**Comment by acdvorak** [comment]
After talking to Patty, the entrance animation is going to look weird with the changes I suggested above, because we would be animating from coordinate `(0, 0)` to wherever the new active tab is.

@RobJacobs Can you tell us a little bit more about your use case? Why aren't you able to add the
`--active` CSS classes in the HTML?

**Comment by RobJacobs** [comment]
@acdvorak Thanks for looking into this.  When a user loads the view with the tab-bar, I want to set the active tab to the tab they were previously on.  Using the activateTab method seemed like the better approach rather than having to write my own querySelector or go after children[index] to apply the --active classes (both the tab and tab-indicator) manually.  Could you bypass the animation if there is no previously activated tab?

**Comment by kfranqueiro** [comment]
Thanks for the explanation. The idea seems reasonable; we'll need to see what implementation details are required to bypass the animation in that case.

**Comment by marcoherzog** [comment]
I am facing the same issue as I am implementing _multiple_ MDCTabBars as navigation elements on a theme. Indicating the current page. Sure... might not be the original use case.   


![Screenshot 2019-03-16 at 11 26 10](https://user-images.githubusercontent.com/2692054/54473901-625bb580-47de-11e9-8b22-0a74e346ab2f.png)
