### ISSUE TITLE
MDC Menu: Menu pop-up gets reopen on selection using space key (Firefox)

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4231]
### What MDC Web Version are you using?

> v0.42.1

### What browser(s) is this bug affecting?

> Only Firefox

### What OS are you using?

> Mac OS X

### What are the steps to reproduce the bug?

1. Open [menu catalog](https://material-components.github.io/material-components-web-catalog/#/component/menu) page.
2. Navigate to menu button using keyboard and open using space key.
3. Select menu option using space key.

### What is the expected behavior?

> The menu should stay closed on menu selection using space key.

### What is the actual behavior?

> Menu pop-popup reopens on menu item selection.

**Comment by acdvorak** [comment]
I was able to repro in the v0.43.0 catalog:

![screen capture of bug](https://user-images.githubusercontent.com/409245/50992878-1f731e00-14cd-11e9-9a56-f0a1a0cc1ea2.gif)

This is an event timing bug. It only occurs if you press and hold <kbd>Space</kbd> for a long time (e.g., 1 second) before releasing it.

This is because we're closing the menu on `keydown` and restoring focus to the `Open Menu` button. So when the user finally releases the space key, it ends up activating the button, which re-opens the menu.

@kfranqueiro What should we do about this?

**Comment by kfranqueiro** [comment]
Key repeat seems related; this doesn't occur if I quickly tap the key. Ultimately, a click event is registering on the button after it is re-focused (which occurs intentionally when the menu closes, for accessibility). Additionally, if you hold enter instead of space, the menu rapidly re-opens and closes due to keyboard repeat.

This is also observable in other implementations such as [ARIA's menu examples](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html) (enter keypress specifically; they don't react to space, although the ARIA spec suggests that both space and enter should activate).

This is effectively a result of native browser behavior, and I'm inclined to think it's beyond the scope of MDC Menu to resolve, especially since hooking up a handler to open the menu is already outside the scope of the component itself. Working around this would likely require specifically handling `keydown` and `keyup`.

**Comment by acdvorak** [comment]
This might be technically solvable, but there are some gnarly edge cases that make it not worth the effort.

The menu could conceivably store a bit of internal state on `keydown` that would cause it to ignore all future `keydown` events until it detects a corresponding `keyup` event on the `document`.

However, I can see situations where this would cause problems. E.g., if the user does `keydown` <kbd>Enter</kbd>, and before releasing the <kbd>Enter</kbd> key, presses







 <kbd>Alt</kbd>+<kbd>Tab</kbd> to a different window—does `keyup` fire? In every browser?

Technically solvable, but probably not worth the effort. Close it.
