### ISSUE TITLE
select documentation points to wrong reference

### ISSUE THREAD

**Issue by mcalmus** [material-components/material-components-web#4247]
This is a documentation issue.

This page https://material-components.github.io/material-components-web-catalog/#/component/select links to the material design guidelines for text field rather than for select.

**Comment by kfranqueiro** [comment]
There is no dedicated page in the guidelines for the Select component. We currently point to the Text Field documentation since all of the styles and states for the select box itself are the same as Text Field.

The only other possible thing to point to would be the [Exposed Dropdown Menu](https://material.io/design/components/menus.html#exposed-dropdown-menu) which our enhanced Select variant implements using MDC Menu.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Perhaps surprisingly, the Material Guidelines don't have a separate "Select" component.
It's technically considered a variant of a "Text Field" with a dropdown menu.

On the Web, this functionality is normally provided by a native `<select>` element, and since we created this component before the design spec had firmed up, we decided to name it `mdc-select`.

As far as the _official_ design guidance is concerned, it's a "Text Field", which is why we link to
the [Text Field design article](https://material.io/design/components/text-fields.html#anatomy). We just gave it a platform-specific name on Web.

Sorry for the confusion, and thanks for helping to make MDC better by filing issues! 😀
