### ISSUE TITLE
mdc- on Beginning of Subdirectories Makes Keyboard Navigation Hard

### ISSUE THREAD

**Issue by nbtorcol** [material-components/material-components-web#425]
In some of the directories, such as packages, the subdirectories all start with mdc-, which makes keyboard navigation hard because many people who use the keyboard, including people who use screen readers, use first letter navigation--pressing the first letter of an item to move to it--to navigate.

**Comment by amsheehan** [comment]
@nbtorcol is this an issue related to file navigation in Github? If so I suggest taking a look at some of the (file finding features)[https://github.com/blog/793-introducing-the-file-finder] in Github. This does not require the user type `mdc-` before a component name, or even its path—so first letter navigation is still an option.

If this is an issue as it relates to text editors, all of the popular editors I know of have some sort of fuzzy file finder plugin (if one isn't built right in), e.g.: (ctrlP for Vim)[https://github.com/kien/ctrlp.vim] or (fuzzy-finder for Atom)[https://github.com/atom/fuzzy-finder]

I'll leave this issue open for further feedback. Thanks again!

**Comment by nbtorcol** [comment]
It is an issue where the repository is copied to a file system on a
computer.

**Comment by traviskaufman** [comment]
Hey @nbtorcol,

Thanks for bringing this to our attention. We were unaware of this restriction and will definitely keep it in mind going forward.

That being said, for this particular case, we're hesitant to rename all of our packages since we want those folder names to be representative of the CSS block classes that they expose. Furthermore, we use the `mdc-` prefix in some of our release tooling, which would have to be reworked. 

One workaround for this would be to create a saved search within the `packages/` folder which you could then use to search for files or directories. Hope that helps!
