### ISSUE TITLE
MDCTabBar: Scrolling does not work

### ISSUE THREAD

**Issue by RobJacobs** [material-components/material-components-web#4253]
### What MDC Web Version are you using?

Latest from master branch

### What browser(s) is this bug affecting?

Chrome, Edge

### What are the steps to reproduce the bug?

Got to the demo page, Tab section, Scrolling Tabs demo:

https://material-components.github.io/material-components-web-catalog/#/component/tabs

Resize the page so some tabs are hidden, notice the horizontal scroll bar below the tabs does not appear.

### What is the expected behavior?

A horizontal scrollbar should appear when the tabs overflow.

### What is the actual behavior?

No horizontal scrollbar appears.

**Comment by kfranqueiro** [comment]
This was done intentionally because the presence of scrollbar would be quite jarring within a tab bar above tab contents, especially on platforms where the scrollbar is always visible (e.g. windows).

Despite the scrollbar being hidden, horizontal scrolling does work, via touch or trackpad. Scrolling is also possible via mousewheel in combination with one of the modifier keys (shift on windows).

There is also an open request #3716 to add optional tab scroller indicators, and trimox has a suggested workaround in the interim.

**Comment by eprigorodov** [comment]
Scrollbar is visible in Firefox (123.0.1), and on the desktop that is much more intuitive to use. I'd guess that many end users are not aware of shift+scroll.
