### ISSUE TITLE
mdc-text-field-helper-text overlaping textarea label

### ISSUE THREAD

**Issue by rubenmendoza** [material-components/material-components-web#4288]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

![image](https://user-images.githubusercontent.com/3853885/51654706-42352480-1fed-11e9-9c75-56c5f4671c81.png)

### What MDC Web Version are you using?

> 0.4.31

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.
![image](https://user-images.githubusercontent.com/3853885/51654669-1023c280-1fed-11e9-90b0-d5652951f3bd.png)

##Solution
.mdc-text-field-helper-text{
margin-bottom: 0.75rem
}

**Comment by CyborgSemon** [comment]
I think a better solution would just to add extra top margin on the text area below the helper text? I'm not sure its an issue with the helper text as such, more of a user specific CSS issue rather than a global MDC CSS issue.
On the material components text field page, they have a title that separates the 2 text areas in question:
<img width="238" alt="screen shot 2019-01-24 at 8 32 33 pm" src="https://user-images.githubusercontent.com/26075792/51662028-686fba00-2017-11e9-88a5-466e7aca7d7d.png">
If you remove that title, then yes the helper text does overlap:
<img width="230" alt="screen shot 2019-01-24 at 8 32 44 pm" src="https://user-images.githubusercontent.com/26075792/51662044-74f41280-2017-11e9-8042-df09e1e8f90b.png">
But by just adding `margin-top: 8px;` to the bottom text field, the issue goes away:
<img width="218" alt="screen shot 2019-01-24 at 8 33 15 pm" src="https://user-images.githubusercontent.com/26075792/51662063-89380f80-2017-11e9-9572-68bc8571fed2.png">
This is not really something that should be changed in the MDC CSS for text field as it would only be needed for specific purposes.

**Comment by moog16** [comment]
This is actually intention. We did have margin/padding around TFs before, but removed them since it was as one-size fits all. If we kept the margin/padding on the TFs it might look good on your app, but not on someone else's. 

Therefore we ask that you implement the margin/padding yourself.
