### ISSUE TITLE
Select Menu not anchored to the control

### ISSUE THREAD

**Issue by tranrate** [material-components/material-components-web#435]
## What MDC-Web Version are you using?

0.7.0
## What browser(s) is this bug affecting?

Chrome Version 57.0.2987.110 (32-bit)
Firefox 52.0.1 (64-bit)
## What OS are you using?

Windows 10
## What are the steps to reproduce the bug?

On your Demo site, go to the Select demo. Reduce the size of your browser window so that you've got a scroll bar for the page. Open the Fully Featured Component, then use the scroll bar to scroll the page. 
## What is the expected behavior?

The Select Menu should scroll with the rest of the page so that it stays above its Input Control.
## What is the actual behavior?

The Menu doesn't move.
## Any other information you believe would be useful?

This only seems to happen to the Menu which is part of the Select. When the Simple Menu Control is used on its own, it works fine.

**Comment by tranrate** [comment]
mdc-select.scss line 87 change fixed to absolute. Seems to solve but needs fully testing.

**Comment by amsheehan** [comment]
Looks like you may be right on the proposed fix. Would you mind making a pull request with that change?

**Comment by lukebergen** [comment]
Running into a different but semi-related bug. Warning about checking that position from fixed to absolute: I think it'll mess up the position of the menu if the page has scrolled. e.g.
1) On the demo page http://material-components-web.appspot.com/select.html
2) Edit the style on the `.mdc-select__menu` to set the position to `absolute`
3) Edit the style on the H1 at the top of the page and set `margin-bottom: 1200px;` or so to force the select menu down below the fold.
4) Now scroll down to the menu and open it.

Note that the menu opens well above the element that it's supposed to be anchored to.

**Comment by traviskaufman** [comment]
err...are we sure that we want the intended behavior to be to have modal menus scroll with the page?

The JS menu was modeled after the browser's native contextual menu which:

- Has the highest possible z-index and true modality within the viewport regardless of it's stacking context
- Overflows any contained element to expand to the height of the viewport in order to show all possible options.

For this reason, we made the menu fixed position. If it were absolute, and the user scrolled past the menu, how would she then know that clicking on part of a page is actually canceling that menu.

Perhaps I'm missing something here? @amsheehan ?

**Comment by traviskaufman** [comment]
In any case, if I take the same repro steps with the native select menu, the page doesn't allow me to scroll. So maybe the right solution here would be to add scroll-locking to the select menu? However, if we do that then we may not be able to scroll the _menu_ item itself when its elements are overflowing, which could be the reason why we omitted that behavior in the first place 😉

**Comment by tranrate** [comment]
@traviskaufman Yes, like your suggestion of aligning with the css only select.

A quick test on Windows 10 - Chrome allows the css only menu to go outside the window, Firefox keeps it inside and goes up when necessary, and Edge goes up but only as far as necessary. Interestingly Edge seems to have the menu in a 'Fixed' position and allows scrolling of the window like the current fully featured component, Firefox and Chrome both close the menu as soon as you scroll.

Let me know when you've decided the best way to handle this as it should be fairly easy for me to do as I already know the code.

Also in the patch I submitted there is a fix for Luke Bergen's problem mentioned above when the select menu is at the bottom of the screen. Do you want me to raise a seperate issue for this and then submit a PR for just that?

**Comment by amsheehan** [comment]
After conferring with @traviskaufman we've reached consensus on how MDC Select should function. We do indeed want it to mimic the native select menu in its positioning and resizing behaviors. This would mean that a few things need to happen:

- Menus are truly modal. This also means that they should stay in view at all times, so that when they are dismissed, the user isn't left at an arbitrary point on the page with no context around why that is.
- Menus resize themselves to have enough vertical space to show all options
- Menus resize themselves to the height of the viewport, and scrolls overflowed options if the height of the viewport is too short for the number of options

Because of these things, the intended behavior is in fact already implemented in the current MDC Select component, and we do not need to add an adapter method to compute the container, nor do we need to bind the menu to it. Our defining characteristic for MDC Select is that as many of the select options should be visible at all times, even if it means moving and resizing the menu to achieve that behavior.

We appreciate the thought and effort evident in your pull request, but we have decided that the Select component is functioning as intended. Thank you for your work.
