### ISSUE TITLE
Snackbar should dismiss after action is taken

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#436]
When providing an `actionHandler` to a snackbar, some UI is shown for taking action:

![image](https://cloud.githubusercontent.com/assets/409615/24300981/294bc9d6-10a6-11e7-99e0-9b1992808cf6.png)

However, clicking the provided action does not dismiss the snackbar; instead, the snackbar remains visible until the end of its timeout.

Clicking the action should dismiss the snackbar immediately, as its purpose has been fulfilled: the user has read it and chosen to take the action. It should also remove the event handler, so that the action is not triggered twice.

**Comment by traviskaufman** [comment]
We should probably roll this into #28

**Comment by Garbee** [comment]
The reason I left it the way it is in my original implementation is simply because the spec never says what action should be done. So I assumed to let the timeout continue and disable further action presses (via disabled button attribute being added.)

While I agree it should close out when the action is pressed, that's something I'd double-check with the MD team on just to be certain. I'm not sure of any reason it shouldn't though.

**Comment by traviskaufman** [comment]
Spoke with design regarding this and indeed the default behavior is to dismiss when an action is taken. However, users should have the option for this not to be the case. For example for `Undo` it makes sense. For something like `Learn More`, maybe not so much. Closing and rolling into #28
