### ISSUE TITLE
text-field full-width place holder not working in V0.44.0

### ISSUE THREAD

**Issue by alexandrestein** [material-components/material-components-web#4366]
### What MDC Web Version are you using?

> 0.44.0

### What browser(s) is this bug affecting?

> Firefox and Chromium on Linux but I guess it the same for all browsers

### What OS are you using?

> Linux Arch (up to date)

### What are the steps to reproduce the bug?

> Simply us full-width text-field with placeholder 

### What is the expected behavior?

> To see the placeholder as it was in 0.43.1

### What is the actual behavior?

> The all field is blank 

### Any other information you believe would be useful?

Codepen with version 0.43.1: https://codepen.io/anon/pen/KJyYqJ
Codepen with version 0.44.0: https://codepen.io/anon/pen/mvqgqq

**Comment by abhiomkar** [comment]
Thanks for reporting this bug!

We changed the styles related to placeholder so that it is shown only when there is no label (`.mdc-text-field--no-label`) or when the label is floating. Full width variant is a special case where we don't use a label. So the styles for placeholder needs to be updated for full width variant too.

Temporary solution is to append `.mdc-text-field--no-label` class name to make the placeholder appear. Here is the updated [codepen](https://codepen.io/abhiomkar/pen/OdQRNm).
