### ISSUE TITLE
Intended Use for notifyChange() Method of Select Adapter

### ISSUE THREAD

**Issue by marceux** [material-components/material-components-web#437]
I'm attempting to create a React implementation of the Select component, and I had trouble wrapping my head around the intended use of `notifyChange()` and `setSelectedTextContent()` in response to selection events.

I think it's intuitive to call React's `this.setState()` within `setSelectedTextContent()` because it makes sense to trigger a re-render, and fill in a `<div>{this.state.selectedText}</div>` with the updated text.

But defining appropriate behavior for `notifyChange()` is not as intuitive.

In your component code, you emit a `MDCSelect:change` custom event, and that makes sense, because it looks like with the component you directly modify the DOM. But with the React component lifecycle, I want to minimize re-renders and I would rather set a new state with the updated value (if there is a value change), selected text, and anything else within one call.

My [current implementation](https://github.com/marceux/mdc-select-react/blob/master/src/adapters/selectAdapter.js#L105-L125) does something similar within `setSelectedTextContent()`: 

- It checks if the optionText is actual text. If it's not, it sets that value of the component to undefined, sets the selectedText (which is rendered directly in the DOM) to a default or placeholder.
- If the optionText is actual text, then it finds the values within an options array, and updates the state with the value and the new selectedText.

This minimizes re-renders, but now I'm left with an unused `notifyChange()`. It does not pass any data on determining what the selected value/element is, and it doesn't fit my needs.

Was this intended solely for DOM notifications or event handlers? Is **NOT** using an adapter method okay? Any help is appreciated, thanks.

**Comment by amsheehan** [comment]
@traviskaufman could you weigh in on this? It looks like you added that method a few months ago.

**Comment by traviskaufman** [comment]
@marceux Great question. I'd suggest using [stackoverflow](http://stackoverflow.com/questions/tagged/material-components+web) to ask questions like these in the future.

**The intended use of `notifyChange` is to allow clients to be made aware of when a select element's selected value changes as a result of user interaction.**

The way I might model it is to have an `onChange` prop, e.g.

```jsx
<MDCSelect onChange={(data) => this.handleOptionChanged(data)} ...>
```

In order to implement this, you could have `notifyChange` proxy to that prop, and use the foundation's `getSelectedIndex()` and `getValue()` methods to return data to it.

```js
// in an adapter definition...
notifyChange: () => this.props.onChange({
  selectedIndex: this.mdcSelectFoundation.getSelectedIndex(),
  value: this.mdcSelectFoundation.getValue(),
}),
// ...
```

The reason why we don't pass these values ourselves is because we modeled this method after the `change` event emitted by an `HTMLSelectElement`. However, your implementation should feel free to do so. 

Let me know if that answers your question and I'll close this issue. I'm also going to submit a PR adding this documentation to our README, where I realized we were missing docs on the `notifyChange` adapter method (sorry about that!)

**Comment by marceux** [comment]
I appreciate the answer. It's super thorough. Thank you! It didn't quite click in my head to use `Foundation` in that way.

Though I wonder: would it be okay to not use `notifyChange()` at all?

For my React implementation, I feel like it may be too much to update the DOM with `setSelectedIndex()`, which eventually calls the adapter's `setSelectedTextContent()` method, **AND THEN** call a callback in the adapter's `notifyChange()`.

Assuming we have a `onChange` prop that we want to call whenever the component changes, here are two examples:

```javascript
// example one

// in an adapter definition...
setSelectedTextContent: (selectedTextContent) => {
    this.setState({ selectedTextContent }, this.props.onChange);
},
// ...

// example two

// in an adapter definition...
setSelectedTextContent: (selectedTextContent) => this.setState({ selectedTextContent }),
// ...

// in a React component class
componentDidUpdate(prevProps, prevState) {
    if (this.state.selectedTextContent !== prevState.selectedTextContent) {
        this.props.onChange();
    }
}
```

Are there other use cases that I'm not seeing? If I come off as thick-headed, I apologize. You guys are doing great work, and I don't want to miss out on utilizing a tool properly if I can.

I'll use StackOverflow in the future for implementation questions (thanks for the link).

**Comment by moog16** [comment]
Closing this as issue has gone stale
