### ISSUE TITLE
Drawer type secondary classes

### ISSUE THREAD

**Issue by prateekbh** [material-components/material-components-web#441]
### What MDC-Web Version are you using?

0.7.0

### What browser(s) is this bug affecting?

All

### What OS are you using?

Mac OS

### Information
Just a question , not really a bug. High risk of sounding super dumb here.

The drawer component is separated as mdc-permanent-drawer and mdc-temporary-drawer.
What stapped us from having mdc-drawer and then attach mdc-drawer__temporary/permanent here.

**Comment by amsheehan** [comment]
I was not around when this was implemented, but I believe the reason is that temporary drawers require JavaScript while permanent drawers are simple CSS only components and do not. While both flavors of drawer are subsets (stylistically) of drawer, it makes sense to only require that temporary drawers include the extra JS overhead. @traviskaufman is this accurate?

**Comment by prateekbh** [comment]
Unless there is major difference in the markup itself of the two, cant we just gracefully degrade it to css only behavior?

**Comment by amsheehan** [comment]
I now have a bit more context on this issue.

The reason for splitting out the different flavors of drawer is not necessarily because of the extra JS, but the DOM structure. Specifically, temporary drawers must sit directly under `<body>` to achieve a backdrop and correct `z-index` relative to the rest of the page's content. Also, Permanent drawers can sit under headers, and toolbar spacers, while temporary drawers must enclose headers and toolbar spacers.

cc: @sgomes correct me if I'm way off base 👍

**Comment by sgomes** [comment]
@amsheehan Nope, sounds about right!
