### ISSUE TITLE
mdc-theme CSS variable customization for calculated colors

### ISSUE THREAD

**Issue by monstasat** [material-components/material-components-web#4431]
Hi!
I am trying to implement switching between light and dark themes in my app.
As far as I understand, to switch between two themes at runtime, without sass recompilation, I should override some css variables. I've declared a CSS class applied to the `:root` element where the variables like `--mdc-theme-primary`, `--mdc-theme-background` and others are redefined.
Despite the seeming simplicity of the described approach, I am facing some issues. Here is a couple of them:
#### 1. MDCDrawer SASS mixins for styling inner lists are defined [in the following manner](https://github.com/material-components/material-components-web/blob/7ed6123a959b48e2b3062d557b35633922bad87d/packages/mdc-drawer/_mixins.scss#L113):
```
@mixin mdc-drawer-item-text-ink-color($color) {
  $value: rgba(mdc-theme-prop-value($color), $mdc-drawer-item-inactive-text-ink-opacity);

  .mdc-list-item {
    @include mdc-list-item-primary-text-ink-color($value);
  }
}
```
Inside this mixin, another MDCTheme mixin, `mdc-theme-prop-value`, is used. It means that the color of list item text is not controlled by CSS variables, hence not customizable.

#### 2. MDCTopAppBar SASS mixins for customizing fill color are defined [as follows](https://github.com/material-components/material-components-web/blob/7ed6123a959b48e2b3062d557b35633922bad87d/packages/mdc-top-app-bar/_mixins.scss#L43):
```
@mixin mdc-top-app-bar-fill-color-accessible($color) {
  @include mdc-top-app-bar-fill-color($color);
  @include mdc-top-app-bar-ink-color(mdc-theme-accessible-ink-color($color));
}
```
Inside this mixin, another MDCTheme mixin, `mdc-theme-accessible-ink-color`, is used.
It is defined as follows:
```
@function mdc-theme-accessible-ink-color($fill-color, $text-style: primary) {
  $fill-color-value: mdc-theme-prop-value($fill-color);
  $color-map-for-tone: map-get($mdc-theme-text-colors, mdc-theme-contrast-tone($fill-color-value));

  @if not map-has-key($color-map-for-tone, $text-style) {
    @error "Invalid $text-style: '#{$text-style}'. Choose one of: #{map-keys($color-map-for-tone)}";
  }

  @return map-get($color-map-for-tone, $text-style);
}
```
Once again, the `mdc-them-prop-value` mixin is used inside, and this breaks ink color customization by CSS variables.

How can I fix the mentioned issues? Maybe my approach for theme switching is wrong?
Or the color system of material components web is not yet finished/debugged?

**Comment by monstasat** [comment]
I've already partly referenced this issue in #4256, but when I've tried to change theme colors globally via css vars, it seems that the problem affects many components.
In fact, the question comes down to the following: do you consider to make it possible in the future to change color theme via css variables redefinition? If not, what other approach should be used?

**Comment by acdvorak** [comment]
Thanks for filing this issue! 😀 

In order to meet accessibility requirements for contrast ratios, we frequently need to calculate the lightness/darkness level of a color. It's not possible to do this in pure CSS, so we do it in Sass mixins and functions instead.

The `mdc-theme-prop()` mixin automatically emits an alternate CSS variable declaration for theme color values:

https://github.com/material-components/material-components-web/blob/70672f12ff19591c53fef6876c059c854f9cb816/packages/mdc-theme/_mixins.scss#L104-L113

Unfortunately, we don't do the same thing for calculated colors, which leaves CSS-only users hanging.

If you're looking for runtime theme customization, your best option is to compile two separate stylesheets with Sass, and switch between them. Our old Demo pages do this (clone the repo and run `npm i && npm run dev` to try it out):

https://github.com/material-components/material-components-web/blob/70672f12ff19591c53fef6876c059c854f9cb816/demos/theme/index.js#L180-L185

https://github.com/material-components/material-components-web/blob/70672f12ff19591c53fef6876c059c854f9cb816/demos/interactivity.js#L192-L216

We'd love to fix this at some point, but it's unlikely we'll have the resources to address it in the foreseeable future 😢

**Comment by kfranqueiro** [comment]
Notable suggestions for solving this:

https://github.com/material-components/material-components-web/issues/3066#issuecomment-404826683

https://github.com/material-components/material-components-web/pull/3145

There is also likely to be more work on the color system this year which may also impact this in some way.

**Comment by abhiomkar** [comment]
Closing this as dup of #4709
