### ISSUE TITLE
Naming of mdc-drawer is arbitrary and inconsistent

### ISSUE THREAD

**Issue by marvingreenberg** [material-components/material-components-web#4444]
Making a change to the name of components that are widely used elsewhere only adds cognitive friction.  Why is the material design Navigation drawer called mdc-drawer but material design Bottom navigation is called mdc-bottom-navigation (not mdc-bottom).

From the architecture document 

> MDC Web follows naming and documentation best practices to keep our code consistent, and our APIs user-friendly."

This should at least be justified as a decision.

**Comment by acdvorak** [comment]
Thanks for filing this issue!

Unfortunately, the `mdc-drawer` package was named that way a few years ago, and we generally try to avoid renaming packages because it ends up causing even more problems.

For example, `@material/textfield` should really be `@material/text-field`, but then we'd have _two_ identical-sounding packages in npm: `textfield` and `text-field`.

As a new user, how do you know which one is correct? Deprecation notices help, but many people won't see them; they'll install the old package by mistake and get super confused when things don't work as expected. Or they'll wonder why `textfield` is the only package that didn't get upgraded by [Greenkeeper](https://greenkeeper.io/).

What's more, renaming a package is yet another breaking change our clients have to deal with.

Consistency is great—_I'm all for it!_—but in this case it's not worth the tradeoff.

Thanks again for the feedback! 😀

**Comment by marvingreenberg** [comment]
I get all that.  And the nature of angular and web development in general is that the name leaks all over the place, so you can't easily just make an alias or extend a class for backwards compatibility.  But you can maybe put a note or two somewhere, maybe https://material-components.github.io/material-components-web-catalog/#/ to figure a way to show that the "drawer" is a shortened version of "navigation-drawer".  I'm brand new to this package and spent a while looking for the navigation drawer.   Since I didn't know if all the material design components were implemented.  Now I know, not a big deal.
