### ISSUE TITLE
Broken compatibility with Google Closure Compiler

### ISSUE THREAD

**Issue by rarous** [material-components/material-components-web#4492]
1.0.0 breaks compatibility with Google Closure Compiler. I think this is unfortunate to break not only GCC users but whole ClojureScript community as well. It is failing on `export * from ...` syntax in `index.js` files, because it's not supported in GCC. Is it possible to not use imports from `/index` modules and instead to be explicit what concrete module (eg. `/component`) is actually imported? I tested it by hand editing package files and it works again. I hope this will also help with tree-shaking for other consumers of this amazing library.

**Comment by kfranqueiro** [comment]
Thanks for the report, and sorry for the issue! I have a few ideas/questions in terms of resolving this:

Firstly (and in the interim, presuming we ultimately solve it), is it possible for you to avoid these errors if you avoid referencing the `index.js` files, and instead reference specific modules directly? All that our `index.js` files do is forward exports from other modules.

In terms of resolving this, I think there's two ways we could go:

* Include our `*.ts` files in the packages, so that people are free to do what they want if they have a use case not supported by our current distributed formats (e.g. running [tsickle](https://github.com/angular/tsickle) to produce closure-friendly JS)
* Use [tsickle](https://github.com/angular/tsickle) on our end to produce closure-friendly JS, either in-place if it doesn't seem to cause considerable increase to minified files in other common build toolchains, or possibly in a dedicated folder otherwise (I believe Angular does something like this)

Can you let us know which of these options seems most likely to work from your perspective (and whether avoiding importing index.js also works)?

**Comment by rarous** [comment]
I'm not referencing `/index` but only `/component`s. In your code, some components are referencing `/index` of other components they are composited of. IMO the problem is in convention how you reference modules internally. You don't need any heavy machinery of another transpilers. Most of the files are GCC consumable as they are.

**Comment by kfranqueiro** [comment]
That's a good point. We purposely avoid referencing index from foundations/adapters for the sake of wrapper libraries which shouldn't need index or the component, but we allowed referencing index from components under the assumption that if you're using it in the context of vanilla MDC Web, there shouldn't be an issue.

So I guess avoiding referencing index from component files is a third option.

**Comment by abhiomkar** [comment]
As per my knowledge, PR #4594 by @moog16 fixes this issue.

**Comment by rarous** [comment]
Hi @kfranqueiro, today I tried to update to v2.2.0. I can confirm the `export * ...` issue is fixed. But there is still one breaking change that prevents GCC to directly consume this package. Pre v1.0 packages were in ES6 that GCC understands without extra js-doc or externs, but current output is ES5 target with ES6 modules. Is there any reason to emit this combination? It would help to have proper ES6 modules with classes. There is already `/dist` with ES5 code. I don't see any reason to emit ES5/ES6 hybrid in modules output.

**Comment by moog16** [comment]
@rarous we are tracking this new issue in https://github.com/material-components/material-components-web/issues/4722. Thanks for bringing that to our attention.
