### ISSUE TITLE
Select dropdown arrow not hidden in Google Chrome

### ISSUE THREAD

**Issue by dawsonc623** [material-components/material-components-web#4494]
### What MDC Web Version are you using?

`@material/select: 0.40.1` via `@material/react-select: 0.8.0`

### What browser(s) is this bug affecting?

Google Chrome 72.0.3626.121

### What OS are you using?

Windows 10 1803 Build 17134.590

### What are the steps to reproduce the bug?

Using the following HTML (produced by the `Select` React component noted above) with the mentioned versions of the components shows the issue:

```HTML
<div class="mdc-select">
  <select class="mdc-select__native-control" label="Number" options="">
    <option disabled="" value=""></option>
    <option value="1">One</option>
    <option value="2">Two</option>
  </select>
  <label class="mdc-floating-label">Number</label>
  <div class="mdc-line-ripple" style="transform-origin: 108px center;"></div>
</div>
```

### What is the expected behavior?

The built-in select arrow should not be rendered.

### What is the actual behavior?

The built-in select arrow is shown on top of the one provided by the component.

### Any other information you believe would be useful?

The issue is that https://github.com/material-components/material-components-web/pull/3949 introduced a number of things including the `appearance: none;` style [here](https://github.com/material-components/material-components-web/pull/3949/files#diff-b1d2c84cc87fdf64df95f4ae8532048aR292). Google Chrome needs that to be prefixed still, but the CSS ultimately sent to the browser does not contain a prefixed version of it (for any browser). The degradation of this feature in lacking browsers is not elegant.

As an aside: that PR mentions the arrow should be rotating, but that does not seem to be working, either. That might be unrelated, though.

**Comment by kfranqueiro** [comment]
#3949 is unrelated to your issue if you're using MDC Select 0.40.1, since 0.41.0 was the first version that #3949 is present in. That's also why you're not seeing the rotating arrow. Our team is still in the process of updating MDC React against the latest MDC Web release.

Regarding the absence of `-webkit-appearance: none`, this is generated by the `autoprefixer` package in MDC Web's builds (e.g. you can see it if you search for `appearance:` in https://unpkg.com/@material/select@0.40.1/dist/mdc.select.css). If you're relying on MDC Web's SCSS directly, you should incorporate `autoprefixer` into your build pipeline (we specify it as a plugin to postcss-loader).

**Comment by dawsonc623** [comment]
Ah, my eyes deceived me! I misread the version from the PR.

Anyway, I did not know prefixes were added automatically in the build step rather than in the SASS itself. I added `postcss-loader` and `autoprefixer` to my Webpack build and all is well 👍 

On the MDC React front: are you looking for community help on that project? My workplace is pushing for Material Design as a standard across all projects, so I will be using MDC React quite heavily and am willing to help improve it as I find things.

**Comment by kfranqueiro** [comment]
Contributions are definitely welcome, and there are especially a few active folks pitching in on MDC React. We also have a #react channel in our [discord server](https://discord.gg/material-components) if you want to coordinate.

I'll go ahead and close this since it sounds like the issue itself has been resolved. Thanks!
