### ISSUE TITLE
Auto-init: Enable it to run twice and track what has been initialized

### ISSUE THREAD

**Issue by williamernest** [material-components/material-components-web#4495]
If the user updates the DOM and adds more components, the auto-init function should be able to be run again only initializing the components that were added.

**Comment by abhiomkar** [comment]
This might be resolved by setting `data-` attribute (Eg, data-mdc-auto-init-state="registered") to DOM elements after a component is initialized. So that, next time when we run `.mdcAutoInit()` it'll only process DOM elements that do not have this `data-` attribute.

On related note, MDC also needs to be able to provide a way to retrieve component instance via DOM element. But we can track it as separate issue.
