### ISSUE TITLE
MDCDialog: focus-trap@^4.0.2?module does not provide an export named 'default'

### ISSUE THREAD

**Issue by gertcuykens** [material-components/material-components-web#4507]
`import {MDCDialog} from 'https://unpkg.com/@material/dialog?module'`

results in

Uncaught SyntaxError: The requested module 'https://unpkg.com/focus-trap@^4.0.2?module' does not provide an export named 'default'

https://jsbin.com/saqoyinufi/edit?html,console,output

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. I wasn't aware this was a thing on unpkg; I'll have to test with it and see if there's anything even beyond #4485 that we can/should do.

**Comment by kfranqueiro** [comment]
I investigated this, and it is due to the fact that the `focus-trap` package does not export an ES module. It's possible to make focus-trap interoperate with ES modules when working in conjunction with TypeScript or a bundler such as webpack, but when using `script type="module"` with unpkg, no transformations are applied to the modules in question, so the process simply breaks down when a non-ES module is encountered.

Out of curiosity I also tried with MDC Web 1.0.0 specifically (prior to #4485), and it also fails, with a different error, because `script type="module"` doesn't expect to encounter CommonJS `require`.

This is not something we can resolve within the scope of MDC Web. If you're heavily invested in this use case, I would suggest opening an issue on the focus-trap and tabbable package repositories to request ESM support.

For what it's worth, `script type="module"` should be either limited strictly to prototyping cases only, or used in some sort of build toolchain which optimizes modules together, since otherwise it requires individually downloading every module in the dependency graph.

**Comment by gertcuykens** [comment]
But modules improve the developer experience by a lot if we can just do this without any build process required example https://jsbin.com/fotedog/edit?html,output

Also I am pretty sure the focus-trap and tabbable can't switch to modules because then if breaks everything else that uses it. So we are in a one way street where two opposite cars are stuck and neither can move. Can't we not seperate does dependencies? So at least we have a option to replace does dependencies with our own? Something like you did with Ripple.

**Comment by kfranqueiro** [comment]
I believe it should be feasible for focus-trap and tabbable to continue to ship the existing CommonJS module while also shipping ES5 wrapped in an ES module under a different file path, then point to the new file via the `module` property in `package.json` (`?module` on unpkg seems to correctly follow this).

Again, modules improve the developer experience _for prototyping_. You probably don't want your users to incur all of these network requests...

![image](https://user-images.githubusercontent.com/398379/54708676-4b88cc00-4b1a-11e9-9651-1164080618b3.png)

**Comment by gertcuykens** [comment]
When using http2 the number of request don't matter. In http1 on the other hand yes definitely don't want this. Actually if am not mistaken separate requests will be even faster because it will be done in parallel when using http2 if am not mistaken.

**Comment by gertcuykens** [comment]
Just want to add this as reference, apperenatly simular module request was already asked in march 2017 https://github.com/davidtheclark/focus-trap/issues/30

**Comment by gertcuykens** [comment]
trying to fix this but I am stuck at tsconfig https://stackoverflow.com/questions/55517669/material-components-web-es6-modules

**Comment by dy** [comment]
Workable solution - using pika CDN instead of unpkg: https://www.pika.dev/npm/material-components-web

**Comment by stefcameron** [comment]
FYI, this is fixed in `focus-trap@6.0.0` which now provides an ESM build! 🎉
