### ISSUE TITLE
material-components-package README  incorrect import

### ISSUE THREAD

**Issue by ALMaclaine** [material-components/material-components-web#4509]
The material-components-package README has not been updated to reflect the UMD bundle change.

https://github.com/material-components/material-components-web/tree/master/packages/material-components-web

**Comment by moog16** [comment]
@ALMaclaine I'm not sure what you mean,

```
import * as mdc from 'material-components-web';
// AND
import { checkbox } from 'material-components-web';
```

are both supported by UMD and ESM. Is there another import/export format that you'd like to see? We cover this in [importing-js](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md).

**Comment by ALMaclaine** [comment]
From importing-js:
![Screen Shot 2019-03-21 at 10 33 06 AM](https://user-images.githubusercontent.com/16461670/54772726-39b03300-4bc5-11e9-9fb9-64fd2e127046.png)

My understanding is after the UMD update you need to specifically references the index file as referenced from the importing-js file. I see the message about the module property, but it specifically states to use reference the index file and much of the code base.

Also in the changelog [Changelog](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#breaking-changes-4)

So I was attempting to update the READMe to reflect these suggestions am I misunderstanding?

**Comment by moog16** [comment]
If you directly reference the `index` file that will actually target ESM. The UMD files are located within the `/dist` directory. I also saw your PR, and was thinking it is actually easier to reference the `importing-js` document below the JS so that the documentation remains in one place. Do you mind updating your PR? Otherwise we can close yours and we can open a new one. 

For reference see the https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox#javascript-instantiation. You can just copy the line that states `See Importing the JS component for more information on how to import JavaScript.`.

**Comment by ALMaclaine** [comment]
I updated the PR based on what I understood you to mean.

I still feel somewhat confused, is referencing the index not correct? I thought that's what was supposed to be done after the UMD update. I think maybe my wording wasn't clear? What I was attempting to say is that imports have not been updated to import the ESM module and are referencing the UMD because it had not been updated SINCE the UMD update.

**Comment by moog16** [comment]
We're glad you brought this up, as we totally missed this Readme during the TypeScript conversion. To answer your question, it all depends on your build setup. If you're using Webpack or Rollup, then you shouldn't need to reference `/index`, since the module resolver will look at the `package.json` and use either `main` or `module`. If you're not using Webpack/Rollup/Some other Module Resolver, you should specify either UMD or ESM. 

In most cases you shouldn't need to reference `/index` since the resolver will usually look there by default.

**Comment by ALMaclaine** [comment]
I do understand that from reading the js-importing. My question is more directed specifically to the MCW project. I've read through a lot of the docs and it sounds like the is one soft goal of the project is to have a consistent code base throughout. 

What is the MCW specified way of importing packages? Is it what I've done? Should it be reflected throughout all the code and docs? Why do the ts files import index if it's no big deal? I'm trying to figure out the correct way and am attempting to update anyplace it isn't consistent.

**Comment by moog16** [comment]
That's a good point. We shouldn't need to have `/index` there, and should remove that for consistency.

**Comment by ALMaclaine** [comment]
Okay I updated the docs per your change requests.

So final answer is no index after testing phase is over? Any idea when that is?

Thanks

**Comment by moog16** [comment]
Sorry if that was unclear. What I'm trying to say is that when we are bug fixing/developing a new feature on a component, if we don't point directly at `/index` our webpack.config points to the `/dist/index`, which is compiled. So if we make a code change and try to rerun the unit/screenshot tests, the code change isn't reflected. This is because everything under `/dist` must be recompiled.

Does that make sense?

**Comment by kfranqueiro** [comment]
That was definitely true prior to us including `module`. I wonder if it's still true with `module`?

**Comment by moog16** [comment]
True, that might not be the case anymore. However @ALMaclaine mentioned that he was looking at our packages to determine what was the correct way to import them in his own project. So I can see how this can be confusing for people that are going through the same process as @ALMaclaine.

**Comment by ALMaclaine** [comment]
@moog16 it is a concern of mine for my projects but I'm also trying to contribute back where I can so I would like to understand it from both perspectives. I was attempting to update the docs to what I understood to be the correct importing method. I had another PR prior to the ts update where I had added /index to a number of spots in the docs and js files but I canceled it to assess what might have changed after the update.

**Comment by moog16** [comment]
@ALMaclaine we appreciate your contributions! It helps fill in our gaps and mistakes. I will take a look at your PR.

**Comment by ALMaclaine** [comment]
Of course, happy to help. I updated the PR again.

Can one of you let me know what the final word on /index is when you've worked it out? The PR will probably close this issue but I'm in the discord.

Thanks

**Comment by moog16** [comment]
Yes the final word is that the `/index` shouldn't be necessary. Your build tool or the npm module resolver should default to the correct file given that we have the package.json setup.
