### ISSUE TITLE
MDC Ripple before/after background color should be set to currentColor

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4571]
Ripple's before/after background color is set via `mdc-states-interactions_` sass mixin. This is used 3 times in the baseline, activated, and selected mixins. This has reportedly has caused incorrect ripple colors when theming. 

The proposed solution is to replace `@include mdc-theme-prop(background-color, $color, $edgeOptOut: true);` found in the `mdc-states-base-color` mixin with `background-color: currentColor`. 

An extra win for us is that it will decrease the bundled css size of ripple, and therefore decreasing the css of all components using ripple.

**Comment by jamesmfriedman** [comment]
Thanks for recording this Matt. I can verify that the `currentColor` method works in every situation I've come across. In my own downstream apps, I now just have it set as a global override with `!important`.

**Comment by abhiomkar** [comment]
I just realized that not all block elements have `color` CSS property to inherit to ripple `background-color`. 

Block elements that don't have text or font icons not necessarily has `color` CSS property, for example the thumb overlay in switch component.

Current implementation:

![image](https://user-images.githubusercontent.com/47312/55997629-2a367e00-5c89-11e9-8baa-78ce50414c2d.png)

with `currentColor`:

![image](https://user-images.githubusercontent.com/47312/55997599-19860800-5c89-11e9-906e-072f0b815655.png)

The ripple color is grey instead of primary color because the currentColor is inherited from its parent.

**Comment by jamesmfriedman** [comment]
That seems trivially easy to fix by just applying color in css to these elements.

**Comment by moog16** [comment]
Yes, but ripple won't just "work out of the box" then. Although you can consider the unbounded ripple on another surface element (ie radio, checkbox) advanced usage. If we go this route, we would require the users with ripple on another surface to use another mixin.

**Comment by jamesmfriedman** [comment]
Maybe I’m missing something, but why don’t you just specify the color property on the radio, checkbox, and switch? Then you don’t need any special behavior. 

Or, make the mixin where it defaults to currentColor but accepts an override for situations like this (I know there are default argument values on SASS). 

I don’t think the fact that they’re unbounded is what makes them special since icon buttons can have colored icons which the ripple should respond to.

**Comment by moog16** [comment]
Ya I'm sure there is a good way around that. I will figure something out :)

**Comment by bonniezhou** [comment]
Closing this, infeasible due to comments above.

**Comment by jamesmfriedman** [comment]
I would like to say that the original comment wasn’t understood. It’s not infeasible. It does in fact work in all cases I’ve tested. Right now the ripple doesn’t just work at of the box in all contexts... would be happy to provide a working test case and examples. 

Css doesn’t need to be semantically correct. You can absolutely set the color properly on the knob for the switch above to get the ripple to work correctly. Everything in Mat web is wrapped in mixins anyways so it would be transparent to the consumer.
