### ISSUE TITLE
mdc-menu 1.1.0 compiled files don't have the latest code.

### ISSUE THREAD

**Issue by luissardon** [material-components/material-components-web#4573]
None of the compiled js files under **node_modules/@material/menu** have the latest code from its respective source files even tho the package json points to 1.1.0 version.

**Comment by abhiomkar** [comment]
There are no new JS changes in [v1.1.0](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#110-2019-03-26) since `v1.0.0`. are there any specific changes that you're not finding in npm's version and [v1.1.0](https://github.com/material-components/material-components-web/tree/v1.1.0) tag?

**Comment by luissardon** [comment]
My bad, I wasn't looking at the v1.1.0 tag, I assumed that master was the latest release.
