### ISSUE TITLE
TextFields are horizontally aligned by default

### ISSUE THREAD

**Issue by ZeJ0hn** [material-components/material-components-web#4604]
Hello,

I use TextField to create a Form and compare to the default behavior of a form, the textfield are horizontally aligned.
This is because the `mdc-text-field` class has a `display: inline-flex` property.

So, why is it like this by default ? and why the display is not block or inline-block by default ?

Thank you

**Comment by abhiomkar** [comment]
TextField component is not opinionated about the context it is being used. We tried not to add any styles that impacts layout outside of component since it is too dependent with use case.

Native `input` element also has similar behaviour which defaults to `inline-block`:

![image](https://user-images.githubusercontent.com/47312/56366286-cb10c600-61c0-11e9-822c-efcbc536431d.png)

**Comment by ZeJ0hn** [comment]
Thank you for your answer.

My mistake :-)
