### ISSUE TITLE
Ripples incorrectly laid out for dialog buttons

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#464]
### What MDC-Web Version are you using?

0.8.0

### What browser(s) is this bug affecting?

Tested on Chrome Version 57.0.2987.133 (64-bit)

### What OS are you using?

macOS v10.12.3

### What are the steps to reproduce the bug?

1. Navigate to http://material-components-web.appspot.com/dialog.html
1. Click the "Show Dialog" button
1. Press and hold the spacebar key, observing the ripple on the accept button as you do so

### What is the expected behavior?

The ripple should cover the entirety of the button

### What is the actual behavior?

The ripple is sized incorrectly and placed incorrectly within the dialog.

### Any other information you believe would be useful?

If you open a dialog and then resize the screen, even a little bit, the ripple becomes positioned and sized correctly. This leads me to believe that _this is an issue with when the ripple is being laid out_. 

I think that a solution might be to call `layout()` on all of the ripple instances after the dialog opens. However, this presents an issue since the `layout()` method is not exposed at the `MDCRipple` component level. Perhaps this is something we should look into in order to accomplish this.

**Comment by strogonoff** [comment]
Same unexpected ripple behavior—more specifically, ripple being shifted to the left of actual click/tap point—can be observed on buttons outside of dialogs as well.

In my case this occurs when my CSS overrides the width of the button (whether by setting width or using absolute positioning). With button width exceeding certain threshold, ripple ignores click/tap coordinates and always behaves as if the click or tap occurred on the leftmost edge of the button. Haven’t looked deeper into what causes it to behave this way.

Similarly looking ripple mis-positioning also happens if button label text is cut off due to button’s containing element being too narrow.

**Comment by anton-kachurin** [comment]
Ran into it when implementing a button component whose caption is changing. The bug is related to changing the dimensions of the ripple's container. As @traviskaufman said, the solution might be to call `layout()` more often than just on initialization and resize. Regarding this, I'm asking for some clarification:
1. Why is it important to count the dimensions inside animation frame listener?

**Comment by traviskaufman** [comment]
> Why is it important to count the dimensions inside animation frame listener?

We do this so that we know the browser is ready to devote the rendering cycles necessary to perform the CPU-intensive tasks of layout computations. More on this at https://www.html5rocks.com/en/tutorials/speed/rendering/

**Comment by anton-kachurin** [comment]
I came across this bug when testing a button component whose width changes after ripple initialization.

In my case, the width changes because I change the caption text of the button, and I could call some method (e.g. `reset`) of the ripple component every time this happens. The dialog component could call this method when necessary too.

This puts a very serious constraint, though. Every single component which uses bounded ripples needs to be aware of it's own dimensions changes. These changes are trackable on per-component level, but not on the application level.

Imagine a page with a persistent drawer and some other component which takes 50% of the available width. This other component has a ripple. When the drawer opens, the available width shrinks, which means the `reset` needs to be called. What component would call it? Not ripple because there was no `resize` event, not drawer because it doesn't know about existence of other components, and not the other component because its state didn't change anyhow.

From this perspective, I find re-laying out the ripple before activation a better solution.

Am I missing anything?

**Comment by traviskaufman** [comment]
(see discussion on #588 )

**Comment by Alexey1** [comment]
It looks like ripples don't initialize properly when there is css scale transform which the dialog has by default. Ripples work correctly if they are initialized when the dialog does NOT have scale transform. 

Here are the workarounds for the users which are based on this observation. But each has its own limitations. They work in my local setup in v0.14.0 but online examples below are in v0.13.0 because unpkg CDN has v0.14.0 broken at this time. These workarounds are NOT guaranteed to work for future versions. Tested in Chrome and Firefox.

**Workaround 1**
The simplest one. Use it if you are fine to loose scale animation of the dialog during opening and closing time.
`.mdc-dialog__surface {
  transform: translateY(150px);
}`

**Workaround 2**
Scale animation is preserved. "cancel", "accept" buttons have correct ripples. But it applies only if the dialog will not have elements with ripples in its body or all ripples are initialized while the dialog is hidden and not opened yet and before a certain piece of code is invoked. This limitation is visible if you click "init ripple button", open the dialog, then the "ripple button" will have incorrect ripple.
https://jsfiddle.net/9w0d6c30/

**Workaround 3**
Scale animation is preserved. "cancel", "accept" buttons have correct ripples. This approach is less straightforward than the previous one but it allows to have correct ripples which are added in the dialog body at arbitrary times except during opening and closing animations. if you click "init ripple button", open the dialog, then the "ripple button" will have correct ripple.
https://jsfiddle.net/maqeavo3/

**Comment by kfranqueiro** [comment]
It sounds like when this was first entered, `layout` was not exposed on mdc-ripple at the component level, but that is no longer the case as of 0.15.0.  I'm going to PR a fix that uses it to re-layout ripples within the footer region, which the dialog component already stores references to.
