### ISSUE TITLE
sourcemap not load correctly when using as es module

### ISSUE THREAD

**Issue by XHMM** [material-components/material-components-web#4656]
When I use this library as node modules and with typescript, 
because `module` field in `package.json`, 
the entry file is now `index.js`  instead `dist/mdc.xx.js` as we known,
   
But I found  that `dist/mdc.xx.js.map` has `sourcesContent` field,  but such as `index.js.map`, `foundation.js.map` don't hava `sourcesContent` filed, so bundler(I am using parceljs) cannot search source content because either `sourcesContent` or source ts file exists, so I have to delete `module` field in `package.json` so bundler can load sourcemap from `dist/mdc.xx.js.map` which contains `sourcesContent`

so, is there a way to solve this ?

**Comment by moog16** [comment]
I don't have knowledge of parcelJS, however in unpkg and on npm we have the correct entries of foundation.ts, component.ts, etc. The map files are properly placed which allows us to work with webpack. Could you provide more information? Maybe an example project.

**Comment by XHMM** [comment]
@moog16 Thanks for reply, I created an [example repo](https://github.com/XHMM/issue-about-mdc-sourcemap-load) to re-produce what I said above, please try it and wish you can better what I said 😀

**Comment by moog16** [comment]
@XHMM I spent some time trying to figure out Parcel, but I can't spend too much diving in.  Based off of the provided screenshot, I think you need to configure ParcelJS to serve the other files from node_modules. It seems like it is copying the node_module files you require into a temporary directory from which the ParcelJS server serves files from.

Another possible next step (even though it isn't correct, but might push you in the right direction) is to `import '@material/dialog/component.js.map'`. This import line will not work, but you might gain some insight into what is missing. 

Closing this issue since its not MDC Web related, but is related to ParcelJS configuration.

<img width="236" alt="Screen Shot 2019-05-02 at 8 24 42 AM" src="https://user-images.githubusercontent.com/579873/57087150-4a6bc280-6cb4-11e9-885f-e6393265d65b.png">
