### ISSUE TITLE
[chipset/chip] Break MDCChipSet and MDCChip into separate packages

### ISSUE THREAD

**Issue by smoyer64** [material-components/material-components-web#4763]
## Feature Request
``MDChipSet`` and ``MDCChip`` are currently in the same package.  For consistency, it would be better if these two components were in separate packages.  Currently, ``MDCMenu`` and ``MDCMenuSurface`` are in separate packages as the former can be used without the latter.  Likewise, the ``tabs`` package was recently deprecated, splitting ``MDCTab``, ``MDCTabIndicator`` and ``MDCTabScroller`` into separate packages.

It's also notable that a single ``MDCChip`` functions well outside an ``MDCChipSet`` so long as it's properly attached to an element.  This is very analogous to using ``MDCMenu`` without an ``MDCMenuSurface``.

### Proposed solution
Deprecate the ``chips`` package and replace it with a ``chip`` and ``chipset`` package.

**Comment by moog16** [comment]
Thanks for opening the issue! We disagree with several points to back up our claim

- ideally tabs should be in one package. We find it more difficult to use/maintain being in separate packages. We don't see why you would use the indicator or scroller separately as individual packages.
- Menu & MenuSurface make sense as individual packages since Menu is a combination of menu surface and list. Menu Surface can be used individually since you can contain other elements within it.
- A chip should always be used within a chipset, even if its just a chipset of 1 chip. 
- We do not believe that you will gain anything from separating the chip and chipset package.

Please feel free to continue commenting here if you disagree :)

**Comment by smoyer64** [comment]
I guess I've the example of the tabs package being deprecated made me think that's the way you were moving with the components ... I'm a bit curious why you refactored the package that way if you find it less convenient to move.

I don't have any experience using the menu surface without a menu but I can tell you that a single MDCChip does in fact work perfectly fine without being encapsulated in an MDCChipSet.  If used in a chip-set you have to make sure that you don't instantiate the chip using ``attachTo`` but rather use the ``addChip`` method on the enclosing chip-set.  And if you want to use the chip without a chip-set, use its ``attachTo`` method.

Maybe I'm not experienced enough with the whole design aspect of using these components to understand why some make sense in the same package and some don't.  Anyway ... I'm not insulted that you closed this but I don't think I learned anything foundational either.  Thanks for taking the time to write up the rationale!

**Comment by moog16** [comment]
RE Tabs rewrite/deprecation: we rebuilt it with new theming capabilities in mind. You can see this in text field, select, and other components. There were also many bugs with the previous version which were fixed in the new version. The multiple packages was an oversight.

RE Chip/ChipSet: Yes we know it works on its own, however it was never design with that intent.

Last thoughts: We appreciate you opening the issue. Please do not be discouraged from opening more as experience has nothing to do with this project. The fact that you do not sit with us in our meetings means you (and everyone else) don't have a window into our thought/design-process or history. If you have a question, there are usually at least 5 - 10 others with the same question. In turn you help us understand our missing pieces and help others by asking questions on these public forums.

**Comment by smoyer64** [comment]
I certainly won't quit if you close issues ... and yes, it's sometimes hard to understand if you don't hear the team's conversation.  I was looking at the design guidelines for the chip and it doesn't talk about chipset at all ... but the examples all include the need for multiple chips so it makes sense to have a "manager" for the group.

Thanks for all the work you've put into this! ... I'm wrapping the components in Go and compiling and running in WASM and everything "just works"!
