### ISSUE TITLE
[Linear Progress] CSS-Animation still running/calculating even in "closed"-state. Unecessary high CPU/GPU load

### ISSUE THREAD

**Issue by thomasd** [material-components/material-components-web#4896]
## Bug report

When `close()` is called on the components foundation class the component gets the class `.mdc-linear-progress--closed` which results in `opacity: 0`. This does not stop the css animation, which leads to constant CPU/GPU load even when the component is not visible for the user.

### Actual behavior

Page is calculated and rerendered even when nothing is happening and progress-bar is not visible.

### Expected behavior

CPU/GPU load should drop to almost nothing, when nothing on the page is visibly changing.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  3.0.0
| Browser          | Firefox latest and Chrome latest
| Operating System | Windows 10

### Possible solution

Why is it set to `opacity: 0`? Is this necessary?
Replacing `opacity: 0` with `display: none` stops animation.
https://github.com/material-components/material-components-web/blob/3ee2675e4214d65f9072e4f14bf0413ce771be7d/packages/mdc-linear-progress/mdc-linear-progress.scss#L121-L123

**Comment by TroyTae** [comment]
I think there are two ways to solve this problem.
1. Give `display: none;` instead of `opacity: 0;`. (Your suggestion)
2. Add `animation: none;` (My suggestion)
Maybe your solution is more efficient.
But `--closed` is already `opacity: 0;` and that means linear-progress affect layout continuously.
So I told `2` idea, how about your thought?
