### ISSUE TITLE
TopAppBar short never reopens after initial scroll

### ISSUE THREAD

**Issue by jamesmfriedman** [material-components/material-components-web#4928]
### Steps to reproduce
1. Go to https://material.io/develop/web/components/top-app-bar/
2. Scroll down to the "short" variant of the top-app-bar
3. Scroll down, notice it shrinks
4. Scroll back to top, notice it does not restore to its original full size

### Expected behavior
The top-app-bar should restore to its original size for the short variant whenever the page is scrolled back to the top

Noticed this while upgrading RMWC to 3.0.0. I don't believe this was an issue with 2.0.0

**Comment by TroyTae** [comment]
@abhiomkar 
![Jul-29-2019 19-44-14](https://user-images.githubusercontent.com/20078201/62042632-81ad2980-b239-11e9-9e0d-d274a616b8bb.gif)
You mean this issue, right?
I try to find guideline for fixing this but I was confused more and more.
Because there is no guideline for Short TopAppBar.
(https://material.io/design/components/app-bars-top.html)
Is this a deprecated feature?

**Comment by jamesmfriedman** [comment]
Thanks for the gif. That is the one

**Comment by abhiomkar** [comment]
I'm able to repro this issue. This is not deprecated feature.

We added this to our backlog.

**Comment by jamesmfriedman** [comment]
You can reproduce right from your own docs, unless this was accidentally fixed in the latest release.
