### ISSUE TITLE
[Top App Bar]  width overflows

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web#4960]
## Question
mdc-top-app-bar width appears to extend beyond its container.
### Steps to reproduce
Go to [codepen](https://codepen.io/CNL/pen/YmxMKN)
_This is a fork from https://codepen.io/rustemgareev/pen/NXoqwR_
with _MMMM_ added.

### Actual behavior
_MMMM_ is barely visible. If _1234_ replaces _MMMM_, it will be completely invisible.

### Expected behavior
The width of mdc-top-app-bar is expected to be limited by its parent element.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| Firefox          | 60.3
| Linux |

**Comment by CyborgSemon** [comment]
I don't believe this is a bug as the `MMMM` is inside a material icons class. In this case you should have put a material icons icon. (For example, `person` [see CodePen](https://codepen.io/anon/pen/voWGoP))

If you wanted text there, then you should use a span and remove all the button classes. (For example, [see other CodePen](https://codepen.io/anon/pen/PMONMY))

The text inside a material icon purposefully looks weird because the only element that is supposed to be in the element is the material icon itself.

**Comment by masaoliou** [comment]
@CyborgSemon Thanks you for your enlightenment.
