### ISSUE TITLE
[mdc-drawer] Color Theme Propagation Missing in Active Icon / Text

### ISSUE THREAD

**Issue by una** [material-components/material-components-web#5068]
### Steps to reproduce
1. Go to any drawer component
2. Update CSS Custom Property `mdc-theme-primary` to any color value
3. See error

### Actual behavior

Icon and text in active selection are not getting the correct values

### Expected behavior

The icon and text should also take the primary color value

### Screenshots

<img width="1114" alt="Screen Shot 2019-09-11 at 10 37 08 AM" src="https://user-images.githubusercontent.com/1693164/64707182-a7586000-d480-11e9-8000-d4cea7162f94.png">

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  latest
| Browser          |  Chrome 76
| Operating System | MacOS Mojave

### Possible solution
Missing passing the theme value in i.e. `...ink-color(primary, $query)`

**Comment by allan-chen** [comment]
The drawer component currently offers very limited support for CSS custom properties such as `--mdc-theme-primary`. In order to apply correct opacity values (i.e. for text color), it is required at SASS compile time to extract the literal color values from theme variables and apply alpha transformations, which means modifications to theme variables through custom properties post SASS compilation cannot be incorporated into such elements. We recommend adjusting the theme properties directly through SASS variables instead.
