### ISSUE TITLE
Some cool changes

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#507]
Hey,
I made some cool changes to material-components-web that you could implement in the real project... You can check my work at https://github.com/Touficbatache/mdc-web-custom if you like and I made a README.md for you to understand how it works. A live version is available [here.](https://touficbatache.github.io/mdc-web-custom/)
Thank you for checking my work.

**Comment by YUzhva** [comment]
[Somebody, please, get this man a gun...](http://coub.com/view/sd015)

**Comment by traviskaufman** [comment]
I've deleted the prior comment on this thread, because it was inappropriate. Also, I'd like to remind everyone that we have a [Code of Conduct](https://github.com/material-components/material-components/blob/develop/CONDUCT.md) that we expect our community to adhere to.

@Touficbatache 

Thanks for clueing us in to your work. From the Readme and your demos, it looks like these are some additions to toolbar for Phonegap. We have a [component request policy](https://github.com/material-components/material-components/blob/develop/COMPONENTS_REQUEST_POLICY.md) around introducing new components or UX changes/additions to existing components. However, because this is specific for PhoneGap, we probably wouldn't have it as part of our core codebase.

That being said, we very much encourage "3rd party" mdc-web components; e.g. components that extend / wrap our core components in a certain way for certain use cases. I'd encourage you to take a look at our [authoring components guide]() for information on how to architect your components in an MDC-Web style, and [reach out to us on discord](https://discord.gg/pRKaJB9) if you'd like to chat with us more about leveraging our library for your use case. Thanks!

**Comment by Touficbatache** [comment]
Oh okay! But have you checked the align-icons? It automatically aligns icons correctly on the toolbar.
