### ISSUE TITLE
MDC Select with lit elements 

### ISSUE THREAD

**Issue by keinagae** [material-components/material-components-web#5162]

**Comment by abhiomkar** [comment]
We're in the process of implementing this in Lit Element. Please follow this bug to track in web-components repository: https://github.com/material-components/material-components-web-components/issues/315

**Comment by YodaNinja** [comment]
Yes, the enhanced mdc-select's mdc-menu-surface gets "hoisted" to the body element.
I did the following to make it work (although I wrapped the mdc elements using Angular Elements web component).

There's a comment in the mdc-menu-surface code saying: 
`/*Removes the menu-surface from its current location and appends it to the
   * body to overcome any overflow:hidden issues.*/`

Though, since we are wrapping in shadow dom, the shadow dom should isolate any such issues.
So we need to "unhoist" the mdc-menu-surface, and undo what the mdc-menu-surface was trying to fix by throwing it up to the body, so the menu can be visible again.

Simply appending the element to another in the wrapping component's shadow dom wasn't enough.
The mdc-menu does additional an `adjustPositionForHoistedElement_()` call which `/*Calculates the offsets for positioning the menu-surface when the menu-surface has been hoisted to the body.*/`
This can offset the menu far away from the mdc-select; specifiically if you have a side menu and top application header bar.

There's some angular stuff here, so replace as needed with lit-html equivalent loop (https://lit-html.polymer-project.org/guide/template-reference#loops-with-arraymap), etc...
In my environment, we use a combination of lit-html/lit-element/angular-elements for writing web components.  :)

Add an mdc-menu-surface--anchor just before the mdc-select in your web component wrapper for mdc-select:

`<div #mdcMenuAnchor class="mdc-menu-surface--anchor"></div>
<div class="mdc-select demo-width-class" #mdcSelect>
	<input type="hidden" name="enhanced-select">
	<i class="mdc-select__dropdown-icon"></i>
	<div class="mdc-select__selected-text"></div>
		<div class="mdc-select__menu mdc-menu mdc-menu-surface demo-width-class" #mdcMenu #mdcMenuSurface>
			<ul class="mdc-list" #mdcList role="menu">
				<li #itemList *ngFor="let item of items; let i = index;" [class]="getItemClass(i)" [attr.data-value]="getItemValuePath(i)" [attr.role]="getItemRole(i)">{{getItemLabelPath(i)}}</li>
			</ul>
		</div>
	<span class="mdc-floating-label mdc-floating-label--float-above" #mdcFloatingLabel>{{label}}</span>
	<div class="mdc-line-ripple"></div>
</div>
`
Then do the following to "unhoist" the mdc-menu back from the document body and into the wrapping web component's shadow dom to the mdc-menu-surface--anchor point:

`    this.menuAnchor.nativeElement.appendChild(this.menu.nativeElement);
    this.mdcMenu = (<any>this.mdcSelect).menu_;  //yes, this is sneaky, but there's no exposed getMenu() method.... :(
    this.mdcMenu.setIsHoisted(false); 
`

I hope this helps someone else while waiting for the mwc-select implementation to be finished.

**Comment by shirleyhsliu81** [comment]
> <div #mdcMenuAnchor class="mdc-menu-surface--anchor"></div>

Hi YodaNinja,

I am trying your workaround solution. But I am not sure where I should put the 2nd part of your coding about "unhoist" the mdc-menu.

Could you please shed some light on this?

Many Thanks,
Shirley
