### ISSUE TITLE
IE 11 and Edge support ? (Ripple)

### ISSUE THREAD

**Issue by BerndWessels** [material-components/material-components-web#525]
### What MDC-Web Version are you using?

`0.9.0`

### What browser(s) is this bug affecting?

IE 11
Edge

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

Run any of the [demos](https://material-components-web.appspot.com/button.html) on IE 11 and Edge.

### What is the expected behavior?

Ripple effect to work exactly like on Chrome and Firefox.

### What is the actual behavior?

Ripple effect is not working at all.

**Comment by traviskaufman** [comment]
Hey @BerndWessels,

we actually talk about this within the [ripple readme](https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple#an-aside-regarding-browser-support):

>In order to function correctly, MDC Ripple requires a browser implementation of CSS Variables. MDC Ripple uses custom properties to dynamically position pseudo elements, which allows us to not need any extra DOM for this effect.
>
>Because we rely on scoped, dynamic CSS variables, static pre-processors such as postcss-custom-properties will not work as an adequate polyfill.
>
>Most modern browsers support CSS variables, so MDC ripple will work just fine. In other cases, MDC ripple will still work if you include it in your codebase. It will simply check if CSS variables are supported upon initialization and if they aren't, gracefully exit. The only exception to this rule is Safari, which does support CSS variables but unfortunately ripples are disabled for (see below for an explanation).

I believe that CSS variables recently landed in Edge, so it should work there. However, Ripples will have to gracefully degrade in IE11 since no updates are being made by MS to IE.
