### ISSUE TITLE
Chip Set stops working after casting element to chipset in javascript

### ISSUE THREAD

**Issue by sqljim** [material-components/material-components-web#5250]
## Bug report
Chipsets stop working after casting the element to chipset.

### Steps to reproduce
See code pen: https://codepen.io/jim257/pen/YzzpwYg

### Actual behavior
Before doing anything with the chipsets in javascript after they've been initialised for the first time everything works as expected. But after getting the element in javascript the chipsets stop working as usual, i.e. filter chips no longer have the check mark added or removed upon press.

As a work around I'm having to reinitialise the chipsets each time using the below code:

[].slice.call(document.querySelectorAll('.mdc-chip-set')).forEach(
function(ele) {
    mdc.chips.MDCChipSet.attachTo(ele);
});

which doesn't feel very efficient. What am I missing?

**Comment by abhiomkar** [comment]
I'm not able to reproduce this with following setup:

HTML:
https://github.com/material-components/material-components-web/blob/master/test/screenshot/spec/mdc-chips/classes/filter.html

JS:
https://github.com/material-components/material-components-web/blob/master/test/screenshot/spec/mdc-chips/fixture.js

Demo:
https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/11/12/21_44_32_300/spec/mdc-chips/classes/filter.html

**Comment by ItangSanjana** [comment]
I was planning to create chip-related issues as well, specifically regarding interactivity that doesn't work on version 4.0.0. It turns out that there is a change in the HTML structure that hasn't been updated to the doc on the official website :)

**Comment by sqljim** [comment]
> I was planning to create chip-related issues as well, specifically regarding interactivity that doesn't work on version 4.0.0. It turns out that there is a change in the HTML structure that hasn't been updated to the doc on the official website :)

It would be useful to know exactly which change you're referring to.

**Comment by sqljim** [comment]
> I'm not able to reproduce this with following setup:
> 
> HTML:
> https://github.com/material-components/material-components-web/blob/master/test/screenshot/spec/mdc-chips/classes/filter.html
> 
> JS:
> https://github.com/material-components/material-components-web/blob/master/test/screenshot/spec/mdc-chips/fixture.js
> 
> Demo:
> https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/11/12/21_44_32_300/spec/mdc-chips/classes/filter.html

You won't be able to with that set up because you've not used the chipset in javascript anywhere. You need to include the below somewhere in your code to be able to reproduce the problem:

var chipSet = new mdc.chips.MDCChipSet(currentChipSet);

You'll notice that if you click the RESET button in my codepen twice the chip starts working again. Also, no idea why that happens?

**Comment by ItangSanjana** [comment]
> It would be useful to know exactly which change you're referring to.

Something like this:
Before version 4.0.0:
```
<div class="mdc-chip-set">
  <button class="mdc-chip">
    <span class="mdc-chip__text">Chip content</span>
  </button>
  ...
</div>
```
Now:
```
<div class="mdc-chip-set" role="grid">
  <div class="mdc-chip" role="row">
    <div class="mdc-chip__ripple"></div>
    <span role="gridcell">
      <span role="button" tabindex="0" class="mdc-chip__text">Chip One</span>
    </span>
  </div>
  <div class="mdc-chip" role="row">
    <div class="mdc-chip__ripple"></div>
    <span role="gridcell">
      <span role="button" tabindex="-1" class="mdc-chip__text">Chip Two</span>
    </span>
  </div>
  ...
</div>
```
The document on the official web has not changed, while the latest version (4.0.0) has been released (UNPKG latest). This causes interactivity to not work as it should.

For version 4.0.0 HTML structure:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips

**Comment by sqljim** [comment]
I've updated the codepen to reflect the new HTML structure, but the issue is still there.

If you select the chip in the codepen, then hit the reset button twice, it works as expected. But if you only click the reset button once the chip stops working at all.

**Comment by bonniezhou** [comment]
Hi, thanks for the question. A few things on the original codepen:
- you shouldn't need to reinstantiate MDCChipSet in the `reset` function (line 17)
- `chipSet.selectedChipIds` returns an array of strings (representing chip IDs), not elements (line 20)
- it's not necessary to instantiate each chip individually if you have already instantiated the chip set (line 23)
- the `foundation` is not meant to be accessed as it is a private property within the component (line 28)

I've simplified your code in [this codepen](https://codepen.io/bonniezhou/pen/zYxOrOM) that deselects all chips in all chip sets on a page. It keeps track of all chip sets in an array, and deselects all chips using the `chips` property in MDCChipSet Hope this helps!

**Comment by sqljim** [comment]
Hi,

Thanks for the new pen, that does fix the problem, kind of. I was trying to avoid declaring the chipset as a global variable, and just use when needed. I assume it's not possible to do that?

Also, if you do instantiate a new chipset each time you want to work with the chipset in question you end up with a memory leak.

Just to address your other points:
you shouldn't need to reinstantiate MDCChipSet in the reset function (line 17)

- chipSet.selectedChipIds returns an array of strings (representing chip IDs), not elements (line 20)
 - Yep, thats just poor naming on my behalf, you can see later I do use the string to get the element (line 23)

- it's not necessary to instantiate each chip individually if you have already instantiated the chip set (line 23)
 - Yeah, I was just trying different things to get it to work.

- the foundation is not meant to be accessed as it is a private property within the component (line 28)
 - Now that is helpful, thank you for this piece!

**Comment by bonniezhou** [comment]
Glad this was at least somewhat helpful! :)
To avoid the memory leak you would have to call `.destroy` on the chip set each time you're done with it.

**Comment by Yavanosta** [comment]
Hi @sqljim !

Looks like the root of the problem is in creating multiple instance of the component. Once you created `MDCChipSet` on line 2 of [original codepen](https://codepen.io/jim257/pen/YzzpwYg) you should save an instance of the `MDCChipSet` (returned by `attachTo`) and then interact with component via this instance.

In your code you are creating new instance for every interaction (for every click reset button) so you will create as many instances of `MDCChipSet` as many times you pressed `RESET` button. And every instance will react for the click event

So the actual behaviour of you ChipSet will depend on amount of times you pressed the `RESET` button. If its odd (so with initial creation overall amount of instances will be even) it will look like "broken" because you click event will be handled even amount of times (for example `selected -> deselected -> selected`). If vice versa - it will work. You can check by your self - every next click to `RESET` will circularly "fix" and then "break" `MDCChipSet`.

You can place a breakpoint to `click` event handled (`webpack://mdc/./packages/mdc-chips/chip/foundation.ts`) then click to `RESET` button several times and then try to interact with Chip. Hope it helps.

Main ideas in short:
1. Save instance of `MDCChipSet` once you created it (with constructor or with `attachTo`).
1. Do not recreate `MDCChipSet` once you created it (or at least destroy old one with `.destroy()` method on previous instance).
1. Use code pen by @bonniezhou as a good example.

Please feel free to let me know if you have more questions.
