### ISSUE TITLE
Very Poor Documentation

### ISSUE THREAD

**Issue by jaimeamedina** [material-components/material-components-web#5407]
Sorry if this is the wrong place, but I have to give some feedback here. 

I'm a professional developer re-platforming an ancient web forms app to angular and _was_ intrigued by Material. However, I have never seen such poor documentation for an emerging framework - ever, in 30 years in this business. I mean, there are certainly a ton of words. Page after page of blah blah blah blah blah. Yes I get it's super-important white-paper stuff, but there's no Nobel prize for UI Frameworks. Sorry. 

Heres an idea: How about some markup examples instead of all the writing? You know this thing call HTML? I count 10 tabs open across my browser from switching between Documentation and the component page and the source code page. It's horrifying. I've spent a good couple of days trying to compose a UI using material. And I mean a professional, holistic UI. Any fool can grab a button here and there and past it in. But there are no good start to finish walkthroughs that i can see. Take a look at Bootstrap. There's ton's of markup to copy and paste. There's a clear pithy exposition of the grid system. It doesn't take a Phd to write good technical copy. 

All of the text and verbiage that drones on and on, is in great contrast to conspicuous lack of example code! This makes me think you guys really have no idea what UI and UX are all about. What would be very easy to do is to take some concepts that are described in the Guidelines section, and build it out with Bootstrap. That would be easy; a couple hours of work.

**Comment by asyncLiz** [comment]
Thanks for the feedback. I'm sorry you feel that the documentation is lacking or confusing.

I think you're referring to the [material.io](https://material.io) site since you mention component page and source code page. Unfortunately this project just focuses on the web implementation of Material, not the design itself or the UX docs.

I'd recommend checking out [Material Web Components](https://github.com/material-components/material-components-web-components/). That library will supersede MDC as the go-to web implementation of Material and should be a lot simpler to consume.

If you have any suggestions on MDC-specific documentation improvements, such as our readmes in this repo, feel free to open an issue for a component or submit a PR with suggestions! You can also [join us on Slack](https://www.polymer-project.org/slack-invite) in the [#material](https://polymer.slack.com/archives/CC0Q3PRCL) channel if you have more general questions.

**Comment by berenddeboer** [comment]
@jaimeamedina, this seems to be an extremely unfair comment. For what the documentation is intended to do it is top in its class. It's very detailed, and I use it all the time. I think you're struggling with completely different issues that are simply outside the scope of this project.
