### ISSUE TITLE
[MDCSelect] validation helper text is not visible when the select is invalid

### ISSUE THREAD

**Issue by Darhakexge** [material-components/material-components-web#5463]
### Steps to reproduce
1. Go to the [screenshot test](https://storage.googleapis.com/mdc-web-screenshot-tests/travis/2019/09/27/20_25_07_077/spec/mdc-select/classes/invalid-helper-text.html)
2. The helper text on the invalid select are not visible

### Actual behavior
The validation helper text is not visible when the select is invalid

### Expected behavior
The validation helper text should visible when the select is invalid

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |4.0.0
| Browser          |All
| Operating System |Windows

**Comment by asyncLiz** [comment]
Good find! It looks like the [selector for `.mdc-select-helper-text--validation-msg`](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/mdc-select.scss#L138) is incorrect. It should be a child selector, not a sibling selector.

One thing to note though: in the screenshot test that is regular helper text, it's doesn't have the class that indicates it is a validation message. It's accurate that it wouldn't be visible until focused.

I'm not sure if that's a mistake though. We should either remove the DOM markup (since we're not testing it), or make it a validation message and test that it shows when the select is invalid.
