### ISSUE TITLE
manually download

### ISSUE THREAD

**Issue by JoaquimFMF** [material-components/material-components-web#549]
Is it possible to manually download "material-components-web" (js and css)?

**Comment by traviskaufman** [comment]
Yep! You can use a command-line tool like [curl](https://curl.haxx.se/) or [wget](https://www.gnu.org/software/wget/) to download our built versions from the [unpkg cdn](https://unpkg.com).

CSS:

```
wget https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
```

JS:

```
wget https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js
```

Most operating systems will have these tools installed, so you can just open up your terminal program and begin using them.

**Comment by JoaquimFMF** [comment]
Can I just include the 'link' and 'script' tags in HTML? Which links should I use for each tag?

**Comment by amsheehan** [comment]
Something like this should work:

```html
<html>
  <head>
    <meta charset="utf-8">
    <title>My Site</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
  </head>
  <body>
    <!-- ...your web page... -->
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js" charset="utf-8"></script>
  </body>
</html>
```

**Comment by JoaquimFMF** [comment]
How can i donwload de css e js files in windows 10 without installing any application?

**Comment by amsheehan** [comment]
Unfortunately there is no such built-in tool in Windows. You will have to install an application like wget or cURL.

As an alternative you can go to `https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css` and `https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js` in your browser. This will render the contents of each file which you can copy and paste into a new document.

This is not recommended though, since you will only be getting a snapshot of MDC Web at the time you download it.
