### ISSUE TITLE
Navigation Drawer incorrectly positioned in RTL context

### ISSUE THREAD

**Issue by null-dev** [material-components/material-components-web#551]
## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

0.9.1

### What browser(s) is this bug affecting?

Chrome on Arch Linux (Version 58.0.3029.81 (64-bit))

### What OS are you using?

Arch Linux (rolling release)

### What are the steps to reproduce the bug?

Please view this codepen:

When in RTL mode and in the closed state, the drawer is incorrectly positioned inside the page: http://codepen.io/nulldev/pen/LyRBZZ

~~With the drawer is in RTL mode and the header and text in LTR mode (hence creating a LTR right-hand drawer), the margins on the icons are set incorrectly:
http://codepen.io/nulldev/pen/rmMrwN~~

**Comment by Touficbatache** [comment]
That's a bug, I tried it on my Android 7 phone

**Comment by traviskaufman** [comment]
Hey @null-dev ,

The first codepen is definitely a bug. Not sure where that regression was introduced but we'll be sure to look into it.

The second codepen, however, is _not_ a bug but rather a limitation of how we do RTL. If you're trying to get the drawer to simply be on a different side of the page, RTL is not what you want. That is a UX consideration that I believe we omitted due to the spec explicitly stating where the drawer should come in from:

> The navigation drawer slides in from the left and contains the navigation destinations for your app.
- https://material.io/guidelines/patterns/navigation-drawer.html

**Comment by esaesa** [comment]
I see the bug still exists after the merge of the fix
https://codepen.io/nulldev/pen/LyRBZZ

**Comment by Elemecca** [comment]
@esaesa that codepen works fine for me in Firefox 45.0.1 and Chrome 58.0.3029.110 on Linux. What browser are you still seeing issues on? Can you provide a screenshot?

**Comment by Touficbatache** [comment]
The problem has been actually fixed. @esaesa posted this when MDC was in 0.11.1.

**Comment by touficbatache** [comment]
Should [this](https://www.pivotaltracker.com/story/show/144457931) be closed?
