### ISSUE TITLE
Contributing interim TypeScript definitions?

### ISSUE THREAD

**Issue by Elemecca** [material-components/material-components-web#552]
I'm producing TypeScript definitions for the subset of mdc-web components that I'm using in one of my company's products. It seems silly to do that work and not share, so I'm trying to figure out how I should make them available to the community. I understand that (per #134) you plan to eventually convert your code to the Closure type system and mechanically produce TypeScript definitions, but it would be nice to have TypeScript definitions in the interim. Are you interested in incorporating my definitions, or should I contribute them to DefinitelyTyped instead?

**Comment by traviskaufman** [comment]
Hey @Elemecca,

Thanks so much for volunteering to help out with this! We'd love to have typings for our components, but are a little skeptical of including them in our core codebase _yet_, since we're still in the process of converting to closure and need to focus on that first. 

That being said, we'd strongly encourage you to contribute your typings to DefinitelyTyped. Furthermore, you can use a tool like [Greenkeeper]() to track our releases and since we follow SemVer, you can keep a look out for any minor version bumps that would warrant a typings update ("minor" since we're still v0.x). Furthermore, we're happy to help assist you with any questions you have regarding these types; reach out to us on discord at https://discord.gg/pRKaJB9
