### ISSUE TITLE
code gardening - For events instead of string literals use constants

### ISSUE THREAD

**Issue by jonboj** [material-components/material-components-web#556]
#### What MDC-Web Version are you using?
0.9.1

#### Purpose
As the api for framework integration is interpreted, the framework will add listeners for events. In order easier to get en overview of the event api collect the events as constants. In current version the events is defined by string literals in index.js.

#### Example
For `mdc-menu` expose event api with `MDCSimpleMenu:selected` and `MDCSimpleMenu:cancel` in e.g.
https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/constants.js

Current string literal `MDCSimpleMenu:selected`
https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/index.js#L95

Current string literal `MDCSimpleMenu:cancel`
https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/index.js#L99

**Comment by traviskaufman** [comment]
Great suggestion @jonboj! I can definitely see why we'd want to put event names into our `strings` constants. @amsheehan noted that this would help facilitate action creators in Redux as well, which is a big plus. The work to be done here would be the following:

- [ ] Refactor all of our string literals for events into their `strings` constants counterparts
- [ ] Update `docs/authoring-components.md` to ensure that guidance on putting event names in `strings` is included
- [ ] Update the tests for all of these components to use the `strings`  constants rather than the literal event names
