### ISSUE TITLE
[MDCTextField]. Getting started.  Quick Start approach. mdc-text-field mdc-text-field--with-leading-icon does not centrally align.

### ISSUE THREAD

**Issue by lycandroid** [material-components/material-components-web#5632]
Hi,

In summary - text field leading icon is not horizontally centered in text field - it is left aligned.

When using the "Quick Start (CDN)" from the "Getting Started" guide https://material.io/develop/web/docs/getting-started/ and defining an mdc-text-field with a leading icon using the html as shown from https://material-components.github.io/material-components-web-catalog/#/component/text-field?icons=leadingIcon i.e.

```html
<div class="mdc-text-field mdc-text-field--with-leading-icon">
  <i class="material-icons mdc-text-field__icon">favorite</i>
  <input class="mdc-text-field__input" id="text-field-hero-input">
  <div class="mdc-line-ripple"></div>
  <label for="text-field-hero-input" class="mdc-floating-label">Name</label>
</div>
```
the icon is not horizontally centered in the leading icon area - it is left aligned.

![image](https://user-images.githubusercontent.com/14123917/74921214-581a4200-53c5-11ea-9cfb-fc8686bd4de0.png)

See glitch https://horse-metatarsal-bin3xwtg.glitch.me/

Is there something additional that needs doing when using the CDN?

Thanks

**Comment by asyncLiz** [comment]
You are missing the [`mdc-text-field__icon--leading`](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield/icon#leading-icon) class on the icon. Adding it to your glitch fixes the problem. This was part of the breaking changes in [v5.0.0](https://github.com/material-components/material-components-web/releases/tag/v5.0.0).

> **textfield**: icons must use `.mdc-text-field__icon--leading` or `.mdc-text-field__icon--trailing` classes. `mdc-text-field-icon-color()` mixin has been split into `mdc-text-field-leading-icon-color()` and `mdc-text-field-trailing-icon-color()`.

The catalog has not been updated to v5.0.0, which is why it still shows the old version.

**Comment by lycandroid** [comment]
Confirmed works as described. That's great, thank you.
