### ISSUE TITLE
Consolidate text field icons

### ISSUE THREAD

**Issue by zbot473** [material-components/material-components-web#5653]
I think it would be best if `mdc-text-field__icon` was merged into the leading and trailing variant, to make 2 resulting classes, and omitting the first class. The result would be 2 separate and functional classes, `mdc-text-field__icon--leading` and `mdc-text-field__icon--leading`; and would make the first obsolete.

**Comment by asyncLiz** [comment]
Thanks for the suggestion!

We use the [BEM (Block Element Modifier)](http://getbem.com/introduction/) convention for styling. The `--leading` and `--trailing` classes are modifiers of the `__icon` element, which is why they exist separate from it.

Common classes shared between text field icon variants are on the first class, while the modifier classes specify additional style rules.
