### ISSUE TITLE
Support non Latin Script fonts using Noto in Typography component

### ISSUE THREAD

**Issue by Brahmasmi** [material-components/material-components-web#566]
The current Typography component supports the Roboto font only - https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_variables.scss. If I am not wrong, Roboto does not support all non Latin fonts.

Please consider adding support for non Latin fonts as well.

This issue is open on https://github.com/google/material-design-lite/issues/1435 and is discussed further in https://github.com/google/material-design-lite/issues/1717.

Relevant material design spec - https://material.io/guidelines/style/typography.html

**Comment by omerziv** [comment]
Hey, our current recommendation for projects with non-Latin languages is to use Noto, which is available on Google Fonts in various versions for various languages. 
Noto was designed to work with Roboto so the font sizes, line heights, and other variables in mdc-typography should work well (and you can always override specific styles if anything feels weird in your use-case.)

Unfortunately, I don't have a recommendation for loading different fonts based on the language that is currently on the page (as requested in the discussions you linked to). This is a well known issue for sites that support multiple languages. Some browsers help with this by supporting unicode-range to load just the parts of fonts that are actually needed, and to my understanding Google Fonts should support that automatically.
Perhaps @davelab6 from Google Fonts can recommend some best practices?

**Comment by Brahmasmi** [comment]
I may be wrong here but I am not sure if the problem is well understood here.

I am aware of the material design spec's recommendation to use Noto for non-Latin fonts. In fact, your statement that "font sizes, line heights, and other variables ... should work well" points me to the inadvertent lack of understanding of the typography spec. The Latin specs are very different from non-Latin ones - https://material.io/guidelines/style/typography.html#typography-line-height.

Could I please request a thorough reading of both the issues linked in the bug report and the typography spec? Additionally, there is a TODO here - https://github.com/material-components/material-components-web/blob/master/packages/mdc-typography/_variables.scss#L30
/* TODO(sgomes): Figure out what to do about i18n and i18n font sizes. */

Polymer's approach is here - https://github.com/PolymerElements/paper-styles/blob/master/typography.html#L28. It uses fall through - Roboto, Noto, sans serif. However, it lacks the needed line height adjustments.

**Comment by davelab6** [comment]
I'm curious if you can recommend projects that you think do a good job with
this problem :)

The GF API supports Unicode Range, but almost all Noto fonts are not
available in the API but in fonts.google.com/earlyaccess and that has no
API features at all; it is much more like self hosting, but using a central
CDN url for cross site caching is an important benefit over self hosting.

A developer could create a hand crafted set of `@font-face` rules that have
unicode range data... but linking directly to font file URLs on the GF CDN
is unsupported, and the URLs change over time so even if this works when's
it's developed then it will need close monitoring.

Also each Noto writing system font is named (and served) by itself; there
isn't a single Noto family, rather "Noto Sans Thai" and "Noto Sans
Georgian" etc, so based on what you said, polymer's approach is unlikely to
work as intended. (It might work on some systems where the Noto fonts may
be composed into a single family by the OS font manager, depending on the
Chromium OS fontconfig or similar Android subsystem setups...)

I believe that contemporary browsers won't download fonts that are linked
to a page but aren't actually used. However I don't know if this is true
for the fallback stack. It could be that if you add `@import` statements
for all the Noto fonts in Early Access and then have a very long
`font-family: Roboto, Noto this, Noto that` rule, then only the ones used
on a page will be loaded.

If we are not so lucky and some/all browsers will fetch all the fonts as
they are "used" (since a family rule with them in the fall back stack
applies to an element on the page...) then if this can be done async so
page rendering isn't blocked, then that's maybe as good as it gets with the
current resources.

**Comment by Brahmasmi** [comment]
Danke @davelab6 for the detailed analytical treatment of the problem.

I will be the first to admit that I do not know the definite answer to the problem. However, as this issue and the linked previous issues highlight - the real challenge till now has been to register the existence of the problem itself. The hope is that it gets acknowledged and put on a list of todo's somewhere. Which in turn sparks a discussion, and hopefully a robust scalable solution.

As regards to the various options that you have discussed:
1) I do not have any visibility into the Google Fonts API, and why the Noto fonts are in Early Access. I acknowledge that there could be issues with Noto font renderings, but it is a gargantuan task. I am thankful to Google's i18n team for their sustained effort in building a font that will serve the Unicode range, hopefully of all living languages.
2) As regards to the custom font face with self hosted fonts, I agree that it may be a brittle solution.
3) I understand that there are various Noto scripts and just putting Noto in the list would not do anything, except for the cases which you have outlined. But not putting anything there certainly does not solve the problem.
4) Instead of listing all known Noto fonts, may be the solution to the problem could be to have a configuration/variable/setting in the component where the developer could list the fonts that the developer wishes to support. These would then be inserted after Roboto but before generic serif/sans serif fonts. If that is not feasible, they could be inserted before Roboto itself. In this case, if the specific script fonts do not have the Latin range, the logic should fall back to using Roboto for the Latin range.
```
pseudo-code
specific_fonts = "Noto Sans Thai, ..."
...
within-typography-component
font-order = $specific_fonts, Roboto,...
```
5) I have limited knowledge of async font loading, or browser behaviour loading all fonts in the fallback stack, so it would be difficult for me to comment.

**Solution**
May be, the current state of font loading needs to come out of the assumption that all fonts are Latin, and just serif/sans serif suffices as fall back. May be we need something specific for each script.
```
pseudo-code
font-Latin = Roboto, serif
font-Thai = Noto Sans Thai, some-fall-back-that-makes-sense-in-Thai
...
font-specific-script = font-order-in-that-script
```
I am speculating here, but the ranges for these scripts might be known within Unicode, so the browsers would know based on the character they are being asked to render, to look for and load that font.
```
pseudo-code
switch (character_range)
  case Latin:
   loadLatin(latin-font-order)
  case Thai:
   loadThai(thai-font-order)
  ...
```
Since there are no more than 100 odd living scripts and few-to-none being added, this would be a bounded problem. It would also convert the problem of loading a huge font-family with all scripts in it, into a much simpler problem of the browser itself figuring out which fonts to load based on the developers input. Also, it would allow typography to be defined in terms of every script, rather than the catch-all serif/sans serif. So, adding a new language to support would mean adding the specific font only, and not wondering about the fallback and loading behaviour.

In case you have a connect with the Google Fonts i18n team, may be they could figure something out with the Google Chrome team.

**Comment by Brahmasmi** [comment]
@davelab6 any thoughts/ideas/comments/criticisms/actionables on my response?

**Comment by Brahmasmi** [comment]
@davelab6 ping a.k.a. polite reminder.

**Comment by Brahmasmi** [comment]
Could someone please help with this?

I had hoped that there would be at least some discussion on this issue. I wrote an entire response because the problem that I have outlined in this issue is real. However, it seems non-Latin scripts are destined to be neglected.

Is there a better place/channel/mailing list to raise this issue?

**Comment by patrickrodee** [comment]
Please use the `$font-family` variable.

https://github.com/material-components/material-components-web/blob/39ed5fe73c20ebf579aa7e5aef23dfdec3b5cda2/packages/mdc-typography/_variables.scss#L27
