### ISSUE TITLE
Creating a Custom Native Select Implementation

### ISSUE THREAD

**Issue by katiep23** [material-components/material-components-web#5690]
According to "abhiomkhar" in [this thread](https://github.com/material-components/material-components-web/issues/4799), it's possible to create custom implementation using combination of mdc-notched-outline + mdc-floating-label.  Can anyone assist in how to implement that?

**Comment by asyncLiz** [comment]
I would recommend looking at the HTML structure for our textfield and replacing the `<input>` with your own `<select>` and adjusting styles from there.

While possible, it's outside the scope of what we're doing in this project, so I'll be closing this issue.

**Comment by nerg4l** [comment]
With some styling the look can be quite similar to how the native select looked like in earlier versions. However, the value won't be changeable by using `textField.value = 'x'` because of the differences between the two elements. This framework expects value changes to be done by changing that property therefor it won't have the same functionality.
