### ISSUE TITLE
Separate _variables.scss for all packages?

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#576]
Do you plan to refactor out variables to a separate _variables.scss for each package?

I'd like to reference some of the variables in the drawer and toolbar packages, but as they reside in .scss files that also outputs css I get that css twice in my bundle.

When needing to reference variables from the grid-layout package I don't run in to this problem as that package has a separate _variables.scss I can import.

**Comment by amsheehan** [comment]
The aim is make sure that all default styles are defined in some `_variables.scss` file so they can be `@import`ed into a user's css files. This would be considered fixed by taking the following steps:

- [ ] Update files in packages to surface all `default` css rules in their corresponding `_variables.scss` file
- [ ] Update the `authoring_components.md` file to document the process moving forward

We have added this to Tracker, but if this is something you'd like to take we'd be happy to review a PR. 

Thanks!
