### ISSUE TITLE
Templates are outdated

### ISSUE THREAD

**Issue by wolfy01** [material-components/material-components-web#5824]
The templates have been outdated for awhile now, and this makes it difficult when trying to upgrade NPM modules or install NPM modules because of all the updates, even if I do get it to build, the HTML seems wrong, all buttons and everything have lost the css or whatever. I haven't found a way to fix this issue

**Comment by wolfy01** [comment]
This also makes it really difficult because some of the things I have made using material can't be updated, since I used a template to start out with, installing a new NPM module breaks everything.

**Comment by asyncLiz** [comment]
Hi, can you please be specific and address point out what is outdated? All of the templates in our readme documentation should be up to date.

**Comment by wolfy01** [comment]
@asyncLiz 

All the templates seem to be using @import, which doesn't work with current material.
The CSS and styling also break if any material modules are updated. The templates were made using material-1.0.0 which is also not the current version.

**Comment by wolfy01** [comment]
An example of one of these templates is https://glitch.com/~material-example-app-shrine

**Comment by asyncLiz** [comment]
Thanks for the issue! Unfortunately there are a lot of example and sample apps out in the wild, and not all of them remain up to date with new features.

Updating various codelabs is always a slow and ongoing effort. Our recommendation would be to either use the version specified in the examples you're following, or reference the documentation in this repository as you follow along if you want to use the latest features.

Also don't forget that `@import` still works with the current version of Material as a backwards compatible solution if you need to copy/paste some code and get running.

Closing since the templates in question are out of scope for this repository.
