### ISSUE TITLE
React Material Components Web Update Request

### ISSUE THREAD

**Issue by danialBakhtiary** [material-components/material-components-web#5868]
**Hi, I'm Daniel from Iran. I have been following your work for a year. Thank you. You are better every day than yesterday. I wanted to say that I can't use your services. I face many challenges. Please update "React Material Components Web" or show me a way so that I can use your services. Thank you.**

**Comment by abhiomkar** [comment]
Hi Daniel, Thank you for the kind words.

In order to increase our focus on implementing our core, framework-independent libraries (MDC-Web and [MWC](https://github.com/material-components/material-components-web-components)), we no longer be updating and maintaining [Material Components for React (MDC React)](https://github.com/material-components/material-components-web-react).

Two options:

* We recommend using [Web Components implementation](https://github.com/material-components/material-components-web-components) of MDC-Web.
* Or please feel free to switch to another open source implementation and keep building beautiful, usable apps based on Material Design.
