### ISSUE TITLE
[mdc-card] Example code for the "Horizontal Image and Text" card demo produces a normal card

### ISSUE THREAD

**Issue by mbestavros** [material-components/material-components-web#5925]
## Bug report

Example code paired with the "Horizontal Image and Text" demo does not produce the desired card with an image to the left of text; rather, it produces the same layout that a standard card would.

### Steps to reproduce
1. Go to 'https://material-components.github.io/material-components-web-catalog/#/component/card'
2. "Variant" -> "Horizontal Image and Text"
3. Click "Web" tab above the demo card
4. Copy example code
5. Run it
6. Card does not appear as advertised

### Actual behavior
A generic card, with image above text, is displayed.

### Expected behavior

A card with image horizontally aligned with text is displayed, as would match the demo.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.1.0
| Browser          | Chromium 81
| Operating System | Fedora 32

**Comment by asyncLiz** [comment]
This looks like a version issue with the catalog, which is still on v4.

Can you try following the readme documentation at https://github.com/material-components/material-components-web/tree/v5.1.0/packages/mdc-card to create the markup for your card?

**Comment by mbestavros** [comment]
The up-to-date documentation doesn't help -- it doesn't provide any guidance on how to make a card look like the horizontal one showed off on the demo page (where the image is inline with the text).

I did some digging, and I think this PR might be worth looking at: https://github.com/material-components/material-components-web/pull/2025

While that PR is kind of old, what I'm reading is that a horizontal card now needs to be designed via custom CSS (which is never provided as part of the example).

Might it make sense to include an example of how to accomplish this somewhere? As-is, the demo is completely misleading.

**Comment by asyncLiz** [comment]
The thing with card is that the layout is extremely customizable. The classes provided are very barebones and apply only to specific areas of the card itself, not its content or the layout.

The catalog variants demo is a bit misleading because it provides some custom classes to show off examples of different layouts. These layouts are just samples, they're not pre-built into MDC.

Here is an example outside of the catalog that shows how you can achieve the same horizontal layout: https://jsbin.com/mayuxococe/edit?html,output.

Hope this answers your question!

Closing since this is more of a catalog issue with the variant demo code. I've created https://github.com/material-components/material-components-web-catalog/issues/285 to track the problem.

**Comment by mbestavros** [comment]
@asyncLiz Thanks for the example! That's helpful.

Is there a single place I can find examples of what we can do with these custom classes? Perhaps as a Glitch project? I'd imagine that would be useful for a number of folk.

**Comment by asyncLiz** [comment]
That'd be difficult, since there's so many possibilities with what's possible on the web. I'd recommend getting started with [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), since that should give you a solid foundation in all the browsers supported by MDC to achieve many unique layouts. 

The horizontal layout I demonstrated was built with flexbox.
