### ISSUE TITLE
[Cards] Improvements to cards (Missing elements)

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#5926]
## Feature Request
According to [Material Design Guidelines](https://material.io/components/cards) and its demo, you can add the following elements that are not currently supported by MDC Web:
- Thumbnail or icon (2)
- Card title (3)
- Secondary Text (4)
- Supporting text (6)

![MDC Cards guideline](https://lh3.googleusercontent.com/KpK-WVnI_vmkGh7-jzwdoN-azXeAgsbzb1rZG_r902t2fZxOoh2NwCHxPyhITk53gve26ohDBNc2EeJ1ah97Q5hxTNfty9qDK5krXw=w1064-v0)

### Proposed solution
Add the missing elements. The demo on the guidelines page already supports Title, secondary text and supporting text so these could be easily picked up from that.
Instead, the thumbnail can be done following [this](https://stackoverflow.com/questions/51821311/add-icon-to-an-mdc-card)

**Comment by asyncLiz** [comment]
All of these elements are already supported via the icon and typography packages.

Cards by their nature are incredibly dynamic. It was a conscious choice not to have a specific `mdc-card__title` class for example. The user could use the `mdc-typography--subtitle1` class and position it where appropriate within the `mdc-card`.

We don't want our implementation to limit the possibilities of what can be done with a card's layout, which is why it's rather "barebones". The classes are just for the card itself, not the content inside it.

Let us know if that answers your question!

**Comment by maicol07** [comment]
Sorry, but where is the icon package? I can't find it anywhere... do you mean the icon button one?

**Comment by asyncLiz** [comment]
Apologies, I meant the [icon font](https://material.io/resources/icons/?style=baseline).

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<span class="material-icons">code</span>
```
