### ISSUE TITLE
Expansion panel

### ISSUE THREAD

**Issue by Misiu** [material-components/material-components-web#5939]
**Is your feature request related to a problem? Please describe.**
I need a way to show/hide some options that are considered advanced. The expansion panel is ideal for that.
Another use case is the agreement panel:
![image](https://user-images.githubusercontent.com/1741838/82299755-345f9b80-99b6-11ea-9f96-c3d1a005a806.png)
You want to show the title, but also provide a way to see the details.
The multi-step form is another great example.

**Describe the solution you'd like**
I'd like to have the expansion panel component.
For my use case, I need to show a panel with title and description (similar to one of above)
![image](https://user-images.githubusercontent.com/1741838/82300234-d2536600-99b6-11ea-8886-eda9b519dcec.png)
after clicking on the title I want the panel to expand and show a form that will allow filling the details. After collapsing the panel, the label should reflect changes in the form.
This will allow showing a large form in logical groups.

**Describe alternatives you've considered**
Using material-ui with React or searching for a web component implementation

**Additional context**
The spec is available here: https://material.io/archive/guidelines/components/expansion-panels.html#
The demos in material-ui: https://material-ui.com/components/expansion-panels/

**Comment by asyncLiz** [comment]
Closing since expansion panels are no longer part of the current spec (see https://github.com/material-components/material-components-web/issues/46#issuecomment-413898267).

I spoke with design, and we agree that the pattern is still actively used throughout the spec (such as expanding/collapsing sections in lists and data tables). Whether this translates to a well-defined separate component or an animation pattern is a different story.

Additionally, there are several variations of this pattern, such as expansion panels vs accordions, that would need to be defined.

Right now the pattern as a component is not defined and there's not much for us to do for either MDC or MWC. However our design team is aware of the need for clarity and will be looking into exploring options and patterns for fleshing out the pattern in the future.

In the meantime we'd recommend building your own components using the [motion principles](https://material.io/design/motion/understanding-motion.html#principles) of Material as guidance.

**Comment by Misiu** [comment]
@asyncLiz thank you for the reply and for talking with the design.
As you wrote the pattern is very popular and I think it should be there.
I'm aware that your team isn't responsible for the design, but where can I ask for adding expansion panel/accordion to the spec? Does such a place exist?

For now, I'll use https://vaadin.com/components/vaadin-accordion/java-examples or https://vaadin.com/components/vaadin-details/java-examples

**Comment by Misiu** [comment]
@asyncLiz I'd like to get back to this.
I recently used google travel and I notice that expand/collapse panels (list) is used a lot in there:
[![Image from Gyazo](https://i.gyazo.com/88dfd0901279f5bfeee7f62a666a4da0.gif)](https://gyazo.com/88dfd0901279f5bfeee7f62a666a4da0)

can similar results be achieved right now (ideally with web components, but let's start here)

**Comment by asyncLiz** [comment]
Our role as the Material Web team is to implement the components laid out in spec by the designers of our overall Material team. We're aware that expansion panels are a requested feature, but we won't be adding them until design has a chance to spec out exactly how the components should function and behave.

Once they do that, then each platform (Web, Android, iOS, and Flutter) will implement the components. In the meantime, our best suggestion would be to use the principles laid out by Material Design around motion and layout to create something yourself until an official component is specced out and created.

**Comment by derwaldgeist** [comment]
I can't believe this is the current state as of 2024?! How do expect people to adopt the MWC library if so essential components are just missing?

**Comment by derwaldgeist** [comment]
Just saw that there is a spec for these:
https://m1.material.io/components/expansion-panels.html#
Not sure if this is the official specs, though.
