### ISSUE TITLE
MDC-Select float label disabled

### ISSUE THREAD

**Issue by jimmyhdolores** [material-components/material-components-web#5983]
Hello, I am using version 6.0.0, when SELECT is disabled the label can still float when I click on it, this happens with the SELECT of outline type, I don't know if this behavior is normal, I hope they explain it to me, thanks.

**Comment by Its-treason** [comment]
It appears to happen when you click the `mdc-floating-label` Element. I created to small CodePen to visualize [here](https://codepen.io/The_Senate/pen/xxweoPw).

**Comment by jimmyhdolores** [comment]
any suggestion from the team? @asyncLiz

**Comment by asyncLiz** [comment]
It looks like this has been fixed in the latest version of select on the canary branch

v6 (bug) https://jsbin.com/zogobixiyi/edit?html,output
v7 (fixed) https://jsbin.com/dikafoguyi/edit?html,output

For a temporary workaround, add the following CSS to your project in v6:

```css
.mdc-select--outlined .mdc-floating-label {
  pointer-events: none;
}
```

One more reminder, there is a bug in the v6 docs. Make sure you do not include the `mdc-select__ripple` element in the outlined variant of select.
