### ISSUE TITLE
Request a new feature in the components

### ISSUE THREAD

**Issue by danialBakhtiary513** [material-components/material-components-web#6043]
Hello
Is it possible to give the components of the component with JavaScript?
Example:

`topAppBar = new mdc.topAppBar.MDCTopAppBar(topAppBarElement)`
`topAppBar.variant="mdc-top-app-bar--fixed"`

**Comment by applemonkey496** [comment]
You could probably use `topAppBarElement.classList.addClass('mdc-top-app-bar--fixed');` which would, as far as I know, have the same effect.

**Comment by danialBakhtiary513** [comment]
> You could probably use `topAppBarElement.classList.addClass('mdc-top-app-bar--fixed');` which would, as far as I know, have the same effect.

This can be done, but it seems that they should do this in the package because it needs to be redefined. I don't know how it should work.

For example, if we change the attribute in any way, it must be redefined. This is very problematic

**Comment by danialBakhtiary513** [comment]
I mean, from now on, it will be redefined with each change of feature. If you could do something to prevent redefining, it would be great.

link
[https://material-components-web.appspot.com/top-app-bar.html](url)

**Comment by danialBakhtiary513** [comment]
![Untitled](https://user-images.githubusercontent.com/65126900/84060676-db41c100-a9d1-11ea-8174-7c3f6216ac4f.png)

**Comment by asyncLiz** [comment]
Re-defining the variant at runtime in JS isn't something that will be supported out of the box in MDC. The JS component is very minimal and does not hydrate the DOM. That's to say, it won't fill in missing elements or change the DOM structure for you. It expects everything to be there already.

The reason behind this is primarily performance, as discussed in the [migrating from MDL doc](https://github.com/material-components/material-components-web/blob/master/docs/migrating-from-mdl.md#initializing-components).

While MDC is minimal and does not include a rendering or templating library to support this, you may be interested in checking out [Material Web Components](https://github.com/material-components/material-components-web-components/). MWC is the future direction of MDC.

These web components _are_ built off a templating library called [LitElement](https://lit-element.polymer-project.org/), and you can change their variant at runtime by simply changing an attribute.

Closing since we won't be implementing this in MDC and it's already implemented in MWC.
