### ISSUE TITLE
[Button] core-styles should apply density by default (remove theme-baseline mixin)

### ISSUE THREAD

**Issue by btalb** [material-components/material-components-web#6066]
## Bug report
A lot of the component documentation pages ([https://material.io/develop/web/](https://material.io/develop/web/)) show example code that produces vastly different output to what is suggested. I'm filing this bug report with specifics from the "Button" component, as it is the simplest and most blatant example of these issues for me.

I've tried to get into using this project many times over the years, but have consistently struggled in sinking a lot of time without much progress. While most time sunk was due to my lack of experience in the area, I still feel there's a lot of friction in just "getting up & running" with web MDC. I've persevered this time and gotten a lot further, but most of the progress has required hacking together mixins / mashing different classes together / digging through source code, rather than just following the documentation.

I'm probably missing something blatantly obvious, but regardless think it is a valid bug that following the documentation produces vastly different results to what's shown in the documentation.

### Steps to reproduce

*Note: all "documentation" references are talking about [this page](https://material.io/develop/web/components/buttons/)*

1. Create an `index.scss` file using the code from "Using Buttons -> Styles":

```scss
@use "@material/button";

@include button.core-styles;
```
2. Paste example HTML code from "Text buttton -> Text button example", "Outlined button -> Outlined button example", & "Contained button -> Contained button"  into an `index.html`:

```html
<html>
  <head>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link href="./index.scss" rel="stylesheet" />
  </head>
  <body>
    <button class="mdc-button">
      <div class="mdc-button__ripple"></div>
      <span class="mdc-button__label">Text Button</span>
    </button>
    <button class="mdc-button--outlined">
      <div class="mdc-button__ripple"></div>
      <span class="mdc-button__label">Outlined Button</span>
    </button>
    <button class="mdc-button--raised">
      <span class="mdc-button__label">Contained Button</span>
    </button>
  </body>
</html>
```
See Glitch for full example: https://glitch.com/~skinny-glacier-potassium

### Actual behavior

Ghastly looking buttons ;)

![bad_buttons](https://user-images.githubusercontent.com/3508780/84559403-9fb24880-ad7d-11ea-9274-0d863bf32631.png)

### Expected behavior

Buttons that look exactly the same as the images included with the examples.

### Your Environment:

*Everything in this bug is reproducible in the Glitch example*

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | ^6.0.0 |
| Browser          | Version 81.0.4044.138 (Official Build) (64-bit) |
| Operating System | Ubuntu 18.04 |

### Possible solution

I achieved the expected behaviour screenshot by going on the following dig through source code & patching stuff together from various other examples:

1. Found other examples with both `mdc-button--blah` & `mdc-button` classes. Added it in for the second two buttons (Looks better, but still have some ugly spacing / sizing going on):

![better_buttons](https://user-images.githubusercontent.com/3508780/84559610-6084f700-ad7f-11ea-9af3-8af6bca56008.png)

2. Can't find anything in the documentation about spacing, relevant mixins, etc. Dig through the source looking for what I could be missing. *Guess* that the second mixin included: `@include mixins.theme-baseline` in `.../@material/button/mdc-button.scss` must be what I'm missing from moving to `@use` statements. Add `@include button.theme-baseline` to `index.scss`, & my buttons almost look as expected:

![best_buttons](https://user-images.githubusercontent.com/3508780/84559709-6f1fde00-ad80-11ea-9ca0-9e17eb7e0f88.png)

3. Find the `outline-color()` mixin, add `@include button.outline-color(primary)` in `index.scss` for the `mdc-button--outline` class:

![perfect_buttons](https://user-images.githubusercontent.com/3508780/84559778-13098980-ad81-11ea-9b10-c23ad07a6dfe.png)

Perfect? I hope. From making so many deviations from the example to get something that looks like the example... I'm a user left without much confidence that I actually know what I'm doing going forward. I feel like I've just hacked & slashed until I *think* I've got the right thing.

It probably seems a bit whiny, but this is step 1, creating really basic buttons. As I got further & further into my project I discovered all sort of subtle errors (e.g. highlight colours not matching theme, ripple shapes, squashed margins, etc.) and have no confidence of whether there's an undocumented step I'm missing in using the components, I'm missing a SASS include, I've stuffed up in my theming, I've got the wrong HTML classes, etc.

It would be really nice as not a particularly experienced user to have confidence that all the code I take from examples gets me in a working state, & errors from that point on are most likely of my own doing.

At the moment I feel it is more likely I'm missing something obvious / doing something wrong?

**Comment by asyncLiz** [comment]
Thanks for the issue!

This looks to be a combination of two problems:

**1. missing mdc-button class**

This was reported in https://github.com/material-components/material-components-web/issues/5978 and fixed in https://github.com/material-components/material-components-web/pull/5987 a couple weeks ago. The documentation hasn't been pushed to the material.io site since we haven't published a new release yet.

In the first outlined and first raised snippet example, the `<button>` element is missing the `mdc-button` class. It should be `<button class="mdc-button mdc-button--outlined">` and `<button class="mdc-button mdc-button--raised">`.

**2. theme-baseline mixin**

If we look at the original [@material/button/mdc-button](https://github.com/material-components/material-components-web/blob/bfe957ca7dc7c0584ead080dbbf8494cbc8dd47e/packages/mdc-button/mdc-button.scss#L25) import, it does look like it's doing more than just applying the core-styles mixin.

This was likely missed as we upgraded the documentation. The core-styles() should be applying the default density() that "theme-baseline()" is doing.

**Fixing the problem**

For the short term, a better solution may be to continue using the `mdc-*` imports to "apply styles" while we continue to find and fix documentation issues. We have plans to improve the Sass organization of our components to make things less confusing since this has been a common pain point.

Here is your glitch remixed with the solution in place: http://glitch.com/~pickled-apple-farm

> Note that per your #3 point, the outlined button's outline color is _not_ supposed to be the primary color; it should be grey (see https://github.com/material-components/material-components-web/issues/5650 and https://github.com/material-components/material-components-web/issues/5170).

I'm going to keep this issue open and update the title to reflect the fix that needs to happen for button's core-styles mixin.

Additionally, I'd recommend joining the [Polymer Slack](https://www.polymer-project.org/slack-invite) #material channel (more active and broader community), or the [Material Discord](https://discord.gg/material-components) (less active, but focused on MDC only). Both are great places to ask live questions to the community and get help troubleshooting problems.

**Comment by btalb** [comment]
Excellent, thanks for the detailed response @asyncLiz . The glitch also helped affirm for me I wasn't too far off, & generally heading in the right direction.

I'll use the component READMEs on `master` as a second point of reference from now on, & the live question forums for help.

Only other comment I'd add RE outline colour. Completely agree the functionality is exactly to spec as is, I'd just recommend either updating the images in the documentation to show the grey outline is what a user should expect, or adding a note to the text saying the `@button-outline-color()` mixin is required to get the results shown below.

**Comment by asyncLiz** [comment]
Great point about the images! It looks like those do need to be updated in the readme too.
