### ISSUE TITLE
Using Yarn: Latest version not pulled in

### ISSUE THREAD

**Issue by rkiller** [material-components/material-components-web#6075]
I'm using a number of these components in a rails project using webpacker. I'm using Yarn to manage the components. I've recently updated to 6.0.0 and it seems like not all the changes have been pulled in. For example, layoutOptions() does not exist on MDCSelect and basically the upgrade broke some of the functionality. Any ideas why this is happening?

**Comment by asyncLiz** [comment]
`layoutOptions()` is not part of the [v6.0.0 documentation](https://github.com/material-components/material-components-web/tree/v6.0.0/packages/mdc-select) for select. You may be looking at the master branch which is the latest canary version.

Additionally, have you looked at the [changelog's v6 breaking changes](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#breaking-changes) to see if the issues you're seeing are intentional breakages? Most of those breaking changes have short instructions for what to do to upgrade.
