### ISSUE TITLE
Fix mdc demo site bugs for color specification

### ISSUE THREAD

**Issue by liquidx** [material-components/material-components-web#608]
When the accent color is set to green, it seems like the ripples are purple instead of green.

I can see this in the Ripple example (at the bottom). I expect it to be green.

![screen shot 2017-05-09 at 1 56 17 pm](https://cloud.githubusercontent.com/assets/72062/25864970/543e7714-34bf-11e7-8390-9d2621ae51fe.png)

**Comment by amsheehan** [comment]
We use custom theme variables to style ripples. One thing we can do is update the demos so that they use SASS. 

Here is more info on why you're getting a very easter-y ripple color: https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple#caveat-theme-custom-variables

**Comment by traviskaufman** [comment]
To clarify, the work to be done here is:

- [ ] Convert `demos/demos.css` to `demos/demos.scss`
- [ ] Make `demos.scss` buildable by sass/webpack such that the demos change the scss theme vars, import `material-components-web`, and then add whatever custom CSS is already present
