### ISSUE TITLE
mdx-text-field

### ISSUE THREAD

**Issue by Silly-V** [material-components/material-components-web#6133]
### Steps to reproduce
Not sure.

### Actual behavior
Text area does not have a purple outline when focused.
It has some different CSS working on it that did not affect it the same way before.

### Expected behavior
Text area component should have rounded borders and purple outline when focused, also min-height wasn't applied before so I could override it without using !important.

### Screenshots
Before today, text field used to look like this:
![image](https://user-images.githubusercontent.com/11342704/85470707-07824380-b575-11ea-9218-8a604cf3bc58.png)

Now it looks like this:
![image](https://user-images.githubusercontent.com/11342704/85470759-149f3280-b575-11ea-9780-b29ff2551b33.png)

### Solution

Including css/script versions for *5.1.0* corrects the issue and now it displays as expected:
![image](https://user-images.githubusercontent.com/11342704/85471353-f423a800-b575-11ea-9911-844d9e5a5995.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | latest (? 06232020)
| Browser          | Chrome
| Operating System | Windows 10

**Comment by asyncLiz** [comment]
The latest version of MDC on 6/23/2020 is v7.0.0. There have been several breaking changes to textfield's DOM structure since v5.1.0. Notably, this looks like a textarea, which now requires specifying the `mdc-text-field--outlined` class as well.

I'd recommend reading through the [CHANGELOG](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md) for the breaking changes and upgrading your components accordingly. 

If you are pulling the project from a CDN such as https://unpkg.com, avoid using the `latest` version and instead lock it to a specific version. This will avoid breaking changes in the future.

**Comment by Silly-V** [comment]
Ok, fair enough.
