### ISSUE TITLE
[mdc-menu] v7.0.0 Arrows keys navigation don't work

### ISSUE THREAD

**Issue by ma-5** [material-components/material-components-web#6168]
## Bug report
Opened menu list items can't select by Arrow Top Arrow Bottom keys

### Steps to reproduce
1. Go to demo page, https://material-components.github.io/material-components-web-catalog/#/component/menu , Navigation by arrow top, arrow bottom keys doesn't work
2. press TAB key to open menu toogle button
3. Navigation by arrow top, arrow bottom keys 

### Actual behavior
Navigation by arrow top, arrow bottom keys doesn't work

### Expected behavior
Select menu list item by arrow keys

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0 |
| Browser          | all |
| Operating System | all |

**Comment by allan-chen** [comment]
Hi,

Thanks for opening the issue. A couple of things here:

- The most likely root cause: if you recently upgraded from an earlier version of MDC, please ensure that the each list item `<li>` has a `<span class="mdc-list-item__ripple">` as its first child. There was a recent refactor that moved the ripple into its own element, and not including the element would prevent the ripple from showing up.
- Optionally, you can use the `setDefaultFocusState()` method on the menu component to focus the first item upon menu open if desired. [Here's](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu#accessibility) the doc's recommendation on where default focus state should go depending on whether the menu button had a click or keydown event.
- Our catalog is still at v4.0 I believe. We will prioritize updating it to the latest version.

Let me know if you have any further questions!

**Comment by allan-chen** [comment]
Here's a codepen example:

https://codepen.io/allanchenmdc/pen/gOPXPyE

**Comment by ma-5** [comment]
Thanks Works nice
