### ISSUE TITLE
Selects missing from documentation?

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6201]
## Bug report
Since the 7.0.0 release I'm unable to find the documentation for Select controls. Is your menu missing one or more items?

### Steps to reproduce
1. Go to https://material.io/develop/web
2. "Select" is missing under the "Components" menu item

**Comment by asyncLiz** [comment]
Thanks for the bug!

We've reported the issue to the material.io team (Googlers: b/161009363)

In the meantime, if you click on the search icon in the app bar and search for "select", you should be able to find a link to the documentation page: https://material.io/develop/web/components/input-controls/select-menus

**Comment by simonziegler** [comment]
Hi @asyncLiz thanks for this. I managed to find that link (by hacking around). I think the content relates still to Material Theme 6.0.0. For now I'm directly using https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/README.md.

One note on the readme: it tantalisingly references `isTypeaheadInProgress()` and `typeaheadMatchItem` but has no example of how to use a typeadhead. It would be great to know how to do this because I have a rather hacked together typeahead at the moment that I could do with throwing away in favour of something far better.

**Comment by asyncLiz** [comment]
Thanks for the info, I'll include that in our bug to the material.io team so they can get it updated.

My recommendation would be to use the branches/tags dropdown in the top-left corner of GitHub to select the correct version, since the default `master` branch may contain changes that are not present in the version you have installed. v7's documentation is available here: https://github.com/material-components/material-components-web/tree/v7.0.0/packages/mdc-select

**Comment by simonziegler** [comment]
Thanks @asyncLiz. I think I'll migrate from the material.io docs to those on github for everything I reference, and your point about tags is well noted.
