### ISSUE TITLE
[TextField] Clicking of leading or trailing icon triggers focusout of textfiled 

### ISSUE THREAD

**Issue by Sourav-21** [material-components/material-components-web#6209]
## Bug report
Leading and Trailing icons are the parts of TextField. If I click on those icons TextFiled should preserve its previous focus state. Suppose I have a text filed for password and there is trailing icon button for showing the password. After typing the password, if I click on that show button, text filed loses its focus. But it isn't following the Material Design guideline.

### Steps to reproduce
1. Set a leading/trailing icon for the text field.
2. Type something in the text field. And the text field is now in focused state.
3. Click on the trailing icon.
4. Text filed loses its focus. 

### Expected behaviour
Text filed should be in focused state if I click on textField icon.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0
| Browser          | Chrome 83
| Operating System | Windows 10

**Comment by asyncLiz** [comment]
This is working as intended on the web. When an icon in a text field is actionable (such as the visibility icon for a password), it has its own focus state. Clicking on the icon will change the focus from the input to the icon.

If this is undesirable in your use case, you can always add a click listener to re-focus the input after the icon is clicked to shift the user's focus back to the text field. This can be a common pattern with certain trailing actions such as a delete icon that clears a text field for new entry.

However, that should be up to each individual use case and the user setting up the text field and its icon, which is why clicking an actionable icon does not re-focus the text field by default.
