### ISSUE TITLE
[mdc-textfield] readme omission

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6269]
## Bug report
The [mdc-textfield readme](https://github.com/material-components/material-components-web/tree/v7.0.0/packages/mdc-textfield) is missing a reference to the `outlined-textarea-density` SASS mixin.

As a question: is there a reason that there is no mixin for a filled text areas with leading icons? This puts filled text areas at odds with outlined ones, and both filled and outlined [mdc-selects](https://github.com/material-components/material-components-web/tree/v7.0.0/packages/mdc-select#sass-mixins).

Thanks!

**Comment by asyncLiz** [comment]
Thanks for the bug! We'll get that added to the readme.

Text areas do not support icons, which is why there are no mixins for text areas with icons. If you're asking about a single line filled text field with icon, there are currently no extra special requirements for the filled text field with leading icon compared to without it. The `textfield.density()` mixin may be used for filled text fields with and without leading icons.

Outlined text fields have different styling requirements for density depending on whether or not they have a leading icon. This is due to the fact that they have different animation styling requirements.

Similarly, the filled select has different styling requirements for density depending on whether or not it has an icon. This is because the select leading icon will change size based on density, and that affects the position of the floating label.

Select is a newer component that has been written to be more aligned with the latest Material spec guidelines, while text field is a slower-to-update component since it's widely used. It has a similar requirement where icons should be resizing to density changes. When this is implemented, it will likely need a separate mixin for filled text fields with leading icons.

**Comment by simonziegler** [comment]
Thanks @asyncLiz. I did of course mean the one line text fields and your explanation was interesting. Thanks!
