### ISSUE TITLE
Make a :host() -aware sass mixin

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#6295]
## Feature Request

For theming we often have to do a pattern like this

```
@mixin {
  &:hover {
    --some-custom-prop: blue;
  }
}
```

The problem is that the `&` selector will not work as intended if the mixin is used inside of a `:host` selector. This would result in `:host:hover` which is incorrect; it should be `:host(:hover)`.

### Proposed solution

Liz made a simple solution that only so far supports `:host` and not `:host(...)`

https://www.sassmeister.com/gist/c61e05d5f5a20c8c8cd6d27c4c1fe03b

### Alternatives considered

We tried asking users if "in root" but it's leaky

**Comment by asyncLiz** [comment]
As part of this we should file an internal bug with the Sass team and ask for guidance.

I doubt this will become a feature that is natively supported, but we can ask if it'll be reconsidered since the last conversations were from several years ago. Historically there are some issues that provide good context to why adding this is a [bad idea](https://github.com/sass/sass/issues/1436#issuecomment-56225206) in Sass:

- https://github.com/sass/sass/issues/1436
- https://github.com/sass/sass/issues/2354

However there is a good issue thread (https://github.com/sass/sass/issues/1425) about supporting trailing parent selectors (`selector&`) that gives some context to strategies around problems like this.

An internal bug with the Sass team will give them a heads up about what we're trying to do, our use case, and they may be able to give us some guidance and direction on a best approach/solution.
