### ISSUE TITLE
[mdc-drawer] Empty area if resize Drawer to fit content

### ISSUE THREAD

**Issue by redradist** [material-components/material-components-web#6318]
## Bug report
I have playing with Blazor binding for Material Components named MatBlazor and by some reason when I change size of 
aside tag (Drawer) between aside tag and content appear white space area

### Steps to reproduce
You can find issue in playground blazorfiddle.com:

https://blazorfiddle.com/s/bfr7ox9x

### Actual behavior
White area appear

### Expected behavior
There should not be white empty area

### Screenshots
![image](https://user-images.githubusercontent.com/6311799/89033497-8b330b00-d33f-11ea-8e4f-8760523811d1.png)

### Your Environment:
MatBlazor Firefox

**Comment by redradist** [comment]
Seems like fix for this issue was done https://github.com/material-components/material-components-web/pull/3459/files

But how to use custom drawer width in raw css ?

**Comment by patrickrodee** [comment]
Hey Denis, thanks for filing this bug. We provide [Sass](https://sass-lang.com/) mixins as the primary interface for customizing our components. We do provide a Sass mixin for [customizing drawer width](https://github.com/material-components/material-components-web/blob/fbb1381e1474d84e6066a85a307bcb1d876c543f/packages/mdc-drawer/_mixins.scss#L436) that you can use.

I'm going to close this since it appears your bug has been fixed but feel free to reopen it if you have any questions.

**Comment by redradist** [comment]
> 
> 
> Hey Denis, thanks for filing this bug. We provide [Sass](https://sass-lang.com/) mixins as the primary interface for customizing our components. We do provide a Sass mixin for [customizing drawer width](https://github.com/material-components/material-components-web/blob/fbb1381e1474d84e6066a85a307bcb1d876c543f/packages/mdc-drawer/_mixins.scss#L436) that you can use.
> 
> I'm going to close this since it appears your bug has been fixed but feel free to reopen it if you have any questions.

@patrickrodee How to use it without Sass ? For example in raw css ? Is it possible at all ?

**Comment by patrickrodee** [comment]
@redradist Sass is our primary style customization API. We don't support setting the `width` of a drawer outside of Sass.

**Comment by redradist** [comment]
> 
> 
> @redradist Sass is our primary style customization API. We don't support setting the `width` of a drawer outside of Sass.

@patrickrodee Okay, got it !!
Can you help, I should do something like this:
```scss
.mat-drawer-custom {
  @include width(max-content);
}
```

But what is the name space for `width` ?

**Comment by redradist** [comment]
> 
> 
> @redradist Sass is our primary style customization API. We don't support setting the `width` of a drawer outside of Sass.

@patrickrodee I have successfully used sass with width and it works, but there is one issue ...

width do-not work with `max-content` property for width !!

In such way I have to hard-code value of width instead of rely on content size ... it make working little bit not convenient

**Comment by redradist** [comment]
@patrickrodee Also seems like I cannot change width dynamically ...

I have generated two Drawer classes with different width, but when I apply it dynamically Drawer just disappear ... (

**Comment by asyncLiz** [comment]
The drawer needs an explicit width. `max-content` does not work because that CSS property is invalid for `margin`, which the drawer needs to set for the app's content.

Dynamic and runtime theming support will be added in https://github.com/material-components/material-components-web/issues/5242 via custom properties.

**Comment by redradist** [comment]
> 
> 
> The drawer needs an explicit width. `max-content` does not work because that CSS property is invalid for `margin`, which the drawer needs to set for the app's content.
> 
> Dynamic and runtime theming support will be added in #5242 via custom properties.

@patrickrodee @asyncLiz 
Okay, got it !! )
But its sad because React components https://material-ui.com/components/ allows me easily to manipulate width of the Drawer ... I will wait for this feature ...

But also I see some artifact when drawer goes out it I see right border of the Drawer goes after white area in background ...

I mean that I first see white area goes out little-bit then Drawer, seems like it is possible to fix with transisions like it is done in React components https://material-ui.com/components/

**Comment by asyncLiz** [comment]
Keep in mind that there are reasons to why we've chosen certain implementations.

The React Material UI components are a fantastic implementation, and I'd encourage you to use them if they fit your app's needs more appropriately. One reason the MDC drawer does not animate the same way as Material UI is due to performance.

MUI's drawer animates the margin and width properties of the content and drawer. This achieves a silky smooth effect of the persistent drawer "pushing" and "pulling" the content, but animating these properties comes at a heavy performance cost: they trigger CSS layout updates.

For simple demo UIs that only show a few elements and text, it's hard to notice anything. In real world applications, this translate to less than 60fps as the drawer animates and the page struggles to keep up with the constant forced re-layouts.

While we would love to achieve a similar silky smooth effect, on the web we don't have a great solution yet and performance is a more critical metric.

**Comment by redradist** [comment]
> 
> 
> Keep in mind that there are reasons to why we've chosen certain implementations.
> 
> The React Material UI components are a fantastic implementation, and I'd encourage you to use them if they fit your app's needs more appropriately. One reason the MDC drawer does not animate the same way as Material UI is due to performance.
> 
> MUI's drawer animates the margin and width properties of the content and drawer. This achieves a silky smooth effect of the persistent drawer "pushing" and "pulling" the content, but animating these properties comes at a heavy performance cost: they trigger CSS layout updates.
> 
> For simple demo UIs that only show a few elements and text, it's hard to notice anything. In real world applications, this translate to less than 60fps as the drawer animates and the page struggles to keep up with the constant forced re-layouts.
> 
> While we would love to achieve a similar silky smooth effect, on the web we don't have a great solution yet and performance is a more critical metric.

@asyncLiz Actually I cannot get why you are care abount perfomance for Drawer that is in common case is shown up only on click user ...
If user continuously open/close Drawer it could affect performance, but in common case it will not ...

**Comment by redradist** [comment]
> While we would love to achieve a similar silky smooth effect, on the web we don't have a great solution yet and performance is a more critical metric.

@asyncLiz You can use custom css properties to allow developer to enable optional animation

**Comment by asyncLiz** [comment]
Opening a persistent drawer, even just once, can cause a page with a lot of content (especially high render cost content such as animating content or video) to lag and suffer in performance.

Performance and reliability is one of our top priorities, but every app has its own concerns. Feel free to fork our library and make tweaks for your own drawer variant that fits your needs!

**Comment by redradist** [comment]
> 
> 
> Opening a persistent drawer, even just once, can cause a page with a lot of content (especially high render cost content such as animating content or video) to lag and suffer in performance.
> 
> Performance and reliability is one of our top priorities, but every app has its own concerns. Feel free to fork our library and make tweaks for your own drawer variant that fits your needs!

@asyncLiz  Okay, why not to add option ?
If user want cool animation or best performance ?
