### ISSUE TITLE
[mdc-text-field] Outlined <input> element mis-sizing with large border radius

### ISSUE THREAD

**Issue by simonziegler** [material-components/material-components-web#6362]
## Bug report
Outlined text fields with a large border radius have a mis-calculation on the width of the `<input type="text" class="mdc-text-field__input" ...` element. This element is too wide meaning that it has zero padding/margin on its right hand side against its parent `<label class="mdc-text-field mdc-text-field--outlined">` element.

### Steps to reproduce
1. Go to https://blazormdc.com/textfield and scroll to the bottom of the page.
2. Type something long like "Lorem ipsum dolor sit amet, consectetur adipiscing elit." into the two text fields with the "Default Density" label as below - so far so good with zero border radius
![image](https://user-images.githubusercontent.com/11708435/89988041-dec62280-dc76-11ea-8eb7-28cfb78aa1d1.png)
3. Click on the scroll icon button to the top right of the top app bar and select "Red Rounded Theme"
4. See the result below where the outlined text field on the right looks awkward
![image](https://user-images.githubusercontent.com/11708435/89988165-07e6b300-dc77-11ea-8710-3eef0d46c299.png)

### Actual behavior
Poor alignment of the right and side of the `<input ...` element

### Expected behavior
Good spacing of the right hand side of the `<input ...` element to mirror that of the left hand side.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 7.0.0 |
| Browser          |  Chrome, Edgium and Firefox |
| Operating System | Windows 10 |

### Further Information:

The "Red Rounded" theme's Sass variables can be found [in our repo (click here)](https://github.com/BlazorMdc/BlazorMdcWebsite/blob/main/BlazorMdcWebsite.Components/Styles/red-round-variables.scss) as:

```scss
@use '@material/theme/color-palette' as cp;

$mdc-theme-primary: cp.$red-800;
$mdc-theme-secondary: cp.$cyan-300;
$mdc-theme-background: cp.$grey-200;

$mdc-typography-font-family: unquote("Merriweather, serif");
$mdc-typography-styles-button: ( font-size: 14px, font-weight: 400, letter-spacing: 0.05em, );

$mdc-typography-styles-headline1: ( font-family: unquote("Shrikhand, serif") );
$mdc-typography-styles-headline2: ( font-family: unquote("Shrikhand, serif") );
$mdc-typography-styles-headline3: ( font-family: unquote("Shrikhand, serif") );
$mdc-typography-styles-headline4: ( font-family: unquote("Shrikhand, serif") );
$mdc-typography-styles-headline5: ( font-family: unquote("Shrikhand, serif") );
$mdc-typography-styles-headline6: ( font-family: unquote("Shrikhand, serif") );

$mdc-shape-small-component-radius: 50%;
$mdc-shape-large-component-radius: 50%;
```

**Comment by asyncLiz** [comment]
I noticed in your stylesheet that several rules are missing for the outlined shape styles. Notably the shape custom property declarations are missing (I only see the fallback declarations) and the `padding-right` declaration (which is the problem that you're seeing) is also missing.

That declaration uses `max()` and is wrapped in an `@supports` query. That, plus the other missing styles, is leading me to suspect that `clean-css` is the problem here. We've encountered this before internally where that tool was stripping styles.

I would try removing the `clean-css` step from your build process first and see if that resolves the issue. If it does, you can then move forward and try to configure the utility more granularly for what you need.

We use duplicate fallback declarations to support browsers that do not support CSS custom properties like IE11. If you do not need to support those browsers, you can turn off all duplicate declarations from being generated:

```scss
// Include at the top of mt-default-theme.scss
// Note that in the next release, this is changing to $enable-fallback-declarations in @material/theme/css 
@use '@material/theme/custom-properties' with ($ie-fallback: false);
```

Otherwise, configure `clean-css` not to strip duplicate properties (they're only there in our CSS if they need to be for a specific purpose).

Next, make sure `clean-css` doesn't remove `@supports` queries or `max()` declarations.

There may be other optimizations that the tool performs that cause side effects with our code. If you encounter similar issues to this in the future, I'd suggest temporarily turning it off and seeing if that fixes whatever weird problem you're encountering. If it does, dig deeper into the stylesheet before/after `clean-css` and see what styles have been changed and what rules you need to configure/turn off to compensate.

**Comment by simonziegler** [comment]
Thanks so much for the help @asyncLiz. It's going to take me a while to step through this and get it all sorted out. Can I come back to you next week on it please?

**Comment by asyncLiz** [comment]
Sure thing. To help clear our untriaged issue list, I'm going to go ahead and close this for now since I believe we've identified the problem as `clean-css`. Feel free to re-comment next week if you're still having trouble and we can re-open it.

**Comment by simonziegler** [comment]
@asyncLiz thanks, and closing is a good plan. One question: does your public repo have an example of how you use `clean-css` that I cold reference please?

**Comment by asyncLiz** [comment]
We do not use `clean-css`. When we identified that tool as a problem in one of our internal projects, we disabled it and relied purely on Sass's built-in minification.

**Comment by simonziegler** [comment]
I just tested locally using the non minified version of the compiled scss files (compiled with dart-sass), and still get the same issue. I wonder therefore if the way we're using dart-sass is at fault? If we can fix that then I'm very happy to use dart-sass to create both minified and non-minfied css files. I'll then say goodbye to clean-css based on your recommendation that it gave you trouble.
