### ISSUE TITLE
Mark $mdc-theme-text-colors !default

### ISSUE THREAD

**Issue by gjdev** [material-components/material-components-web#645]
It would be really helpful if that variable was marked default.

I see the material design specs actually have very specific values for opacity levels, which are replicated in this map. However, I'm not entirely sure why those values are fixed. Even with maximal contrast between text and background, this may need to be tuned for different fonts to stay readable/accessible.

**Comment by yeelan0319** [comment]
Hi @gjdev , MDC used the defined text color with in [guideline - Dark text on light backgrounds](https://material.io/guidelines/style/color.html#color-usability). That's why the variable is not proper to be marked as `default` after we discussed.

However, you point definitely makes a lot of sense, I will forward this issue to our designer team as feedbacks from our community. Let's keep this in mind and follow up in the future.

**Comment by yeelan0319** [comment]
@gjdev Could you list a specific use case that you have in mind, our designer is trying to get more background about this request. More detail would be really helpful!

Thanks!

**Comment by yeelan0319** [comment]
I am closing this issue again since I haven't heard any reply.

**Comment by gjdev** [comment]
Yes sorry for the late reply. I am working against a few deadlines, so parked this until I could spend some time on preparing a few examples. Our issue was that the opacity levels, as defined in the material guidelines, don't seem to work for all fonts. We had a few pre-designs where text is becoming very difficult to read at lower opacity levels (we later switched to different fonts, so this isn't really an issue for our own designs anymore). If there is still interest from your designer to have a look at this, I can prepare a few example screenshots.
