### ISSUE TITLE
Control the ripple speed

### ISSUE THREAD

**Issue by danialbakhtiari3884** [material-components/material-components-web#6538]
## Feature Request

Hello
I have a suggestion that could be good, I feel it can be done. Slow wave playback in play mode and fast wave in reverse mode.

### Additional context

![ezgif com-gif-maker](https://user-images.githubusercontent.com/72765801/96355747-327b3f00-10f2-11eb-8feb-b7366aaa907a.gif)

**Comment by allan-chen** [comment]
Hello,

Thank you for the question. Since the ripple is quite a self contained element implemented to material spec we are unlikely to support speed customizations. However, feel free to modify the [constants](https://github.com/material-components/material-components-web/blob/43c1c5e2fc3b679ffa5ff60c0b624b2c812482ac/packages/mdc-ripple/constants.ts#L45) for activation/deactivation here (as well as the corresponding constants in the Sass stylesheets) and compile to see if the timing adjusts to your requirements.
