### ISSUE TITLE
Ripple surfaces stays colored when the click/touch event actually is start of drag/scroll

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#654]
Follow the template below to ensure the quickest and most accurate response to your issue.

### What MDC-Web Version are you using?

Current.

### What browser(s) is this bug affecting?

Probably all.

### What OS are you using?

Windows 10.

### What are the steps to reproduce the bug?

Use the demo page:
https://material-components-web.appspot.com/ripple.html

Start dragging on one of the ripple surfaces, the surface stays colored after releasing mouse/finger.
The issue is especially notable on touch screen, as dragging the page also is how you scroll. If you start scroll on a ripple surface, it stays colored.

### What is the expected behavior?

Drag event does not start ripple OR ripple effect fades out on mouse/finger release so that element is returned to initial state.

### What is the actual behavior?

Ripple surface stays colored on drag event after mouse/finger release.

**Comment by anton-kachurin** [comment]
This is not quite the same issue that is tracked in #196 but very similar to it: we need to define at what conditions ripples automatically get deactivated.

**Comment by j-o-d-o** [comment]
Not sure if I should post on here on or #196 , what is the difference between "active/deactive" and "focus/blur". I would think active=focus and deactive=blur.

**Comment by traviskaufman** [comment]
@anton-kachurin is right, this issue is being tracked in #196. As @sgomes mentioned in that issue, one workaround to this would `pointer-capture`, if supported by browsers. 

In terms of the current behavior, unfortunately the motion design around the ripple means that it deactivates on the "up" event of whatever interaction event initially activated it (e.g. `touchend`, `mouseup`, etc.), so we have to use that pattern.

In terms of language, *activate* refers to the _initial event which causes the ink ripple to first animate_, and *deactivate* refers to the _symmetric event which causes the ink ripple to dissipate_. E.g. "touchstart" and "touchend" are *activation/deactivation pairs*. We use this language as general terms to cover all of the possible interaction events that could trigger the ripple :p Focus and blur are a bit different because they can also happen not necessarily from direct interaction, e.g. when `focus()` is programatically called or a user re-focuses on a browser tab in which that element was focused when the user left. 

Let's continue this discussion in #196.
