### ISSUE TITLE
mdc-menu - overflow bug - regression of #2288

### ISSUE THREAD

**Issue by iteratelance** [material-components/material-components-web#6545]
#2288

https://github.com/material-components/material-components-web/issues/2288#issuecomment-712214566

**Comment by allan-chen** [comment]
Please use fixed menu positioning when using menu inside constrained environments (i.e. inside an overflow hidden parent). Please see the [docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-menu#fixed-position) here for more details.

**Comment by iteratelance** [comment]
For all those curious, fixed position also works.             

const menu = new mdc.menu.MDCMenu.attachTo(menuEl);
menu.setAnchorElement(event.target);
menu.setFixedPosition(true);

**Comment by GPla** [comment]
This is broken in the latest release because of `will-change:transform` that is applied to the (deprecated) list-item by the ripple. `will-change: transform` (see [here](https://stackoverflow.com/a/52937920/7938503)) results in the creation of a new containing block and, thus, `position:fixed`  is not anchored to the viewport but to the (deprecated) list-item instead. It will be clipped by the list-item. 

To fix this, globally apply `* { will-change: auto !important }` as CSS style and apply `mdc-ripple-surface` on the `mdc-deprecated-list-item` instead of using `<span class="mdc-deprecated-list-item__ripple"></span>` for the menu items.
