### ISSUE TITLE
mdc-data-table pagination select does not show full number

### ISSUE THREAD

**Issue by DouglasRiddle** [material-components/material-components-web#6599]
## Bug report
When using the new data-table pagination with 8.0 the "Rows per page" select shows "..." instead of the selected value.

### Steps to reproduce
See [this codepen](https://codepen.io/DouglasRiddle/pen/YzWRGOV) based on [this documentation](https://github.com/material-components/material-components-web/tree/d6b5cd4181d0bf11b598b5ca142343fbc87976b9/packages/mdc-data-table#data-table-with-pagination)

### Actual behavior
Pagination select shows "..." instead of "Rows per page" selected value

### Expected behavior
Show "10"

### Screenshots
![image](https://user-images.githubusercontent.com/42001902/98697541-a946d900-233a-11eb-98c1-f7bc73d51d9c.png)

**Comment by simonziegler** [comment]
The pagination also displays poorly on a mobile device, with the `mdc-data-table__pagination-total` element overflowing beyond the left hand side of the device in portrait mode.

**Comment by allan-chen** [comment]
Hi,

Thanks for reaching out. The misalignment of the selected text is a docs issue - the docs for datatable in 8.0 weren't updated to reflect the new select markup. I'll send a PR shortly for this.

For the ellipsis, it appears that the styles for density don't seem to be applying correctly in the generated css because the datatable styles are emitted before the standalone select's styles, not after. We'll investigate.

**Comment by DouglasRiddle** [comment]
@allan-chen, thanks for the update. I will keep an eye out for the updated docs, but I would appreciate it if you would give a heads-up here as well in case I miss the update.

**Comment by allan-chen** [comment]
@DouglasRiddle the fix is in flight. The style ordering can be worked around for now (until next release) by separately importing the datatable styles ([unpkg link](https://unpkg.com/@material/data-table@8.0.0/dist/mdc.data-table.min.css)), but otherwise it should just be a markup change.

[Here's](https://codepen.io/allanchenmdc/pen/wvzWObx) the updated codepen with the changes above applied.
