### ISSUE TITLE
[MDCList] Can't initialize a checkbox list

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6640]
## Bug report
I have this error when I try to add a checkbox list. The markup is copied from https://github.com/material-components/material-components-web/tree/master/packages/mdc-list#list-with-checkbox-items

Codepen: https://codepen.io/maicol07/pen/BazXxqM (try to open the dialog with the list item and try to use the list inside the dialog)

Note that I have this issue only when the list is inside a dialog which is inside another list

### Actual behavior
Error when list is initialized

### Expected behavior
List is initialized without errors

### Screenshots
Console error:
![immagine](https://user-images.githubusercontent.com/9463142/100003707-d083b880-2dc6-11eb-9d3a-1e95aad23172.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0
| Browser          | Firefox
| Operating System | Windows 10

### Workaround until a fix
Add the dialog after the list

**Comment by sayris** [comment]
Hi!

Apologies that this fell through the cracks and hasn't been addressed for so long. Is this still giving you issues, the attached codepen is working for me (opened in firefox on windows 10 and chrome on chromeOS)

**Comment by asyncLiz** [comment]
Separate lists should not be nested within each other. The problem presents itself since the parent list recognizes the child list's checkbox items and believes they are its own list items. 

I would recommend changing the DOM structure of your example, since the `mdc-dialog` element with its child list does not need to be a child of the parent list with the button that displays the dialog.

You can move the dialog element away as a sibling of the list with the button and open the dialog normally when the button is clicked.
