### ISSUE TITLE
[Tooltip] Tooltip cannot be opened if anchor is a list element or something inside a list element

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6644]
## Bug report
Tooltip doesn't open when hovering a list element (tooltip is anchored to this list element)
Check the codepen: https://codepen.io/maicol07/pen/vYKowgQ

### Steps to reproduce
1. Create a list
2. Create a tooltip
3. Create a list element and anchor the tooltip to it

### Actual behavior
Tooltip doesn't open on hover

### Expected behavior
Tooltip opens on hover

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0
| Browser          | Firefox
| Operating System | Windows 10

**Comment by sayris** [comment]
Hi, thanks for the question (and codepen)!

Looks like the issue is that the HTML for the tooltip element is nested underneath the `<li>` tag, rather than as a direct child of the `<body>` element (mentioned in the docs [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tooltip#tooltips)).  Unfortunately, some of the styling for the MDC list interferes with that of tooltip and so it's not shown when nested under `<li>`. Restructuring the html as follows works for me:

```
<ul class="mdc-list">
  <li class="mdc-list-item" aria-describedby="tooltip-id">
    <span class="mdc-list-item__ripple"></span>
    <span class="mdc-list-item__text">Hover on me</span>
  </li>
</ul>
<div id="tooltip-id" class="mdc-tooltip" role="tooltip" aria-hidden="true">
  <div class="mdc-tooltip__surface">
    lorem ipsum dolor
  </div>
</div>
```

Codepen: https://codepen.io/shws/pen/vYXOywR

Let me know if you have any other issues!
