### ISSUE TITLE
[MDCSelect] Overflow MDCSelect menu in MDCDialog

### ISSUE THREAD

**Issue by DouglasRiddle** [material-components/material-components-web#6735]
## Bug report
I need to overflow a ```MDCSelect``` menu within a ```MDCDialog``` object but still want my select menu width to match the select component width. The resolution in #5590 is to set a custom width on both the anchor and menu, however I do not think that will work in my case as I have dynamic component widths using ```mdc-layout-grid``` and ```width: 100%```.

### Steps to reproduce
[Example CodePen of the issue](https://codepen.io/DouglasRiddle/pen/mdrLxro)

### Actual behavior
Fixed MDCSelect menu width does not match component

### Expected behavior
Fixed MDCSelect menu width matches component width

### Screenshots
![image](https://user-images.githubusercontent.com/42001902/103675881-0f6c6880-4f46-11eb-9a88-eaef736724cc.png)

### Your Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | v9.0.0
| Browser          | Chrome
| Operating System | Windows

### Additional thoughts
I agree with [DimaChaichan](https://github.com/material-components/material-components-web/issues/5590#issuecomment-588370098) in that using a fixed position is not a good fix as it introduces a separate issue as the menu position is not updated when the dialog content scrolls.

**Comment by allan-chen** [comment]
Hi Douglas,

Thanks for reaching out regarding this issue. Unfortunately this is a caveat of using fixed positioning. Some suggestions for workarounds, ordered by complexity:

1.  Make the dialog always mobile-friendly instead of consuming additional space on larger viewports, such that no dynamic width adjustments need to be made.
![image](https://user-images.githubusercontent.com/7828061/104059468-45aa2200-51aa-11eb-9c91-72ba307d1764.png)
2. Using a resize observer to adjust the menu width when anchor width changes. Here's an [example in another component](https://github.com/material-components/material-components-web/blob/9c8a70a23c31827d77dca6dff9d39fccb8604fda/packages/mdc-linear-progress/foundation.ts#L75).

**Comment by DouglasRiddle** [comment]
@allan-chen, thanks for the response. Since the resize observer is already being used in another material design component does it make sense to add one for this component/use case rather than asking users to implement it individually?

**Comment by allan-chen** [comment]
I can discuss with the team whether this is something we would want to support. It is a relatively niche corner case where layout workarounds exist, and setting styles in TS may not be the best approach here. I would suggest considering the first approach above if feasible and trying out a more compact dialog.

**Comment by DouglasRiddle** [comment]
Okay. Thanks again for the communication on this. I'll leave it up to you if you want to leave this issue open for tracking or go ahead and close it.
