### ISSUE TITLE
[textfield] textarea handle not properly themed for dark theme on firefox

### ISSUE THREAD

**Issue by rebootl** [material-components/material-components-web#6783]
## Bug report

On firefox the textarea handle is not properly themed when a dark background is used.

Maybe I'm missing a mixin or something?

Demo:

https://codepen.io/rebootl/pen/ZEpdpJx

Thx.

### Screenshots

![image](https://user-images.githubusercontent.com/3398507/105643484-6784f380-5e90-11eb-9d91-9fac64a08415.png)

### Your Environment:

Browser: firefox (latest)
OS: Arch Linux/Linux

**Comment by asyncLiz** [comment]
Unfortunately on some older versions of Firefox and some Linux distributions, the resize handle still uses the previous non-transparent image instead of a transparent one, resulting in this effect. I'd recommend checking to see if there are any updates to Firefox or your OS to see if that resolves the issue.

Here is the original bug from Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=554810

On other Linux distributions, OS X, and Windows, the resize handle is transparent (similar to Chrome).

**Comment by rebootl** [comment]
Thanks for your reply.

I just re-tested on Ubuntu 20.04 with firefox 84.0.2 (latest I think), as well as Arch Linux (rolling release) with firefox 84.0.2.

Sorry I was a bit lazy with the versions in my original report, mb.

![image](https://user-images.githubusercontent.com/3398507/105760479-28b77200-5f52-11eb-8395-e827df82375d.png)

When I add a plain `<textarea>` element with a backround color, it does not happen, as u can see in the screenshot. I added it in the codepen.

I'll try to debug it further, but I'm not sure if I can figure it out. Any ideas welcome.
Thx

**Comment by asyncLiz** [comment]
The actual element in question is a container element with the `resize` CSS property set, not a `<textarea>`. You can reproduce the effect sans-textarea with the following markup:

```html
<style>
  #resize {
    width: 250px;
    height: 56px;
    border: 1px solid black;
    background: darkgray;
    resize: both;
    overflow: hidden;
  }
</style>
<div id="resize"></div>
```
That should give you an indication if your Firefox/OS combination is still using the old non-transparent resize handle image.

**Comment by rebootl** [comment]
Ohhh, omg, rip. Okay, thx, I'll try to report there then I guess.
