### ISSUE TITLE
How to Properly Space Form Elements

### ISSUE THREAD

**Issue by flyboarder** [material-components/material-components-web#682]
Hello,

Is there a component which properly spaces form element like in the spec demos?

https://material.io/guidelines/components/text-fields.html#text-fields-layout
-- or --
https://material.io/guidelines/components/text-fields.html#text-fields-field-types

<img width="485" alt="screen shot 2017-05-18 at 4 08 17 pm" src="https://cloud.githubusercontent.com/assets/147004/26225407/4977c85e-3be4-11e7-8ee7-0d90b847fc58.png">

Goal-ish:
https://codepen.io/tutsplus/pen/avbNMM

**Comment by anton-kachurin** [comment]
I think left and right margins could be implemented in the MDC Component plus, maybe, `width: 100%`, but things like placing two elements side by side should be addressed in application CSS rather than via some special MDC Component.

If you're writing a responsive application, sometimes you want textfields to stack up (on a smaller screen) and sometimes to be inline (on a bigger one), and choosing proper breakpoints is up to you.

**Comment by Touficbatache** [comment]
You could make the textfields full-width so it takes all the width of the card.

**Comment by yeelan0319** [comment]
@anton-kachurin is right. We only provided minimal needed style for MDC component and encourage user to override any style they need to customize. It seems that you need a stacked form field, that should be defined at application level.
