### ISSUE TITLE
[MDCDrawer] REOPEN/CRASH/REGRESSION: FocusTrap: Element must have at least one focusable child

### ISSUE THREAD

**Issue by regnaio** [material-components/material-components-web#6829]
https://github.com/material-components/material-components-web/issues/6825 was closed. I should have provided more information or a repro

Reopening with a repro:

Please make sure the **console log** is opened and **refresh** so the crash can be viewed

## v10.0.0 crash: https://codepen.io/regnaio/pen/mdOEBzq

![Screenshot (1918)](https://user-images.githubusercontent.com/65579333/107281634-c3ae5280-6a0e-11eb-8734-8a9356ccdb79.png)

## v9.0.0 good (no crash): https://codepen.io/regnaio/pen/VwmjrZM

The code comes directly from the documentation: https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

**Comment by sayris** [comment]
Hi!

Can you specify what browser/machine you're using? Unfortunately, I'm unable to reproduce using Chrome + pixelbook (I made sure to refresh after opening the devtools console)

![screenshot_noerror](https://user-images.githubusercontent.com/6932089/107699847-aaaed700-6c84-11eb-9417-97ee43e8296c.png)

**Comment by steven-cole-elliott** [comment]
Thanks for looking into this!

If helpful, I'm also experiencing this issue after upgrading from 9.0.0 to 10.0.0.

I'm experiencing it after opening the MDCDrawer on Chrome Version 88.0.4324.150 (Official Build) (x86_64) on MacOS Big Sur Version 11.2.1 (20D74).

**Comment by regnaio** [comment]
Thank you for following up @sayris and @steven-cole-elliott! I see this on:

Windows 10 Pro, ThinkPad T470p:
* Chrome: Version 88.0.4324.150 (Official Build) (64-bit)

macOS 11.0 Big Sur, MacBook Pro (2018):
* Chrome: Version 88.0.4324.150 (Official Build) (x86_64)
* Safari: Version 14.0

**Comment by allan-chen** [comment]
Thanks for providing these details. Some notes: on macOS Chrome 88 I can reproduce the difference between the v9 codepen and v10. Drawer code didn't change between the releases, so changes to the list component may be worth taking a look. Stubbing the canary releases for commits in the range between v9 and v10 into the codepen would probably shed some light.

**Comment by regnaio** [comment]
The regression occured somewhere between v9.0.0 and v10.0.0-canary.776c18681.0

This seems to correspond with the v9.0.0 commit: 555aecc

and the 776c186 commit: 776c186

Though, I'm unsure in which exact commit the regression was introduced

**Comment by steven-cole-elliott** [comment]
FWIW, I did some more investigating, and the issue seems to be stemming from this bit in the mdc-list's `component.ts` file:

https://github.com/material-components/material-components-web/blob/71e615bc8fa757d22190641db0c2940e24bdf59b/packages/mdc-list/component.ts#L147

where the `tabindex` values of any focusable elements - `a` tags in my case - are forceably set to `-1`.

In the particular case of the `MDCDrawer`, this means that when focus trap tries to do its thing within mdc-dom's `focus-trap.ts`, it doesn't find any focusable elements, due to 

https://github.com/material-components/material-components-web/blob/71e615bc8fa757d22190641db0c2940e24bdf59b/packages/mdc-dom/focus-trap.ts#L128

expecting the `tabindex` to be greater than or equal to 0.

I don't like being the "here's the problem" guy without a solution, but I don't have a handle for how impactful changes to how focus trap works would be, though I'm guessing potentially quite large, so I can't reason intelligently at this point about how that might need to change, or if that is even the place that needs to change.

I think @regnaio may have mentioned something about bringing back the focus sentinel wrapping in the issue that preceded this one, so maybe that is what's needed?

**Comment by regnaio** [comment]
Just wanted to copy and paste some debugging notes from the duplicate (https://github.com/material-components/material-components-web/issues/6843) closed above:

When opening a MDCDrawer, this crash occurs

I'm just using the **modal navigation drawer** example from https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

Observe that when the drawer is opened, v8.0.0 surrounds the `mdc-drawer__content` with `mdc-dom-focus-sentinel` with `tabindex="0"`, as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
    <div class="mdc-drawer__content">...</div>
    <div tabindex="0" aria-hidden="true" class="mdc-dom-focus-sentinel"></div>
</aside>
```

v10.0.0 forgets to do this surround, as shown below:

```
<aside class="mdc-drawer mdc-drawer--modal ...>
    <div class="mdc-drawer__content">...</div>
</aside>
```

Due to no wrapping with `tabindex="0"`, this causes `focusableEls.length === 0`, which causes the crash (source code below)

```
if (focusableEls.length === 0) {
    throw new Error('FocusTrap: Element must have at least one focusable child.');
}
```

Can we please bring back the behavior that wraps and does not crash?

**Comment by sayris** [comment]
Thanks everyone for your patience on this. I believe I identified the issue and have a fix in the pipeline.  

The issue seems to have come from [this commit](https://github.com/material-components/material-components-web/commit/766981c15a200b374a14c2ab80bf746824bf7434#diff-dfef8fa8cae3fd074732e4509dce4b785297266ba709bffc3aca1a0a3c192352) -- specifically the call to `MDCListComponent#layout` was updated to use a different selector to grab the focusable child elements. Rather than using: 
```
   .mdc-list-item button:not(:disabled),
   .mdc-list-item a,
   .mdc-list-item input[type="radio"]:not(:disabled),
   .mdc-list-item input[type="checkbox"]:not(:disabled)
```

it is using

```
   .mdc-list-item button:not(:disabled),
    a,
    input[type="radio"]:not(:disabled),
    input[type="checkbox"]:not(:disabled)
```
which results in certain list items themselves (rather focusable children of the list items) having their `tabindex` set to `-1`... which led to the `FocusTrap#getFocusableElements` not finding any focusable elements.

**Comment by mindaugasvcs** [comment]
> Thanks everyone for your patience on this. I believe I identified the issue and have a fix in the pipeline.
> 
> The issue seems to have come from [this commit](https://github.com/material-components/material-components-web/commit/766981c15a200b374a14c2ab80bf746824bf7434#diff-dfef8fa8cae3fd074732e4509dce4b785297266ba709bffc3aca1a0a3c192352) -- specifically the call to `MDCListComponent#layout` was updated to use a different selector to grab the focusable child elements. Rather than using:
> 
> ```
>    .mdc-list-item button:not(:disabled),
>    .mdc-list-item a,
>    .mdc-list-item input[type="radio"]:not(:disabled),
>    .mdc-list-item input[type="checkbox"]:not(:disabled)
> ```
> 
> it is using
> 
> ```
>    .mdc-list-item button:not(:disabled),
>     a,
>     input[type="radio"]:not(:disabled),
>     input[type="checkbox"]:not(:disabled)
> ```
> 
> which results in certain list items themselves (rather focusable children of the list items) having their `tabindex` set to `-1`... which led to the `FocusTrap#getFocusableElements` not finding any focusable elements.

How to reinit Focusable Elements after HTML fragment injection?
