### ISSUE TITLE
Icon for marking people as 'dead'

### ISSUE THREAD

**Issue by VanonckelenDieter** [material-components/material-components-web#6834]
## Feature Request
Is it possible to add any kind of icon that could be use to mark someone as 'PASSED_AWAY aka DEAD'? Thank you. Maybe a cross? Like FA-ICON.

**Comment by sayris** [comment]
We allow for arbitrary SVGs, so feel free to define your own icon and use it in the material components ([example for icon buttons](https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button#icon-button-toggle-with-svg)).

Otherwise the [Material Design Icon](https://github.com/google/material-design-icons) repo is the appropriate place to request new icons.

Thanks!
