### ISSUE TITLE
How to use it without ES modules?

### ISSUE THREAD

**Issue by Shyam-Chen** [material-components/material-components-web#685]
```js
// The browser test failed
// I don't know how to compile ES2015+ to ES5 (reserved ES modules).
import { MDCTemporaryDrawer } from '@material/drawer';

const drawerEl= document.querySelector('.mdc-temporary-drawer');

const drawer = new MDCTemporaryDrawer(drawerEl);
```

*-*:arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down: :arrow_down:*-*

```js
import '@material/drawer/dist/mdc.drawer';

const drawerEl= document.querySelector('.mdc-temporary-drawer');

// Uncaught ReferenceError: MDCTemporaryDrawer is not defined
const drawer = new MDCTemporaryDrawer(drawerEl);
// or
const drawer = new drawer.MDCTemporaryDrawer(drawerEl);
// or
const drawer = new mdc.drawer.MDCTemporaryDrawer(drawerEl);
```

```js
// OK
import * as drawer from '@material/drawer/dist/mdc.drawer';

const drawerMobile = new drawer.__moduleExports.MDCTemporaryDrawer(drawerMobileEl);

// or

import { __moduleExports as mdDrawer } from '@material/drawer/dist/mdc.drawer';

const drawerMobile = new mdDrawer.MDCTemporaryDrawer(drawerMobileEl);
```

**Comment by yeelan0319** [comment]
Hi @Shyam-Chen ,
I am not sure what exactly the problem is. If you have trouble loading modules, you can refer to our [REAME.md](https://github.com/material-components/material-components-web#javascript) or the ways we use webpack and babel to transpile our modules. 

Furthermore, it sounds like this is more about transpile ES2015 to ES5, which really not within the scope of MDC component. I highly recommend you search related questions or ask for help on stackoverflow.
