### ISSUE TITLE
[MDCSelect] material-components-web/CHANGELOG.md Missing important breaking change

### ISSUE THREAD

**Issue by hobbitronics** [material-components/material-components-web#6870]
The changelog failed to include this change:

@use "@material/button";

is used in the sass file instead of:

@include button.core-styles;
@use "@material/button/styles";

**Comment by asyncLiz** [comment]
I'm not entirely sure what mdc-select's changes has to due with mdc-button, since the two packages do not depend on each other.

If there was a gap in the changelog, I apologize! It's automatically generated from our commit messages, so we may have missed documenting a breaking change. We'll do our best to continue documenting breaking changes across components.

Closing this issue since there's no action item for us to take from it right now.

**Comment by hobbitronics** [comment]
> I'm not entirely sure what mdc-select's changes has to due with mdc-button, since the two packages do not depend on each other.
> 
> If there was a gap in the changelog, I apologize! It's automatically generated from our commit messages, so we may have missed documenting a breaking change. We'll do our best to continue documenting breaking changes across components.
> 
> Closing this issue since there's no action item for us to take from it right now.

Yeah, sorry about the confusion with button. There was a similar issue with the changelog in mdc-button so I just forgot which one I was talking about, lol. Anyways, It would be good to see these changes in the changelog for those upgrading.
