### ISSUE TITLE
Animation delay between switching tabs

### ISSUE THREAD

**Issue by Touficbatache** [material-components/material-components-web#690]
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

> Chrome for Android 58.0.3029.83

### What OS are you using?

Android 7.0

### What are the steps to reproduce the bug?

1. Go to http://material-components-web.appspot.com/tabs.html on a phone.
2. Tap on a different tab than the selected one.
3. Observe the component's behavior.

### What is the expected behavior?

The animation between tabs should be triggered in the same time as the tab was clicked.

### What is the actual behavior?

The animation takes place after clicking on the other tab by about 1 second.

### Any other information you believe would be useful?

Video demo of bug: https://youtu.be/DiMGN2ei4wo

**Comment by rockdriven** [comment]
It is and looks as normal behavior to me! click follow by the animated underline...

**Comment by Touficbatache** [comment]
Try it on a phone not a PC. The animation triggers after about a second.

**Comment by yeelan0319** [comment]
Hi @Touficbatache ,

This is by design but not a bug. According to this [article]:(https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)

> mobile browsers applied a 300-350ms delay between touchend and click while they waited to see if this was going to be a double-tap or not, since double-tap was a gesture to zoom into text

MDC-tab emit `MDCTab:selected` event on click. This introduce no delay on desktop, but might introduce delay on mobile devices if the mobile browser think it need to wait to differentiate the double tap action. 

There are a few known methods that can remove this delay as introduced in the above article:
- Add `<meta name="viewport" content="width=device-width">` to tell browser drop the delay
- [Fastclick](https://github.com/ftlabs/fastclick): a very light-weight lib to remove the delay using touch event

You could choose and pick depends on your needs.
