### ISSUE TITLE
[MDCTooltip] Rich tooltip has transparent border and wrapper size changes

### ISSUE THREAD

**Issue by DouglasRiddle** [material-components/material-components-web#6905]
## Bug report
The [rich dialog](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tooltip#rich-tooltip-example) has a transparent border, but the surface is much more opaque and the ```mdc-tooltip-wrapper--rich``` size changes when hidden vs hovered.

### Steps to reproduce
[codepen example](https://codepen.io/DouglasRiddle/pen/mdOjrJW)

### Actual behavior
Hidden tooltip (notice size of ```mdc-tooltip-wrapper--rich``` with black border)
![image](https://user-images.githubusercontent.com/42001902/109992488-ee6b8e00-7cd0-11eb-8de2-ac74bac14394.png)

Visible tooltip with transparent edges and changed size of ```mdc-tooltip-wrapper--rich```
![image](https://user-images.githubusercontent.com/42001902/109992546-fd524080-7cd0-11eb-9617-fcc2ce4fbae3.png)

### Expected behavior
I would expect the ```mdc-tooltip-wrapper--rich``` container to always be the height it becomes when the tooltip is visible and that the tooltip edges would match the tooltip surface opacity.

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |  v10.0.0 |
| Browser          | Chromium and Firefox |
| Operating System | Windows 10 20H2 |

**Comment by sayris** [comment]
Hi!

Thanks for flagging this -- the issue with `.mdc-tooltip-wrapper--rich` changing height is due to a missing `mdc-tooltip` class on the tooltip itself (see [codepen](https://codepen.io/shws/pen/ExNOJgL)). I realize that the example html for rich tooltips in the README was incorrect (it leaves off this class) -- so I'm submitting a fix to the README.

The issue with the tooltip edges was actually fixed in #6813 and so that should be resolved in the next release.

**Comment by DouglasRiddle** [comment]
Excellent. Thank you for the additional info!
