### ISSUE TITLE
Investigate adding focus trapping to all relevant components

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#70]
Helpers package for reusable functions for dealing with UI interactions. For this particular issue, we are simply implementing focus trapping, but the package has the potential to facilitate more ui-related helper functions as well.

- [ ] Create package
- [ ] Refactor mdc-temporary-drawer to use package

**Comment by sgomes** [comment]
As a note, we already have focus trapping implemented on the menu. We should refactor that code out into the `mdc-ui-helpers` package.

**Comment by Garbee** [comment]
The dialog component could also be refactored to use this helper library. iirc it has/had some problems with focus trapping as well.

**Comment by kfranqueiro** [comment]
MDC Web now relies upon the focus-trap third-party library for modal behavior within MDC Dialog and MDC Drawer. This is hooked up via an adapter and util API so that it can be replaced in other contexts if necessary.

MDC Menu's focus trapping logic is a bit more unique and does not reuse focus-trap.
