### ISSUE TITLE
Slider Not Forwarding Mixins

### ISSUE THREAD

**Issue by Full-lifey** [material-components/material-components-web#7005]
### Steps to reproduce
1. Create App.scss for Theme Build
2. Add `@use "@material/slider/styles"`
3. Attempt to use any Slider mixin

### Actual behavior

ERROR in ./app.scss
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
    ╷
268 │   @include mdc-slider-tick-mark-active-color(white);
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  my-components.scss 268:3  @import
  app.scss 53:9             root stylesheet
SassError: SassError: Undefined mixin.
    ╷
268 │   @include mdc-slider-tick-mark-active-color(white);
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Expected behavior

I expected the mixins to function.

I then dug into the @material/silder files and found no forwarding rules for the mixins created under _slider-theme.scss

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 10.0.0
| Browser          | N/A
| Operating System | N/A

### Possible solution

@forward the mixins from _slider-theme.scss.

**Comment by asyncLiz** [comment]
Public Sass mixin APIs are forwarded from the [`_index.scss` file](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/_index.scss), not the `styles.scss` file. Additionally, you need to change your `app.scss` file to use the namespace-prefixed mixins instead of the old `@import` `mdc-*` prefixed versions.

```scss
// app.scss
@use '@material/slider/styles'; // import slider's concrete styles
@use '@material/slider'; // import mixins to customize (default namespace is "slider")

.my-slider {
  @include slider.tick-mark-active-color(white);
}
```

Hope that helps!
