### ISSUE TITLE
Compile Issue with the Persistent and Temporary Drawer.

### ISSUE THREAD

**Issue by Livly** [material-components/material-components-web#703]
### What MDC-Web Version are you using?

material-components-web@0.11.1

### Sass Versions

Compiling with Sass 4.0.0.alpha.1 Also tried multiple previous patches 3.4.x 

### What OS are you using?

Windows 10 x64

### What are the steps to reproduce the bug?

Importing the material-components-web into my own Sass file and trying to compile it caused a few compiler errors. The first one was in the Elevation Module (That one is already documented under issue [#2241](https://github.com/sass/sass/issues/2241) in Sass).

The second issue was caused by the import of the Slidable mixins for the Persistent and Temporary Drawers in the Drawer Module. It took me a while to realize, but the _mixins and _variables in '@material/drawer/slidable' are .css and not .scss

I'm fairly new to Sass and I wasn't sure if I was doing something wrong with my additional paths config. My compiler issue was fixed when I changed the file type and everything seems to be working fine.

**Comment by yeelan0319** [comment]
Hi @Livly , given the information you provided so far, it is very hard for us to know what exactly the problems are. One thing that you mentioned about the `scss` and `css`, we just merged #691 to fix that. See if this help you solve the problem.

If you continue to have it, could you paste the error messages you see so that we can have a better idea what's going on? Or if you can provide concrete steps to repro the problem, that would be even better.

**Comment by abhiomkar** [comment]
This is fixed in latest drawer version.
