### ISSUE TITLE
[slider] Slider is stuck in a broken state when initially rendered as hidden

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#7031]
## Bug report

When slider is hidden, initialized, and then shown, it is in a broken state that needs layout to be called.

### Steps to reproduce
1. Go to https://spice-open-wealth.glitch.me/
2. Click on the button
3. Try to slide slider

(source: https://glitch.com/edit/#!/spice-open-wealth?path=components.js%3A9%3A35)

### Actual behavior

Display is broken and non-slidable until calling layout or resize

### Expected behavior

It shouild work on display or at least on touch.

### Screenshots

![image](https://user-images.githubusercontent.com/5981958/115629002-5e03ff80-a2b6-11eb-8a7c-9dc4f0fdf7ae.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0
| Browser          | Chrome
| Operating System | All

### Additional context

material-components/material-components-web-components#1885

### Possible solution

Change knob position implementation to be relative on init (percentages instead of px) and then call layout on `pointerdown`

**Comment by joyzhong** [comment]
We'd like to avoid calling layout on `pointerdown` since in most cases, this causes an unnecessary reflow. We do automatically call layout on window resize, but for the case where the slider is hidden or not in its final position on component initialization, which can vary based on the app use case, the guidance would be to invoke `MDCSlider#layout` to recalculate slider dimensions once the slider is rendered in its final state.

Note that we also have [guidance](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/README.md#setting-slider-position-before-component-initialization) for marking up the DOM to display the slider thumb/track correctly before component initialization.

**Comment by e111077** [comment]
The components that require layout to be called tend to be the components with the most DX complaints. Granted calling layout in the foundation on pointerdown would add some performance issues, but it wouldn't block initial load since it only happens on user interaction, and since it's only on down, it would not thrash the renderer since it only happens once on interaction.

Alternatively we can perhaps hide it behind a flag and enable it for those who would like to set it declaratively.
