### ISSUE TITLE
Menus should add padding

### ISSUE THREAD

**Issue by WordlessEcho** [material-components/material-components-web#708]
In [Material Design Guidelines](https://material.io/guidelines/components/menus.html#menus-specs), menus should have:
- Top padding: 8dp
- Bottom padding: 8dp

![components_menus_specs1.png (1520×768)](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3aEFjbTF1T1FjQTQ/components_menus_specs1.png)

But [Material Design Components Web Menu](https://material-components-web.appspot.com/simple-menu.html) only have bottom padding, have no top padding:

![Simple Menu - Material Components Catalog](https://cloud.githubusercontent.com/assets/12007025/26386960/91e660ae-407c-11e7-9c6a-0bc6288eebc9.png)
 
Anyway, seems that menus "dividing line" should have 16px padding? Guidelines is not clear about that.

![components_menus_specs4.png (1520×1412)](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3aHdodkt4Z0tvblE/components_menus_specs4.png)

**Comment by robzenn92** [comment]
@WordlessEcho nice catch! However, to me it seems that it does not have the bottom padding too. To the best of my knowledge the little space between the last child and the end of the menu is caused by [line 66](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/mdc-simple-menu.scss#L66).

Isn't enough to remove [line 66](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/mdc-simple-menu.scss#L66) and replace [line 128](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/mdc-simple-menu.scss#L128) with `padding: 8px 0;` ? Am I wrong?

Regarding the dividing line I think it definitely needs to be adjusted.

**Comment by WordlessEcho** [comment]
Yep! That's right!

![right_menus](https://cloud.githubusercontent.com/assets/12007025/26436259/c74231f8-4147-11e7-8c80-c9cb28acece0.png)

**Comment by robzenn92** [comment]
Cool! 😃 So I am going to open a PR with the fix!

There is still the need to understand whether the desktop should have a 16px padding and where to put it, cause I don't see media queries.

**Comment by WordlessEcho** [comment]
Top padding, bottom padding and dividing line need 8px on mobile, 16px on desktop (Anyway, seems that table is same of desktop).
Thanks!

**Comment by robzenn92** [comment]
Actually, [here](https://material.io/guidelines/components/menus.html#menus-simple-menus) I found the following:

> Default desktop menu
Menu item height: 32px
Menu item text left padding: 24px
Top padding: 8px
Bottom padding: 8px
Typography: 15px

So both the top and bottom padding for desktop are the same as the mobile while the difference is the *Menu item height* and the *Menu item text left padding*.

The third picture you posted for the *dividing line* is related to the *Cascading menu* which is different. See [#53](https://github.com/material-components/material-components-web/issues/53).

**Comment by WordlessEcho** [comment]
> The third picture you posted for the *dividing line* is related to the Cascading menu which is different.

I nearly forget it... You're right. XD
