### ISSUE TITLE
Background color to header for a more complex dialog?

### ISSUE THREAD

**Issue by mdecaffmeyer** [material-components/material-components-web#712]
In the guidelines we see an example of two types of dialog. [Simple dialogs](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3V0VvZEFDTUt2ZEU/components_dialogs_usage1.png) with a single message or asking to select a single item ; and a more [complex dialog](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3MDdSZ0Rnd1pKeWM/components_dialogs_fullscreen1.png) that may contain more items, like set of form inputs, ... The latter shown in the guide are called full-screen.

Now in the case of MDC-Web it makes sense not to have full-screen dialogs, but it seems to me that we now lack a type of dialog that may contain more than a message, like a set of inputs or anything more than a simple message or input. It would be nice for example to have a dialog which has a header filled with a background color, like seen [here](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3LWY1ZXlYTFdMeUU/components_dialogs_fullscreen2.png), maybe with a X button top right, etc.

**Comment by yeelan0319** [comment]
Hi @mdecaffmeyer ,

Thanks for filing the issue. We talked about this on the team. [Full screen section of dialog in material guideline](https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs) is very specific to mobile devices and not applicable to web.

> (In full screen dialog section) Mobile only: Due to limited space, full-screen dialogs may be more appropriate for mobile devices than dialogs used on devices with larger screens.

In general, mdc-web try to create a minimal out-of-box components that complies material design guideline and because of that we think the best way for us is to keep the dialog simple to support text and action for the moment. However, even though we don't offer that as part of our library, we highly encourage you to overwrite based on your design needs. For features that you are asking for, I create a [prototype](https://codepen.io/yeelan0319/pen/ZKPgqW?editors=1000) as reference how to achieve the thing you mentioned using customized markups and styles. Hope this helps you.

Also if you want something different than a dialog and works more like a modal, you may also consider using `mdc-elevation` to create your own markup.
