### ISSUE TITLE
Question: What is feature targeting?

### ISSUE THREAD

**Issue by MatteuSan** [material-components/material-components-web#7196]
Yes I know "go look at the docs", but I really don't understand what it is or what it does or how it affects the component styling overall. I'm really sorry if I get scolded in this thread for asking a useless question, I'm just new to the field.

**Comment by asyncLiz** [comment]
Feature targeting allows users to selectively include and exclude large pieces of Sass that are emitted. This is useful when building separate stylesheets (such as compiling all animation styles separately to lazy load animation).

[Angular uses feature targeting](https://github.com/angular/components/blob/4caf039949cbd0ce1bf598936fac0ac3faba5398/src/material-experimental/mdc-helpers/_mdc-helpers.scss#L14-L18) to achieve this.

Moving forward, we have plans to improve and rework feature targeting since it doesn't quite fulfill all of our needs, but that's what it currently does!
