### ISSUE TITLE
[Slider] gets stuck in drag state when pointerup is outside of window

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web#7209]
## Bug report

If dragging a slider and releasing the pointer outside the window, when coming back to the slider, it will continue to slide

### Steps to reproduce

[repro link](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuICA8bGluayByZWw9XCJzdHlsZXNoZWV0XCIgaHJlZj1cImh0dHBzOi8vdW5wa2cuY29tL0BtYXRlcmlhbC9zbGlkZXJAbGF0ZXN0L2Rpc3QvbWRjLnNsaWRlci5jc3NcIj5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IGNsYXNzPVwibWRjLXNsaWRlclwiPlxuICA8aW5wdXQgY2xhc3M9XCJtZGMtc2xpZGVyX19pbnB1dFwiIHR5cGU9XCJyYW5nZVwiIG1pbj1cIjBcIiBtYXg9XCIxMDBcIiB2YWx1ZT1cIjUwXCIgbmFtZT1cInZvbHVtZVwiIGFyaWEtbGFiZWw9XCJDb250aW51b3VzIHNsaWRlciBkZW1vXCI-XG4gIDxkaXYgY2xhc3M9XCJtZGMtc2xpZGVyX190cmFja1wiPlxuICAgIDxkaXYgY2xhc3M9XCJtZGMtc2xpZGVyX190cmFjay0taW5hY3RpdmVcIj48L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibWRjLXNsaWRlcl9fdHJhY2stLWFjdGl2ZVwiPlxuICAgICAgPGRpdiBjbGFzcz1cIm1kYy1zbGlkZXJfX3RyYWNrLS1hY3RpdmVfZmlsbFwiPjwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cIm1kYy1zbGlkZXJfX3RodW1iXCI-XG4gICAgPGRpdiBjbGFzcz1cIm1kYy1zbGlkZXJfX3RodW1iLWtub2JcIj48L2Rpdj5cbiAgPC9kaXY-XG48L2Rpdj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6ImluZGV4LnRzIiwiY29udGVudCI6ImltcG9ydCB7TURDU2xpZGVyfSBmcm9tICdAbWF0ZXJpYWwvc2xpZGVyJztcblxuY29uc3Qgc2xpZGVyID0gbmV3IE1EQ1NsaWRlcihkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcubWRjLXNsaWRlcicpKTsifV0)

1. Go to link above
2. click and drag slider
3. drag out of iframe or window
4. let go of pointer
5. move mouse back into window
6. observe dragging continues

### Actual behavior

Dragging will not be cancelled

### Expected behavior

dragging should stop

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 11.0.0
| Browser          | Chrome 91
| Operating System | Mac OS

### Additional context

Related material-components/material-components-web-components#1279

### Possible solution

pointer up not being captured outside of window despite setPointerCapture.

**Comment by e111077** [comment]
How odd I was able to repro it with the scuba debug target internally as well in the mdc repo. Sdom shouldn't really make much of a difference here, but it's really odd that it just works with codepen

**Comment by joyzhong** [comment]
I tested using the scuba debug target and it seems to work there. Also, the pointerup event is fired as expected if you drag outside the window in [this lit.dev playground demo](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zY3JpcHQuanNcIj48L3NjcmlwdD5cbiAgPHN0eWxlPlxuICAgICNyZWQge1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7XG4gIGJhY2tncm91bmQ6IHJlZDtcbn1cbiAgPC9zdHlsZT5cbjwvaGVhZD5cbjxib2R5PlxuPGRpdiBpZD1cInJlZFwiPlxuPC9kaXY-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJzY3JpcHQuanMiLCJjb250ZW50IjoiY29uc3QgcG9pbnRlck1vdmVIYW5kbGVyID0gKGUpID0-IHtcbiAgY29uc29sZS5sb2coZS5jbGllbnRYKTtcbn07XG5cbnJlZC5hZGRFdmVudExpc3RlbmVyKCdwb2ludGVyZG93bicsIChlKSA9PiB7XG4gIHJlZC5zZXRQb2ludGVyQ2FwdHVyZShlLnBvaW50ZXJJZCk7XG4gIFxuICByZWQuYWRkRXZlbnRMaXN0ZW5lcigncG9pbnRlcm1vdmUnLCBwb2ludGVyTW92ZUhhbmRsZXIpO1xufSk7XG5cbnJlZC5hZGRFdmVudExpc3RlbmVyKCdwb2ludGVydXAnLCAoKSA9PiB7XG4gIHJlZC5yZW1vdmVFdmVudExpc3RlbmVyKCdwb2ludGVybW92ZScsIHBvaW50ZXJNb3ZlSGFuZGxlcik7XG4gIGNvbnNvbGUubG9nKCdQT0lOVEVSVVAgPT09PT09PT09PT09PT09PT09PT09PT09PT09Jyk7XG59KTsifV0).

If you set a breakpoint in `MDCSliderFoundation#handlePointerup` in the original Lit demo, it is not called when releasing the pointer outside of the window, so the browser is for some reason not firing the pointerup event as expected (since we set pointer capture).

**Comment by e111077** [comment]
Ah, this problem is twofold:

1. the playground page was messing with pointerup (confirmed by opening the link in the iframe)
2. This is only replicable in the m1 slider.

Feel free to close this as I'm literally working on releasing the new slider in mwc right now
