### ISSUE TITLE
[mdc-list] list-item with graphic

### ISSUE THREAD

**Issue by markborner** [material-components/material-components-web#7291]
## Bug report
None of the HTML examples of lists in the (readme)[https://github.com/material-components/material-components-web/tree/master/packages/mdc-list] have icons on the list-items, even though the images of the three types of lists all have an icon before the list-item text.

Also, the HTML example of a "List with radio group" has the following list-item:

```html
  <li class="mdc-list-item" role="radio" aria-checked="false">
    <span class="mdc-list-item__ripple"></span>
    <span class="mdc-list-item__graphic">
      <div class="mdc-radio">
        <input class="mdc-radio__native-control"
              type="radio"
              id="demo-list-radio-item-1"
              name="demo-list-radio-item-group"
              value="1">
        <div class="mdc-radio__background">
          <div class="mdc-radio__outer-circle"></div>
          <div class="mdc-radio__inner-circle"></div>
        </div>
      </div>
    </span>
    <label class="mdc-list-item__text" for="demo-list-radio-item-1">Option 1</label>
  </li>
```

However, the class "mdc-list-item__graphic" seems to be depreciated - in version 12 I can only find the class "mdc-deprecated-list-item__graphic".

What's the proper markup for a list item with an icon?

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 12.0.0
| Browser          | Chrome
| Operating System | MacOS

**Comment by allan-chen** [comment]
CC/ and assigning to @brandondiamond who may be able to provide more context beyond this

Hey @markborner ,

Apologies for the delay in update of documentation. Currently the list styles shipped on npm should still be deprecated styles. If you can compile Sass, then the evolution mixins can be used to [compile](https://github.com/material-components/material-components-web/issues/7013#issuecomment-888035304) into the styles for new lists. The draft for the updated markup is mentioned in [this issue](https://github.com/material-components/material-components-web/issues/7013#issuecomment-827034121), but please note that the `*-evolution` suffixes on class names should already have been removed.

As an example, if you can compile Sass into the new styles, this is a preview of the updated markup:

```html
<ul class="mdc-deprecated-list" role="radiogroup">
  <li class="mdc-list-item mdc-list-item--with-one-line mdc-list-item--with-leading-icon mdc-list-item--with-trailing-icon">
    <span class="mdc-list-item__ripple"></span>
    <span class="mdc-list-item__start">
      <i class="material-icons">data_usage</i>
    </span>
    <span class="mdc-list-item__content">
      <span class="mdc-list-item__primary-text">Evolution icon item</span>
    </span>
    <span class="mdc-list-item__end">
      <i class="material-icons">data_usage</i>
    </span>
  </li>
</ul>
```

Otherwise, it is recommended to use the deprecated markup for now. For radio items, it would look as follows:

```html
<ul class="mdc-list" data-evolution="true">
  <li class="mdc-deprecated-list-item" role="radio" aria-checked="true" tabindex="0">
    <span class="mdc-deprecated-list-item__ripple"></span>
    <span class="mdc-deprecated-list-item__graphic">
      <div class="mdc-radio">
        <input class="mdc-radio__native-control"
              type="radio"
              id="test-list-radio-item"
              name="test-list-radio-item-group"
              value="test"
              checked>
        <div class="mdc-radio__background">
          <div class="mdc-radio__outer-circle"></div>
          <div class="mdc-radio__inner-circle"></div>
        </div>
      </div>
    </span>
    <label class="mdc-deprecated-list-item__text test-list-item__label" for="test-list-radio-item">Option</label>
  </li>
</ul>
```

**Comment by markborner** [comment]
Thanks for both examples!

**Comment by joyzhong** [comment]
See documentation for the new list as linked [here](https://github.com/material-components/material-components-web/blob/master/packages/mdc-list/README.md#list-is-being-updated).
