### ISSUE TITLE
CSS only ripple doesn't work on mobile Safari

### ISSUE THREAD

**Issue by yeelan0319** [material-components/material-components-web#734]
### What MDC-Web Version are you using?

> 0.11.1

### What browser(s) is this bug affecting?

> Mobile Safari

### What OS are you using?

> iOS 10.2.1

### What are the steps to reproduce the bug?

> 1. Open [ripple](http://material-components-web.appspot.com/ripple.html) in catelog om mobile safari
> 2. click any css only ripple

### What is the expected behavior?

> Ripple should appear

### What is the actual behavior?

> While it not

**Comment by kfranqueiro** [comment]
Mobile Safari unfortunately doesn't trigger `:active` on touch presses by default, which is why our CSS-only styles don't work.

This is evidently a known and [documented](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/AdjustingtheTextSize/AdjustingtheTextSize.html#//apple_ref/doc/uid/TP40006510-SW5) "feature", which can be worked around by simply registering a touch event handler on a common ancestor in the DOM. (More explanation in [this SO answer](https://stackoverflow.com/a/33681490).)

This might be worth another caveat in our ripple documentation, but other than that I don't think it's something we can directly mitigate within MDC Web.
