### ISSUE TITLE
Bug in Toolbar when using Waterfall

### ISSUE THREAD

**Issue by arjendeblok** [material-components/material-components-web#742]
### Using
Using toolbar version 0.3.2.
Browser: Chrome 58.0.3029.110 (64-bit)
OS: Windows 10

### HTML

```
<header class="mdc-toolbar mdc-toolbar--fixed mdc-toolbar--waterfall mdc-toolbar--flexible mdc-toolbar--flexible-default-behavior mdc-toolbar--flexible-space-maximized">
        <div class="mdc-toolbar__row" style="height: 224px;">
            <section class="mdc-toolbar__section mdc-toolbar__section--align-start">                
                <span class="mdc-toolbar__title" style="transform: translateY(168px); font-size: 2.125rem;">pyxX</span>
            </section>
        </div>
    </header>
```

### What is the expected behavior?

I should see the text **pyxX** correctly.

### What is the actual behavior?

The toolbar title is cutting off the lower parts of the p and y when not scrolled.
If it is scrolled then the parts become available.
See https://codepen.io/arjendeblok/pen/GmaWoE 

### Investigation

The toolbar title is changing its font and translation as the user scrolls, but it has a fixed line height of 1.5

**Comment by arjendeblok** [comment]
Toolbar has a line height of 1.5rem, so it is fixed to 24px.
If changed to 1.5 (so without suffix) it scales with the font which is better.
But then the translation factor must be changed, because it is too big and the title is shown to low.

**Comment by arjendeblok** [comment]
A line height of 1.2 seems the best option.

**Comment by yeelan0319** [comment]
@arjendeblok 

Thanks for filing the issue. It seems like you provided a static pen at a certain stage, however, `waterfall-toolbar` need to work with Javascript to correctly layout itself, could you try improve the pen you provided with Javascript and see if the issue continue to exist?

**Comment by arjendeblok** [comment]
@yeelan0319 Improved the Pen with JavaScript. But issue remains.

**Comment by touficbatache** [comment]
I think that `overflow: visible;` could do the trick.

**Comment by yeelan0319** [comment]
Hi @arjendeblok ,

Is this still an on-going issue? Sorry for the tardiness but I think the way it is implemented in the pen seems not very right. 
1. We don't specify `mdc-toolbar--fixed` `mdc-toolbar--waterfall` `mdc-toolbar--flexible` all at the same time, they may conflicting with each other.
2. All the style and `mdc-toolbar--flexible-space-maximized` should be set automatically by Javascript if you are using one of the Javascript enabled type of toolbar, but do not add them manually
3. If you are using `fixed` you probably need to have `mdc-toolbar-fixed-adjust` for the body content, otherwise the toolbar might overlay with the content.

See a [pen](https://codepen.io/yeelan0319/pen/VWRQbj) here for the idea

**Comment by arjendeblok** [comment]
It seems that the latest version of toolbar solves the issue. It works fines now.
So the issue van be closed.
