### ISSUE TITLE
Issue with customizing colors

### ISSUE THREAD

**Issue by mdecaffmeyer** [material-components/material-components-web#755]
By default, the color used are: 
```
$mdc-theme-primary: #3f51b5 !default; /* Indigo 500 */
$mdc-theme-accent: #ff4081 !default; /* Pink A200 */
$mdc-theme-background: #fff !default; /* White */
```

By looking into developer tools, I see that the text on the primary is color is white:
`:root { --mdc-theme-text-primary-on-primary: white; }`

However when I change the primary color to cyan:
```
$mdc-theme-primary: #00BCD4;
@import "material-components-web/material-components-web";
```

Suddenly the text on primary color becomes black:
`:root { --mdc-theme-text-primary-on-primary: rgba(0, 0, 0, 0.87); }`

Why did this property change as I didn't change it manually?

**Comment by Garbee** [comment]
The text color is automatically selected for the best contrast. This is done not only because the specification requires it but simply for accessibility for users to be most capable to read the content.

The calculations for the contrast are handled in the [theme functions](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_functions.scss) sass file.

**Comment by mdecaffmeyer** [comment]
Indeed when I choose Cyan in the color tool, I have black text by default on the cyan background:

https://material.io/color/#!/?view.left=0&view.right=0&primary.color=00BCD4

However I've seen on another palette that it shows white text on cyan bg:

https://www.materialpalette.com/cyan/red

I also think that the latter is much more beautiful (white text on cyan), but then I violate material's recommendations, which leaves me pretty confused... ;-(

What do you think?

**Comment by Garbee** [comment]
Material.io is the official resource, so I'd err towards that. MaterialPalette is a completely un-related community site doing its own thing.

To check the contrast on your own, you can use one of many [color contrast tools](http://webaim.org/resources/contrastchecker/) and see if they pass the a11y recommendations or not. In this case, `#ffffff` on `#00bcd4` fails while `#000000` on it passes. Hence, why we chose black instead of white.

**Comment by mdecaffmeyer** [comment]
Thank you, I didn't know the WCAG 2.0 spec:-) it's really nice that the library computes automatically the required text color according to the spec.

As you seem much more informed on the subject, may I ask you if  I may change the font weight of the titles (e.g. dialog's title) as I please without breaking the material's recommendation? (font weight requirements are not very explicit on the WCAG 2.0 spec for what I've read..) E.g. I find it really nice to have a Roboto text of 300 weight which is thin as titles. By default, the dialog will show a rather bold title (500).

**Comment by Garbee** [comment]
> without breaking the material's recommendation

Any custom modifications you're kinda edging on not "following the spec". That being said, I can't urge enough that for *your applications* if you feel the spec is creating worse usability and accessibility for your users, go ahead and change something. That's the entire point, MCW adheres to the spec as best we can and users can modify as they want freely. Whether or not it adheres to the specification.

If you have a situation where you feel MD guidance is not in alignment with other usability/accessibility guidelines from trusted organizations **open an issue** about that in particular. That way there is something trackable and actionable for to be handed off to the MD spec team to look at.

**Comment by traviskaufman** [comment]
Looks like @Garbee has addressed the issue here, so closing ;) 

_However_,  you may be able do it at the custom variables level:

```css
/* After importing mdc-web */
:root {
  --mdc-theme-text-primary-on-primary: white;
}
```
