### ISSUE TITLE
Change MDC-toolbar flexible behavior adapter and constant name to remove ambiguity

### ISSUE THREAD

**Issue by griest024** [material-components/material-components-web#765]
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

Tested on electron 1.6.7 initially (so Chromium?) and reproduced in codepen on Chrome 58.0.3029.110 (64-bit).

### What OS are you using?

Windows 8.1 64-bit

### What are the steps to reproduce the bug?

Please refer to [this pen](https://codepen.io/griest024/pen/pPMOdV?editors=1011) to reproduce the bug. The functions in question start on line 47 and 60.

### What is the expected behavior?

I would think that the foundation should only try to obtain information about the flexible row element only if it exists. That is, `getFlexibleRowElementOffsetHeight()` and `setStyleForFlexibleRowElement()` should only be called if `hasFlexibleRow_` is `true`. Since flexible is not a required mode of the toolbar, the element itself should be optional.

### What is the actual behavior?

`getFlexibleRowElementOffsetHeight()` and `setStyleForFlexibleRowElement()` are called whenever `init()` is called, regardless of the value of `hasFlexibleRow_`. This produces a `TypeError: Cannot read property 'offsetHeight' of undefined` since the flexible row element is undefined.

### Any other information you believe would be useful?

Note that the toolbar is in waterfall mode: `<header class="mdc-toolbar mdc-toolbar--fixed mdc-toolbar--waterfall mdc-theme--primary">` and *not* in flexible mode.

Here is a more informative stack trace than the one on codepen:
```
TypeError: Cannot read property 'offsetHeight' of undefined
    at Object.getFlexibleRowElementOffsetHeight (eval at <anonymous> (http://localhost:9080/renderer.js:1552:1), <anonymous>:58:64)
    at MDCToolbarFoundation.initKeyRatio_ (eval at <anonymous> (http://localhost:9080/renderer.js:1288:1), <anonymous>:168:47)
    at MDCToolbarFoundation.init (eval at <anonymous> (http://localhost:9080/renderer.js:1288:1), <anonymous>:95:10)
    at VueComponent.mounted (eval at <anonymous> (http://localhost:9080/renderer.js:1552:1), <anonymous>:76:21)
```

So it appears that [this line](https://github.com/material-components/material-components-web/blob/43cef6c06b66874c74449cc31072e03a17d239f1/packages/mdc-toolbar/foundation.js#L166) and [this one](https://github.com/material-components/material-components-web/blob/43cef6c06b66874c74449cc31072e03a17d239f1/packages/mdc-toolbar/foundation.js#L206) are to blame.

**Comment by yeelan0319** [comment]
@griest024 ,

Thanks for filing the issue! The flexible behavior is optional as you pointed out and we have the [waterfall example](http://material-components-web.appspot.com/toolbar/waterfall-toolbar.html) in our catalog without the flexible modifier. 

The "trick" is in our adapter implementation, we have:
```
get flexibleRowElement_() {
  return this.root_.querySelector(MDCToolbarFoundation.strings.FLEXIBLE_ROW_SELECTOR);
}
...
getDefaultFoundation() {
  ...
  setStyleForFlexibleRowElement: (property, value) => this.flexibleRowElement_.style.setProperty(property, value),
  ...
}
```
and we have `FLEXIBLE_ROW_SELECTOR` being the value `.mdc-toolbar__row:first-child`, which will always exist no matter whether the flexible modifier is set or not. In the pen you provided, I see you specifically looking for `vm.$props.flexibleRowElement` or `vm.$slots.flexibleRow` and it raise the error you see.

So up to this point, we can see how confusing the names are to our user and even mislead them to implement the adapter in the wrong way. We would like to

1. In *constant.js*: 
    - [ ] In line 29, change `FLEXIBLE_ROW_SELECTOR` to `FIRST_ROW_SELECTOR`

 2. In *foundation.js*:
    - [ ] line 44 & 167,  change adapter name `getFlexibleRowElementOffsetHeight` to `getFirstRowElementOffsetHeight` 
    - [ ] line 167, change variable name `flexibleRowMaxRatio` to `firstRowMaxRatio`

3. In *index.js*:
    - [ ] line 30, change `flexibleRowElement_` to `firstRowElement_` and using the new selector constant name
    - [ ] line 59 & 63, change the name of the adapter method and the implementation to use the new name

4. In *mdc-toolbar.test.js* and *foundation.test.js*, the new name should be reflected all correspondingly.

ps: the adapter method `setStyleForFlexibleRowElement` should remain unchanged because it will only be called if `this.hasFlexibleRow_==true`.

If you would like to help us file a PR for those updating, we would willing to help get it merge into our codebase 👍

**Comment by yeelan0319** [comment]
Once side note: **Why this is needed in the first place if there is no flexible space?**

The calculation of flexible space is not only used the height of the flexible space, but also used to indicate the status of the toolbar. When `flexibleExpansionRatio == 0`, the toolbar sets its states to `mdc-toolbar--flexible-space-minimized` and further scroll would trigger a elevation being added to the toolbar. This behavior is applicable to all cases where you want to use toolbar with JavaScript (waterfall, flexible, etc..) and that's why the logic is needed in the first place.

For the naming change, we would like to restrict the changes to only our public APIs (adapter method, string constant and directly related variables) to help removing ambiguity. However, we would like to keep most of the internal implementation unchanged to prevent overhead introduced by large refactoring.

**Comment by griest024** [comment]
@yeelan0319 Thank you for the response, it was very informative.

>  the adapter method `setStyleForFlexibleRowElement` should remain unchanged because it will only be called if `this.hasFlexibleRow_==true`

If I recall correctly from my debugging, this method was also called when `this.hasFlexibleRow_==false`. I'll wait until the PR has been merged to test that and submit a new issue if needed.

> If you would like to help us file a PR for those updating, we would willing to help get it merge into our codebase

Sure I'll whip something up. Should the PR also include the relevant changes to the adapter documentation?
