### ISSUE TITLE
No @material folder after npm install

### ISSUE THREAD

**Issue by kodeJ** [material-components/material-components-web#802]
Hi. I want to try to use whole library, so I did `npm install --save material-components-web`

And now I got an error, since there's a bunch of component SCSS imports from `@material` folder which I do not have with `npm install --save material-components-web`!!!

Why this needs to be so confusing? How to use it?

**Comment by traviskaufman** [comment]
As detailed in our [README](https://github.com/material-components/material-components-web#css), you must insure that your `node_modules` folder is added to your SASS include path.

We have addressed this [multiple](https://github.com/material-components/material-components-web/issues/692) [times](https://github.com/material-components/material-components-web/issues/603) [before](https://github.com/material-components/material-components-web/issues/351) but I think that we have to surface it so that it's more visible.

**Comment by kodeJ** [comment]
I think you guys have too much spare time in that awful Google corp, because I can't imagine how normal person can create such awful integration. Only absolute schizophrenic nerds, or may be another California gay with fucked up mind. What the hell is SASS include path? Why do I need to mess with this homo tools anyway? Why so fucking opinionated? Today is 2017, fucking Google. I hope this Jews and multicultural gay human trash will burn soon. SASS include path, for fucks sake. Shit!
