### ISSUE TITLE
Content auto-adjust with toolbar

### ISSUE THREAD

**Issue by touficbatache** [material-components/material-components-web#808]
Hey,
I made a small JavaScript script that calculates the height of the toolbar and spaces the content in `<main>` correctly. I thought it could be useful if you have a toolbar with multiple rows so it calculates it by itself. You can add the `mdc-toolbar-adjust-content` to the parent containing the content. 

This is the code I made: `document.querySelector('.mdc-toolbar-adjust-content').style = "padding-top: calc(" + document.querySelector('.mdc-toolbar').clientHeight + "px + 24px);";`

It's so simple, it gets the toolbar height, adds 24px to it and applies it to the content's style as a `padding-top`. The content should also have a `padding-right` and `padding-left` of 16px according to Material Design Guidelines.

**Comment by traviskaufman** [comment]
Hey @touficbatache,

We actually already perform this logic within our `MDCToolbar` JS Component, when using `mdc-toolbar--flexible`. It seems here like you're trying to account for a fixed - but not flexible - toolbar that has a height different from what `mdc-toolbar-adjust-content` assumes. Because we encourage toolbars to be at the heights specified within the spec, and we don't want to make assumptions about the box model that the main element is using, we're hesitant to add this in just to  handle the intrinsic heights of fixed toolbars. We suggest this be done on an application-by-application basis either by applying custom styles or by taking your approach here if it's appropriate.
