### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by henezq** [material-components/material-components-web#813]
I am having troubles with implementing mdc with my Vue app.

I added includePaths for resolving this `@material`, and pass build process, but if I go to the page, I got error

```
/home/nwdw/TESTING/mdc-nuxt/node_modules/@material/checkbox/index.js:17
import {MDCComponent} from '@material/base';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by Garbee** [comment]
What version of node are you running on?

**Comment by henezq** [comment]
@Garbee v8.0.0
How this can be related?

**Comment by Garbee** [comment]
It can be related because if you're running an older node version import doesn't exist.

Are you trying to run this through babel? Any way you could provide an example repo that has a reproduction of the issue?

**Comment by henezq** [comment]
@Garbee yes, setup has Babel in it. I am using Nuxt, it handles all that stuff.

Here's repo - https://github.com/henezq/mdc-nuxt-issue
If you not familiar with Nuxt, then in `pages/index.vue` I have markup, scripts and SCSS, and in `nuxt.config.js` I can extend Webpack configuration.

I was able to include `node_modules` paths, since I had problems on compiling stage from the start

```
     extend (config) {
      const vueLoader = config.module.rules.find((rule) => rule.loader === 'vue-loader')
      vueLoader.query.loaders.scss = 'vue-style-loader!css-loader!sass-loader?' + JSON.stringify({ includePaths: [path.resolve(__dirname), 'node_modules'] })
    }
```
It fixed errors and start the app, but then this error appear. Will appreciate any help. This mdc setup is very confusing, I didn't has such issues with any other packages. Very frustrating.

**Comment by traviskaufman** [comment]
Hey @henezq,

Sorry that this has been frustrating for you so far. From your `unexpected token import` error, it actually looks like the mdc-web code is _not_ being run through babel. Otherwise, that `import` statement would have been transpiled.

I'm definitely not a Vue expert, but I believe [this line](https://github.com/henezq/mdc-nuxt-issue/blob/master/pages/index.vue#L35) should be `<script lang="babel">` instead of just `<script>`. This will tell Vue to transpile your sources using the babel-loader IIRC. You may also have to modify your `nuxt.config.js` to ensure that any path within the `node_modules/@material` get transpiled by babel. 

Alternatively, you can `import` our pre-built version instead:

```js
import {MDCCheckbox} from '@material/checkbox/dist/mdc.checkbox';
// use MDCCheckbox...
```

This should allow you to use the MDC Components without having to transpile.

**Comment by henezq** [comment]
@traviskaufman everything in Nuxt run through babel. I am pretty sure it not the issue. https://github.com/nuxt/nuxt.js/blob/dev/lib/webpack/vue-loader.config.js#L7

**Comment by traviskaufman** [comment]
Thanks for those links  @henezq . From them, it looks like while all application code runs through babel, it may not be the case for code within the `node_modules` folder. Can you confirm that nuxt runs all code from the `node_modules` folder through babel as well? If not, then you'd have to modify your config to run the code through the `node_modules/@material` folder manually. Otherwise, as mentioned above, you can always use our pre-built ES5 code via `@material/checkbox/dist/mdc.checkbox`.

**Comment by henezq** [comment]
@traviskaufman thanks for reply. With this code I was able to run only CSS version, which I don't like

```
import {MDCCheckbox} from '@material/checkbox/dist/mdc.checkbox'

export default {
  mounted () {
    this.MDCCheckbox.init()
  },
  beforeDestroy () {
    this.MDCCheckbox.destroy()
  }
}
```
So I guess something still working bad.

**Comment by traviskaufman** [comment]
That code doesn't look correct...but, it looks like your original issue has been fixed! Can I close this issue then? 😄 For your above comment the best place to get help with that would be [stack overflow](https://stackoverflow.com/search?q=material-components+web)

**Comment by henezq** [comment]
Horrible! This package has now future with such approach. Awful architecture. This is not a components, this is peace of shit. I don't know who's that 4.7k people stared this, I am pretty sure only few people using this nonsense.
