### ISSUE TITLE
Raised button on dark theme uses primary-on-dark text even though the background is primary, not dark

### ISSUE THREAD

**Issue by unascribed** [material-components/material-components-web#819]
### What MDC-Web Version are you using?

0.13.0

### What browser(s) is this bug affecting?

Chromium 58.0.3029.81
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Firefox Developer Edition 54.0b12
> Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

### What OS are you using?

Arch Linux x86_64 (last updated May 3rd)

### What are the steps to reproduce the bug?

1. Create a raised button
2. Add mdc-theme--dark to a parent element
3. Set the primary color to something bright, like Yellow 500
4. Observe the fact the button is completely illegible

https://codepen.io/anon/pen/EXyBGe

### What is the expected behavior?

The button text color should change to black, as if it was using --mdc-theme-text-primary-on-primary

### What is the actual behavior?

The button text color stays white, as it's using --mdc-theme-text-primary-on-dark

**Comment by touficbatache** [comment]
That seems like a bug!

**Comment by makotosalon** [comment]
Please unsubscribe.


2017/06/14 5:06、William Thompson <notifications@github.com> のメッセージ:

What MDC-Web Version are you using?

0.13.0

What browser(s) is this bug affecting?

Chromium 58.0.3029.81

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Firefox Developer Edition 54.0b12

Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

What OS are you using?

Arch Linux x86_64 (last updated May 3rd)

What are the steps to reproduce the bug?

Create a raised button
Add mdc-theme--dark to a parent element
Set the primary color to something bright, like Yellow 500
Observe the fact the button is completely illegible
https://codepen.io/anon/pen/EXyBGe

What is the expected behavior?

The button text color should change to black, as if it was using --mdc-theme-text-primary-on-primary

What is the actual behavior?

The button text color stays white, as it's using --mdc-theme-text-primary-on-dark

―

**Comment by touficbatache** [comment]
However, you can do this manually by adding the `mdc-theme--text-primary-on-light` class to the button.

**Comment by traviskaufman** [comment]
Hey @unascribed,

Thanks for reporting! 

I actually think this looks like there's some incorrect styles being applied when using a raised button in dark mode. Looking at [our code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-button/mdc-button.scss#L117):

```scss
// .mdc-button--raised

  @include mdc-theme-dark(".mdc-button") {
      @include mdc-theme-prop(background-color, primary);
      // ...
  }
```

I'm not sure it's correct to set the `background-color` to the theme's primary color for raised buttons. I'd accept a PR removing this, instead just having the button use a default BG color (perhaps `inherit`?) 
<img width="1432" alt="screen shot 2017-06-15 at 12 51 28" src="https://user-images.githubusercontent.com/1185269/27192443-655c8e88-51c9-11e7-9811-89bd43d620c2.png">

@material-components/mdc-web thoughts?

**Comment by unascribed** [comment]
Using the primary color as the background for default buttons on the dark theme seems to be correct according to the guidelines:

![image](https://user-images.githubusercontent.com/6185037/27192653-28e09bd8-51ca-11e7-89f1-50f1ca54f796.png)

And it's a bit hard to tell raised uncolored dark buttons from the background, since the shadow is black.

**Comment by unascribed** [comment]
Actually, I think I like the uncolored buttons:

![image](https://user-images.githubusercontent.com/6185037/27193092-a8fe6ab0-51cb-11e7-9796-0f36f2d8a54c.png)

Of course, that's your decision, not mine.

**Comment by lynnjepsen** [comment]
Sorry for the confusion here. I've taken a look at this issue, and the [related pull request](https://github.com/material-components/material-components-web/pull/833)...and I've talked to our MD team.

The [spec](https://material.io/guidelines/components/buttons.html#buttons-raised-buttons) does state that raised buttons on dark theme should use primary color. It says "Normal color: 500", which I confirmed is the primary color. You could also use the accent color, but MDC Web's code will default to the primary color.

The real issue is using #FFEA00 (bright yellow) as a "primary color" doesn't work with white text. @makotosalon demonstrated this with his [codepen](https://codepen.io/anon/pen/EXyBGe)

Using bright yellow as a primary color means --mdc-theme-text-primary-on-primary should be set to a darker color. You can use this [color tool](https://material.io/color/#!/?view.left=0&view.right=0&primary.color=FFEA00) (slide three shows the darker text on a yellow button)
Here is a [new codepen](https://codepen.io/anon/pen/pwrzbN) demonstrating the changes to this --mdc-theme-text-primary-on-primary.

I've created a [new PR](https://github.com/material-components/material-components-web/pull/853) with a fix to include mdc-theme-text-primary-on-primary on raised buttons on dark theme. Hopefully that removes @Garbee concerns with the first pull request.
 
I would also like to close out the [older pull request](https://github.com/material-components/material-components-web/pull/833).
