### ISSUE TITLE
Upper case letters in custom event names makes events "invisible" to Aurelia event bindings

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#837]
The events emitted by the MDC Web Components follows the form of "MDCTabBar:change" etc.

I'm using Aurelia and in that framework a custom event can be bound using the following syntax, assuming the custom event name is foo;
`<div foo.trigger="someFunction()">...</div>`

I tried to use this on an mdc-tab-bar like this:
`<div ... MDCTabBar:change.trigger="someFunction()">...</div>`
but it didn't work.

After some testing with my own custom events I've reached the conclusion that this is due to Aurelia being all lower case when it comes to attributes. If I create a facade in code;
```
$(this.tabs).on('MDCTabBar:change', () => {
	let ev = DOM.createCustomEvent('mdctabbar:change', {});
	this.tabs.dispatchEvent(ev);
});
```
 (this.tabs is the tab-bar element, DOM.createCustomEvent is an Aurelia helper)

This works great;
`<div ... mdctabbar:change.trigger="someFunction()">...</div>`

I can totally understand if you feel this is outside the scope of MDC, but; Would you consider changing the naming standard of custom events to be all lower case or alternatively always emit a lower cased event as well?

**Comment by traviskaufman** [comment]
Hey @deap82,

Thanks for filing this issue. As you mentioned, I feel like this is kind of outside the scope of MDC-
 Web and moreso falls into Aurelia's wheelhouse. 

The reason why we structure our event names the way we do is because it is always prefixed with the component class which would cause the event to be emitted. Because this class is always prefixed, there's no ambiguity for a developer as to what may have triggered the event. If we were to use something like `mdctabbar:change`, that would probably still solve the problem but we'd have the opposite issue of users wondering why we we lowercase the entire event name. So we're probably going to keep the event names as-is for now. 

That being said, it looks like Aurelia _does_ support capital letters in custom event names, it just kebab-cases them for attributes: https://ilikekillnerds.com/2016/06/dont-get-skewered-kebab-case-aurelia/

So `MDCTabBar:change` would be written as `-m-d-c-tab-bar:change`: 

```js
const kebabCase = require('kebab-case'); // https://www.npmjs.com/package/kebab-case
kebabCase('MDCTabBar:change'); // "-m-d-c-tab-bar:change"
```

While that does look pretty ugly, I believe it should work? Otherwise, you could always work around it by listening to the event within the code, as you're doing in your example. Hope this helps!
