### ISSUE TITLE
Remove underscores from protected properties

### ISSUE THREAD

**Issue by nckh** [material-components/material-components-web#858]
Internal linter says that underscores are limited to private properties. Currently `root_`, `foundation_` and `adapter_` are being converted from `@private` to `@protected` (#767) but to make internal adoption smoother, they may also need to be renamed to `root`, `foundation` and `adapter`.

**Comment by lynnjepsen** [comment]
Seems pretty reasonable. I'd be happy to accept a PR for this!

**Comment by nckh** [comment]
How are breaking changes usually communicated to users? Even though it's a small change it may disrupt their workflow once they upgrade. Should we keep the underscored props for a while, alias them to the correct ones and mark them as `@deprecated`? Or is it overkill?

```
constructor(root, foundation = undefined, ...args) {
  /** @protected {!Element} */
  this.root = root;

  /** 
    * Legacy property. Please use {@code this.root}.
    * @protected {!Element} 
    * @deprecated
    */
  this.root_ = this.root;

  // etc.
}
```

**Comment by peterculak** [comment]
what would you do about this getter https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/helper-text/index.js#L45
```
  /**
   * @return {!MDCTextFieldHelperTextFoundation}
   */
  get foundation() {
    return this.foundation_;
  }

**Comment by kfranqueiro** [comment]
RE @peterculak's comment, those getters are intentionally public so that the text field component is able to access foundations from its subcomponents.

RE the original concern regarding internal lint rules, IIUC an exception is made for OSS libraries that may also be used in other contexts. We're in the midst of converting to TypeScript but are still preserving the trailing underscores for purposes of clearly signaling to non-TS users what members are intentionally not public.
