### ISSUE TITLE
grid layout

### ISSUE THREAD

**Issue by broros** [material-components/material-components-web#910]
I would recommend making the layout grid easier to implement

instead of 

```
<div class="demo-grid mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="demo-cell mdc-layout-grid__cell mdc-layout-grid__cell--span-4">4</div>
            <div class="demo-cell mdc-layout-grid__cell mdc-layout-grid__cell--span-4">4</div>
          </div>
        </div>
```

you can do something like this

```
<div class=" mdc-layout-grid mdc-layout-grid__inner mdc-layout-grid__cell mdc-layout-grid__cell--span-4">

        </div>
```

**Comment by yeelan0319** [comment]
Hi @broros ,

I am not 100% sure what is the rationale behind this improvement, but I will try my best to explain the current design. 
1. The nested structure `mdc-layout-grid` and `mdc-layout-grid__inner` is implemented to support the usage of nested layout grid #496 . Single container is great but it is lacking of enough flexibility to support parameterization and new attributes like `display: grid`. So we decided to add an extra layer instead to increase the flexibility of the implementation.
2. The nested structure of `mdc-layout-grid` and `mdc-layout-grid__cell` is implemented because layout grid is not only about single container width but multiple container interacting with each other on different devices (e.g, desktop, tablet, mobile). Container and children relationship in this case is essential to help the bounding and reflow logic.

Hopefully this explanation make sense to you and I am going to close this issue here since it doesn't contain enough information to act on, but you are also welcomed to file another issue with more explanation behind your design. Please go through the issue filing rules we have in the template before open another issue and we really appreciate all well thought suggestions.
