### ISSUE TITLE
Radio button ink ripple not functioning properly

### ISSUE THREAD

**Issue by chriscox** [material-components/material-components-web#93]
After checking out Master branch (no known tag or version as of yet):

1) On **Chrome** browser, when selecting a radio button label, the ink stays shown and will not dissipate.  See attached image.  However, when selecting the actual input buttons, it works properly.

2) On **Safari** browser, selecting a label doesn't fire the ink at all. Nothing shows when toggling the options using the labels. However, selecting input button works properly

Steps to reproduce (all browsers):
- run the demo server
- go to http://localhost:8080/radio.html
- select any label to toggle between selected options

Example Chrome Screenshot:
---
![screen shot 2016-12-14 at 10 22 29 am](https://cloud.githubusercontent.com/assets/265710/21195261/ec29a54e-c1e7-11e6-8a53-a3a0317f5a8a.png)

**Comment by traviskaufman** [comment]
Thanks for the thorough bug report @chriscox! 

Is this a dupe of #9? 

The issue with label selection right now is that it triggers the "focus" behavior for the ink ripple, rather than the interaction behavior that should result from when an input control's label.

In safari, this probably isn't happening because clicking the label does not focus the element, as it does in Chrome. This should also be taken care of by the work required for #9.

**Comment by chriscox** [comment]
Yeah this is a dupe of #9.  Gonna close this.  Thanks!
