### ISSUE TITLE
Buttons and Accessibility

### ISSUE THREAD

**Issue by JosefJezek** [material-components/material-components-web#977]
Touch targets should be at least 48 x 48 dp.

https://material.io/guidelines/usability/accessibility.html#accessibility-style

**Comment by lynnjepsen** [comment]
Hey @JosefJezek. You're absolutely correct, touch targets should be 48 x 48dp. However I cannot tell which component you're referring to. Please open new issues specific to each component you think needs fixing. The [template on CodePen](http://codepen.io/traviskaufman/pen/pNQmRp) is particularly helpful for demonstrating which component you think does not meed accessibility standards.

**Comment by Garbee** [comment]
**If** this is about the actual Button component, we are still proper. `48px * 48px = 1936px`. The specs on button is a min width of 88px with a height of 36px. Which provides 3168px of touch target space. Now the spec does define a separate "Touch target height" of 48dp on buttons. But, this isn't feasible on the web where you can't accurately detect touch being available compared to cursors. So the spec team would need to provide guidance on one way to do it instead of two to resolve this issue.
